* chtab5_037_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 38 rows x 4 bytes, 340 segment bytes
*
chtab5_037_p0:
        fcb     38,4  ; height, width in bytes
        fcb     $41,$C2,$C0,$3F,$0F,$F0,$41,$00,$C1,$FC,$03,$81
        fcb     $FF,$C1,$03,$FC,$41,$00,$C1,$FC,$03,$81,$FF,$C1
        fcb     $03,$FC,$41,$00,$41,$C2,$F0,$0F,$03,$FC,$41,$00
        fcb     $41,$81,$AA,$C1,$03,$FC,$41,$00,$41,$81,$AA,$C1
        fcb     $0F,$F0,$41,$00,$41,$81,$AA,$C1,$3F,$80,$41,$00
        fcb     $41,$C1,$C0,$3E,$81,$AF,$C1,$3F,$C0,$00,$41,$82
        fcb     $FE,$AF,$C1,$03,$E8,$00,$C1,$F0,$0A,$82,$FF,$FF
        fcb     $C1,$03,$E8,$00,$C1,$F0,$0A,$82,$FF,$FF,$C1,$03
        fcb     $E8,$00,$83,$FF,$FF,$AA,$C1,$03,$E8,$00,$83,$AA
        fcb     $FF,$AA,$C1,$03,$E8,$00,$41,$82,$AA,$FF,$C1,$03
        fcb     $E8,$00,$41,$C1,$C0,$3E,$81,$AA,$C1,$03,$A8,$00
        fcb     $41,$C1,$C0,$3F,$81,$EA,$C1,$03,$A8,$00,$41,$C1
        fcb     $F0,$0F,$81,$FF,$C1,$0F,$F0,$00,$41,$C1,$F0,$0F
        fcb     $81,$FF,$C1,$0F,$F0,$00,$41,$C1,$F0,$0F,$81,$FF
        fcb     $C1,$03,$FC,$00,$41,$C1,$F0,$0F,$81,$FF,$C1,$03
        fcb     $FC,$00,$41,$C1,$F0,$0F,$81,$FF,$C1,$03,$FC,$00
        fcb     $41,$C1,$F0,$0F,$81,$FF,$C1,$0F,$F0,$00,$41,$C1
        fcb     $F0,$0F,$81,$FF,$C1,$0F,$F0,$00,$41,$C1,$C0,$3F
        fcb     $81,$FF,$C1,$0F,$F0,$00,$41,$C1,$C0,$3F,$81,$FF
        fcb     $C1,$0F,$F0,$00,$41,$C1,$C0,$3F,$81,$FF,$C1,$3F
        fcb     $C0,$00,$41,$C1,$C0,$3F,$81,$FF,$C1,$3F,$C0,$00
        fcb     $41,$C1,$C0,$3F,$81,$FF,$C1,$3F,$C0,$00,$41,$82
        fcb     $FF,$FF,$C1,$3F,$C0,$00,$41,$C1,$C0,$3F,$81,$FF
        fcb     $C1,$0F,$F0,$00,$41,$C1,$F0,$0F,$81,$FF,$C1,$0F
        fcb     $F0,$00,$41,$C1,$FC,$03,$81,$FF,$C1,$03,$FC,$00
        fcb     $42,$82,$FF,$FF,$00,$42,$C1,$C0,$3F,$81,$FF,$00
        fcb     $42,$C1,$F0,$0F,$81,$FF,$00,$42,$C1,$C0,$3F,$81
        fcb     $FF,$00,$42,$C1,$C0,$3F,$81,$FF,$00,$42,$C2,$F0
        fcb     $0F,$0F,$F0,$00
