* chtab5_022_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 28 rows x 7 bytes, 328 segment bytes
*
chtab5_022_p0:
        fcb     28,7  ; height, width in bytes
        fcb     $C2,$FC,$00,$03,$FC,$45,$00,$C1,$C0,$0F,$81,$FF
        fcb     $C1,$0F,$C0,$44,$00,$84,$7F,$FF,$F7,$FF,$C1,$03
        fcb     $F0,$42,$00,$85,$FF,$EF,$FE,$AF,$7F,$C1,$3F,$00
        fcb     $41,$00,$85,$EA,$AF,$FE,$AF,$FF,$C1,$03,$F0,$41
        fcb     $00,$86,$AF,$FE,$AF,$FC,$7E,$AA,$41,$00,$C1,$FC
        fcb     $00,$85,$FF,$FE,$AF,$FF,$AA,$C1,$3F,$00,$00,$41
        fcb     $C2,$C0,$0A,$0C,$80,$83,$EA,$FF,$FF,$C1,$3F,$00
        fcb     $00,$C1,$F0,$03,$81,$FE,$C2,$0F,$80,$F0,$0F,$82
        fcb     $EA,$FF,$C1,$0F,$C0,$00,$C2,$F0,$03,$03,$FC,$41
        fcb     $C1,$FC,$00,$82,$AA,$FF,$C1,$0F,$C0,$00,$C2,$FC
        fcb     $00,$03,$FC,$41,$C1,$FC,$00,$82,$AF,$FF,$C1,$0F
        fcb     $C0,$00,$C2,$F0,$03,$03,$FC,$41,$C1,$F0,$0A,$82
        fcb     $FF,$FF,$C1,$3F,$00,$00,$C1,$F0,$03,$81,$FF,$C1
        fcb     $3C,$00,$83,$FF,$FC,$AF,$41,$00,$C3,$FC,$00,$03
        fcb     $F0,$F0,$03,$82,$FF,$FF,$C1,$03,$F0,$41,$00,$42
        fcb     $C1,$C0,$0F,$82,$FF,$FF,$C1,$3F,$C0,$41,$00,$42
        fcb     $C1,$C0,$0F,$82,$FF,$FC,$42,$00,$42,$C1,$C0,$0F
        fcb     $81,$FF,$C1,$03,$F0,$42,$00,$42,$C1,$C0,$0F,$82
        fcb     $FF,$FC,$42,$00,$42,$C1,$C0,$0F,$82,$FF,$FC,$42
        fcb     $00,$42,$C1,$F0,$03,$82,$FF,$FC,$42,$00,$42,$C1
        fcb     $FC,$00,$82,$FF,$FF,$C1,$3F,$00,$41,$00,$42,$C1
        fcb     $FC,$00,$82,$FF,$FF,$C1,$3F,$00,$41,$00,$43,$C1
        fcb     $F0,$0F,$81,$FF,$C1,$3F,$00,$41,$00,$43,$C1,$F0
        fcb     $0F,$81,$FF,$C1,$3F,$00,$41,$00,$42,$C1,$FC,$00
        fcb     $82,$FF,$FF,$C1,$3F,$C0,$41,$00,$42,$C2,$FC,$00
        fcb     $0F,$F0,$81,$3F,$C1,$03,$F0,$41,$00,$44,$81,$3F
        fcb     $C1,$03,$F0,$41,$00,$43,$C1,$FC,$00,$81,$FF,$C1
        fcb     $3F,$00,$41,$00
