* chtab5_022_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 28 rows x 7 bytes, 288 segment bytes
*
chtab5_022_p0:
        fcb     28,7  ; height, width in bytes
        fcb     $41,$C1,$03,$FC,$45,$00,$C1,$F0,$0F,$81,$FF,$C1
        fcb     $3F,$C0,$44,$00,$84,$7F,$FF,$F7,$FF,$C1,$0F,$F0
        fcb     $42,$00,$85,$FF,$EF,$FE,$AF,$7F,$42,$00,$85,$EA
        fcb     $AF,$FE,$AF,$FF,$C1,$0F,$F0,$41,$00,$85,$AA,$AF
        fcb     $FE,$AF,$7E,$C1,$03,$FC,$41,$00,$41,$85,$FF,$FE
        fcb     $AF,$FF,$AA,$41,$00,$41,$C2,$F0,$0A,$3F,$80,$83
        fcb     $EA,$FF,$FF,$41,$00,$C1,$FC,$03,$81,$FE,$C2,$3F
        fcb     $80,$F0,$0F,$82,$EA,$FF,$C1,$3F,$C0,$00,$C2,$FC
        fcb     $03,$03,$FC,$42,$82,$AA,$FF,$C1,$3F,$C0,$00,$41
        fcb     $C1,$03,$FC,$42,$82,$AF,$FF,$C1,$3F,$C0,$00,$C2
        fcb     $FC,$03,$03,$FC,$41,$C1,$F0,$0A,$82,$FF,$FF,$41
        fcb     $00,$C1,$FC,$03,$81,$FF,$41,$82,$AF,$FF,$C1,$03
        fcb     $FC,$41,$00,$41,$C2,$0F,$F0,$FC,$03,$82,$FF,$FF
        fcb     $C1,$0F,$F0,$41,$00,$42,$C1,$F0,$0F,$82,$FF,$FF
        fcb     $C1,$3F,$C0,$41,$00,$42,$C1,$F0,$0F,$81,$FF,$C1
        fcb     $03,$FC,$42,$00,$42,$C1,$F0,$0F,$81,$FF,$C1,$0F
        fcb     $F0,$42,$00,$42,$C1,$F0,$0F,$81,$FF,$C1,$03,$FC
        fcb     $42,$00,$42,$C1,$F0,$0F,$81,$FF,$C1,$03,$FC,$42
        fcb     $00,$42,$C1,$FC,$03,$81,$FF,$C1,$03,$FC,$42,$00
        fcb     $43,$82,$FF,$FF,$42,$00,$43,$82,$FF,$FF,$42,$00
        fcb     $43,$C1,$F0,$0F,$81,$FF,$42,$00,$43,$C1,$F0,$0F
        fcb     $81,$FF,$42,$00,$43,$82,$FF,$FF,$C1,$3F,$C0,$41
        fcb     $00,$43,$C3,$0F,$F0,$C0,$3F,$0F,$F0,$41,$00,$44
        fcb     $C2,$C0,$3F,$0F,$F0,$41,$00,$44,$81,$FF,$42,$00
