* chtab5_044_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 17 rows x 8 bytes, 195 segment bytes
*
chtab5_044_p0:
        fcb     17,8  ; height, width in bytes
        fcb     $47,$C1,$FC,$01,$00,$44,$81,$FF,$42,$C1,$FC,$01
        fcb     $00,$43,$C1,$FC,$03,$82,$FF,$EF,$41,$C1,$FC,$01
        fcb     $00,$43,$C1,$FC,$03,$82,$FF,$EF,$C2,$3F,$C0,$CF
        fcb     $10,$00,$43,$C1,$FC,$03,$81,$FF,$C3,$0F,$F0,$3F
        fcb     $80,$CF,$10,$00,$42,$C1,$F0,$0F,$82,$FE,$FF,$C1
        fcb     $03,$FC,$41,$C1,$CF,$10,$00,$42,$C1,$F0,$0F,$82
        fcb     $FE,$FF,$C3,$03,$FC,$FC,$01,$0F,$50,$00,$42,$C3
        fcb     $F0,$0F,$03,$FC,$C0,$3F,$81,$FF,$C1,$3C,$C1,$41
        fcb     $00,$42,$C1,$FC,$03,$84,$FF,$FF,$FF,$55,$41,$00
        fcb     $43,$84,$FF,$7F,$FF,$55,$41,$00,$43,$83,$55,$7F
        fcb     $F5,$C1,$0F,$50,$41,$00,$43,$83,$7F,$EF,$F5,$42
        fcb     $00,$42,$C2,$FC,$03,$3C,$C3,$82,$FF,$F7,$C1,$3F
        fcb     $C0,$41,$00,$41,$C1,$FC,$01,$84,$57,$FF,$FF,$F7
        fcb     $C1,$3F,$C0,$41,$00,$C1,$FC,$01,$84,$55,$57,$FF
        fcb     $FF,$C1,$0F,$F0,$42,$00,$C1,$FC,$01,$84,$55,$57
        fcb     $FF,$FF,$C1,$0F,$F0,$42,$00,$43,$C1,$C0,$3F,$81
        fcb     $FF,$43,$00
