* chtab5_020_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 20 rows x 7 bytes, 246 segment bytes
*
chtab5_020_p0:
        fcb     20,7  ; height, width in bytes
        fcb     $41,$C2,$C0,$3F,$0F,$F0,$44,$00,$41,$81,$FF,$C2
        fcb     $03,$FC,$C0,$3F,$81,$FF,$C1,$3F,$C0,$41,$00,$C1
        fcb     $FC,$03,$85,$FF,$F5,$7F,$FF,$FF,$41,$00,$C1,$F0
        fcb     $0F,$85,$F7,$F5,$57,$FF,$FF,$C1,$3F,$C0,$00,$C1
        fcb     $F0,$0F,$85,$57,$FF,$55,$7F,$55,$C1,$0F,$F0,$00
        fcb     $41,$C1,$C0,$15,$84,$55,$7F,$F5,$57,$C1,$03,$FC
        fcb     $00,$41,$C1,$FC,$01,$85,$7F,$55,$7F,$FF,$55,$00
        fcb     $42,$C1,$FC,$01,$84,$55,$7F,$FF,$FF,$00,$42,$C1
        fcb     $C0,$17,$83,$FF,$FF,$F7,$C1,$03,$FC,$00,$42,$C1
        fcb     $C0,$17,$83,$FF,$FF,$F7,$C1,$0F,$F0,$00,$C4,$FC
        fcb     $01,$FC,$01,$0F,$50,$3C,$83,$82,$FF,$FF,$C1,$3F
        fcb     $C0,$00,$81,$7F,$C1,$FC,$01,$41,$82,$F7,$FF,$C1
        fcb     $0F,$F0,$41,$00,$C1,$F0,$0F,$81,$55,$41,$C1,$C0
        fcb     $3F,$81,$FF,$C1,$0F,$F0,$41,$00,$C2,$FC,$01,$0F
        fcb     $50,$41,$C1,$F0,$0F,$81,$FF,$C1,$0F,$F0,$41,$00
        fcb     $C2,$F0,$0F,$0F,$F0,$42,$81,$FF,$C1,$0F,$F0,$41
        fcb     $00,$81,$7F,$C1,$0F,$F0,$42,$81,$FF,$C1,$0F,$F0
        fcb     $41,$00,$81,$7F,$C1,$3F,$C0,$41,$C1,$FC,$03,$81
        fcb     $FF,$C1,$0F,$F0,$41,$00,$43,$C3,$F0,$0F,$3F,$C0
        fcb     $0F,$F0,$41,$00,$45,$C1,$03,$FC,$41,$00,$44,$C2
        fcb     $F0,$0F,$0F,$F0,$41,$00
