* chtab5_021_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 24 rows x 7 bytes, 285 segment bytes
*
chtab5_021_p0:
        fcb     24,7  ; height, width in bytes
        fcb     $41,$81,$FF,$C1,$3F,$C0,$44,$00,$C1,$FC,$03,$81
        fcb     $FF,$C2,$03,$FC,$C0,$3F,$81,$FF,$42,$00,$C1,$F0
        fcb     $0F,$84,$FF,$FE,$F5,$7F,$C1,$0F,$F0,$41,$00,$86
        fcb     $57,$F5,$57,$FF,$7F,$F5,$41,$00,$86,$55,$7F,$57
        fcb     $FF,$7F,$55,$C1,$3F,$C0,$00,$41,$C1,$C0,$15,$84
        fcb     $55,$7F,$55,$7F,$C1,$0F,$F0,$00,$42,$C1,$C0,$17
        fcb     $83,$F5,$7F,$FF,$C1,$03,$FC,$00,$42,$C2,$CF,$10
        fcb     $F0,$0F,$82,$F5,$7F,$C1,$03,$FC,$00,$42,$C2,$CF
        fcb     $10,$FC,$03,$82,$F5,$7F,$C1,$03,$FC,$00,$C1,$FC
        fcb     $03,$81,$F5,$41,$C1,$C0,$3F,$82,$57,$FF,$C1,$03
        fcb     $FC,$00,$C1,$FC,$03,$81,$F5,$C1,$FC,$03,$83,$7F
        fcb     $FF,$F5,$C1,$0F,$F0,$00,$C1,$FC,$03,$81,$F5,$C2
        fcb     $FC,$03,$3C,$C3,$82,$FF,$FF,$41,$00,$C3,$FC,$03
        fcb     $03,$FC,$FC,$03,$82,$EF,$FF,$C1,$0F,$F0,$41,$00
        fcb     $C1,$FC,$03,$81,$FF,$C1,$FC,$03,$82,$EF,$FF,$C1
        fcb     $3F,$C0,$41,$00,$C2,$FC,$03,$03,$FC,$41,$82,$AF
        fcb     $FF,$C1,$3F,$C0,$41,$00,$43,$C1,$C0,$3F,$81,$FF
        fcb     $C1,$0F,$F0,$41,$00,$43,$C1,$F0,$0F,$81,$FF,$C1
        fcb     $0F,$F0,$41,$00,$43,$C1,$FC,$03,$81,$FF,$C1,$0F
        fcb     $F0,$41,$00,$43,$C1,$FC,$03,$81,$FF,$C1,$0F,$F0
        fcb     $41,$00,$43,$C1,$C0,$3F,$81,$FF,$C1,$0F,$F0,$41
        fcb     $00,$43,$C3,$C0,$3F,$FC,$03,$03,$FC,$41,$00,$44
        fcb     $C2,$FC,$03,$03,$FC,$41,$00,$44,$C2,$C0,$3F,$0F
        fcb     $F0,$41,$00,$44,$C1,$CF,$10,$42,$00
