* chtab5_045_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 16 rows x 9 bytes, 213 segment bytes
*
chtab5_045_p0:
        fcb     16,9  ; height, width in bytes
        fcb     $45,$C2,$FC,$03,$0F,$F0,$42,$00,$44,$C3,$C0,$3F
        fcb     $FC,$03,$03,$FC,$42,$00,$44,$81,$FF,$C2,$FC,$03
        fcb     $03,$FC,$42,$00,$44,$81,$FF,$41,$C1,$CF,$10,$42
        fcb     $00,$42,$C1,$F0,$0F,$82,$FF,$7F,$C2,$FC,$03,$0F
        fcb     $F0,$42,$00,$42,$C1,$F0,$0F,$81,$FF,$C3,$0F,$F0
        fcb     $F0,$0F,$03,$FC,$42,$00,$42,$C1,$FC,$03,$81,$FF
        fcb     $C3,$3F,$C0,$F0,$0F,$03,$FC,$42,$00,$42,$C1,$FC
        fcb     $03,$81,$FF,$C3,$0F,$F0,$C0,$3F,$03,$FC,$42,$00
        fcb     $43,$83,$7F,$FF,$FF,$C1,$3F,$C0,$42,$00,$41,$C2
        fcb     $FC,$01,$0F,$50,$83,$57,$FF,$F5,$C1,$3F,$C0,$41
        fcb     $C1,$C0,$15,$00,$41,$C2,$FC,$01,$0F,$50,$83,$57
        fcb     $FF,$F5,$C1,$3F,$C0,$41,$C1,$C0,$15,$00,$41,$C4
        fcb     $C0,$15,$FC,$03,$3C,$C1,$0F,$50,$81,$FF,$C3,$3F
        fcb     $C0,$FC,$01,$0F,$50,$00,$C1,$C0,$15,$85,$57,$FF
        fcb     $FF,$F7,$55,$C1,$3C,$C1,$81,$55,$41,$00,$C1,$C0
        fcb     $15,$86,$FF,$FF,$F5,$55,$55,$7F,$C1,$0F,$50,$41
        fcb     $00,$41,$C1,$C0,$15,$85,$FF,$FE,$F5,$55,$7F,$42
        fcb     $00,$43,$C1,$C0,$3F,$81,$FF,$44,$00
