* chtab5_020_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 20 rows x 7 bytes, 243 segment bytes
*
chtab5_020_p0:
        fcb     20,7  ; height, width in bytes
        fcb     $41,$81,$3F,$C1,$03,$F0,$44,$00,$C1,$FC,$00,$84
        fcb     $FF,$FC,$3F,$FF,$C1,$3F,$C0,$41,$00,$C1,$F0,$03
        fcb     $85,$FF,$F5,$7F,$FF,$FF,$C1,$3F,$00,$00,$C1,$C0
        fcb     $0F,$85,$F7,$F5,$57,$FF,$FF,$C1,$0F,$C0,$00,$C1
        fcb     $C0,$0F,$85,$57,$FF,$55,$7F,$55,$C1,$03,$F0,$00
        fcb     $41,$86,$7F,$F5,$57,$FC,$15,$55,$00,$41,$C1,$FC
        fcb     $01,$85,$7F,$55,$7F,$FF,$55,$00,$42,$C1,$F0,$01
        fcb     $84,$55,$7F,$FF,$FF,$00,$42,$85,$F7,$FF,$FF,$FC
        fcb     $17,$00,$42,$84,$17,$F7,$FF,$FF,$C1,$03,$F0,$00
        fcb     $C2,$F0,$01,$3C,$01,$84,$50,$83,$FF,$FF,$C1,$0F
        fcb     $C0,$00,$81,$7F,$C2,$3C,$01,$3C,$00,$82,$F7,$FF
        fcb     $C1,$03,$F0,$41,$00,$C1,$C0,$0F,$81,$55,$C1,$3F
        fcb     $00,$82,$3F,$FF,$C1,$03,$F0,$41,$00,$C2,$F0,$01
        fcb     $03,$50,$41,$C1,$F0,$0F,$81,$FF,$C1,$03,$F0,$41
        fcb     $00,$C2,$C0,$0F,$03,$F0,$41,$C1,$FC,$00,$81,$FF
        fcb     $C1,$03,$F0,$41,$00,$81,$7F,$C1,$03,$F0,$41,$C1
        fcb     $FC,$00,$81,$FF,$C1,$03,$F0,$41,$00,$81,$7F,$C1
        fcb     $0F,$C0,$41,$C1,$F0,$03,$81,$FF,$C1,$03,$F0,$41
        fcb     $00,$43,$C3,$F0,$0F,$0C,$C0,$03,$F0,$41,$00,$44
        fcb     $C1,$FC,$00,$81,$FC,$41,$00,$44,$C2,$C0,$0F,$03
        fcb     $F0,$41,$00
