* chtab5_044_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 17 rows x 9 bytes, 216 segment bytes
*
chtab5_044_p0:
        fcb     17,9  ; height, width in bytes
        fcb     $47,$C2,$F0,$01,$3F,$00,$00,$43,$C1,$FC,$00,$81
        fcb     $FF,$C1,$3F,$00,$41,$C2,$F0,$01,$3F,$00,$00,$43
        fcb     $C1,$F0,$03,$82,$FF,$EF,$C3,$3F,$00,$F0,$01,$3F
        fcb     $00,$00,$43,$C1,$F0,$03,$82,$FF,$EF,$C2,$0F,$C0
        fcb     $03,$10,$41,$00,$43,$C1,$F0,$03,$82,$FF,$F0,$C2
        fcb     $0F,$80,$03,$10,$41,$00,$42,$C1,$C0,$0F,$83,$FF
        fcb     $FC,$FE,$41,$C1,$03,$10,$41,$00,$42,$C1,$C0,$0F
        fcb     $83,$FF,$FC,$FE,$C2,$F0,$01,$03,$50,$41,$00,$42
        fcb     $C1,$C0,$0F,$84,$FC,$3F,$FF,$C1,$42,$00,$42,$C1
        fcb     $F0,$03,$84,$FF,$FF,$FF,$55,$42,$00,$42,$C1,$FC
        fcb     $00,$84,$FF,$7F,$FF,$55,$42,$00,$42,$C1,$FC,$00
        fcb     $83,$55,$7F,$F5,$C1,$03,$50,$42,$00,$42,$C1,$FC
        fcb     $00,$83,$7F,$EF,$F5,$C1,$3F,$00,$42,$00,$42,$C1
        fcb     $F0,$03,$83,$FF,$F7,$C3,$C1,$0F,$C0,$42,$00,$41
        fcb     $C1,$FC,$01,$84,$57,$FF,$FF,$F7,$C1,$0F,$C0,$42
        fcb     $00,$C1,$F0,$01,$84,$55,$57,$FF,$FF,$C1,$03,$F0
        fcb     $43,$00,$C1,$F0,$01,$84,$55,$57,$FF,$FF,$C1,$03
        fcb     $F0,$43,$00,$43,$82,$3F,$FF,$C1,$3F,$00,$43,$00
