* chtab4fat_003_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 36 rows x 11 bytes, 464 segment bytes
*
chtab4fat_003_p0:
        fcb     36,11  ; height, width in bytes
        fcb     $44,$81,$FF,$C1,$3F,$C0,$45,$00,$43,$C1,$F0,$0F
        fcb     $82,$FF,$FF,$45,$00,$43,$C1,$F0,$0F,$82,$FF,$FF
        fcb     $C1,$3F,$C0,$44,$00,$43,$C1,$FC,$03,$82,$FF,$FF
        fcb     $C1,$3F,$C0,$44,$00,$43,$C1,$F0,$0A,$82,$FF,$FF
        fcb     $C1,$3F,$C0,$44,$00,$44,$C1,$C0,$3F,$81,$FF,$45
        fcb     $00,$43,$C1,$FC,$01,$82,$57,$FF,$45,$00,$43,$C1
        fcb     $FC,$01,$82,$7F,$FF,$C1,$3F,$C0,$44,$00,$43,$C1
        fcb     $C0,$3F,$82,$FF,$FF,$C1,$0F,$F0,$44,$00,$42,$84
        fcb     $AA,$FF,$FF,$FF,$C1,$03,$FC,$44,$00,$C1,$FC,$01
        fcb     $85,$AA,$AF,$FF,$FF,$7E,$C1,$03,$FC,$44,$00,$C1
        fcb     $FC,$01,$86,$AF,$FF,$FF,$FF,$7E,$AA,$44,$00,$42
        fcb     $84,$AA,$AF,$FF,$FF,$C1,$03,$FC,$44,$00,$42,$C1
        fcb     $FC,$03,$84,$FF,$FF,$FF,$FE,$C1,$3F,$80,$43,$00
        fcb     $42,$C1,$FC,$03,$84,$FF,$FF,$FF,$FE,$C1,$3F,$80
        fcb     $43,$00,$42,$C1,$FC,$03,$84,$FF,$F5,$55,$55,$44
        fcb     $00,$43,$C3,$C0,$15,$0F,$50,$C0,$15,$81,$7F,$44
        fcb     $00,$43,$84,$AA,$AA,$FF,$FF,$C1,$3F,$C0,$43,$00
        fcb     $43,$84,$AA,$AA,$AF,$FF,$C1,$3F,$C0,$43,$00,$43
        fcb     $84,$AA,$AA,$AF,$FF,$C1,$3F,$C0,$43,$00,$42,$C1
        fcb     $F0,$0A,$84,$AA,$AA,$AA,$FF,$C1,$0F,$F0,$43,$00
        fcb     $42,$C1,$F0,$0A,$84,$AA,$AA,$AA,$FF,$C1,$0F,$F0
        fcb     $43,$00,$42,$C1,$F0,$0A,$84,$AA,$AA,$AA,$FF,$C1
        fcb     $03,$FC,$43,$00,$42,$C1,$F0,$0A,$85,$AA,$AA,$FF
        fcb     $FF,$AA,$43,$00,$42,$86,$AA,$AA,$AF,$FF,$AA,$AA
        fcb     $43,$00,$42,$82,$AA,$AA,$C2,$03,$A8,$F0,$0A,$82
        fcb     $AF,$FF,$C1,$3F,$C0,$42,$00,$42,$82,$AA,$AA,$C2
        fcb     $03,$A8,$F0,$0A,$82,$AA,$FF,$C1,$0F,$F0,$42,$00
        fcb     $42,$82,$AA,$AA,$C1,$03,$A8,$41,$82,$AA,$FF,$C1
        fcb     $03,$FC,$42,$00,$42,$82,$AA,$AA,$C2,$3F,$80,$FC
        fcb     $03,$83,$AF,$FF,$EA,$C1,$3F,$C0,$41,$00,$42,$82
        fcb     $AA,$AA,$C1,$3F,$80,$41,$83,$AA,$FF,$FE,$C1,$0F
        fcb     $F0,$41,$00,$42,$C2,$F0,$0A,$03,$A8,$42,$83,$EA
        fcb     $FF,$FF,$C1,$0F,$F0,$41,$00,$42,$C2,$F0,$0A,$3F
        fcb     $80,$42,$84,$FF,$FF,$EA,$FF,$C1,$3F,$C0,$00,$42
        fcb     $C2,$F0,$0F,$3F,$C0,$42,$81,$FF,$C1,$0F,$F0,$41
        fcb     $C2,$C0,$3F,$0F,$F0,$00,$42,$81,$FF,$C1,$3F,$C0
        fcb     $45,$C2,$F0,$0F,$0F,$F0,$00,$41,$82,$FF,$FF,$C1
        fcb     $3F,$C0,$45,$C2,$F0,$0F,$3F,$C0,$00,$41,$C1,$C0
        fcb     $3F,$81,$FF,$C1,$3F,$C0,$47,$00
