* chtab4fat_030_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 22 rows x 6 bytes, 223 segment bytes
*
chtab4fat_030_p0:
        fcb     22,6  ; height, width in bytes
        fcb     $83,$0F,$FC,$15,$43,$00,$83,$FF,$FF,$17,$C1,$0F
        fcb     $F0,$42,$00,$C1,$F0,$03,$83,$FF,$FC,$FF,$42,$00
        fcb     $C1,$F0,$01,$83,$FF,$FC,$7F,$42,$00,$C1,$FC,$00
        fcb     $83,$FF,$FC,$AF,$42,$00,$41,$C1,$FC,$03,$81,$FF
        fcb     $C1,$0F,$F0,$42,$00,$41,$82,$17,$FF,$C1,$0F,$C0
        fcb     $42,$00,$41,$83,$7F,$FC,$15,$42,$00,$C1,$FC,$00
        fcb     $83,$FF,$FF,$FF,$C1,$0F,$C0,$41,$00,$41,$C1,$C0
        fcb     $0F,$82,$FF,$FF,$C1,$03,$F0,$41,$00,$C1,$F0,$03
        fcb     $84,$FF,$FF,$FF,$FC,$41,$00,$C1,$C0,$0F,$84,$FF
        fcb     $FF,$FF,$FC,$41,$00,$C1,$C0,$0F,$84,$FF,$FF,$FF
        fcb     $FC,$41,$00,$85,$FF,$FF,$FF,$F5,$7F,$C1,$3F,$00
        fcb     $00,$85,$FF,$EA,$FF,$F5,$7F,$C1,$3F,$00,$00,$85
        fcb     $FF,$0A,$AF,$57,$7F,$C1,$3F,$C0,$00,$C1,$C0,$0F
        fcb     $84,$FF,$EA,$AF,$57,$C1,$3F,$C0,$00,$C1,$FC,$00
        fcb     $84,$AA,$FE,$AA,$FF,$C1,$3F,$C0,$00,$C1,$C0,$0A
        fcb     $84,$AA,$FE,$AA,$FF,$C1,$3F,$C0,$00,$C1,$C0,$0A
        fcb     $84,$AA,$AA,$AA,$FF,$C1,$3F,$00,$00,$C1,$C0,$0A
        fcb     $84,$F5,$0A,$AF,$FF,$C1,$3F,$00,$00,$C1,$C0,$0A
        fcb     $84,$F5,$7E,$AF,$FC,$41,$00
