* chtab4fat_028_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 35 rows x 5 bytes, 327 segment bytes
*
chtab4fat_028_p0:
        fcb     35,5  ; height, width in bytes
        fcb     $C1,$FC,$00,$81,$FF,$C1,$0F,$C0,$42,$00,$C1,$C0
        fcb     $0F,$82,$FF,$FF,$C1,$3F,$00,$41,$00,$C1,$C0,$0F
        fcb     $82,$FF,$FF,$C1,$0F,$C0,$41,$00,$C1,$F0,$03,$82
        fcb     $FF,$FF,$C1,$0F,$C0,$41,$00,$C1,$C0,$0A,$82,$FF
        fcb     $FF,$C1,$0F,$C0,$41,$00,$41,$82,$3F,$FF,$C1,$3F
        fcb     $00,$41,$00,$C1,$F0,$01,$82,$7F,$FC,$42,$00,$C1
        fcb     $F0,$01,$81,$57,$C1,$03,$F0,$42,$00,$C1,$C0,$0F
        fcb     $81,$FF,$C1,$03,$F0,$42,$00,$C1,$FC,$00,$82,$FF
        fcb     $FC,$42,$00,$C1,$F0,$03,$82,$FF,$FF,$C1,$3F,$00
        fcb     $41,$00,$C1,$C0,$0F,$82,$FF,$FF,$C1,$3F,$00,$41
        fcb     $00,$C1,$C0,$0F,$82,$FF,$FF,$C1,$0F,$C0,$41,$00
        fcb     $83,$FF,$FF,$7F,$C1,$0F,$F0,$41,$00,$83,$EA,$83
        fcb     $7F,$C1,$0F,$F0,$41,$00,$84,$7F,$EA,$AF,$FC,$41
        fcb     $00,$84,$FF,$EA,$AF,$FC,$41,$00,$83,$EA,$AF,$FF
        fcb     $C1,$0F,$50,$41,$00,$84,$15,$0A,$81,$55,$C1,$3F
        fcb     $00,$00,$81,$15,$C1,$03,$08,$82,$17,$FF,$C1,$3F
        fcb     $00,$00,$84,$AF,$0A,$FF,$FF,$C1,$3F,$00,$00,$84
        fcb     $A8,$15,$0F,$FF,$C1,$3F,$00,$00,$84,$A8,$15,$0A
        fcb     $FF,$C1,$3F,$00,$00,$84,$A8,$15,$0A,$FF,$C1,$3F
        fcb     $00,$00,$84,$AA,$AA,$A8,$3C,$41,$00,$84,$AA,$AA
        fcb     $AA,$FC,$41,$00,$84,$AA,$AA,$83,$FF,$C1,$3F,$00
        fcb     $00,$84,$AA,$AA,$AF,$FF,$C1,$03,$F0,$00,$84,$AA
        fcb     $AA,$83,$FF,$C1,$0F,$C0,$00,$82,$AA,$AA,$C1,$0F
        fcb     $80,$81,$3F,$C1,$3F,$00,$00,$C1,$C0,$0A,$82,$AA
        fcb     $A8,$42,$00,$C1,$C0,$0A,$82,$AA,$A8,$42,$00,$41
        fcb     $C1,$C0,$0A,$81,$FC,$42,$00,$41,$82,$3F,$FF,$C1
        fcb     $3F,$00,$41,$00,$C1,$FC,$00,$82,$FF,$FF,$C1,$3F
        fcb     $00,$41,$00
