* chtab4fat_003_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 36 rows x 11 bytes, 514 segment bytes
*
chtab4fat_003_p0:
        fcb     36,11  ; height, width in bytes
        fcb     $43,$C1,$FC,$00,$81,$FF,$C1,$3F,$C0,$45,$00,$43
        fcb     $C1,$F0,$0F,$82,$FF,$FF,$C1,$3F,$00,$44,$00,$43
        fcb     $C1,$F0,$0F,$82,$FF,$FF,$C1,$0F,$C0,$44,$00,$43
        fcb     $C1,$F0,$03,$82,$FF,$FF,$C1,$0F,$C0,$44,$00,$43
        fcb     $C1,$F0,$0A,$82,$FF,$FF,$C1,$0F,$C0,$44,$00,$44
        fcb     $82,$3F,$FF,$C1,$3F,$00,$44,$00,$43,$C1,$F0,$01
        fcb     $82,$57,$FF,$C1,$3F,$00,$44,$00,$43,$C1,$F0,$01
        fcb     $82,$7F,$FF,$C1,$0F,$C0,$44,$00,$43,$83,$FF,$FF
        fcb     $3F,$C1,$03,$F0,$44,$00,$41,$C1,$FC,$00,$85,$FF
        fcb     $FF,$FF,$FC,$AA,$44,$00,$C1,$F0,$01,$86,$AF,$FF
        fcb     $FF,$FC,$7E,$AA,$44,$00,$C1,$F0,$01,$86,$AF,$FF
        fcb     $FF,$FF,$7E,$AA,$44,$00,$41,$C1,$FC,$00,$85,$AF
        fcb     $FF,$FF,$FC,$AA,$44,$00,$42,$C1,$F0,$03,$84,$FF
        fcb     $FF,$FF,$FE,$C1,$0F,$80,$43,$00,$42,$C1,$F0,$03
        fcb     $84,$FF,$FF,$FF,$FE,$C1,$0F,$80,$43,$00,$42,$C1
        fcb     $F0,$03,$84,$FF,$F5,$55,$55,$44,$00,$43,$81,$15
        fcb     $C2,$03,$50,$C0,$15,$81,$7F,$44,$00,$42,$C1,$FC
        fcb     $00,$84,$AA,$AA,$FF,$FF,$C1,$0F,$C0,$43,$00,$42
        fcb     $C1,$FC,$00,$84,$AA,$AA,$AF,$FF,$C1,$0F,$C0,$43
        fcb     $00,$42,$C1,$FC,$00,$84,$AA,$AA,$AF,$FF,$C1,$0F
        fcb     $C0,$43,$00,$42,$C1,$C0,$0A,$84,$AA,$AA,$AA,$FF
        fcb     $C1,$03,$F0,$43,$00,$42,$C1,$C0,$0A,$84,$AA,$AA
        fcb     $AA,$FF,$C1,$03,$F0,$43,$00,$42,$C1,$C0,$0A,$85
        fcb     $AA,$AA,$FF,$FC,$AA,$43,$00,$42,$C1,$C0,$0A,$85
        fcb     $AA,$AA,$FF,$FF,$AA,$C1,$3F,$00,$42,$00,$41,$C1
        fcb     $FC,$00,$86,$AA,$AA,$AF,$FF,$AA,$AA,$C1,$3F,$00
        fcb     $42,$00,$41,$C1,$FC,$00,$83,$AA,$A8,$AA,$C1,$C0
        fcb     $0A,$82,$AF,$FF,$C1,$0F,$C0,$42,$00,$41,$C1,$FC
        fcb     $00,$83,$AA,$A8,$AA,$C1,$C0,$0A,$82,$AA,$FF,$C1
        fcb     $03,$F0,$42,$00,$41,$C1,$FC,$00,$83,$AA,$A8,$AA
        fcb     $C1,$FC,$00,$82,$AA,$FF,$C1,$03,$FC,$42,$00,$41
        fcb     $C1,$FC,$00,$82,$AA,$AA,$C2,$0F,$80,$F0,$03,$83
        fcb     $AF,$FF,$EA,$C1,$0F,$C0,$41,$00,$41,$C1,$FC,$00
        fcb     $82,$AA,$AA,$C2,$0F,$80,$FC,$00,$83,$AA,$FF,$FE
        fcb     $C1,$03,$F0,$41,$00,$42,$C1,$C0,$0A,$81,$A8,$41
        fcb     $C1,$FC,$00,$83,$EA,$FF,$FF,$C1,$03,$F0,$41,$00
        fcb     $42,$C2,$C0,$0A,$0F,$80,$41,$C1,$FC,$00,$84,$FF
        fcb     $FF,$EA,$FF,$C1,$0F,$C0,$00,$42,$C2,$C0,$0F,$0F
        fcb     $C0,$41,$C1,$FC,$00,$81,$FF,$C1,$03,$F0,$41,$81
        fcb     $3F,$C1,$0F,$F0,$00,$41,$C1,$FC,$00,$81,$FF,$C1
        fcb     $0F,$C0,$45,$C2,$C0,$0F,$0F,$F0,$00,$C1,$FC,$00
        fcb     $82,$FF,$FF,$C1,$0F,$C0,$45,$C2,$C0,$0F,$0F,$C0
        fcb     $00,$41,$82,$3F,$FF,$C1,$0F,$C0,$47,$00
