* chtab4fat_004_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 33 rows x 13 bytes, 509 segment bytes
*
chtab4fat_004_p0:
        fcb     33,13  ; height, width in bytes
        fcb     $43,$C1,$FC,$00,$81,$FF,$C1,$3F,$C0,$47,$00,$43
        fcb     $C1,$F0,$0F,$82,$FF,$FF,$C1,$3F,$00,$46,$00,$43
        fcb     $C1,$F0,$0F,$82,$FF,$FF,$C1,$0F,$C0,$46,$00,$43
        fcb     $C1,$F0,$03,$82,$FF,$FF,$C1,$0F,$C0,$46,$00,$43
        fcb     $C1,$F0,$0A,$82,$FF,$FF,$C1,$0F,$C0,$46,$00,$44
        fcb     $83,$FF,$FC,$3F,$46,$00,$C2,$F0,$01,$03,$50,$41
        fcb     $84,$3F,$FF,$FF,$FF,$C1,$0F,$C0,$45,$00,$C1,$F0
        fcb     $01,$87,$FF,$FF,$FF,$FE,$AA,$AF,$50,$C1,$0F,$80
        fcb     $44,$00,$41,$C1,$FC,$00,$86,$FF,$FF,$FF,$F0,$AA
        fcb     $AF,$C1,$03,$A8,$44,$00,$41,$C1,$FC,$00,$87,$FF
        fcb     $FF,$EA,$AF,$AA,$FF,$AA,$C1,$03,$50,$43,$00,$42
        fcb     $C1,$C0,$0A,$85,$FF,$FF,$FF,$FE,$AA,$C1,$03,$A8
        fcb     $81,$15,$C1,$3F,$00,$42,$00,$43,$C1,$F0,$0F,$84
        fcb     $FF,$FF,$FF,$FE,$C1,$0F,$80,$81,$15,$C1,$3F,$00
        fcb     $42,$00,$43,$84,$3F,$FF,$FF,$F5,$C1,$03,$50,$45
        fcb     $00,$43,$84,$3F,$FF,$F5,$55,$C1,$03,$50,$45,$00
        fcb     $43,$C1,$F0,$01,$84,$55,$55,$7F,$FF,$C1,$0F,$C0
        fcb     $44,$00,$43,$C2,$F0,$0A,$0C,$80,$83,$FF,$FF,$AF
        fcb     $C1,$0F,$C0,$44,$00,$43,$C1,$F0,$0A,$84,$AA,$AA
        fcb     $AF,$FF,$C1,$03,$FC,$44,$00,$43,$C1,$F0,$0A,$84
        fcb     $AA,$AA,$AF,$FF,$C1,$03,$FC,$44,$00,$43,$C1,$F0
        fcb     $0A,$85,$AA,$AA,$FF,$FF,$AA,$C1,$3F,$00,$43,$00
        fcb     $42,$C1,$FC,$00,$86,$AA,$AA,$FF,$FF,$AA,$AA,$C1
        fcb     $3F,$00,$43,$00,$42,$C1,$FC,$00,$86,$AA,$AA,$FF
        fcb     $FF,$AA,$AA,$C1,$0F,$C0,$43,$00,$42,$C1,$FC,$00
        fcb     $86,$AA,$AA,$AF,$FF,$AA,$AA,$C1,$0F,$C0,$43,$00
        fcb     $42,$C1,$FC,$00,$86,$AA,$AA,$AF,$FF,$AA,$AA,$C1
        fcb     $03,$F0,$43,$00,$42,$C1,$FC,$00,$82,$AA,$AA,$C2
        fcb     $3C,$80,$03,$F0,$83,$FF,$FC,$AA,$43,$00,$43,$C1
        fcb     $F0,$0A,$81,$AA,$C2,$3C,$80,$03,$F0,$83,$FF,$FF
        fcb     $AA,$C1,$0F,$C0,$42,$00,$43,$C1,$F0,$0A,$81,$AA
        fcb     $C1,$3C,$80,$85,$EA,$AF,$FF,$FC,$FF,$42,$00,$43
        fcb     $C1,$F0,$0A,$81,$A8,$C1,$F0,$03,$85,$FE,$AF,$FF
        fcb     $FF,$FF,$C1,$0F,$C0,$41,$00,$43,$C1,$F0,$0A,$81
        fcb     $A8,$C1,$F0,$03,$86,$EA,$FF,$FE,$AF,$FF,$FF,$C1
        fcb     $3F,$C0,$00,$43,$C1,$FC,$00,$81,$A8,$C1,$C0,$0F
        fcb     $86,$EA,$AA,$AA,$AF,$FF,$FF,$C1,$3F,$C0,$00,$43
        fcb     $C3,$F0,$0F,$03,$F0,$C0,$0F,$86,$FF,$F0,$A8,$3F
        fcb     $FF,$FF,$C1,$3F,$C0,$00,$43,$81,$3F,$C2,$03,$F0
        fcb     $C0,$0F,$83,$FF,$FF,$FF,$C1,$3F,$00,$41,$81,$3F
        fcb     $C1,$3F,$00,$00,$42,$C1,$F0,$03,$82,$FF,$FC,$42
        fcb     $81,$FF,$C1,$03,$F0,$42,$81,$3C,$41,$00,$42,$83
        fcb     $FF,$FC,$3F,$48,$00
