* chtab4fat_031_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 17 rows x 8 bytes, 205 segment bytes
*
chtab4fat_031_p0:
        fcb     17,8  ; height, width in bytes
        fcb     $47,$C1,$C0,$15,$00,$47,$C1,$C0,$15,$00,$47,$C1
        fcb     $C0,$3F,$00,$43,$C1,$F0,$0F,$81,$FF,$C1,$3F,$C0
        fcb     $41,$C1,$03,$A8,$00,$43,$83,$FF,$FF,$FF,$41,$C1
        fcb     $03,$A8,$00,$42,$C1,$F0,$0F,$83,$FF,$FF,$FF,$C2
        fcb     $3F,$C0,$03,$A8,$00,$42,$C1,$F0,$0F,$83,$FF,$FF
        fcb     $FF,$C2,$3F,$C0,$03,$A8,$00,$42,$C1,$C0,$3F,$84
        fcb     $FF,$FF,$FF,$FE,$C1,$03,$A8,$00,$42,$C1,$C0,$3F
        fcb     $84,$FF,$FF,$FF,$FE,$C1,$03,$A8,$00,$42,$C1,$C0
        fcb     $3F,$84,$FF,$57,$FF,$FF,$C1,$03,$E8,$00,$42,$C1
        fcb     $C0,$3F,$81,$F5,$C2,$F3,$08,$FC,$03,$81,$FF,$C1
        fcb     $03,$FC,$00,$41,$C3,$C0,$17,$03,$FC,$C0,$17,$81
        fcb     $FF,$C1,$0F,$F0,$81,$FF,$C1,$0F,$F0,$00,$C1,$F0
        fcb     $0A,$86,$FF,$FF,$FE,$FF,$AF,$FE,$C1,$0F,$F0,$00
        fcb     $C1,$F0,$0A,$86,$FF,$FF,$FE,$FF,$AF,$F7,$C1,$3F
        fcb     $C0,$00,$C1,$F0,$0A,$85,$F7,$FF,$FF,$FE,$AF,$C1
        fcb     $03,$FC,$41,$00,$41,$85,$F7,$FF,$FF,$F7,$AF,$C1
        fcb     $3F,$C0,$41,$00,$42,$C1,$C0,$3E,$82,$FF,$FF,$43
        fcb     $00
