* chtab4fat_027_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 40 rows x 4 bytes, 350 segment bytes
*
chtab4fat_027_p0:
        fcb     40,4  ; height, width in bytes
        fcb     $C1,$FC,$00,$81,$FF,$C1,$0F,$C0,$41,$00,$C1,$C0
        fcb     $0F,$82,$FF,$FF,$C1,$3F,$00,$00,$C1,$C0,$0F,$82
        fcb     $FF,$FF,$C1,$0F,$C0,$00,$C1,$F0,$03,$82,$FF,$FF
        fcb     $C1,$0F,$C0,$00,$C1,$C0,$0A,$82,$FF,$FF,$C1,$0F
        fcb     $C0,$00,$41,$82,$3F,$FF,$C1,$3F,$00,$00,$C1,$F0
        fcb     $01,$82,$7F,$FC,$41,$00,$C1,$F0,$01,$81,$57,$C1
        fcb     $03,$F0,$41,$00,$C1,$C0,$0F,$81,$FF,$C1,$03,$F0
        fcb     $41,$00,$C1,$FC,$00,$81,$FF,$C1,$03,$F0,$41,$00
        fcb     $C1,$FC,$00,$82,$FF,$FF,$C1,$3F,$00,$00,$C1,$F0
        fcb     $03,$82,$FF,$FF,$C1,$3F,$00,$00,$C1,$C0,$0F,$82
        fcb     $FF,$FF,$C1,$0F,$C0,$00,$C1,$C0,$0F,$82,$FF,$FF
        fcb     $C1,$0F,$C0,$00,$83,$FF,$FF,$7F,$C1,$0F,$F0,$00
        fcb     $83,$EA,$FF,$7F,$C1,$0F,$F0,$00,$83,$EA,$FF,$7F
        fcb     $C1,$0F,$F0,$00,$84,$FF,$EA,$FF,$FC,$00,$83,$EA
        fcb     $F5,$FF,$C1,$0F,$50,$00,$81,$FF,$C1,$03,$E8,$81
        fcb     $15,$C1,$0F,$50,$00,$81,$15,$C1,$03,$08,$82,$15
        fcb     $7C,$00,$84,$17,$EA,$FF,$FC,$00,$84,$AF,$57,$FF
        fcb     $FC,$00,$84,$AF,$57,$FF,$FC,$00,$84,$81,$57,$FF
        fcb     $FC,$00,$83,$AA,$FF,$AA,$C1,$0F,$F0,$00,$83,$AA
        fcb     $FF,$AA,$C1,$0F,$F0,$00,$83,$AA,$FF,$AA,$C1,$0F
        fcb     $C0,$00,$83,$AA,$FF,$AA,$C1,$0F,$C0,$00,$83,$AA
        fcb     $FF,$AA,$C1,$3F,$00,$00,$83,$AA,$FF,$AA,$C1,$3F
        fcb     $00,$00,$C1,$C0,$0A,$82,$AA,$FF,$C1,$3F,$00,$00
        fcb     $C1,$C0,$0A,$82,$AA,$FF,$C1,$3F,$00,$00,$C1,$C0
        fcb     $0A,$82,$AA,$AF,$C1,$0F,$C0,$00,$C1,$C0,$0A,$82
        fcb     $AA,$AF,$C1,$0F,$C0,$00,$C1,$FC,$00,$82,$AA,$AF
        fcb     $C1,$0F,$C0,$00,$41,$C1,$C0,$0A,$81,$A8,$41,$00
        fcb     $41,$C1,$FC,$03,$81,$FC,$41,$00,$41,$82,$3F,$FF
        fcb     $C1,$3F,$00,$00,$41,$C1,$C0,$0F,$81,$FF,$C1,$3F
        fcb     $00,$00
