* chtab4fat_012_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 37 rows x 9 bytes, 495 segment bytes
*
chtab4fat_012_p0:
        fcb     37,9  ; height, width in bytes
        fcb     $44,$C2,$FC,$03,$03,$FC,$43,$00,$44,$82,$AA,$FF
        fcb     $C1,$3F,$C0,$42,$00,$43,$C1,$F0,$0A,$82,$AA,$FF
        fcb     $C1,$0F,$F0,$42,$00,$43,$83,$AA,$FF,$AA,$C1,$0F
        fcb     $F0,$42,$00,$42,$C1,$FC,$03,$83,$AF,$FF,$EA,$C1
        fcb     $0F,$F0,$42,$00,$42,$C1,$FC,$01,$83,$AF,$FF,$7E
        fcb     $C1,$3F,$C0,$42,$00,$42,$C2,$FC,$01,$0F,$50,$82
        fcb     $FF,$FF,$C1,$3F,$C0,$42,$00,$42,$C2,$FC,$03,$0F
        fcb     $F0,$82,$FF,$FF,$C1,$3F,$C0,$42,$00,$43,$C1,$C0
        fcb     $3F,$82,$FF,$FF,$C1,$0F,$F0,$42,$00,$42,$C1,$F0
        fcb     $0F,$83,$FF,$FF,$FF,$C1,$03,$FC,$42,$00,$42,$C1
        fcb     $C0,$3F,$83,$FF,$FF,$FF,$C1,$03,$FC,$42,$00,$42
        fcb     $C1,$C0,$15,$84,$57,$FF,$FF,$FF,$42,$00,$42,$C2
        fcb     $F0,$0A,$3C,$81,$83,$7F,$FF,$55,$42,$00,$42,$85
        fcb     $AA,$F5,$57,$EA,$AA,$C1,$3F,$80,$41,$00,$42,$84
        fcb     $AA,$AA,$FF,$F5,$C2,$F0,$0A,$3F,$80,$41,$00,$42
        fcb     $84,$AA,$AA,$FF,$FF,$43,$00,$42,$84,$AA,$AA,$AF
        fcb     $FF,$C1,$3F,$C0,$42,$00,$41,$C1,$F0,$0A,$84,$AA
        fcb     $AA,$AF,$FF,$C1,$3F,$C0,$42,$00,$41,$C1,$F0,$0A
        fcb     $84,$AA,$AA,$AF,$FF,$C1,$3F,$C0,$42,$00,$41,$C1
        fcb     $F0,$0A,$84,$AA,$AA,$AF,$FF,$C1,$3F,$C0,$42,$00
        fcb     $41,$C1,$F0,$0A,$84,$AA,$AA,$AF,$FF,$C1,$0F,$F0
        fcb     $42,$00,$41,$C1,$F0,$0A,$84,$AA,$AA,$AF,$FF,$C1
        fcb     $0F,$F0,$42,$00,$41,$C1,$F0,$0A,$84,$AA,$AA,$AF
        fcb     $FF,$C1,$0F,$F0,$42,$00,$41,$C1,$F0,$0A,$82,$AA
        fcb     $AA,$C1,$3C,$83,$81,$FF,$C1,$0F,$F0,$42,$00,$41
        fcb     $C1,$F0,$0A,$82,$AA,$AA,$C1,$3C,$83,$81,$FF,$C1
        fcb     $0F,$F0,$42,$00,$41,$C1,$F0,$0A,$82,$AA,$AA,$C1
        fcb     $3C,$83,$81,$FF,$C1,$0F,$F0,$42,$00,$41,$C1,$F0
        fcb     $0A,$81,$AA,$C2,$03,$A8,$FC,$03,$81,$FF,$C1,$03
        fcb     $FC,$42,$00,$41,$C1,$F0,$0A,$81,$AA,$C2,$03,$A8
        fcb     $C0,$3E,$82,$FF,$EA,$C1,$3F,$80,$41,$00,$41,$C1
        fcb     $F0,$0A,$85,$AA,$FE,$FF,$EA,$AA,$C1,$3F,$80,$41
        fcb     $00,$41,$C1,$C0,$3E,$85,$AF,$FE,$FE,$AA,$AA,$C1
        fcb     $03,$A8,$41,$00,$41,$83,$AA,$AF,$FE,$41,$82,$AA
        fcb     $AA,$C1,$03,$A8,$41,$00,$42,$81,$AA,$C1,$3F,$80
        fcb     $41,$C1,$F0,$0A,$81,$AA,$C1,$03,$A8,$41,$00,$42
        fcb     $C1,$F3,$08,$43,$C1,$F0,$0A,$81,$AA,$C1,$3F,$80
        fcb     $00,$42,$C2,$F0,$0F,$3F,$C0,$43,$C2,$FC,$03,$0F
        fcb     $F0,$00,$42,$C2,$C0,$3F,$3F,$C0,$43,$C2,$FC,$03
        fcb     $0F,$F0,$00,$41,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0
        fcb     $43,$C2,$C0,$3F,$03,$FC,$00,$41,$C2,$C0,$3F,$0F
        fcb     $F0,$46,$00
