* chtab4fat_011_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 37 rows x 9 bytes, 467 segment bytes
*
chtab4fat_011_p0:
        fcb     37,9  ; height, width in bytes
        fcb     $44,$C2,$F0,$0F,$03,$FC,$43,$00,$44,$82,$FF,$FF
        fcb     $C1,$0F,$F0,$42,$00,$44,$82,$FF,$FF,$C1,$03,$FC
        fcb     $42,$00,$44,$C1,$C0,$3F,$81,$FF,$C1,$03,$FC,$42
        fcb     $00,$44,$82,$AF,$FF,$C1,$03,$FC,$42,$00,$44,$C1
        fcb     $FC,$03,$81,$FF,$C1,$0F,$F0,$42,$00,$44,$82,$FF
        fcb     $FF,$C1,$3F,$C0,$42,$00,$43,$83,$FF,$FF,$AF,$43
        fcb     $00,$42,$C1,$F0,$0A,$83,$FF,$FF,$AF,$43,$00,$42
        fcb     $C1,$F0,$0A,$83,$FF,$FF,$AF,$C1,$3F,$C0,$42,$00
        fcb     $42,$84,$AA,$AF,$FF,$FF,$C1,$0F,$F0,$42,$00,$41
        fcb     $C1,$FC,$03,$84,$EA,$AF,$FF,$FF,$C1,$0F,$F0,$42
        fcb     $00,$41,$C1,$C0,$17,$84,$EA,$FF,$FF,$FF,$C1,$0F
        fcb     $F0,$42,$00,$41,$C2,$C0,$15,$F0,$0F,$83,$FF,$FF
        fcb     $FF,$C1,$03,$FC,$42,$00,$41,$C2,$CF,$10,$C0,$3F
        fcb     $83,$FF,$FF,$FF,$C1,$03,$FC,$42,$00,$42,$C1,$C0
        fcb     $3F,$83,$F5,$55,$FF,$C1,$F3,$08,$42,$00,$42,$C1
        fcb     $C0,$15,$83,$55,$7F,$55,$C1,$3F,$C0,$42,$00,$42
        fcb     $C1,$F0,$0A,$83,$FF,$FF,$AA,$C1,$3F,$C0,$42,$00
        fcb     $42,$84,$AA,$AA,$AF,$FF,$C1,$0F,$F0,$42,$00,$42
        fcb     $84,$AA,$AA,$AF,$FF,$C1,$0F,$F0,$42,$00,$42,$84
        fcb     $AA,$AA,$AF,$FF,$C1,$0F,$F0,$42,$00,$42,$84,$AA
        fcb     $AA,$AF,$FF,$C1,$0F,$F0,$42,$00,$41,$C1,$F0,$0A
        fcb     $84,$AA,$AA,$AF,$FF,$C1,$0F,$F0,$42,$00,$41,$C1
        fcb     $F0,$0A,$84,$AA,$AA,$AF,$FF,$C1,$0F,$F0,$42,$00
        fcb     $41,$C1,$F0,$0A,$84,$AA,$AA,$FF,$FF,$C1,$0F,$F0
        fcb     $42,$00,$41,$85,$AA,$AA,$FF,$FF,$FE,$C1,$0F,$F0
        fcb     $42,$00,$C1,$F0,$0F,$85,$AA,$AA,$FF,$FE,$FE,$C1
        fcb     $03,$A8,$42,$00,$C1,$FC,$03,$85,$AA,$AA,$FE,$AA
        fcb     $FE,$C1,$03,$A8,$42,$00,$41,$C1,$C0,$3E,$81,$AA
        fcb     $C1,$03,$A8,$41,$82,$AA,$AA,$C1,$3F,$80,$41,$00
        fcb     $41,$C1,$F0,$0A,$81,$AA,$C1,$03,$A8,$41,$82,$AA
        fcb     $AA,$C1,$3F,$80,$41,$00,$41,$C1,$F0,$0A,$81,$AA
        fcb     $C1,$3F,$80,$41,$C1,$F0,$0A,$81,$AA,$C1,$03,$A8
        fcb     $41,$00,$41,$C1,$F0,$0A,$81,$AA,$C1,$3F,$80,$41
        fcb     $C1,$F0,$0A,$81,$AA,$C1,$03,$A8,$41,$00,$41,$C2
        fcb     $F0,$0A,$03,$A8,$43,$81,$AA,$C1,$03,$A8,$41,$00
        fcb     $42,$C1,$3F,$80,$44,$C2,$FC,$03,$3F,$C0,$00,$41
        fcb     $C2,$C0,$3F,$3F,$C0,$44,$C2,$FC,$03,$0F,$F0,$00
        fcb     $C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$44,$C2,$C0,$3F
        fcb     $03,$FC,$00,$82,$7F,$FF,$C1,$3F,$C0,$46,$00
