* chtab4fat_004_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 33 rows x 13 bytes, 487 segment bytes
*
chtab4fat_004_p0:
        fcb     33,13  ; height, width in bytes
        fcb     $44,$81,$FF,$C1,$3F,$C0,$47,$00,$43,$C1,$F0,$0F
        fcb     $82,$FF,$FF,$47,$00,$43,$C1,$F0,$0F,$82,$FF,$FF
        fcb     $C1,$3F,$C0,$46,$00,$43,$C1,$FC,$03,$82,$FF,$FF
        fcb     $C1,$3F,$C0,$46,$00,$43,$C1,$F0,$0A,$82,$FF,$FF
        fcb     $C1,$3F,$C0,$46,$00,$44,$C1,$C0,$3F,$81,$FF,$C1
        fcb     $03,$FC,$46,$00,$C2,$FC,$01,$0F,$50,$41,$C1,$C0
        fcb     $3F,$83,$FF,$FF,$FF,$C1,$3F,$C0,$45,$00,$C2,$FC
        fcb     $01,$0F,$50,$86,$FF,$FF,$FF,$FE,$AA,$AF,$C1,$3F
        fcb     $80,$44,$00,$42,$85,$AF,$FF,$FF,$FF,$AA,$C2,$0F
        fcb     $F0,$03,$A8,$44,$00,$42,$87,$FF,$FF,$EA,$AF,$AA
        fcb     $FF,$AA,$C1,$0F,$50,$43,$00,$42,$C1,$F0,$0A,$85
        fcb     $FF,$FF,$FF,$FE,$AA,$C2,$03,$A8,$C0,$15,$43,$00
        fcb     $43,$C1,$F0,$0F,$84,$FF,$FF,$FF,$FE,$C2,$3F,$80
        fcb     $C0,$15,$43,$00,$43,$C1,$C0,$3F,$83,$FF,$F5,$FF
        fcb     $C1,$0F,$50,$45,$00,$43,$C1,$C0,$3F,$83,$F5,$55
        fcb     $FF,$C1,$0F,$50,$45,$00,$43,$C1,$FC,$01,$84,$55
        fcb     $55,$7F,$FF,$C1,$3F,$C0,$44,$00,$43,$C2,$F0,$0A
        fcb     $3F,$80,$83,$FF,$FF,$AF,$C1,$3F,$C0,$44,$00,$43
        fcb     $C1,$F0,$0A,$84,$AA,$AA,$AF,$FF,$C1,$03,$FC,$44
        fcb     $00,$43,$C1,$F0,$0A,$84,$AA,$AA,$AF,$FF,$C1,$03
        fcb     $FC,$44,$00,$43,$C1,$F0,$0A,$85,$AA,$AA,$FF,$FF
        fcb     $AA,$44,$00,$43,$86,$AA,$AA,$FF,$FF,$AA,$AA,$44
        fcb     $00,$43,$86,$AA,$AA,$FF,$FF,$AA,$AA,$C1,$3F,$C0
        fcb     $43,$00,$43,$86,$AA,$AA,$AF,$FF,$AA,$AA,$C1,$3F
        fcb     $C0,$43,$00,$43,$86,$AA,$AA,$AF,$FF,$AA,$AA,$C1
        fcb     $0F,$F0,$43,$00,$43,$82,$AA,$AA,$C2,$3F,$80,$0F
        fcb     $F0,$82,$AA,$FF,$C1,$03,$FC,$43,$00,$43,$C1,$F0
        fcb     $0A,$81,$AA,$C2,$3F,$80,$0F,$F0,$83,$FF,$FF,$AA
        fcb     $C1,$3F,$C0,$42,$00,$43,$C1,$F0,$0A,$81,$AA,$C1
        fcb     $3F,$80,$84,$FF,$EA,$AF,$FF,$C1,$03,$FC,$42,$00
        fcb     $43,$C3,$F0,$0A,$03,$A8,$FC,$03,$85,$FE,$AF,$FF
        fcb     $FF,$FF,$C1,$3F,$C0,$41,$00,$43,$C3,$F0,$0A,$03
        fcb     $A8,$FC,$03,$86,$EA,$FF,$FE,$AF,$FF,$FF,$C1,$3F
        fcb     $C0,$00,$44,$C2,$03,$A8,$F0,$0F,$86,$EA,$AA,$AA
        fcb     $AF,$FF,$FF,$C1,$3F,$C0,$00,$43,$C3,$F0,$0F,$0F
        fcb     $F0,$F0,$0F,$83,$FF,$FF,$FF,$C4,$0F,$F0,$03,$A8
        fcb     $C0,$3F,$3F,$C0,$00,$43,$C3,$C0,$3F,$0F,$F0,$F0
        fcb     $0F,$83,$FF,$FF,$FF,$42,$C1,$C0,$3F,$41,$00,$42
        fcb     $C1,$FC,$03,$81,$FF,$C1,$03,$FC,$42,$81,$FF,$C1
        fcb     $0F,$F0,$42,$C1,$C3,$3C,$41,$00,$42,$C1,$C0,$3F
        fcb     $81,$FF,$C1,$03,$FC,$48,$00
