* chtab4fat_029_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 32 rows x 6 bytes, 324 segment bytes
*
chtab4fat_029_p0:
        fcb     32,6  ; height, width in bytes
        fcb     $C1,$FC,$00,$81,$FF,$C1,$0F,$C0,$43,$00,$C1,$C0
        fcb     $0F,$82,$FF,$FF,$C1,$3F,$00,$42,$00,$C1,$C0,$0F
        fcb     $82,$FF,$FF,$C1,$0F,$C0,$42,$00,$C1,$F0,$03,$82
        fcb     $FF,$FF,$C1,$0F,$C0,$42,$00,$C1,$C0,$0A,$82,$FF
        fcb     $FF,$C1,$0F,$C0,$42,$00,$41,$82,$3F,$FF,$C1,$3F
        fcb     $00,$42,$00,$C1,$F0,$01,$82,$7F,$FC,$43,$00,$C1
        fcb     $F0,$01,$82,$57,$FC,$43,$00,$C1,$C0,$0F,$82,$FF
        fcb     $FC,$43,$00,$C1,$F0,$03,$82,$FF,$FF,$C1,$3F,$00
        fcb     $42,$00,$C1,$C0,$0F,$82,$FF,$FF,$C1,$3F,$00,$42
        fcb     $00,$83,$FF,$FF,$7F,$C1,$0F,$C0,$42,$00,$83,$EA
        fcb     $FF,$7F,$C1,$0F,$F0,$42,$00,$83,$EA,$FF,$FF,$C1
        fcb     $0F,$F0,$42,$00,$83,$EA,$FF,$FF,$C1,$0F,$F0,$42
        fcb     $00,$83,$EA,$FF,$FF,$C1,$0F,$50,$42,$00,$81,$FF
        fcb     $C1,$03,$E8,$81,$15,$C1,$0F,$50,$42,$00,$83,$EA
        fcb     $83,$FF,$C1,$0F,$F0,$42,$00,$84,$15,$50,$AF,$FC
        fcb     $42,$00,$C1,$F0,$01,$83,$AF,$FF,$50,$C1,$0F,$C0
        fcb     $41,$00,$84,$AA,$AA,$AF,$FF,$C1,$0F,$C0,$41,$00
        fcb     $85,$AA,$AF,$FF,$FC,$AA,$41,$00,$85,$AA,$AF,$FF
        fcb     $FF,$AA,$C1,$03,$F0,$00,$81,$A8,$C1,$FC,$01,$83
        fcb     $FF,$FF,$7F,$C1,$3F,$C0,$00,$81,$A8,$C1,$FC,$01
        fcb     $83,$FF,$FF,$7E,$C1,$3F,$00,$00,$81,$AA,$C1,$0C
        fcb     $81,$82,$7E,$FF,$C1,$03,$F0,$41,$00,$C2,$C0,$0A
        fcb     $0C,$81,$82,$7E,$FF,$C1,$0F,$C0,$41,$00,$C1,$C0
        fcb     $0A,$83,$AA,$A8,$AA,$42,$00,$C1,$C0,$0A,$82,$AA
        fcb     $AA,$C1,$0F,$80,$42,$00,$C1,$FC,$00,$82,$AA,$AA
        fcb     $C1,$0F,$80,$42,$00,$C1,$FC,$00,$82,$AA,$AA,$C1
        fcb     $0F,$F0,$42,$00,$41,$C2,$C0,$0A,$0F,$80,$43,$00
