* chtab4fat_001_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 36 rows x 9 bytes, 441 segment bytes
*
chtab4fat_001_p0:
        fcb     36,9  ; height, width in bytes
        fcb     $44,$81,$FF,$C1,$3F,$C0,$43,$00,$43,$C1,$F0,$0F
        fcb     $82,$FF,$FF,$43,$00,$43,$C1,$F0,$0F,$82,$FF,$FF
        fcb     $C1,$3F,$C0,$42,$00,$43,$C1,$FC,$03,$82,$FF,$FF
        fcb     $C1,$3F,$C0,$42,$00,$43,$C1,$F0,$0A,$82,$FF,$FF
        fcb     $C1,$3F,$C0,$42,$00,$44,$C1,$C0,$3F,$81,$FF,$43
        fcb     $00,$43,$C1,$FC,$01,$81,$57,$C1,$03,$FC,$43,$00
        fcb     $43,$82,$FF,$FF,$C1,$03,$FC,$43,$00,$42,$C1,$F0
        fcb     $0A,$83,$FF,$FF,$FF,$43,$00,$42,$84,$AA,$FF,$FF
        fcb     $FF,$C1,$3F,$C0,$42,$00,$42,$84,$AA,$AF,$FF,$FF
        fcb     $C1,$0F,$F0,$42,$00,$42,$84,$AA,$AF,$FF,$FF,$C1
        fcb     $0F,$F0,$42,$00,$41,$C1,$F0,$0A,$84,$AA,$AF,$FF
        fcb     $FF,$C1,$03,$FC,$42,$00,$41,$C1,$C0,$3E,$84,$AA
        fcb     $FF,$FF,$55,$C1,$03,$7C,$42,$00,$41,$C2,$C0,$15
        fcb     $FC,$03,$83,$55,$55,$FF,$C1,$F3,$08,$42,$00,$41
        fcb     $C2,$C0,$15,$FC,$01,$83,$57,$FF,$55,$C1,$F3,$08
        fcb     $42,$00,$41,$C2,$C0,$15,$F0,$0A,$83,$FF,$FF,$AA
        fcb     $C1,$0F,$F0,$42,$00,$41,$C2,$CF,$10,$F0,$0A,$83
        fcb     $AF,$FF,$AA,$C1,$03,$FC,$42,$00,$42,$C1,$F0,$0A
        fcb     $83,$AA,$FF,$AA,$C1,$03,$FC,$42,$00,$42,$C1,$F0
        fcb     $0A,$83,$AA,$FF,$AA,$C1,$03,$FC,$42,$00,$42,$C1
        fcb     $F0,$0A,$83,$AA,$FF,$AA,$C1,$03,$FC,$42,$00,$42
        fcb     $C1,$F0,$0A,$83,$AA,$FF,$AA,$C1,$03,$FC,$42,$00
        fcb     $42,$84,$AA,$AA,$AA,$FF,$C1,$03,$FC,$42,$00,$42
        fcb     $84,$AA,$AA,$AA,$FF,$C1,$03,$FC,$42,$00,$42,$84
        fcb     $AA,$AA,$AA,$FF,$C1,$03,$FC,$42,$00,$42,$84,$AA
        fcb     $AA,$AF,$FF,$C1,$03,$FC,$42,$00,$42,$84,$AA,$AA
        fcb     $AF,$FF,$C1,$03,$FC,$42,$00,$42,$84,$AA,$AA,$AF
        fcb     $FF,$C1,$03,$FC,$42,$00,$42,$82,$AA,$AA,$C1,$3C
        fcb     $83,$82,$FF,$FE,$C1,$3F,$80,$41,$00,$42,$81,$AA
        fcb     $C2,$03,$A8,$F0,$0F,$82,$FF,$EA,$C1,$3F,$80,$41
        fcb     $00,$42,$C3,$F0,$0A,$03,$A8,$F0,$0F,$82,$FF,$EA
        fcb     $C1,$03,$A8,$41,$00,$42,$C2,$F0,$0A,$03,$A8,$41
        fcb     $82,$AA,$AA,$C1,$03,$A8,$41,$00,$43,$C1,$3F,$80
        fcb     $42,$82,$AA,$AA,$C1,$3F,$80,$00,$42,$C2,$F0,$0F
        fcb     $0F,$F0,$43,$C2,$F0,$0F,$0F,$F0,$00,$42,$C2,$C0
        fcb     $3F,$03,$FC,$43,$C2,$C0,$3F,$03,$FC,$00,$41,$C1
        fcb     $FC,$03,$81,$FF,$C1,$03,$FC,$45,$00
