* chtab4fat_016_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 42 rows x 7 bytes, 493 segment bytes
*
chtab4fat_016_p0:
        fcb     42,7  ; height, width in bytes
        fcb     $42,$C1,$FC,$00,$81,$FF,$C1,$0F,$C0,$42,$00,$42
        fcb     $C1,$C0,$0F,$82,$FF,$FF,$C1,$3F,$00,$41,$00,$42
        fcb     $C1,$C0,$0F,$82,$FF,$FF,$C1,$3F,$C0,$41,$00,$42
        fcb     $C1,$F0,$03,$82,$FF,$FF,$C1,$3F,$C0,$41,$00,$42
        fcb     $C1,$C0,$0A,$82,$FF,$FF,$C1,$3F,$C0,$41,$00,$43
        fcb     $82,$3F,$FF,$C1,$3F,$00,$41,$00,$42,$C1,$F0,$01
        fcb     $82,$57,$FC,$42,$00,$42,$C1,$F0,$01,$82,$57,$FC
        fcb     $42,$00,$43,$82,$3F,$FC,$42,$00,$42,$C1,$F0,$03
        fcb     $82,$FF,$FF,$C1,$3F,$C0,$41,$00,$42,$C1,$C0,$0F
        fcb     $82,$FF,$FF,$C1,$03,$F0,$41,$00,$42,$83,$FF,$FF
        fcb     $3F,$C1,$03,$F0,$41,$00,$42,$84,$3F,$FF,$FF,$FC
        fcb     $41,$00,$41,$C1,$FC,$03,$84,$FF,$FF,$FF,$FC,$41
        fcb     $00,$41,$C1,$C0,$0F,$84,$FF,$FF,$FF,$FC,$41,$00
        fcb     $41,$C1,$C0,$0F,$84,$FF,$FE,$FF,$FC,$41,$00,$41
        fcb     $85,$EA,$A8,$3F,$FC,$3F,$41,$00,$41,$84,$3F,$EA
        fcb     $A8,$3F,$C1,$03,$F0,$41,$00,$41,$84,$15,$0A,$A8
        fcb     $15,$C1,$03,$50,$41,$00,$41,$84,$15,$0A,$AA,$F5
        fcb     $C1,$03,$50,$41,$00,$41,$84,$15,$0A,$AA,$FF,$C1
        fcb     $03,$F0,$41,$00,$C1,$FC,$00,$85,$AA,$AA,$FF,$FC
        fcb     $AA,$41,$00,$C1,$FC,$00,$82,$AA,$AF,$C1,$30,$0A
        fcb     $82,$FF,$FC,$41,$00,$C1,$FC,$00,$82,$AA,$F5,$C1
        fcb     $30,$0F,$82,$FF,$FC,$41,$00,$C2,$FC,$00,$03,$A8
        fcb     $81,$15,$C1,$30,$0F,$82,$FF,$FC,$41,$00,$C2,$FC
        fcb     $00,$03,$A8,$84,$10,$AF,$FF,$FF,$C1,$3F,$00,$00
        fcb     $C1,$FC,$00,$85,$AA,$AF,$FF,$FF,$AA,$C1,$3F,$00
        fcb     $00,$C1,$FC,$00,$85,$AA,$AF,$FF,$FF,$AA,$C1,$3F
        fcb     $00,$00,$41,$C1,$C0,$0A,$84,$AA,$AA,$FF,$FF,$C1
        fcb     $3F,$00,$00,$41,$C1,$C0,$0A,$84,$AA,$AA,$FF,$FF
        fcb     $C1,$3F,$00,$00,$41,$C1,$C0,$0A,$84,$AA,$AA,$FF
        fcb     $FF,$C1,$0F,$C0,$00,$41,$C1,$C0,$0A,$84,$AA,$AA
        fcb     $FF,$FF,$C1,$0F,$C0,$00,$41,$C1,$C0,$0A,$84,$AA
        fcb     $AA,$FF,$FF,$C1,$0F,$C0,$00,$41,$C1,$C0,$0A,$84
        fcb     $AA,$AA,$FF,$FF,$C1,$0F,$C0,$00,$41,$C1,$FC,$00
        fcb     $84,$AA,$AA,$FF,$FF,$C1,$0F,$C0,$00,$41,$C1,$FC
        fcb     $00,$84,$AA,$AA,$FF,$FF,$C1,$0F,$C0,$00,$41,$C1
        fcb     $FC,$00,$82,$AA,$AA,$C1,$0C,$80,$81,$AA,$C1,$0F
        fcb     $80,$00,$42,$C1,$C0,$0A,$81,$A8,$41,$C2,$C0,$0A
        fcb     $0F,$80,$00,$42,$C2,$FC,$00,$0F,$F0,$41,$C2,$C0
        fcb     $0F,$03,$F0,$00,$42,$C1,$F0,$03,$81,$FC,$41,$C1
        fcb     $C0,$0F,$81,$FC,$00,$42,$82,$3F,$FC,$41,$C1,$C0
        fcb     $3F,$81,$FC,$00,$41,$C1,$FC,$03,$82,$FF,$FC,$43
        fcb     $00
