* chtab4fat_010_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 38 rows x 9 bytes, 477 segment bytes
*
chtab4fat_010_p0:
        fcb     38,9  ; height, width in bytes
        fcb     $44,$81,$FF,$C1,$3F,$C0,$43,$00,$43,$C1,$F0,$0F
        fcb     $82,$FF,$FF,$43,$00,$43,$C1,$F0,$0F,$82,$FF,$FF
        fcb     $C1,$3F,$C0,$42,$00,$43,$C1,$FC,$03,$82,$FF,$FF
        fcb     $C1,$3F,$C0,$42,$00,$43,$C1,$F0,$0A,$82,$FF,$FF
        fcb     $C1,$3F,$C0,$42,$00,$44,$C1,$C0,$3F,$81,$FF,$43
        fcb     $00,$43,$C1,$FC,$01,$82,$57,$FF,$43,$00,$43,$C1
        fcb     $FC,$01,$82,$57,$FF,$43,$00,$43,$C1,$FC,$01,$82
        fcb     $7F,$FF,$C1,$0F,$F0,$42,$00,$43,$C1,$FC,$03,$82
        fcb     $FF,$FF,$C1,$03,$FC,$42,$00,$43,$C1,$C0,$3F,$82
        fcb     $FF,$FF,$C1,$03,$FC,$42,$00,$43,$83,$FF,$FF,$FF
        fcb     $C1,$03,$FC,$42,$00,$42,$C1,$F0,$0F,$84,$FF,$FE
        fcb     $AF,$FF,$42,$00,$42,$C1,$F0,$0F,$84,$FF,$EA,$AF
        fcb     $FF,$42,$00,$42,$C1,$C0,$3F,$82,$FE,$AA,$C2,$3C
        fcb     $83,$0F,$F0,$42,$00,$42,$C2,$C0,$3F,$0F,$F0,$81
        fcb     $AA,$C2,$3C,$81,$0F,$50,$42,$00,$42,$C2,$C0,$3F
        fcb     $0F,$50,$82,$AA,$AF,$C1,$03,$FC,$42,$00,$42,$C3
        fcb     $FC,$01,$0F,$50,$F0,$0A,$81,$FF,$C1,$03,$FC,$42
        fcb     $00,$42,$C1,$3C,$81,$83,$AF,$FF,$7E,$C1,$0F,$F0
        fcb     $42,$00,$42,$84,$AA,$AA,$AF,$FF,$C1,$0F,$F0,$42
        fcb     $00,$42,$84,$AA,$AA,$AF,$FF,$C1,$0F,$F0,$42,$00
        fcb     $42,$84,$AA,$AA,$AF,$FF,$C1,$0F,$F0,$42,$00,$41
        fcb     $C1,$F0,$0A,$84,$AA,$AA,$AF,$FF,$C1,$0F,$F0,$42
        fcb     $00,$41,$C1,$F0,$0A,$84,$AA,$AA,$AF,$FF,$C1,$0F
        fcb     $F0,$42,$00,$41,$C1,$F0,$0A,$81,$AA,$C2,$03,$A8
        fcb     $C0,$3F,$81,$FF,$C1,$03,$FC,$42,$00,$41,$C1,$F0
        fcb     $0A,$81,$AA,$C2,$03,$A8,$C0,$3F,$81,$FF,$C1,$03
        fcb     $FC,$42,$00,$41,$C1,$F0,$0A,$81,$AA,$C2,$03,$A8
        fcb     $C0,$3F,$81,$FF,$C1,$03,$FC,$42,$00,$41,$85,$AA
        fcb     $AA,$FF,$FF,$AA,$C1,$0F,$F0,$42,$00,$41,$85,$AA
        fcb     $AA,$FF,$FF,$AA,$C1,$0F,$F0,$42,$00,$41,$86,$AA
        fcb     $FF,$FF,$EA,$AA,$AA,$C1,$3F,$80,$41,$00,$41,$82
        fcb     $AA,$AA,$C1,$3C,$83,$83,$FE,$AA,$FF,$C1,$03,$A8
        fcb     $41,$00,$41,$82,$AA,$AA,$C1,$3C,$83,$83,$FE,$AA
        fcb     $FF,$C1,$03,$A8,$41,$00,$41,$82,$AA,$AA,$C1,$3C
        fcb     $83,$81,$FF,$41,$81,$AA,$C1,$03,$A8,$41,$00,$41
        fcb     $C4,$C0,$3E,$03,$A8,$FC,$03,$03,$FC,$41,$C1,$F0
        fcb     $0A,$81,$AA,$C1,$03,$FC,$00,$41,$C1,$C0,$3F,$46
        fcb     $C1,$03,$FC,$00,$C2,$FC,$03,$03,$FC,$46,$C1,$03
        fcb     $FC,$00,$81,$FF,$C1,$03,$FC,$45,$C2,$FC,$03,$0F
        fcb     $F0,$00,$81,$7F,$C1,$03,$FC,$47,$00
