* chtab4fat_011_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 37 rows x 9 bytes, 474 segment bytes
*
chtab4fat_011_p0:
        fcb     37,9  ; height, width in bytes
        fcb     $44,$C1,$C0,$0F,$81,$FC,$43,$00,$43,$C1,$FC,$00
        fcb     $82,$FF,$FF,$C1,$03,$F0,$42,$00,$43,$C1,$FC,$00
        fcb     $83,$FF,$FC,$FF,$42,$00,$44,$83,$FF,$FC,$3F,$42
        fcb     $00,$43,$C1,$FC,$00,$83,$FF,$FC,$AF,$42,$00,$44
        fcb     $C1,$F0,$03,$81,$FF,$C1,$03,$F0,$42,$00,$43,$C1
        fcb     $FC,$00,$82,$FF,$FF,$C1,$0F,$C0,$42,$00,$42,$C1
        fcb     $FC,$00,$83,$FF,$FF,$AF,$C1,$3F,$00,$42,$00,$42
        fcb     $C1,$C0,$0A,$83,$FF,$FF,$AF,$C1,$3F,$00,$42,$00
        fcb     $42,$C1,$C0,$0A,$83,$FF,$FF,$AF,$C1,$0F,$C0,$42
        fcb     $00,$41,$C1,$FC,$00,$84,$AA,$AF,$FF,$FF,$C1,$03
        fcb     $F0,$42,$00,$41,$C1,$FC,$03,$84,$EA,$AF,$FF,$FF
        fcb     $C1,$03,$F0,$42,$00,$41,$85,$EA,$FF,$FF,$FF,$17
        fcb     $C1,$03,$F0,$42,$00,$41,$86,$FF,$FF,$FF,$FC,$15
        fcb     $0F,$42,$00,$41,$C1,$03,$10,$85,$FF,$FF,$FF,$FC
        fcb     $3F,$42,$00,$42,$85,$FF,$F5,$55,$08,$3F,$42,$00
        fcb     $42,$84,$15,$55,$55,$7F,$C1,$0F,$C0,$42,$00,$42
        fcb     $C1,$C0,$0A,$83,$FF,$FF,$AA,$C1,$0F,$C0,$42,$00
        fcb     $41,$C1,$FC,$00,$84,$AA,$AA,$AF,$FF,$C1,$03,$F0
        fcb     $42,$00,$41,$C1,$FC,$00,$84,$AA,$AA,$AF,$FF,$C1
        fcb     $03,$F0,$42,$00,$41,$C1,$FC,$00,$84,$AA,$AA,$AF
        fcb     $FF,$C1,$03,$F0,$42,$00,$41,$C1,$FC,$00,$84,$AA
        fcb     $AA,$AF,$FF,$C1,$03,$F0,$42,$00,$41,$C1,$C0,$0A
        fcb     $84,$AA,$AA,$AF,$FF,$C1,$03,$F0,$42,$00,$41,$C1
        fcb     $C0,$0A,$84,$AA,$AA,$AF,$FF,$C1,$03,$F0,$42,$00
        fcb     $41,$C1,$C0,$0A,$84,$AA,$AA,$FF,$FF,$C1,$03,$F0
        fcb     $42,$00,$C1,$FC,$00,$85,$AA,$AA,$FF,$FF,$FE,$C1
        fcb     $03,$F0,$42,$00,$C1,$C0,$0F,$86,$AA,$FF,$FE,$A8
        fcb     $FE,$AA,$42,$00,$C1,$F0,$03,$86,$AA,$FE,$AA,$A8
        fcb     $FE,$AA,$42,$00,$41,$83,$AA,$A8,$3E,$C1,$FC,$00
        fcb     $82,$AA,$AA,$C1,$0F,$80,$41,$00,$41,$C1,$C0,$0A
        fcb     $82,$AA,$A8,$C1,$FC,$00,$82,$AA,$AA,$C1,$0F,$80
        fcb     $41,$00,$41,$C1,$C0,$0A,$81,$AA,$C1,$0F,$80,$41
        fcb     $C1,$C0,$0A,$82,$AA,$A8,$41,$00,$41,$C1,$C0,$0A
        fcb     $81,$AA,$C1,$0F,$80,$41,$C1,$C0,$0A,$82,$AA,$A8
        fcb     $41,$00,$41,$C1,$C0,$0A,$81,$A8,$42,$C1,$FC,$00
        fcb     $82,$AA,$A8,$41,$00,$41,$C2,$FC,$00,$0F,$80,$44
        fcb     $C2,$F0,$03,$0F,$C0,$00,$41,$81,$3F,$C1,$0F,$C0
        fcb     $44,$C2,$F0,$03,$03,$F0,$00,$C1,$F0,$03,$81,$FF
        fcb     $C1,$0F,$C0,$44,$81,$3F,$C1,$03,$FC,$00,$82,$7F
        fcb     $FF,$C1,$0F,$C0,$46,$00
