* chtab4fat_002_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 37 rows x 10 bytes, 474 segment bytes
*
chtab4fat_002_p0:
        fcb     37,10  ; height, width in bytes
        fcb     $44,$C1,$C0,$0F,$81,$FC,$44,$00,$43,$C1,$FC,$00
        fcb     $82,$FF,$FF,$C1,$03,$F0,$43,$00,$43,$C1,$FC,$00
        fcb     $83,$FF,$FC,$FF,$43,$00,$44,$83,$FF,$FC,$3F,$43
        fcb     $00,$43,$C1,$FC,$00,$83,$FF,$FC,$AF,$43,$00,$44
        fcb     $C1,$F0,$03,$81,$FF,$C1,$03,$F0,$43,$00,$44,$82
        fcb     $15,$7F,$C1,$0F,$C0,$43,$00,$44,$82,$15,$7F,$C1
        fcb     $0F,$C0,$43,$00,$41,$C1,$FC,$01,$84,$7E,$A8,$3F
        fcb     $FF,$C1,$03,$F0,$43,$00,$41,$C1,$FC,$01,$85,$AA
        fcb     $AF,$FF,$FC,$7E,$43,$00,$42,$C1,$C0,$0A,$84,$AA
        fcb     $AF,$FF,$FC,$43,$00,$42,$C1,$FC,$00,$84,$AA,$AF
        fcb     $FF,$FC,$43,$00,$42,$C1,$FC,$00,$84,$AA,$AF,$FF
        fcb     $FF,$43,$00,$42,$C1,$F0,$03,$84,$FF,$FF,$FF,$FF
        fcb     $43,$00,$42,$C1,$F0,$03,$84,$FF,$FF,$FF,$FF,$43
        fcb     $00,$42,$C1,$F0,$03,$83,$F5,$55,$FF,$C1,$03,$50
        fcb     $43,$00,$42,$C1,$F0,$01,$83,$55,$55,$55,$C1,$03
        fcb     $50,$43,$00,$42,$C1,$C0,$0A,$84,$AA,$FF,$FF,$FF
        fcb     $43,$00,$42,$C1,$C0,$0A,$84,$AA,$AA,$FF,$FF,$C1
        fcb     $0F,$C0,$42,$00,$42,$C1,$C0,$0A,$84,$AA,$AA,$FF
        fcb     $FF,$C1,$0F,$C0,$42,$00,$42,$C1,$C0,$0A,$84,$AA
        fcb     $AA,$FF,$FF,$C1,$0F,$C0,$42,$00,$42,$C1,$C0,$0A
        fcb     $84,$AA,$AA,$AF,$FF,$C1,$0F,$C0,$42,$00,$42,$C1
        fcb     $C0,$0A,$84,$AA,$AA,$AF,$FF,$C1,$0F,$C0,$42,$00
        fcb     $42,$C1,$C0,$0A,$84,$AA,$AA,$AF,$FF,$C1,$03,$F0
        fcb     $42,$00,$42,$C1,$C0,$0A,$84,$AA,$AA,$AF,$FF,$C1
        fcb     $03,$F0,$42,$00,$41,$C1,$FC,$00,$85,$AA,$AF,$EF
        fcb     $FF,$AA,$C1,$03,$F0,$42,$00,$41,$C1,$FC,$00,$86
        fcb     $AF,$EA,$FF,$FC,$AA,$AA,$42,$00,$41,$C1,$FC,$00
        fcb     $86,$AF,$EA,$FF,$FF,$AA,$AA,$C1,$3F,$00,$41,$00
        fcb     $41,$C1,$FC,$00,$86,$FF,$EA,$FF,$FF,$AA,$AA,$C1
        fcb     $3F,$00,$41,$00,$41,$C1,$FC,$00,$86,$FF,$EA,$FF
        fcb     $FF,$AA,$AA,$C1,$0F,$C0,$41,$00,$41,$C1,$FC,$00
        fcb     $82,$AA,$A8,$41,$C2,$C0,$3C,$C0,$0F,$81,$FF,$C1
        fcb     $03,$F0,$41,$00,$41,$C1,$FC,$00,$82,$AA,$A8,$41
        fcb     $C1,$FC,$00,$82,$AF,$FF,$C1,$03,$E8,$41,$00,$42
        fcb     $C2,$C0,$0A,$0F,$80,$42,$C1,$C0,$0A,$81,$AA,$C1
        fcb     $0F,$80,$41,$00,$41,$C2,$FC,$00,$03,$F0,$45,$C2
        fcb     $C0,$0F,$03,$F0,$00,$C1,$C0,$0F,$82,$FF,$FC,$45
        fcb     $81,$3F,$C1,$03,$F0,$00,$C1,$FC,$00,$82,$FF,$FC
        fcb     $44,$C1,$FC,$00,$81,$FF,$C1,$0F,$C0,$00,$41,$C1
        fcb     $FC,$03,$81,$FC,$47,$00
