* chtab4fat_032_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 14 rows x 9 bytes, 185 segment bytes
*
chtab4fat_032_p0:
        fcb     14,9  ; height, width in bytes
        fcb     $43,$C1,$F0,$0F,$81,$FF,$C1,$3F,$C0,$43,$00,$42
        fcb     $C1,$FC,$00,$83,$FF,$FC,$FF,$43,$00,$42,$C1,$C0
        fcb     $0F,$83,$FF,$FF,$FF,$C1,$3F,$00,$42,$00,$42,$84
        fcb     $3F,$FF,$FF,$FF,$C1,$0F,$C0,$42,$00,$41,$C1,$FC
        fcb     $00,$84,$FF,$FF,$FF,$FF,$C1,$0F,$C0,$42,$00,$41
        fcb     $C1,$FC,$03,$84,$FF,$FF,$FF,$FF,$C1,$03,$F0,$42
        fcb     $00,$41,$C1,$FC,$03,$84,$FF,$FE,$FF,$FF,$C3,$03
        fcb     $F0,$C0,$0A,$0F,$80,$00,$C1,$F0,$01,$85,$FF,$EA
        fcb     $AF,$FF,$57,$C3,$03,$F0,$C0,$0A,$0F,$80,$00,$88
        fcb     $AA,$FF,$F5,$57,$15,$7F,$FE,$AA,$C1,$0F,$C0,$00
        fcb     $83,$FF,$C1,$10,$C1,$30,$0A,$84,$81,$7F,$FF,$55
        fcb     $C1,$3F,$00,$00,$88,$FF,$F7,$FF,$55,$17,$FF,$7F
        fcb     $FF,$C1,$3F,$00,$00,$87,$FF,$FF,$F7,$FF,$FF,$7F
        fcb     $17,$42,$00,$C1,$FC,$00,$86,$FF,$FF,$F7,$FC,$FF
        fcb     $7F,$42,$00,$41,$C2,$C0,$0F,$30,$03,$82,$FF,$FF
        fcb     $C1,$3F,$00,$43,$00
