* chtab4fat_002_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 37 rows x 10 bytes, 454 segment bytes
*
chtab4fat_002_p0:
        fcb     37,10  ; height, width in bytes
        fcb     $44,$C2,$F0,$0F,$03,$FC,$44,$00,$44,$82,$FF,$FF
        fcb     $C1,$0F,$F0,$43,$00,$44,$82,$FF,$FF,$C1,$03,$FC
        fcb     $43,$00,$44,$C1,$C0,$3F,$81,$FF,$C1,$03,$FC,$43
        fcb     $00,$44,$82,$AF,$FF,$C1,$03,$FC,$43,$00,$44,$C1
        fcb     $FC,$03,$81,$FF,$C1,$0F,$F0,$43,$00,$44,$C1,$C0
        fcb     $15,$81,$7F,$C1,$3F,$C0,$43,$00,$44,$C1,$C0,$15
        fcb     $81,$7F,$C1,$3F,$C0,$43,$00,$41,$C1,$FC,$01,$81
        fcb     $7E,$C2,$03,$A8,$C0,$3F,$81,$FF,$C1,$0F,$F0,$43
        fcb     $00,$41,$C1,$FC,$01,$84,$7E,$AA,$AF,$FF,$C1,$03
        fcb     $FC,$43,$00,$42,$C1,$F0,$0A,$83,$AF,$FF,$AA,$C1
        fcb     $03,$FC,$43,$00,$43,$83,$AF,$FF,$AA,$C1,$03,$FC
        fcb     $43,$00,$43,$84,$AA,$AF,$FF,$FF,$43,$00,$42,$C1
        fcb     $FC,$03,$84,$FF,$FF,$FF,$FF,$43,$00,$42,$C1,$FC
        fcb     $03,$84,$FF,$FF,$FF,$FF,$43,$00,$42,$C1,$FC,$03
        fcb     $83,$F5,$55,$FF,$C1,$0F,$50,$43,$00,$42,$C1,$FC
        fcb     $01,$83,$55,$55,$55,$C1,$0F,$50,$43,$00,$42,$C1
        fcb     $F0,$0A,$84,$AA,$FF,$FF,$FF,$43,$00,$42,$C1,$F0
        fcb     $0A,$84,$AA,$AA,$FF,$FF,$C1,$3F,$C0,$42,$00,$42
        fcb     $C1,$F0,$0A,$84,$AA,$AA,$FF,$FF,$C1,$3F,$C0,$42
        fcb     $00,$42,$C1,$F0,$0A,$84,$AA,$AA,$FF,$FF,$C1,$3F
        fcb     $C0,$42,$00,$42,$C1,$F0,$0A,$84,$AA,$AA,$AF,$FF
        fcb     $C1,$3F,$C0,$42,$00,$42,$C1,$F0,$0A,$84,$AA,$AA
        fcb     $AF,$FF,$C1,$3F,$C0,$42,$00,$42,$C1,$F0,$0A,$84
        fcb     $AA,$AA,$AF,$FF,$C1,$0F,$F0,$42,$00,$42,$C1,$F0
        fcb     $0A,$84,$AA,$AA,$AF,$FF,$C1,$0F,$F0,$42,$00,$42
        fcb     $85,$AA,$AF,$EF,$FF,$AA,$C1,$0F,$F0,$42,$00,$42
        fcb     $85,$AA,$AF,$EA,$FF,$AA,$C1,$03,$FC,$42,$00,$42
        fcb     $86,$AF,$EA,$FF,$FF,$AA,$AA,$42,$00,$42,$86,$FF
        fcb     $EA,$FF,$FF,$AA,$AA,$42,$00,$42,$86,$FF,$EA,$FF
        fcb     $FF,$AA,$AA,$C1,$3F,$C0,$41,$00,$42,$81,$AA,$C1
        fcb     $03,$A8,$41,$C2,$C3,$3C,$F0,$0F,$81,$FF,$C1,$0F
        fcb     $F0,$41,$00,$42,$81,$AA,$C1,$03,$A8,$42,$82,$AF
        fcb     $FF,$C1,$03,$E8,$41,$00,$42,$C2,$F0,$0A,$3F,$80
        fcb     $42,$C1,$F0,$0A,$81,$AA,$C1,$3F,$80,$41,$00,$42
        fcb     $C1,$0F,$F0,$45,$C2,$F0,$0F,$0F,$F0,$00,$C1,$F0
        fcb     $0F,$81,$FF,$C1,$03,$FC,$45,$C2,$C0,$3F,$0F,$F0
        fcb     $00,$41,$81,$FF,$C1,$03,$FC,$45,$81,$FF,$C1,$3F
        fcb     $C0,$00,$41,$C2,$FC,$03,$03,$FC,$47,$00
