* chtab4fat_029_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 32 rows x 6 bytes, 322 segment bytes
*
chtab4fat_029_p0:
        fcb     32,6  ; height, width in bytes
        fcb     $41,$81,$FF,$C1,$3F,$C0,$43,$00,$C1,$F0,$0F,$82
        fcb     $FF,$FF,$43,$00,$C1,$F0,$0F,$82,$FF,$FF,$C1,$3F
        fcb     $C0,$42,$00,$C1,$FC,$03,$82,$FF,$FF,$C1,$3F,$C0
        fcb     $42,$00,$C1,$F0,$0A,$82,$FF,$FF,$C1,$3F,$C0,$42
        fcb     $00,$41,$C1,$C0,$3F,$81,$FF,$43,$00,$C1,$FC,$01
        fcb     $81,$7F,$C1,$03,$FC,$43,$00,$C1,$FC,$01,$81,$57
        fcb     $C1,$03,$FC,$43,$00,$C1,$F0,$0F,$81,$FF,$C1,$03
        fcb     $FC,$43,$00,$C1,$FC,$03,$82,$FF,$FF,$43,$00,$C1
        fcb     $F0,$0F,$82,$FF,$FF,$43,$00,$83,$FF,$FF,$7F,$C1
        fcb     $3F,$C0,$42,$00,$83,$EA,$FF,$7F,$C1,$0F,$F0,$42
        fcb     $00,$83,$EA,$FF,$FF,$C1,$0F,$F0,$42,$00,$83,$EA
        fcb     $FF,$FF,$C1,$0F,$F0,$42,$00,$83,$EA,$FF,$FF,$C1
        fcb     $0F,$50,$42,$00,$81,$FF,$C3,$03,$E8,$C0,$15,$0F
        fcb     $50,$42,$00,$82,$FF,$EA,$C2,$3C,$83,$0F,$F0,$42
        fcb     $00,$C2,$C0,$15,$0F,$50,$81,$AF,$C1,$03,$FC,$42
        fcb     $00,$C2,$FC,$01,$0F,$50,$82,$AF,$FF,$C1,$3F,$C0
        fcb     $41,$00,$84,$AA,$AA,$AF,$FF,$C1,$3F,$C0,$41,$00
        fcb     $84,$AA,$AA,$AF,$FF,$C1,$03,$FC,$41,$00,$85,$AA
        fcb     $AF,$FF,$FF,$AA,$C1,$0F,$F0,$00,$C2,$03,$A8,$FC
        fcb     $01,$83,$FF,$FF,$7F,$C1,$3F,$C0,$00,$C2,$03,$A8
        fcb     $FC,$01,$83,$FF,$FF,$7E,$41,$00,$81,$AA,$C1,$3C
        fcb     $81,$82,$7E,$FF,$C1,$0F,$F0,$41,$00,$C2,$F0,$0A
        fcb     $3C,$81,$82,$7E,$FF,$C1,$3F,$C0,$41,$00,$C1,$F0
        fcb     $0A,$82,$AA,$AA,$C1,$03,$A8,$42,$00,$C1,$F0,$0A
        fcb     $82,$AA,$AA,$C1,$3F,$80,$42,$00,$41,$82,$AA,$AA
        fcb     $C1,$3F,$80,$42,$00,$41,$82,$AA,$AA,$C1,$0F,$F0
        fcb     $42,$00,$41,$C2,$F0,$0A,$3F,$80,$43,$00
