* chtab4fat_028_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 35 rows x 5 bytes, 335 segment bytes
*
chtab4fat_028_p0:
        fcb     35,5  ; height, width in bytes
        fcb     $41,$81,$FF,$C1,$3F,$C0,$42,$00,$C1,$F0,$0F,$82
        fcb     $FF,$FF,$42,$00,$C1,$F0,$0F,$82,$FF,$FF,$C1,$3F
        fcb     $C0,$41,$00,$C1,$FC,$03,$82,$FF,$FF,$C1,$3F,$C0
        fcb     $41,$00,$C1,$F0,$0A,$82,$FF,$FF,$C1,$3F,$C0,$41
        fcb     $00,$41,$C1,$C0,$3F,$81,$FF,$42,$00,$C1,$FC,$01
        fcb     $81,$7F,$C1,$03,$FC,$42,$00,$C1,$FC,$01,$81,$57
        fcb     $C1,$0F,$F0,$42,$00,$C1,$F0,$0F,$81,$FF,$C1,$0F
        fcb     $F0,$42,$00,$41,$81,$FF,$C1,$03,$FC,$42,$00,$C1
        fcb     $FC,$03,$82,$FF,$FF,$42,$00,$C1,$F0,$0F,$82,$FF
        fcb     $FF,$42,$00,$C1,$F0,$0F,$82,$FF,$FF,$C1,$3F,$C0
        fcb     $41,$00,$83,$FF,$FF,$7F,$C1,$0F,$F0,$41,$00,$82
        fcb     $7F,$EA,$C2,$3C,$83,$0F,$F0,$41,$00,$83,$EA,$AF
        fcb     $7F,$C1,$03,$FC,$41,$00,$83,$EA,$AF,$FF,$C1,$03
        fcb     $FC,$41,$00,$83,$EA,$AF,$FF,$C1,$0F,$50,$41,$00
        fcb     $C3,$C0,$15,$F0,$0A,$3C,$81,$81,$55,$41,$00,$C3
        fcb     $C0,$15,$F3,$08,$C0,$17,$81,$FF,$41,$00,$81,$AF
        fcb     $C1,$F0,$0A,$82,$FF,$FF,$41,$00,$C3,$03,$A8,$C0
        fcb     $15,$F0,$0F,$81,$FF,$41,$00,$C3,$03,$A8,$C0,$15
        fcb     $F0,$0A,$81,$FF,$41,$00,$C3,$03,$A8,$C0,$15,$F0
        fcb     $0A,$81,$FF,$41,$00,$82,$AA,$AA,$C2,$03,$A8,$C3
        fcb     $3C,$41,$00,$83,$AA,$AA,$AA,$C1,$03,$FC,$41,$00
        fcb     $82,$AA,$AA,$C1,$3C,$83,$81,$FF,$41,$00,$84,$AA
        fcb     $AA,$AF,$FF,$C1,$0F,$F0,$00,$82,$AA,$AA,$C1,$3C
        fcb     $83,$81,$FF,$C1,$3F,$C0,$00,$82,$AA,$AA,$C2,$3F
        fcb     $80,$C0,$3F,$41,$00,$C1,$F0,$0A,$81,$AA,$C1,$03
        fcb     $A8,$42,$00,$C1,$F0,$0A,$81,$AA,$C1,$03,$A8,$42
        fcb     $00,$41,$C2,$F0,$0A,$03,$FC,$42,$00,$41,$C1,$C0
        fcb     $3F,$81,$FF,$42,$00,$41,$82,$FF,$FF,$42,$00
