* chtab4fat_032_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 14 rows x 9 bytes, 183 segment bytes
*
chtab4fat_032_p0:
        fcb     14,9  ; height, width in bytes
        fcb     $43,$C1,$F0,$0F,$81,$FF,$C1,$3F,$C0,$43,$00,$43
        fcb     $82,$FF,$FF,$C1,$03,$FC,$43,$00,$42,$C1,$F0,$0F
        fcb     $83,$FF,$FF,$FF,$43,$00,$42,$C1,$C0,$3F,$83,$FF
        fcb     $FF,$FF,$C1,$3F,$C0,$42,$00,$42,$84,$FF,$FF,$FF
        fcb     $FF,$C1,$3F,$C0,$42,$00,$41,$C1,$FC,$03,$84,$FF
        fcb     $FF,$FF,$FF,$C1,$0F,$F0,$42,$00,$41,$C1,$FC,$03
        fcb     $84,$FF,$FE,$FF,$FF,$C3,$0F,$F0,$F0,$0A,$3F,$80
        fcb     $00,$C1,$FC,$01,$85,$FF,$EA,$AF,$FF,$57,$C3,$0F
        fcb     $F0,$F0,$0A,$3F,$80,$00,$C1,$C0,$15,$87,$AA,$FF
        fcb     $F5,$57,$FE,$AA,$7F,$C1,$3F,$C0,$00,$C1,$CF,$10
        fcb     $81,$FF,$C3,$3C,$C1,$F0,$0A,$3C,$81,$83,$FF,$55
        fcb     $7F,$41,$00,$C1,$C0,$17,$87,$FF,$F7,$FF,$55,$7F
        fcb     $FF,$FF,$41,$00,$C1,$C0,$17,$86,$FF,$FF,$F7,$FF
        fcb     $FF,$7F,$42,$00,$41,$85,$7F,$FF,$FF,$F7,$FF,$C1
        fcb     $03,$FC,$42,$00,$41,$C2,$F0,$0F,$FC,$03,$82,$FF
        fcb     $FF,$44,$00
