* chtab4fat_022_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 39 rows x 7 bytes, 415 segment bytes
*
chtab4fat_022_p0:
        fcb     39,7  ; height, width in bytes
        fcb     $42,$C2,$F0,$0F,$03,$FC,$43,$00,$42,$82,$FF,$FF
        fcb     $C1,$0F,$F0,$42,$00,$42,$82,$FF,$FF,$C1,$03,$FC
        fcb     $42,$00,$42,$C1,$C0,$3F,$81,$FF,$C1,$03,$FC,$42
        fcb     $00,$42,$82,$AF,$FF,$C1,$03,$FC,$42,$00,$42,$C1
        fcb     $FC,$03,$81,$FF,$C1,$0F,$F0,$42,$00,$42,$C1,$C0
        fcb     $17,$81,$FF,$C1,$3F,$C0,$42,$00,$42,$C1,$C0,$15
        fcb     $81,$7F,$C1,$3F,$C0,$42,$00,$42,$82,$FF,$FF,$C1
        fcb     $3F,$C0,$42,$00,$42,$C1,$C0,$3F,$81,$FF,$C1,$03
        fcb     $FC,$42,$00,$41,$C1,$FC,$03,$83,$FF,$FF,$FF,$42
        fcb     $00,$41,$C1,$F0,$0F,$83,$FF,$FF,$EF,$42,$00,$41
        fcb     $84,$AA,$AF,$FF,$FF,$C1,$3F,$C0,$41,$00,$C1,$C0
        fcb     $17,$84,$EA,$AA,$FF,$FF,$C1,$3F,$C0,$41,$00,$C1
        fcb     $C0,$17,$84,$EA,$AA,$FF,$FF,$42,$00,$41,$C1,$F0
        fcb     $0A,$83,$FF,$F5,$AF,$42,$00,$41,$C1,$C0,$3F,$83
        fcb     $F5,$57,$FF,$C1,$0F,$F0,$41,$00,$41,$C1,$C0,$3F
        fcb     $83,$57,$FF,$F5,$C1,$0F,$F0,$41,$00,$41,$C1,$C0
        fcb     $15,$83,$FF,$FF,$57,$C1,$0F,$F0,$41,$00,$41,$C1
        fcb     $CF,$10,$83,$AF,$FF,$AA,$C1,$0F,$F0,$41,$00,$41
        fcb     $C1,$F0,$0A,$83,$AA,$FF,$AA,$C1,$0F,$F0,$41,$00
        fcb     $41,$C1,$F0,$0A,$83,$AA,$FF,$AA,$C1,$0F,$F0,$41
        fcb     $00,$41,$C1,$F0,$0A,$83,$AA,$FF,$AA,$C1,$0F,$F0
        fcb     $41,$00,$41,$C1,$F0,$0A,$83,$AA,$AF,$AA,$C1,$3F
        fcb     $C0,$41,$00,$41,$C1,$F0,$0A,$83,$AA,$AF,$AA,$C1
        fcb     $3F,$C0,$41,$00,$42,$83,$AA,$AF,$AA,$C1,$3F,$C0
        fcb     $41,$00,$42,$83,$AA,$AF,$AA,$42,$00,$42,$82,$AA
        fcb     $AA,$C1,$03,$A8,$42,$00,$42,$83,$AA,$AA,$AA,$C1
        fcb     $3F,$80,$41,$00,$42,$84,$AA,$AA,$AA,$AF,$41,$00
        fcb     $42,$C1,$F0,$0A,$83,$AA,$AF,$AA,$C1,$0F,$F0,$00
        fcb     $42,$C1,$F0,$0A,$84,$AA,$AA,$AF,$FF,$00,$42,$C1
        fcb     $F0,$0A,$82,$AA,$AA,$C1,$3C,$83,$81,$FF,$00,$43
        fcb     $81,$AA,$C1,$03,$A8,$41,$81,$FF,$00,$43,$C2,$F0
        fcb     $0F,$3F,$C0,$41,$C1,$03,$FC,$00,$43,$C2,$C0,$3F
        fcb     $0F,$F0,$41,$C1,$C3,$3C,$00,$43,$81,$FF,$C1,$3F
        fcb     $C0,$41,$C1,$CF,$10,$00,$43,$81,$FF,$43,$00,$42
        fcb     $C2,$FC,$03,$0F,$F0,$43,$00
