* src/harness/compiled_probe.s
*
* POP CoCo3 — P1.3 COMPILED-SPRITE PROOF TARGET.
*
* Sets up the shipping 320x192x4 mode, clears the framebuffer to a canary,
* points U at the cel origin, and JSRs a COMPILED draw routine emitted by
* harness/tools/sprite_compiler.py. The P1.1 harness then reads the framebuffer
* back and diffs it against the source cel.
*
* This is the proof that the compiler's output is not merely self-consistent in
* Python: real LWTools assembly, real 6809, real GIME.
*
* Calling convention the compiler emits against:
*   U = the cel's top-left byte address in the framebuffer.
*   All offsets are cel-local (y*80 + x) relative to U on entry.
*   U is CLOBBERED (PSHU walks it); D/X/Y clobbered. Nothing else touched.
*
* The canary fill matters: transparent bytes must still hold the canary
* afterwards, which is how the harness proves transparency was preserved
* rather than overwritten with black.
*
* No $0100 vector block (idiom §14e). Interrupts masked throughout.
* ---------------------------------------------------------------

FB_A_BASE       equ     $8000
FB_B_BASE       equ     $C000
FB_WORDS        equ     $1E00
CANARY          equ     $A5             ; must match the harness's expectation
PROBE_MAGIC     equ     $C0DE

                org     $0200
                setdp   0

cp_entry        jmp     cp_start        ; $0200 — EXEC

cp_status       fcb     0               ; $0203  0=start 2=complete
cp_magic        fdb     0               ; $0204  $C0DE when done

cp_start
                orcc    #$50            ; mask IRQ/FIRQ for the whole run
                clra
                tfr     a,dp

* --- GIME: INIT0 first (framebuffers are ROM territory until MMUEN) ---
                lda     #$6C
                sta     $FF90

* --- fill BOTH frames with the canary ---
                ldx     #FB_A_BASE
                lda     #CANARY
                tfr     a,b
                ldy     #FB_WORDS
cp_ca           std     ,x++
                leay    -1,y
                bne     cp_ca
                ldx     #FB_B_BASE
                ldy     #FB_WORDS
cp_cb           std     ,x++
                leay    -1,y
                bne     cp_cb

* --- mode 320x192x4, VOFFSET -> frame A, VSCROL/HOFFSET, SAM ---
                ldd     #$8015
                std     $FF98
                ldd     #$F000
                std     $FF9D
                clr     $FF9C
                clr     $FF9F
                clra
                sta     $FFD9
                sta     $FFDF

* --- palette LAST (idiom §9) ---
                ldx     #cp_palette
                ldy     #$FFB0
                ldb     #4
cp_pal          lda     ,x+
                sta     ,y+
                decb
                bne     cp_pal

                lda     #1
                sta     cp_status

* --- THE POINT: U = cel origin, then run the COMPILED sprite -----
                ldu     #FB_A_BASE
                jsr     cp_draw

                lda     #2
                sta     cp_status
                ldd     #PROBE_MAGIC
                std     cp_magic

cp_done         bra     cp_done

cp_palette      fcb     $00             ; 0 Black
                fcb     $24             ; 1 Orange
                fcb     $12             ; 2 Blue
                fcb     $3F             ; 3 White

* The compiled routine. build/cp_include.s is generated by the runner and
* `include`s the chosen compiled cel; cp_draw is its draw entry point.
cp_draw
                include "build/cp_include.s"

                end     cp_entry
