* src/engine/flame_cels.s
*
* POP CoCo3 — the torch flames, as a DISK-RESIDENT code bundle.
*
* WHY THIS IS NOT PART OF THE ROOM PROGRAM. A LOADM'd engine must stay inside
* $2000-$25FF: above that is BASIC's program and variable area, which is DECB's own
* workspace, and a load that runs through it clobbers the loader mid-flight.
* [link/pop_engine.link — "below the graphics pages' end at $25FF"]
*
* That is measured, not theoretical. With the nine compiled flames inside the program
* image, ROOM.BIN's prog section ran $2000-$2C5A and LOADM never returned: the text
* screen showed the command with no "OK" after it, the first segment was in memory and
* the second was not. Trimmed back under $25FF the identical code loads and runs.
*
* So the flames follow the intro's pattern instead: assets live on raw tracks and the
* program reads them at run time. INTROSEQ.BIN is 2,005 B for exactly this reason --
* every screen and caption it uses is read from disk, not carried.
*
* THE TABLES COME FIRST, deliberately. This bundle is loaded at a fixed address and
* indexed from there, so it has to describe itself: three 9-entry pointer tables at a
* known offset, then the code they point at. The room needs one constant, not a link
* map. (Same reasoning as the intro bundle's fixed slots -- an index would be a third
* place to get the layout wrong.)
*
*   $0A00  flame_draw   9 x fdb
*   $0A12  flame_save   9 x fdb
*   $0A24  flame_erase  9 x fdb
*   $0A36  the compiled cels
*
* The compiled routines are position-dependent only through these tables: each is
* straight-line code addressing the framebuffer through U and the peel buffer through
* Y, with no absolute references of its own, so linking the bundle at $0A00 is all
* that placement requires.
* ---------------------------------------------------------------

                ifdef   OBJTARGET
                section prog
                export  flame_draw      ; only so lwlink has an exec address to
                endc                    ; resolve; this bundle is data, never EXEC'd

flame_draw      fdb     _draw_flame1,_draw_flame2,_draw_flame3
                fdb     _draw_flame4,_draw_flame5,_draw_flame6
                fdb     _draw_flame7,_draw_flame8,_draw_flame9
flame_save      fdb     _save_flame1,_save_flame2,_save_flame3
                fdb     _save_flame4,_save_flame5,_save_flame6
                fdb     _save_flame7,_save_flame8,_save_flame9
flame_erase     fdb     _erase_flame1,_erase_flame2,_erase_flame3
                fdb     _erase_flame4,_erase_flame5,_erase_flame6
                fdb     _erase_flame7,_erase_flame8,_erase_flame9

* The compiled cels — straight-line draw/save/erase per flame, generated by
* harness/tools/sprite_compiler.py from the oracle's chtable6 cels 1-9.
                include "build/flames/flame1.s"
                include "build/flames/flame2.s"
                include "build/flames/flame3.s"
                include "build/flames/flame4.s"
                include "build/flames/flame5.s"
                include "build/flames/flame6.s"
                include "build/flames/flame7.s"
                include "build/flames/flame8.s"
                include "build/flames/flame9.s"
