* chtab2_057_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 19 rows x 5 bytes, 194 segment bytes
*
chtab2_057_p0:
        fcb     19,5  ; height, width in bytes
        fcb     $41,$81,$FF,$C1,$3F,$C0,$42,$00,$C1,$F0,$0F,$81
        fcb     $FF,$C1,$0F,$F0,$42,$00,$C1,$F0,$0F,$81,$FF,$C1
        fcb     $0F,$F0,$42,$00,$41,$81,$FF,$C1,$0F,$F0,$42,$00
        fcb     $C1,$FC,$01,$81,$7F,$C1,$0F,$F0,$42,$00,$C1,$FC
        fcb     $01,$82,$57,$FF,$C1,$03,$FC,$41,$00,$C1,$FC,$01
        fcb     $83,$FF,$FF,$57,$C1,$3F,$C0,$00,$41,$C1,$C0,$15
        fcb     $82,$7F,$FF,$C1,$03,$FC,$00,$41,$C1,$C0,$15,$83
        fcb     $FF,$FF,$7F,$00,$41,$C1,$C0,$15,$83,$FF,$FF,$7F
        fcb     $00,$41,$C1,$C0,$15,$83,$FF,$FF,$7F,$00,$41,$C1
        fcb     $C0,$17,$83,$FF,$FF,$FF,$00,$41,$C1,$C0,$17,$82
        fcb     $FF,$FF,$C1,$03,$FC,$00,$41,$C1,$C0,$17,$82,$FF
        fcb     $FF,$C1,$0F,$F0,$00,$41,$C1,$C0,$17,$82,$FF,$FF
        fcb     $C1,$3F,$C0,$00,$C1,$FC,$01,$81,$57,$C3,$0F,$F0
        fcb     $C0,$3F,$0F,$F0,$00,$C2,$FC,$01,$0F,$50,$41,$C2
        fcb     $C0,$3F,$0F,$F0,$00,$C1,$FC,$01,$42,$81,$FF,$C1
        fcb     $3F,$C0,$00,$C1,$C0,$15,$41,$C2,$FC,$03,$03,$FC
        fcb     $41,$00
