* chtab2_061_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 26 rows x 6 bytes, 273 segment bytes
*
chtab2_061_p0:
        fcb     26,6  ; height, width in bytes
        fcb     $C1,$C0,$0F,$81,$FF,$C1,$3F,$00,$43,$00,$82,$FF
        fcb     $FF,$C1,$0F,$C0,$43,$00,$82,$FF,$FE,$C1,$0F,$80
        fcb     $43,$00,$C2,$C0,$0F,$0C,$C0,$81,$FF,$C1,$3F,$00
        fcb     $42,$00,$C1,$C0,$0A,$83,$FF,$FC,$AF,$42,$00,$C1
        fcb     $C0,$08,$83,$FF,$FF,$3F,$C1,$03,$F0,$41,$00,$C1
        fcb     $C0,$08,$84,$3E,$FF,$FF,$FF,$C1,$3F,$00,$00,$41
        fcb     $C1,$C0,$0A,$83,$FF,$FF,$FF,$C1,$3F,$C0,$00,$41
        fcb     $C1,$C0,$0A,$83,$FF,$FF,$AF,$C1,$03,$F0,$00,$41
        fcb     $C1,$C0,$0A,$84,$83,$FF,$FF,$FC,$00,$41,$C2,$FC
        fcb     $00,$0C,$80,$83,$FF,$FC,$FF,$00,$41,$C2,$FC,$00
        fcb     $0C,$80,$83,$FF,$FC,$FF,$00,$41,$C2,$FC,$00,$0C
        fcb     $80,$82,$FF,$FF,$C1,$03,$F0,$00,$41,$C1,$FC,$00
        fcb     $83,$FF,$FF,$83,$C1,$03,$F0,$00,$41,$C1,$FC,$00
        fcb     $83,$FF,$FF,$AF,$C1,$3F,$C0,$00,$41,$C1,$FC,$00
        fcb     $83,$FF,$FF,$AF,$C1,$3F,$00,$00,$41,$C1,$FC,$00
        fcb     $83,$FF,$FF,$AF,$C1,$3F,$C0,$00,$41,$C1,$FC,$00
        fcb     $83,$FF,$FF,$AF,$C1,$3F,$C0,$00,$41,$C1,$FC,$00
        fcb     $83,$FF,$FF,$AF,$C1,$3F,$C0,$00,$41,$C1,$FC,$00
        fcb     $83,$FF,$FF,$AF,$C1,$03,$F0,$00,$41,$C1,$FC,$00
        fcb     $84,$83,$FF,$FF,$FC,$00,$42,$C1,$FC,$00,$83,$FF
        fcb     $FC,$FF,$00,$43,$C2,$0F,$10,$C0,$0F,$81,$FC,$00
        fcb     $44,$C2,$C0,$0F,$03,$F0,$00,$44,$C2,$C0,$0F,$3F
        fcb     $C0,$00,$44,$C2,$C0,$0F,$3F,$00,$00
