* chtab2_055_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 29 rows x 5 bytes, 258 segment bytes
*
chtab2_055_p0:
        fcb     29,5  ; height, width in bytes
        fcb     $41,$C2,$C0,$3F,$0F,$F0,$42,$00,$C1,$FC,$03,$81
        fcb     $FF,$C1,$03,$FC,$42,$00,$C1,$FC,$03,$81,$FF,$C1
        fcb     $03,$FC,$42,$00,$41,$C2,$C0,$3F,$03,$FC,$42,$00
        fcb     $41,$81,$AA,$C1,$03,$FC,$42,$00,$41,$81,$AA,$C1
        fcb     $0F,$F0,$42,$00,$41,$82,$AF,$FF,$C1,$3F,$C0,$41
        fcb     $00,$42,$81,$AF,$C1,$0F,$F0,$41,$00,$42,$81,$AF
        fcb     $C1,$0F,$F0,$41,$00,$42,$81,$AF,$C1,$03,$FC,$41
        fcb     $00,$42,$82,$AF,$FF,$C1,$3F,$C0,$00,$42,$82,$AF
        fcb     $FF,$C1,$0F,$F0,$00,$41,$83,$AF,$FF,$AA,$C1,$03
        fcb     $FC,$00,$41,$C2,$03,$A8,$F0,$0F,$81,$FF,$C1,$0F
        fcb     $F0,$00,$41,$C1,$FC,$03,$82,$FF,$FF,$C1,$0F,$F0
        fcb     $00,$41,$C1,$C0,$3F,$82,$FF,$FF,$C1,$0F,$F0,$00
        fcb     $41,$83,$FF,$FF,$FF,$C1,$3F,$C0,$00,$41,$83,$FF
        fcb     $FF,$FF,$C1,$3F,$C0,$00,$C1,$FC,$03,$82,$FF,$FF
        fcb     $C1,$03,$FC,$41,$00,$C1,$FC,$03,$82,$FF,$FF,$42
        fcb     $00,$C1,$FC,$03,$81,$FF,$C1,$0F,$F0,$42,$00,$41
        fcb     $81,$FF,$C1,$03,$FC,$42,$00,$41,$81,$FF,$C1,$03
        fcb     $FC,$42,$00,$41,$C2,$C0,$3F,$03,$FC,$42,$00,$41
        fcb     $C1,$FC,$03,$81,$FF,$42,$00,$42,$C2,$C0,$3F,$3F
        fcb     $C0,$41,$00,$42,$81,$FF,$C1,$0F,$F0,$41,$00,$41
        fcb     $C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$41,$00,$41,$C2
        fcb     $F0,$0F,$03,$FC,$42,$00
