* chtab2_066_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 38 rows x 4 bytes, 303 segment bytes
*
chtab2_066_p0:
        fcb     38,4  ; height, width in bytes
        fcb     $C1,$FC,$03,$81,$FF,$42,$00,$82,$7F,$FF,$C1,$3F
        fcb     $C0,$41,$00,$82,$7F,$FF,$C1,$3F,$C0,$41,$00,$C1
        fcb     $FC,$03,$81,$FF,$C1,$3F,$C0,$41,$00,$C1,$F0,$0A
        fcb     $81,$FF,$C1,$3F,$C0,$41,$00,$C1,$F0,$0A,$81,$AF
        fcb     $42,$00,$C1,$F0,$0A,$81,$AF,$C1,$3F,$C0,$41,$00
        fcb     $41,$C2,$C0,$3F,$03,$FC,$41,$00,$41,$C1,$C0,$3E
        fcb     $81,$FF,$41,$00,$41,$82,$FE,$AF,$41,$00,$41,$82
        fcb     $FE,$AF,$41,$00,$41,$C1,$C0,$3F,$81,$EF,$C1,$3F
        fcb     $C0,$00,$41,$C1,$C0,$3F,$81,$EF,$C1,$3F,$C0,$00
        fcb     $41,$C1,$C0,$3F,$81,$EA,$C1,$0F,$F0,$00,$41,$C1
        fcb     $F0,$0F,$81,$EA,$C1,$03,$FC,$00,$41,$C1,$FC,$03
        fcb     $81,$FE,$C1,$03,$FC,$00,$41,$C1,$FC,$03,$82,$FE
        fcb     $FF,$00,$42,$82,$FE,$FF,$00,$42,$82,$FE,$FF,$00
        fcb     $42,$81,$FE,$C1,$03,$FC,$00,$42,$81,$AA,$C1,$0F
        fcb     $F0,$00,$42,$81,$AF,$C1,$0F,$F0,$00,$42,$81,$AF
        fcb     $C1,$0F,$F0,$00,$41,$C1,$FC,$03,$81,$FF,$C1,$0F
        fcb     $F0,$00,$41,$C1,$FC,$03,$81,$FF,$C1,$0F,$F0,$00
        fcb     $41,$C1,$FC,$03,$81,$FF,$C1,$0F,$F0,$00,$41,$C1
        fcb     $FC,$03,$81,$FF,$C1,$0F,$F0,$00,$42,$81,$FF,$C1
        fcb     $0F,$F0,$00,$42,$81,$FF,$C1,$0F,$F0,$00,$42,$81
        fcb     $FF,$C1,$0F,$F0,$00,$42,$81,$FF,$C1,$0F,$F0,$00
        fcb     $42,$81,$FF,$C1,$0F,$F0,$00,$42,$C2,$C0,$3F,$0F
        fcb     $F0,$00,$42,$C2,$C0,$3F,$3F,$C0,$00,$42,$C2,$C0
        fcb     $3F,$3F,$C0,$00,$42,$81,$FE,$C1,$3F,$80,$00,$41
        fcb     $C2,$FC,$03,$03,$FC,$41,$00,$41,$C2,$C0,$3F,$03
        fcb     $FC,$41,$00
