* chtab2_061_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 26 rows x 6 bytes, 248 segment bytes
*
chtab2_061_p0:
        fcb     26,6  ; height, width in bytes
        fcb     $C1,$F0,$0F,$81,$FF,$44,$00,$82,$FF,$FF,$C1,$3F
        fcb     $C0,$43,$00,$82,$FF,$FE,$C1,$3F,$80,$43,$00,$C2
        fcb     $F0,$0F,$3F,$C0,$81,$FF,$43,$00,$C1,$F0,$0A,$82
        fcb     $AF,$FF,$C1,$03,$FC,$42,$00,$C2,$F3,$08,$C0,$3F
        fcb     $82,$FF,$FF,$C1,$0F,$F0,$41,$00,$C2,$F3,$08,$C0
        fcb     $3E,$83,$FF,$FF,$FF,$41,$00,$41,$C1,$F0,$0A,$83
        fcb     $FF,$FF,$FF,$C1,$3F,$C0,$00,$41,$C1,$F0,$0A,$83
        fcb     $FF,$FF,$AF,$C1,$0F,$F0,$00,$41,$C2,$F0,$0A,$3C
        fcb     $83,$82,$FF,$FF,$C1,$03,$FC,$00,$42,$C1,$3F,$80
        fcb     $82,$FF,$FF,$C1,$03,$FC,$00,$42,$C1,$3F,$80,$82
        fcb     $FF,$FF,$C1,$03,$FC,$00,$42,$C1,$3F,$80,$82,$FF
        fcb     $FF,$C1,$0F,$F0,$00,$42,$C1,$3C,$83,$82,$FF,$FF
        fcb     $C1,$0F,$F0,$00,$42,$83,$FF,$FF,$AF,$C1,$3F,$C0
        fcb     $00,$42,$83,$FF,$FF,$AF,$41,$00,$42,$83,$FF,$FF
        fcb     $AF,$C1,$3F,$C0,$00,$42,$83,$FF,$FF,$AF,$C1,$3F
        fcb     $C0,$00,$42,$83,$FF,$FF,$AF,$C1,$3F,$C0,$00,$42
        fcb     $83,$FF,$FF,$AF,$C1,$0F,$F0,$00,$42,$C1,$3C,$83
        fcb     $82,$FF,$FF,$C1,$03,$FC,$00,$43,$82,$FF,$FF,$C1
        fcb     $03,$FC,$00,$43,$C3,$CF,$10,$F0,$0F,$03,$FC,$00
        fcb     $44,$C2,$F0,$0F,$0F,$F0,$00,$44,$C2,$F0,$0F,$3F
        fcb     $C0,$00,$44,$C1,$F0,$0F,$41,$00
