* chtab2_068_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 4 rows x 5 bytes, 39 segment bytes
*
chtab2_068_p0:
        fcb     4,5  ; height, width in bytes
        fcb     $41,$81,$F7,$C1,$03,$FC,$42,$00,$41,$82,$FF,$FF
        fcb     $C1,$3F,$C0,$41,$00,$C1,$FC,$03,$82,$FF,$FF,$C1
        fcb     $3F,$C0,$41,$00,$C1,$F0,$0F,$83,$FE,$FF,$FE,$C1
        fcb     $0F,$F0,$00
