* chtab2_070_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 10 rows x 4 bytes, 72 segment bytes
*
chtab2_070_p0:
        fcb     10,4  ; height, width in bytes
        fcb     $81,$10,$C1,$03,$F0,$42,$00,$81,$7F,$C1,$03,$FC
        fcb     $42,$00,$C2,$C0,$0F,$03,$F0,$42,$00,$C2,$C0,$0F
        fcb     $03,$F0,$42,$00,$81,$17,$C1,$03,$FC,$42,$00,$C2
        fcb     $F0,$03,$03,$FC,$42,$00,$C1,$F0,$03,$81,$FF,$C1
        fcb     $3F,$00,$41,$00,$C1,$C0,$0F,$82,$F7,$FC,$41,$00
        fcb     $42,$C2,$C0,$0F,$3F,$00,$00,$42,$81,$3C,$41,$00
