* chtab2_070_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 10 rows x 3 bytes, 68 segment bytes
*
chtab2_070_p0:
        fcb     10,3  ; height, width in bytes
        fcb     $C2,$CF,$10,$0F,$F0,$41,$00,$81,$7F,$C1,$03,$FC
        fcb     $41,$00,$C2,$F0,$0F,$0F,$F0,$41,$00,$C2,$F0,$0F
        fcb     $0F,$F0,$41,$00,$C2,$C0,$17,$03,$FC,$41,$00,$C2
        fcb     $FC,$03,$03,$FC,$41,$00,$C1,$FC,$03,$81,$FF,$41
        fcb     $00,$C1,$F0,$0F,$81,$F7,$C1,$03,$FC,$00,$42,$C1
        fcb     $F0,$0F,$00,$42,$C1,$C3,$3C,$00
