* chtab2_036_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 1 rows x 2 bytes, 2 segment bytes
*
chtab2_036_p0:
        fcb     1,2  ; height, width in bytes
        fcb     $42,$00
