* chtab2_055_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 29 rows x 5 bytes, 277 segment bytes
*
chtab2_055_p0:
        fcb     29,5  ; height, width in bytes
        fcb     $41,$81,$3F,$C1,$03,$F0,$42,$00,$C1,$F0,$03,$82
        fcb     $FF,$FC,$42,$00,$C1,$F0,$03,$82,$FF,$FC,$42,$00
        fcb     $41,$82,$3F,$FC,$42,$00,$C1,$FC,$00,$82,$AA,$FC
        fcb     $42,$00,$C1,$FC,$00,$81,$AA,$C1,$03,$F0,$42,$00
        fcb     $C1,$FC,$00,$82,$AF,$FF,$C1,$0F,$C0,$41,$00,$41
        fcb     $C1,$FC,$00,$81,$AF,$C1,$0F,$F0,$41,$00,$41,$C1
        fcb     $FC,$00,$81,$AF,$C1,$0F,$F0,$41,$00,$41,$C1,$FC
        fcb     $00,$82,$AF,$FC,$41,$00,$41,$C1,$FC,$00,$82,$AF
        fcb     $FF,$C1,$0F,$C0,$00,$41,$C1,$FC,$00,$82,$AF,$FF
        fcb     $C1,$03,$F0,$00,$C1,$FC,$00,$84,$AA,$AF,$FF,$FC
        fcb     $00,$C3,$FC,$00,$03,$A8,$C0,$0F,$81,$FF,$C1,$03
        fcb     $F0,$00,$41,$C1,$FC,$03,$82,$FF,$FF,$C1,$03,$F0
        fcb     $00,$41,$83,$FF,$FF,$3F,$C1,$03,$F0,$00,$C1,$FC
        fcb     $00,$83,$FF,$FF,$FF,$C1,$0F,$C0,$00,$C1,$FC,$00
        fcb     $83,$FF,$FF,$FF,$C1,$0F,$C0,$00,$C1,$F0,$03,$83
        fcb     $FF,$FC,$FF,$41,$00,$C1,$F0,$03,$82,$FF,$FF,$C1
        fcb     $3F,$00,$41,$00,$C1,$F0,$03,$81,$FF,$C1,$03,$F0
        fcb     $42,$00,$C1,$FC,$00,$82,$FF,$FC,$42,$00,$C1,$FC
        fcb     $00,$82,$FF,$FC,$42,$00,$41,$82,$3F,$FC,$42,$00
        fcb     $41,$C1,$FC,$03,$81,$FF,$C1,$3F,$00,$41,$00,$42
        fcb     $81,$3F,$C1,$0F,$C0,$41,$00,$41,$C1,$FC,$00,$81
        fcb     $FF,$C1,$0F,$F0,$41,$00,$41,$C1,$FC,$03,$81,$FF
        fcb     $C1,$0F,$C0,$41,$00,$41,$C1,$C0,$0F,$81,$FC,$42
        fcb     $00
