* chtab2_059_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 22 rows x 6 bytes, 220 segment bytes
*
chtab2_059_p0:
        fcb     22,6  ; height, width in bytes
        fcb     $C2,$C0,$0F,$03,$FC,$44,$00,$82,$FF,$FF,$C1,$3F
        fcb     $00,$43,$00,$83,$FE,$FF,$FF,$C1,$3F,$00,$42,$00
        fcb     $C1,$F0,$03,$83,$FF,$FF,$FF,$C1,$3F,$00,$41,$00
        fcb     $84,$15,$7F,$FF,$FF,$C1,$03,$F0,$41,$00,$85,$7F
        fcb     $FF,$FF,$FC,$15,$41,$00,$85,$57,$FF,$FF,$FF,$15
        fcb     $C1,$3F,$C0,$00,$41,$84,$17,$FF,$FF,$FF,$C1,$3F
        fcb     $C0,$00,$41,$84,$17,$FF,$FF,$FF,$C1,$3F,$C0,$00
        fcb     $41,$84,$17,$FF,$FF,$FF,$C1,$3F,$C0,$00,$41,$84
        fcb     $17,$FF,$FF,$FF,$C1,$3F,$00,$00,$41,$84,$17,$FF
        fcb     $FF,$FC,$41,$00,$41,$83,$FF,$FF,$17,$C1,$0F,$C0
        fcb     $41,$00,$41,$83,$FF,$FE,$17,$C1,$0F,$80,$41,$00
        fcb     $41,$83,$FF,$FC,$17,$42,$00,$41,$84,$17,$FF,$FF
        fcb     $FF,$C1,$3F,$00,$00,$41,$C1,$03,$10,$83,$FF,$FF
        fcb     $3F,$C1,$3F,$00,$00,$41,$C3,$03,$10,$C0,$0F,$0C
        fcb     $C0,$81,$FF,$C1,$3F,$00,$00,$41,$C1,$03,$10,$41
        fcb     $C1,$FC,$00,$81,$FF,$C1,$3F,$00,$00,$41,$C1,$03
        fcb     $10,$41,$C1,$FC,$00,$81,$FC,$41,$00,$41,$C1,$03
        fcb     $10,$41,$C2,$F0,$03,$03,$F0,$41,$00,$C2,$F0,$01
        fcb     $03,$50,$44,$00
