* chtab2_058_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 20 rows x 6 bytes, 212 segment bytes
*
chtab2_058_p0:
        fcb     20,6  ; height, width in bytes
        fcb     $C2,$F0,$0F,$03,$FC,$44,$00,$82,$FF,$FF,$44,$00
        fcb     $82,$FF,$FF,$44,$00,$C1,$F0,$0F,$82,$FF,$FF,$C1
        fcb     $03,$FC,$42,$00,$C1,$C0,$17,$83,$FF,$FF,$FF,$C1
        fcb     $3F,$C0,$41,$00,$C1,$C0,$15,$83,$FF,$FF,$7F,$C1
        fcb     $03,$FC,$41,$00,$C1,$C0,$15,$84,$57,$FF,$FF,$FF
        fcb     $41,$00,$41,$C1,$C0,$17,$83,$FF,$FF,$FF,$C1,$3F
        fcb     $C0,$00,$41,$C1,$C0,$15,$83,$FF,$FF,$7F,$C1,$3F
        fcb     $C0,$00,$41,$C1,$C0,$15,$83,$FF,$FF,$7F,$C1,$3F
        fcb     $C0,$00,$41,$C1,$C0,$15,$83,$FF,$FF,$7F,$C1,$3F
        fcb     $C0,$00,$41,$C1,$C0,$17,$83,$FF,$FF,$FF,$41,$00
        fcb     $41,$C1,$C0,$17,$82,$FF,$FF,$C1,$03,$FC,$41,$00
        fcb     $41,$C1,$C0,$17,$82,$FF,$FF,$C1,$3F,$C0,$41,$00
        fcb     $41,$C1,$C0,$17,$82,$FF,$FF,$C1,$03,$FC,$41,$00
        fcb     $41,$C1,$C0,$17,$81,$FF,$C2,$3C,$C3,$03,$FC,$41
        fcb     $00,$41,$C4,$CF,$10,$F0,$0F,$FC,$03,$03,$FC,$41
        fcb     $00,$41,$C1,$CF,$10,$41,$C2,$FC,$03,$0F,$F0,$41
        fcb     $00,$41,$C1,$CF,$10,$41,$C2,$F0,$0F,$3F,$C0,$41
        fcb     $00,$C2,$FC,$01,$0F,$50,$44,$00
