* chtab2_062_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 29 rows x 7 bytes, 318 segment bytes
*
chtab2_062_p0:
        fcb     29,7  ; height, width in bytes
        fcb     $C1,$F0,$03,$81,$FF,$C1,$3F,$00,$44,$00,$82,$7F
        fcb     $FF,$C1,$0F,$C0,$44,$00,$82,$FF,$FF,$C1,$0F,$C0
        fcb     $44,$00,$82,$FF,$FF,$C1,$0F,$C0,$44,$00,$C1,$C0
        fcb     $0A,$82,$AF,$FF,$C1,$0F,$C0,$43,$00,$C1,$C0,$0A
        fcb     $83,$FF,$FF,$AA,$C1,$0F,$C0,$42,$00,$C1,$FC,$00
        fcb     $84,$AF,$FF,$FF,$FC,$42,$00,$41,$C1,$C0,$0F,$83
        fcb     $FF,$FF,$FF,$C1,$3F,$C0,$41,$00,$41,$C1,$FC,$03
        fcb     $83,$FF,$FF,$EF,$C1,$03,$F0,$41,$00,$41,$C1,$FC
        fcb     $00,$84,$AA,$FF,$FF,$FC,$41,$00,$42,$C1,$C0,$0A
        fcb     $83,$FF,$FC,$FF,$41,$00,$42,$C1,$C0,$0A,$83,$FF
        fcb     $FF,$FF,$C1,$3F,$00,$00,$42,$C1,$C0,$0A,$83,$FF
        fcb     $FC,$FF,$41,$00,$42,$C1,$C0,$0A,$82,$FF,$FF,$C1
        fcb     $03,$F0,$41,$00,$42,$C1,$C0,$0A,$82,$FF,$FF,$C1
        fcb     $3F,$C0,$41,$00,$42,$C1,$C0,$0A,$82,$FF,$FC,$42
        fcb     $00,$41,$C1,$FC,$00,$82,$FE,$FF,$C1,$0F,$C0,$42
        fcb     $00,$41,$C1,$FC,$00,$82,$FE,$FF,$C2,$30,$03,$3F
        fcb     $C0,$41,$00,$41,$C1,$FC,$00,$83,$FE,$FF,$FE,$C1
        fcb     $03,$F0,$41,$00,$41,$C1,$FC,$00,$84,$FE,$FC,$3F
        fcb     $FC,$41,$00,$42,$84,$3E,$FF,$0F,$FF,$C1,$3F,$00
        fcb     $00,$42,$82,$3F,$FF,$C1,$30,$03,$81,$FF,$C1,$3F
        fcb     $00,$00,$42,$82,$3F,$FF,$C1,$30,$03,$81,$FF,$C1
        fcb     $0F,$C0,$00,$42,$C1,$C0,$0F,$81,$FF,$C3,$3F,$00
        fcb     $C0,$0F,$03,$F0,$00,$43,$81,$3F,$C2,$0F,$C0,$C0
        fcb     $0F,$81,$FC,$00,$43,$C4,$F0,$0F,$03,$F0,$C0,$0F
        fcb     $03,$F0,$00,$43,$C1,$F0,$0F,$82,$F0,$FF,$C1,$3F
        fcb     $00,$00,$43,$81,$3F,$C1,$0F,$C0,$42,$00,$42,$C1
        fcb     $FC,$00,$81,$FC,$43,$00
