* chtab2_058_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 20 rows x 6 bytes, 187 segment bytes
*
chtab2_058_p0:
        fcb     20,6  ; height, width in bytes
        fcb     $C2,$C0,$0F,$03,$FC,$44,$00,$82,$FF,$FF,$C1,$3F
        fcb     $00,$43,$00,$82,$FF,$FF,$C1,$3F,$00,$43,$00,$C1
        fcb     $C0,$0F,$83,$FF,$FC,$FF,$42,$00,$84,$17,$FF,$FF
        fcb     $FF,$C1,$0F,$C0,$41,$00,$85,$7F,$FF,$FF,$FC,$15
        fcb     $41,$00,$85,$57,$FF,$FF,$FF,$15,$C1,$3F,$00,$00
        fcb     $41,$84,$17,$FF,$FF,$FF,$C1,$3F,$C0,$00,$41,$84
        fcb     $15,$7F,$FF,$FF,$C1,$3F,$C0,$00,$41,$84,$15,$7F
        fcb     $FF,$FF,$C1,$3F,$C0,$00,$41,$84,$15,$7F,$FF,$FF
        fcb     $C1,$3F,$C0,$00,$41,$84,$17,$FF,$FF,$FF,$C1,$3F
        fcb     $00,$00,$41,$84,$17,$FF,$FF,$FC,$41,$00,$41,$83
        fcb     $FF,$FF,$17,$C1,$0F,$C0,$41,$00,$41,$84,$17,$FF
        fcb     $FF,$FC,$41,$00,$41,$84,$17,$FF,$C3,$FC,$41,$00
        fcb     $41,$C3,$03,$10,$C0,$0F,$30,$03,$81,$FC,$41,$00
        fcb     $41,$C1,$03,$10,$41,$C2,$F0,$03,$03,$F0,$41,$00
        fcb     $41,$C1,$03,$10,$41,$C2,$F0,$0F,$0F,$C0,$41,$00
        fcb     $C2,$F0,$01,$03,$50,$44,$00
