* chtab2_016_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 16 rows x 9 bytes, 216 segment bytes
*
chtab2_016_p0:
        fcb     16,9  ; height, width in bytes
        fcb     $45,$C1,$C0,$3F,$43,$00,$43,$C4,$FC,$03,$0F,$F0
        fcb     $C0,$3F,$3F,$C0,$42,$00,$43,$C4,$F0,$0F,$0F,$F0
        fcb     $C0,$3F,$3F,$C0,$42,$00,$43,$C3,$F0,$0F,$0F,$F0
        fcb     $FC,$01,$43,$00,$42,$82,$FF,$F7,$C2,$0F,$F0,$C0
        fcb     $3F,$43,$00,$42,$82,$FF,$FF,$41,$81,$FF,$C1,$3F
        fcb     $C0,$42,$00,$42,$C2,$C0,$3F,$03,$FC,$41,$81,$FF
        fcb     $C1,$3F,$C0,$42,$00,$42,$C1,$C0,$3F,$81,$FF,$C1
        fcb     $FC,$03,$81,$FF,$C1,$3F,$C0,$42,$00,$42,$C1,$F0
        fcb     $0F,$82,$F7,$FF,$C1,$03,$FC,$43,$00,$41,$C2,$C0
        fcb     $15,$F0,$0F,$82,$55,$7F,$C1,$03,$FC,$41,$C2,$FC
        fcb     $01,$0F,$50,$00,$41,$C2,$C0,$15,$F0,$0F,$82,$55
        fcb     $7F,$C1,$03,$FC,$41,$C2,$FC,$01,$0F,$50,$00,$C6
        fcb     $FC,$01,$0F,$50,$C3,$3C,$C0,$15,$F0,$0F,$03,$FC
        fcb     $41,$C1,$C0,$15,$41,$00,$C1,$C0,$15,$84,$55,$7F
        fcb     $FF,$FF,$C3,$03,$7C,$C0,$15,$0F,$50,$41,$00,$C1
        fcb     $C0,$15,$86,$FF,$FF,$55,$55,$57,$FF,$42,$00,$C1
        fcb     $FC,$01,$85,$FF,$FF,$EF,$55,$57,$C1,$0F,$50,$42
        fcb     $00,$42,$C1,$FC,$03,$81,$FF,$C1,$0F,$F0,$44,$00
