* chtab2_056_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 23 rows x 5 bytes, 227 segment bytes
*
chtab2_056_p0:
        fcb     23,5  ; height, width in bytes
        fcb     $C1,$FC,$00,$81,$FF,$C1,$3F,$00,$42,$00,$C1,$C0
        fcb     $0F,$81,$FF,$C1,$0F,$C0,$42,$00,$82,$7F,$FF,$C1
        fcb     $03,$F0,$42,$00,$C1,$C0,$0F,$81,$FF,$C1,$03,$F0
        fcb     $42,$00,$C1,$FC,$00,$81,$FF,$C1,$03,$F0,$42,$00
        fcb     $C1,$FC,$00,$82,$AA,$FF,$C1,$0F,$C0,$41,$00,$C1
        fcb     $FC,$00,$83,$FF,$FC,$AF,$41,$00,$41,$C1,$C0,$0A
        fcb     $82,$FF,$FF,$C1,$0F,$C0,$00,$41,$C1,$C0,$0A,$82
        fcb     $FF,$FF,$C1,$03,$F0,$00,$41,$C1,$C0,$0A,$83,$FF
        fcb     $FC,$FF,$00,$41,$C1,$C0,$0A,$83,$FF,$FC,$FF,$00
        fcb     $41,$C1,$C0,$0A,$83,$FF,$FC,$FF,$00,$41,$C1,$C0
        fcb     $0A,$83,$FF,$FC,$FF,$00,$C1,$FC,$00,$84,$AA,$FF
        fcb     $FF,$FC,$00,$C1,$FC,$00,$83,$FF,$FF,$AF,$C1,$03
        fcb     $F0,$00,$C1,$FC,$00,$83,$FF,$FF,$AF,$C1,$0F,$C0
        fcb     $00,$C1,$FC,$00,$82,$AF,$FF,$C1,$3F,$00,$41,$00
        fcb     $C1,$C0,$0A,$82,$AF,$FF,$C1,$0F,$F0,$41,$00,$C1
        fcb     $C0,$0A,$83,$C3,$FF,$AF,$C1,$3F,$00,$00,$C3,$C0
        fcb     $0A,$0F,$80,$F0,$03,$81,$FF,$C1,$3F,$00,$00,$42
        fcb     $C1,$F0,$03,$81,$FC,$41,$00,$42,$C2,$F0,$03,$0F
        fcb     $F0,$41,$00,$42,$C2,$C0,$0F,$0F,$C0,$41,$00
