* chtab2_018_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 41 rows x 3 bytes, 345 segment bytes
*
chtab2_018_p0:
        fcb     41,3  ; height, width in bytes
        fcb     $C2,$F0,$0F,$03,$FC,$41,$00,$C1,$F0,$0F,$81,$FF
        fcb     $41,$00,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$00,$C1
        fcb     $C0,$17,$81,$FF,$C1,$3F,$C0,$00,$C1,$C0,$15,$81
        fcb     $7F,$C1,$3F,$C0,$00,$C1,$C0,$15,$81,$7F,$41,$00
        fcb     $C2,$FC,$01,$03,$7C,$41,$00,$C2,$FC,$01,$0F,$50
        fcb     $41,$00,$C2,$FC,$03,$03,$FC,$41,$00,$C1,$FC,$03
        fcb     $81,$FF,$41,$00,$C1,$F0,$0F,$81,$7F,$C1,$3F,$C0
        fcb     $00,$C1,$F0,$0F,$81,$57,$C1,$3F,$C0,$00,$C1,$F0
        fcb     $0F,$81,$57,$C1,$0F,$F0,$00,$C1,$F0,$0F,$81,$F7
        fcb     $C1,$0F,$F0,$00,$C1,$F0,$0F,$81,$F7,$C1,$0F,$F0
        fcb     $00,$C1,$F0,$0F,$81,$F7,$C1,$0F,$F0,$00,$C1,$F0
        fcb     $0F,$81,$F7,$C1,$03,$FC,$00,$C1,$F0,$0F,$81,$F7
        fcb     $C1,$03,$FC,$00,$C1,$F0,$0F,$81,$57,$C1,$03,$FC
        fcb     $00,$C1,$F0,$0F,$81,$57,$C1,$03,$FC,$00,$C1,$F0
        fcb     $0F,$81,$7F,$C1,$03,$FC,$00,$C1,$F0,$0F,$81,$7F
        fcb     $C1,$03,$FC,$00,$C1,$FC,$01,$81,$7F,$C1,$03,$FC
        fcb     $00,$C1,$FC,$01,$81,$7F,$C1,$03,$FC,$00,$C1,$FC
        fcb     $03,$81,$FF,$C1,$0F,$F0,$00,$C1,$FC,$03,$81,$FF
        fcb     $C1,$0F,$F0,$00,$C1,$FC,$03,$81,$FF,$C1,$0F,$F0
        fcb     $00,$C1,$FC,$03,$81,$FF,$C1,$0F,$F0,$00,$C1,$F0
        fcb     $0F,$81,$FF,$C1,$0F,$F0,$00,$C1,$F0,$0F,$81,$FF
        fcb     $C1,$0F,$F0,$00,$C1,$F0,$0F,$81,$FF,$C1,$3F,$C0
        fcb     $00,$C1,$F0,$0F,$81,$FF,$C1,$0F,$F0,$00,$C1,$F0
        fcb     $0F,$81,$FF,$C1,$0F,$F0,$00,$C1,$FC,$03,$81,$FF
        fcb     $C1,$0F,$F0,$00,$C1,$FC,$03,$81,$FF,$C1,$0F,$F0
        fcb     $00,$41,$81,$FF,$C1,$0F,$F0,$00,$41,$81,$FF,$C1
        fcb     $0F,$F0,$00,$41,$81,$FF,$C1,$03,$FC,$00,$C1,$FC
        fcb     $03,$81,$FF,$C1,$03,$FC,$00,$82,$7F,$FF,$C1,$03
        fcb     $FC,$00,$81,$FF,$C1,$3F,$C0,$41,$00
