* chtab2_062_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 29 rows x 7 bytes, 311 segment bytes
*
chtab2_062_p0:
        fcb     29,7  ; height, width in bytes
        fcb     $C1,$FC,$03,$81,$FF,$45,$00,$82,$7F,$FF,$C1,$3F
        fcb     $C0,$44,$00,$82,$FF,$FF,$C1,$3F,$C0,$44,$00,$82
        fcb     $FF,$FF,$C1,$3F,$C0,$44,$00,$C1,$F0,$0A,$82,$AF
        fcb     $FF,$C1,$3F,$C0,$43,$00,$C1,$F0,$0A,$83,$FF,$FF
        fcb     $AA,$C1,$3F,$C0,$42,$00,$41,$83,$FF,$FF,$AF,$C1
        fcb     $03,$FC,$42,$00,$41,$C1,$F0,$0F,$83,$FF,$FF,$FF
        fcb     $C1,$3F,$C0,$41,$00,$41,$C1,$FC,$03,$83,$FF,$FF
        fcb     $EF,$C1,$0F,$F0,$41,$00,$42,$83,$FF,$FF,$AA,$C1
        fcb     $03,$FC,$41,$00,$42,$C1,$F0,$0A,$82,$FF,$FF,$C1
        fcb     $03,$FC,$41,$00,$42,$C1,$F0,$0A,$83,$FF,$FF,$FF
        fcb     $41,$00,$42,$C1,$F0,$0A,$82,$FF,$FF,$C1,$03,$FC
        fcb     $41,$00,$42,$C1,$F0,$0A,$82,$FF,$FF,$C1,$0F,$F0
        fcb     $41,$00,$42,$C1,$F0,$0A,$82,$FF,$FF,$C1,$3F,$C0
        fcb     $41,$00,$42,$C1,$F0,$0A,$81,$FF,$C1,$03,$FC,$42
        fcb     $00,$42,$82,$FE,$FF,$C1,$3F,$C0,$42,$00,$42,$82
        fcb     $FE,$FF,$C2,$FC,$03,$3F,$C0,$41,$00,$42,$83,$FE
        fcb     $FF,$FE,$C1,$0F,$F0,$41,$00,$42,$81,$FE,$C3,$03
        fcb     $FC,$C0,$3F,$03,$FC,$41,$00,$42,$C1,$C0,$3E,$81
        fcb     $FF,$C1,$F0,$0F,$81,$FF,$41,$00,$42,$C1,$C0,$3F
        fcb     $81,$FF,$C1,$FC,$03,$81,$FF,$41,$00,$42,$C1,$C0
        fcb     $3F,$81,$FF,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$00
        fcb     $42,$C1,$F0,$0F,$81,$FF,$41,$C2,$F0,$0F,$0F,$F0
        fcb     $00,$43,$C4,$C0,$3F,$3F,$C0,$F0,$0F,$03,$FC,$00
        fcb     $43,$C4,$F0,$0F,$0F,$F0,$F0,$0F,$0F,$F0,$00,$43
        fcb     $C2,$F0,$0F,$0F,$F0,$81,$FF,$41,$00,$43,$C2,$C0
        fcb     $3F,$3F,$C0,$42,$00,$43,$C1,$03,$FC,$43,$00
