* chtab2_014_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 12 rows x 12 bytes, 192 segment bytes
*
chtab2_014_p0:
        fcb     12,12  ; height, width in bytes
        fcb     $43,$C2,$F0,$0A,$3F,$80,$47,$00,$42,$C1,$FC,$03
        fcb     $81,$EA,$C1,$3F,$80,$47,$00,$42,$C1,$FC,$03,$81
        fcb     $FE,$C1,$03,$A8,$42,$C1,$C0,$3F,$44,$00,$42,$C1
        fcb     $F0,$0F,$82,$FF,$EA,$C1,$3F,$80,$41,$C2,$C0,$3F
        fcb     $0F,$F0,$43,$00,$C1,$FC,$03,$84,$FF,$FF,$FF,$EA
        fcb     $C2,$3F,$80,$FC,$03,$81,$FF,$C1,$03,$FC,$43,$00
        fcb     $C1,$F0,$0F,$84,$FE,$AF,$FF,$EA,$C2,$3F,$80,$F0
        fcb     $0F,$81,$FF,$C1,$03,$FC,$43,$00,$85,$FE,$AF,$FE
        fcb     $AA,$FF,$C2,$3F,$80,$F0,$0F,$82,$FF,$FF,$C1,$3F
        fcb     $C0,$42,$00,$8B,$FF,$FF,$EA,$FF,$FE,$AA,$AA,$AF
        fcb     $EA,$AA,$FF,$41,$00,$8B,$FF,$FF,$EA,$FF,$FE,$AA
        fcb     $AA,$AF,$EA,$AF,$FF,$41,$00,$8B,$FF,$FF,$FE,$AF
        fcb     $FE,$AA,$AA,$AF,$EA,$AF,$7F,$C1,$03,$FC,$00,$43
        fcb     $C1,$F0,$0A,$82,$AF,$FE,$C2,$03,$A8,$F0,$0F,$83
        fcb     $FE,$AF,$FF,$C1,$03,$FC,$00,$42,$C1,$F0,$0A,$82
        fcb     $AA,$AA,$C1,$3F,$80,$81,$AA,$C1,$3F,$80,$44,$00
