* chtab2_014_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 12 rows x 12 bytes, 191 segment bytes
*
chtab2_014_p0:
        fcb     12,12  ; height, width in bytes
        fcb     $43,$C2,$F0,$0A,$0F,$80,$47,$00,$42,$C1,$F0,$03
        fcb     $81,$EA,$C1,$0F,$80,$47,$00,$42,$C1,$F0,$03,$82
        fcb     $FE,$A8,$42,$81,$3F,$C1,$3F,$00,$43,$00,$42,$C1
        fcb     $C0,$0F,$82,$FF,$EA,$C1,$3F,$80,$41,$81,$3F,$C1
        fcb     $03,$F0,$43,$00,$C1,$F0,$03,$84,$FF,$FF,$FF,$EA
        fcb     $C2,$3F,$80,$F0,$03,$81,$FF,$C1,$03,$FC,$43,$00
        fcb     $C1,$C0,$0F,$84,$FE,$AF,$FF,$EA,$C2,$3F,$80,$C0
        fcb     $0F,$81,$FF,$C1,$03,$FC,$43,$00,$85,$FE,$AF,$FE
        fcb     $AA,$FF,$C2,$3F,$80,$C0,$0F,$82,$FF,$FF,$C1,$0F
        fcb     $C0,$42,$00,$8B,$FF,$FF,$EA,$FF,$FE,$AA,$AA,$AF
        fcb     $EA,$AA,$FF,$C1,$3F,$00,$00,$8B,$FF,$FF,$EA,$FF
        fcb     $FE,$AA,$AA,$AF,$EA,$AF,$FF,$C1,$3F,$00,$00,$8C
        fcb     $FF,$FE,$AF,$FC,$AA,$AA,$AF,$FF,$7F,$EA,$AF,$FE
        fcb     $00,$43,$C1,$F0,$0A,$83,$FE,$A8,$AF,$C1,$C0,$0F
        fcb     $84,$FF,$FE,$AF,$FC,$00,$42,$C1,$C0,$0A,$82,$AA
        fcb     $AA,$C1,$3C,$80,$81,$AA,$C1,$0F,$80,$44,$00
