* chtab2_060_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 24 rows x 7 bytes, 294 segment bytes
*
chtab2_060_p0:
        fcb     24,7  ; height, width in bytes
        fcb     $C1,$FC,$00,$81,$FF,$C1,$3F,$00,$44,$00,$C1,$C0
        fcb     $0F,$81,$FF,$C1,$0F,$C0,$44,$00,$82,$7F,$FF,$C1
        fcb     $03,$F0,$44,$00,$85,$FF,$FF,$FF,$FC,$7F,$42,$00
        fcb     $C1,$F0,$01,$84,$7F,$FF,$FF,$FF,$C1,$03,$F0,$41
        fcb     $00,$C1,$F0,$01,$85,$FF,$FF,$FF,$FC,$57,$41,$00
        fcb     $C1,$F0,$01,$85,$7F,$FF,$FF,$FF,$55,$C1,$3F,$00
        fcb     $00,$41,$85,$7F,$FF,$FF,$FF,$15,$C1,$3F,$00,$00
        fcb     $41,$C1,$FC,$01,$84,$7F,$FF,$FF,$FF,$C1,$3F,$00
        fcb     $00,$41,$C1,$FC,$01,$84,$50,$FF,$FF,$FC,$41,$00
        fcb     $41,$C2,$FC,$01,$3F,$00,$82,$3F,$FF,$C1,$03,$F0
        fcb     $41,$00,$41,$C2,$FC,$01,$3C,$00,$82,$FF,$FF,$C1
        fcb     $3F,$C0,$41,$00,$41,$C2,$FC,$01,$3C,$00,$82,$FF
        fcb     $FF,$C1,$3F,$00,$41,$00,$41,$C2,$FC,$01,$30,$03
        fcb     $82,$FF,$FC,$42,$00,$41,$C2,$FC,$01,$30,$03,$82
        fcb     $FF,$FF,$C1,$3F,$00,$41,$00,$41,$C2,$FC,$01,$30
        fcb     $03,$82,$FF,$FF,$C1,$3F,$C0,$41,$00,$41,$C2,$FC
        fcb     $01,$30,$03,$82,$FF,$FC,$C1,$C3,$10,$41,$00,$41
        fcb     $C2,$FC,$01,$3C,$00,$82,$FF,$FF,$C1,$3F,$C0,$41
        fcb     $00,$41,$C2,$FC,$01,$3F,$00,$82,$3F,$FF,$C1,$03
        fcb     $F0,$41,$00,$41,$C3,$FC,$01,$3F,$00,$F0,$0F,$82
        fcb     $C3,$FF,$C1,$3F,$00,$00,$41,$C2,$FC,$01,$3F,$00
        fcb     $41,$C1,$FC,$00,$81,$FF,$C1,$0F,$C0,$00,$41,$C2
        fcb     $FC,$01,$3F,$00,$41,$C1,$FC,$00,$81,$FF,$C1,$3F
        fcb     $00,$00,$44,$C1,$FC,$00,$81,$FC,$41,$00,$44,$C2
        fcb     $F0,$03,$03,$F0,$41,$00
