* chtab2_056_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 23 rows x 5 bytes, 216 segment bytes
*
chtab2_056_p0:
        fcb     23,5  ; height, width in bytes
        fcb     $41,$81,$FF,$43,$00,$C1,$F0,$0F,$81,$FF,$C1,$3F
        fcb     $C0,$42,$00,$82,$7F,$FF,$C1,$0F,$F0,$42,$00,$C1
        fcb     $F0,$0F,$81,$FF,$C1,$0F,$F0,$42,$00,$41,$81,$FF
        fcb     $C1,$0F,$F0,$42,$00,$41,$82,$AA,$FF,$C1,$3F,$C0
        fcb     $41,$00,$41,$82,$AF,$FF,$C1,$03,$FC,$41,$00,$41
        fcb     $C1,$F0,$0A,$82,$FF,$FF,$C1,$3F,$C0,$00,$41,$C1
        fcb     $F0,$0A,$82,$FF,$FF,$C1,$0F,$F0,$00,$41,$C1,$F0
        fcb     $0A,$82,$FF,$FF,$C1,$03,$FC,$00,$41,$C1,$F0,$0A
        fcb     $82,$FF,$FF,$C1,$03,$FC,$00,$41,$C1,$F0,$0A,$82
        fcb     $FF,$FF,$C1,$03,$FC,$00,$41,$C1,$F0,$0A,$82,$FF
        fcb     $FF,$C1,$03,$FC,$00,$41,$83,$FF,$FF,$AA,$C1,$03
        fcb     $FC,$00,$41,$83,$FF,$FF,$AF,$C1,$0F,$F0,$00,$41
        fcb     $83,$FF,$FF,$AF,$C1,$3F,$C0,$00,$41,$82,$AF,$FF
        fcb     $42,$00,$C1,$F0,$0A,$82,$AF,$FF,$C1,$0F,$F0,$41
        fcb     $00,$C1,$F0,$0A,$81,$AF,$C1,$3C,$C3,$81,$FF,$41
        fcb     $00,$C3,$F0,$0A,$3F,$80,$FC,$03,$81,$FF,$41,$00
        fcb     $42,$C2,$FC,$03,$03,$FC,$41,$00,$42,$C2,$FC,$03
        fcb     $0F,$F0,$41,$00,$42,$C2,$F0,$0F,$3F,$C0,$41,$00
