* chtab2_067_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 39 rows x 3 bytes, 315 segment bytes
*
chtab2_067_p0:
        fcb     39,3  ; height, width in bytes
        fcb     $81,$7F,$C1,$0F,$F0,$41,$00,$81,$FF,$C1,$03,$FC
        fcb     $41,$00,$81,$FF,$C1,$03,$FC,$41,$00,$81,$7F,$C1
        fcb     $03,$FC,$41,$00,$81,$AA,$C1,$03,$FC,$41,$00,$81
        fcb     $AA,$C1,$0F,$F0,$41,$00,$81,$AA,$C1,$3F,$80,$41
        fcb     $00,$C2,$F0,$0A,$03,$FC,$41,$00,$C1,$F0,$0F,$81
        fcb     $FF,$C1,$3F,$C0,$00,$C1,$F0,$0F,$81,$FE,$C1,$3F
        fcb     $80,$00,$C1,$F0,$0F,$81,$FE,$C1,$3F,$80,$00,$C1
        fcb     $F0,$0F,$81,$FE,$C1,$3F,$80,$00,$C1,$F0,$0F,$81
        fcb     $FE,$C1,$3F,$80,$00,$C1,$F0,$0F,$81,$FE,$C1,$0F
        fcb     $F0,$00,$C1,$F0,$0F,$81,$FE,$C1,$0F,$F0,$00,$C1
        fcb     $F0,$0F,$81,$FE,$C1,$03,$FC,$00,$C1,$FC,$03,$81
        fcb     $EA,$C1,$03,$FC,$00,$C1,$FC,$03,$81,$EF,$C1,$03
        fcb     $FC,$00,$C1,$FC,$03,$81,$EF,$C1,$03,$FC,$00,$C1
        fcb     $FC,$03,$81,$EF,$C1,$03,$FC,$00,$41,$81,$AF,$C1
        fcb     $03,$FC,$00,$C1,$F0,$0A,$81,$FF,$C1,$3F,$C0,$00
        fcb     $C1,$F0,$0A,$81,$FF,$C1,$3F,$C0,$00,$C1,$FC,$03
        fcb     $81,$FF,$C1,$0F,$F0,$00,$C1,$FC,$03,$81,$FF,$C1
        fcb     $0F,$F0,$00,$C1,$FC,$03,$81,$FF,$C1,$0F,$F0,$00
        fcb     $C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$00,$C1,$FC,$03
        fcb     $81,$FF,$C1,$3F,$C0,$00,$C1,$FC,$03,$81,$FF,$C1
        fcb     $0F,$F0,$00,$C1,$FC,$03,$81,$FF,$C1,$0F,$F0,$00
        fcb     $C1,$FC,$03,$81,$FF,$C1,$0F,$F0,$00,$41,$81,$FF
        fcb     $C1,$0F,$F0,$00,$41,$81,$FF,$C1,$0F,$F0,$00,$41
        fcb     $81,$FF,$C1,$3F,$C0,$00,$41,$C1,$C0,$3F,$41,$00
        fcb     $41,$C1,$C0,$3F,$41,$00,$41,$81,$FF,$41,$00,$C1
        fcb     $FC,$03,$81,$FF,$C1,$3F,$C0,$00,$82,$7F,$FF,$C1
        fcb     $3F,$C0,$00
