* chtab2_069_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 4 rows x 5 bytes, 43 segment bytes
*
chtab2_069_p0:
        fcb     4,5  ; height, width in bytes
        fcb     $C1,$FC,$00,$82,$F7,$FF,$C1,$3F,$00,$41,$00,$C1
        fcb     $FC,$00,$82,$FF,$FF,$C1,$0F,$F0,$41,$00,$C1,$F0
        fcb     $03,$82,$FF,$FF,$C1,$0F,$F0,$41,$00,$C2,$C0,$0F
        fcb     $03,$FC,$83,$7F,$FC,$3F,$00
