* chtab2_057_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 19 rows x 6 bytes, 200 segment bytes
*
chtab2_057_p0:
        fcb     19,6  ; height, width in bytes
        fcb     $C1,$FC,$00,$81,$FF,$C1,$0F,$C0,$43,$00,$C1,$C0
        fcb     $0F,$81,$FF,$C1,$03,$F0,$43,$00,$C1,$C0,$0F,$81
        fcb     $FF,$C1,$03,$F0,$43,$00,$C1,$FC,$00,$81,$FF,$C1
        fcb     $03,$F0,$43,$00,$C1,$F0,$01,$81,$7F,$C1,$03,$F0
        fcb     $43,$00,$C1,$F0,$01,$83,$FF,$FC,$57,$42,$00,$C1
        fcb     $F0,$01,$83,$FF,$FF,$57,$C1,$0F,$C0,$41,$00,$41
        fcb     $84,$15,$7F,$FF,$FC,$41,$00,$41,$84,$15,$7F,$FF
        fcb     $FF,$C1,$3F,$00,$00,$41,$84,$15,$7F,$FF,$FF,$C1
        fcb     $3F,$00,$00,$41,$84,$15,$7F,$FF,$FF,$C1,$3F,$00
        fcb     $00,$41,$84,$17,$FF,$FF,$FF,$C1,$3F,$00,$00,$41
        fcb     $84,$17,$FF,$FF,$FC,$41,$00,$41,$83,$FF,$FF,$17
        fcb     $C1,$03,$F0,$41,$00,$41,$83,$FF,$FF,$17,$C1,$0F
        fcb     $C0,$41,$00,$C1,$F0,$01,$81,$57,$C1,$03,$F0,$81
        fcb     $3F,$C1,$03,$F0,$41,$00,$C2,$F0,$01,$03,$50,$41
        fcb     $81,$3F,$C1,$03,$F0,$41,$00,$C3,$F0,$01,$3F,$00
        fcb     $FC,$00,$81,$FF,$C1,$0F,$C0,$41,$00,$81,$15,$C2
        fcb     $3F,$00,$F0,$03,$81,$FC,$42,$00
