* chtab2_019_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 40 rows x 4 bytes, 375 segment bytes
*
chtab2_019_p0:
        fcb     40,4  ; height, width in bytes
        fcb     $C1,$F0,$03,$81,$FF,$C1,$3F,$00,$41,$00,$C1,$F0
        fcb     $03,$81,$FF,$C1,$0F,$C0,$41,$00,$C1,$FC,$00,$81
        fcb     $FF,$C1,$03,$F0,$41,$00,$C1,$C0,$0A,$81,$FF,$C1
        fcb     $03,$F0,$41,$00,$C1,$C0,$0A,$81,$AF,$C1,$03,$F0
        fcb     $41,$00,$C1,$C0,$0A,$81,$AF,$C1,$0F,$C0,$41,$00
        fcb     $C1,$FC,$00,$81,$AF,$C1,$3F,$00,$41,$00,$C2,$FC
        fcb     $00,$03,$A8,$42,$00,$C1,$FC,$00,$81,$FF,$C1,$03
        fcb     $F0,$41,$00,$C1,$FC,$00,$82,$AF,$FC,$41,$00,$C1
        fcb     $FC,$00,$82,$AA,$FC,$41,$00,$C1,$F0,$03,$82,$EA
        fcb     $FC,$41,$00,$C1,$F0,$03,$82,$EA,$FC,$41,$00,$C1
        fcb     $F0,$03,$82,$FE,$FF,$C1,$3F,$00,$00,$C1,$F0,$03
        fcb     $82,$FE,$AF,$C1,$3F,$00,$00,$C1,$F0,$03,$82,$FE
        fcb     $AF,$C1,$3F,$00,$00,$C1,$F0,$03,$82,$FE,$AF,$C1
        fcb     $3F,$00,$00,$C1,$F0,$03,$82,$FF,$EF,$C1,$0F,$C0
        fcb     $00,$C1,$F0,$03,$82,$FF,$EF,$C1,$0F,$C0,$00,$C1
        fcb     $F0,$03,$82,$FF,$EF,$C1,$0F,$C0,$00,$C1,$F0,$03
        fcb     $82,$FF,$EF,$C1,$0F,$C0,$00,$C1,$FC,$00,$82,$FF
        fcb     $EF,$C1,$0F,$C0,$00,$C1,$FC,$00,$82,$FE,$AF,$C1
        fcb     $3F,$00,$00,$C1,$FC,$00,$82,$FE,$AF,$C1,$3F,$00
        fcb     $00,$C1,$FC,$00,$82,$FF,$FF,$C1,$3F,$00,$00,$C1
        fcb     $FC,$00,$82,$FF,$FF,$C1,$3F,$00,$00,$C1,$FC,$00
        fcb     $82,$FF,$FC,$41,$00,$C1,$FC,$00,$82,$FF,$FC,$41
        fcb     $00,$C1,$FC,$00,$81,$FF,$C1,$03,$F0,$41,$00,$C1
        fcb     $FC,$00,$81,$FF,$C1,$03,$F0,$41,$00,$C1,$FC,$00
        fcb     $82,$FF,$FC,$41,$00,$C1,$FC,$00,$82,$FF,$FC,$41
        fcb     $00,$C1,$FC,$00,$82,$FF,$FF,$C1,$3F,$00,$00,$41
        fcb     $82,$3F,$FC,$41,$00,$41,$C1,$C0,$0F,$81,$FF,$C1
        fcb     $3F,$00,$00,$41,$C1,$C0,$0F,$81,$FF,$C1,$0F,$C0
        fcb     $00,$41,$82,$3F,$FF,$C1,$0F,$C0,$00,$C1,$FC,$00
        fcb     $82,$FF,$FF,$C1,$0F,$C0,$00,$C1,$F0,$03,$82,$FF
        fcb     $FF,$C1,$3F,$00,$00,$C1,$F0,$03,$81,$FF,$C1,$3F
        fcb     $00,$41,$00
