* chtab2_060_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 24 rows x 7 bytes, 273 segment bytes
*
chtab2_060_p0:
        fcb     24,7  ; height, width in bytes
        fcb     $41,$81,$FF,$45,$00,$C1,$F0,$0F,$81,$FF,$C1,$3F
        fcb     $C0,$44,$00,$82,$7F,$FF,$C1,$0F,$F0,$44,$00,$84
        fcb     $7F,$FF,$FF,$FF,$C1,$03,$FC,$42,$00,$C1,$FC,$01
        fcb     $84,$7F,$FF,$FF,$FF,$C1,$0F,$F0,$41,$00,$C1,$FC
        fcb     $01,$84,$57,$FF,$FF,$FF,$C1,$03,$FC,$41,$00,$C1
        fcb     $FC,$01,$85,$7F,$FF,$FF,$FF,$55,$41,$00,$41,$C1
        fcb     $C0,$15,$84,$7F,$FF,$FF,$FF,$41,$00,$41,$C1,$FC
        fcb     $01,$84,$7F,$FF,$FF,$FF,$41,$00,$41,$C2,$FC,$01
        fcb     $0F,$50,$82,$FF,$FF,$C1,$03,$FC,$41,$00,$41,$C1
        fcb     $FC,$01,$41,$C1,$C0,$3F,$81,$FF,$C1,$0F,$F0,$41
        fcb     $00,$41,$C1,$FC,$01,$41,$82,$FF,$FF,$C1,$3F,$C0
        fcb     $41,$00,$41,$C1,$FC,$01,$41,$82,$FF,$FF,$42,$00
        fcb     $41,$C2,$FC,$01,$FC,$03,$81,$FF,$C1,$03,$FC,$42
        fcb     $00,$41,$C2,$FC,$01,$FC,$03,$82,$FF,$FF,$42,$00
        fcb     $41,$C2,$FC,$01,$FC,$03,$82,$FF,$FF,$C1,$3F,$C0
        fcb     $41,$00,$41,$C2,$FC,$01,$FC,$03,$81,$FF,$C2,$03
        fcb     $FC,$CF,$10,$41,$00,$41,$C1,$FC,$01,$41,$82,$FF
        fcb     $FF,$C1,$3F,$C0,$41,$00,$41,$C1,$FC,$01,$41,$C1
        fcb     $C0,$3F,$81,$FF,$C1,$0F,$F0,$41,$00,$41,$C1,$FC
        fcb     $01,$41,$C2,$F0,$0F,$3C,$C3,$81,$FF,$41,$00,$41
        fcb     $C1,$FC,$01,$43,$81,$FF,$C1,$3F,$C0,$00,$41,$C1
        fcb     $FC,$01,$43,$81,$FF,$41,$00,$45,$C1,$03,$FC,$41
        fcb     $00,$44,$C2,$FC,$03,$0F,$F0,$41,$00
