* cel_table.s — the VM's cel-id table (P3.24 piece C).
* GENERATED by harness/tools/gen_cel_table.py — do not hand-edit.
*
* cel number -> (image index, Fdx, Fdy, Fcheck), resolved from ALTSET2 the way
* getfindex/getaltframe2 do [CTRLSUBS.S:927,941].
*
* ★ +3 IS RAW Fcheck NOW, NOT A PRE-COMPUTED PARITY (P3.65, piece G).
*
* It used to be parity, resolved here at GENERATE time against one CharFace —
* and this file said so: "a character that TURNS invalidates this column". That
* came due. Palert ends `aboutface,chx,9` and Vexit ends `aboutface,chx,16`, so
* both characters turn inside the scene and spend part of it at the OTHER parity.
* A column baked for one facing cannot describe them.
*
* The rule is one instruction, so the engine now applies it: parity is 1 when
* bit7(Fcheck) == bit7(CharFace), which vm_resolve computes as
* `eora CH_FACE` + `bmi` [CTRLSUBS.S:805-838 SETUPCHAR]. The table carries the
* FACT (Fcheck) and the engine carries the RULE, which is why this generator no
* longer takes a facing to bake in.
*
*   +0  image index into IMG.CHTAB6.A (1-based)
*   +1  Fdx   (signed)
*   +2  Fdy   (signed)
*   +3  Fcheck — bit7 vs bit7(CharFace) gives parity AT RUN TIME
*   +4  Apple sprite WIDTH in bytes (7 px each) — the mirror anchor
*
* ★ +4 IS THE MIRROR ANCHOR (P3.72g), and it is a POSITION fact, not a size.
*
* The oracle lays a mirrored image down on the OTHER EDGE:
*
*     MLayGen:  LDA XCO / SEC / SBC WIDTH / STA XCO   [HIRES.S:1202-1208]
*
* so `aboutface,chx,N` in a sequence is a REGISTRATION correction, not a move --
* the chx cancels the anchor flip and the character stays where she is. The port
* baked the mirror but drew it at the same left edge, so the chx became visible
* motion: Jay, watching both live, 'the port has her moving forward during the
* turn. she doesn't move in the oracle.' Measured on the oracle across her turn,
* only 21 px of columns differ, where an 18 px shift would have spanned ~58.
*
* Cel 11 is 3 Apple bytes = 21 px against chx,9 = 18 px, so the net is -3 px:
* sub-byte, i.e. no movement. The engine cannot derive that from anything it
* already holds, so the width comes down here with the rest of the cel's facts.
CEL_LO          equ     1
CEL_HI          equ     85
CEL_ENTSZ       equ     5

cel_table
                fcb     10,0,0,$00,3 ; cel 1   pslump-1
                fcb     26,0,0,$80,3 ; cel 2   pturn-4
                fcb     27,0,0,$80,3 ; cel 3   pturn-5
                fcb     28,0,0,$80,3 ; cel 4   pturn-6
                fcb     29,255,0,$00,3 ; cel 5   pturn-7
                fcb     30,2,0,$80,4 ; cel 6   pturn-8
                fcb     31,2,0,$00,4 ; cel 7   pturn-9
                fcb     32,0,0,$80,3 ; cel 8   pturn-10
                fcb     33,1,0,$80,3 ; cel 9   pturn-11
                fcb     0,0,0,0,0       ; cel 10 — unused here
                fcb     25,0,0,$80,3 ; cel 11  pturn-15 (stand)
                fcb     0,0,0,0,0       ; cel 12 — unused here
                fcb     0,0,0,0,0       ; cel 13 — unused here
                fcb     0,0,0,0,0       ; cel 14 — unused here
                fcb     0,0,0,0,0       ; cel 15 — unused here
                fcb     0,0,0,0,0       ; cel 16 — unused here
                fcb     0,0,0,0,0       ; cel 17 — unused here
                fcb     11,0,0,$00,3 ; cel 18  pslump-1
                fcb     0,0,0,0,0       ; cel 19 — unused here
                fcb     0,0,0,0,0       ; cel 20 — unused here
                fcb     0,0,0,0,0       ; cel 21 — unused here
                fcb     0,0,0,0,0       ; cel 22 — unused here
                fcb     0,0,0,0,0       ; cel 23 — unused here
                fcb     0,0,0,0,0       ; cel 24 — unused here
                fcb     0,0,0,0,0       ; cel 25 — unused here
                fcb     0,0,0,0,0       ; cel 26 — unused here
                fcb     0,0,0,0,0       ; cel 27 — unused here
                fcb     0,0,0,0,0       ; cel 28 — unused here
                fcb     0,0,0,0,0       ; cel 29 — unused here
                fcb     0,0,0,0,0       ; cel 30 — unused here
                fcb     0,0,0,0,0       ; cel 31 — unused here
                fcb     0,0,0,0,0       ; cel 32 — unused here
                fcb     0,0,0,0,0       ; cel 33 — unused here
                fcb     0,0,0,0,0       ; cel 34 — unused here
                fcb     0,0,0,0,0       ; cel 35 — unused here
                fcb     0,0,0,0,0       ; cel 36 — unused here
                fcb     0,0,0,0,0       ; cel 37 — unused here
                fcb     0,0,0,0,0       ; cel 38 — unused here
                fcb     0,0,0,0,0       ; cel 39 — unused here
                fcb     0,0,0,0,0       ; cel 40 — unused here
                fcb     0,0,0,0,0       ; cel 41 — unused here
                fcb     0,0,0,0,0       ; cel 42 — unused here
                fcb     0,0,0,0,0       ; cel 43 — unused here
                fcb     0,0,0,0,0       ; cel 44 — unused here
                fcb     0,0,0,0,0       ; cel 45 — unused here
                fcb     0,0,0,0,0       ; cel 46 — unused here
                fcb     0,0,0,0,0       ; cel 47 — unused here
                fcb     74,0,0,$80,3 ; cel 48  vwalk-8
                fcb     75,0,0,$80,4 ; cel 49  vwalk-9
                fcb     76,0,0,$80,5 ; cel 50  vwalk-10
                fcb     77,0,0,$00,5 ; cel 51  vwalk-11
                fcb     78,0,0,$00,4 ; cel 52  vwalk-12
                fcb     79,0,0,$80,4 ; cel 53  vwalk-13
                fcb     80,0,0,$80,3 ; cel 54  vstand-3
                fcb     81,0,0,$80,3 ; cel 55  vstand-2
                fcb     82,0,0,$80,3 ; cel 56  vstand-1
                fcb     83,0,0,$80,3 ; cel 57  vturn-5
                fcb     84,0,0,$80,3 ; cel 58  vturn-6
                fcb     85,0,0,$80,3 ; cel 59  vturn-7
                fcb     86,0,0,$80,4 ; cel 60  vturn-8
                fcb     87,0,0,$00,4 ; cel 61  vturn-9
                fcb     88,0,0,$80,5 ; cel 62  vturn-10
                fcb     89,0,0,$00,5 ; cel 63  vturn-11
                fcb     90,0,0,$00,5 ; cel 64  vturn-12
                fcb     91,0,0,$80,5 ; cel 65  vturn-13
                fcb     92,0,0,$00,5 ; cel 66  vturn-14
                fcb     93,3,0,$00,3 ; cel 67  vcast-2
                fcb     94,3,0,$00,4 ; cel 68  vcast-3
                fcb     95,3,0,$00,3 ; cel 69  vcast-4
                fcb     96,2,0,$00,3 ; cel 70  vcast-5
                fcb     97,3,0,$80,3 ; cel 71  vcast-6
                fcb     98,5,0,$00,4 ; cel 72  vcast-7
                fcb     99,5,0,$00,5 ; cel 73  vcast-8
                fcb     100,1,0,$80,3 ; cel 74  vcast-9
                fcb     101,2,0,$80,3 ; cel 75  vcast-10
                fcb     102,2,0,$80,3 ; cel 76  vcast-11 (held)
                fcb     103,1,0,$80,2 ; cel 77  vcast-13
                fcb     1,1,0,$00,1 ; cel 78  vcast-14
                fcb     2,2,0,$00,1 ; cel 79  vcast-15
                fcb     3,3,0,$00,1 ; cel 80  vcast-16
                fcb     4,3,0,$00,1 ; cel 81  vcast-17
                fcb     5,0,0,$80,1 ; cel 82  vcast-18
                fcb     6,2,0,$80,1 ; cel 83  vcast-10a
                fcb     7,2,0,$80,1 ; cel 84  vcast-10b
                fcb     8,1,0,$00,1 ; cel 85  vcast-1
