# harness/smoke/cfgdir.sh — ONE HOME for the MAME config directory.
#
# ★★ MAME REWRITES ITS CFG DIRECTORY ON EXIT, AND THE TRACKED FILE IS A TEMPLATE.
# `dist/mame-cfg/rgb/coco3.cfg` sets Monitor Type = RGB, which CLAUDE.md §4 makes the
# project's monitor gate. Its own header has said since it was written that "MAME REWRITES
# this file on exit (adds mixer/video/image blocks) — harmless, but it means the file is a
# template, not a constant."
#
# ★ IT IS NOT HARMLESS, AND P5.8 §7.7 IS WHAT FOUND THAT. The rewrite does not append: it
# REGENERATES the file and strips every comment, replacing the header above with
#
#     <!-- This file is autogenerated; comments and unknown tags will be stripped -->
#
# so the documentation of why the file exists is destroyed by the runs that depend on it —
# one run at a time, silently, in a tracked file. It also writes an <image_directories>
# block carrying an ABSOLUTE PATH from whichever machine ran last
# (`C:\Projects\POP3_port\build\` was sitting in the tree at P5.11's receipt).
#
# The gate itself was never affected — `<port tag=":screen_config" ... value="1" />` survives
# the rewrite, so no gate has ever run in the wrong monitor mode. What erodes is the record.
#
# ★★ THE FIX IS THE ONE THE DISK IMAGE ALREADY GETS. Every runner copies build/probe.dmk to
# a scratch name before mounting it, because "MAME opens a floppy read-write and saves back"
# (idiom 24). The cfg directory is the same hazard and had the opposite treatment. This
# copies the template to a scratch directory and points -cfg_directory THERE, so MAME
# rewrites the scratch and the tracked template is never opened for writing.
#
#   MAME_CFG_SRC   the tracked template directory   (default dist/mame-cfg/rgb)
#   CFGOPT         what the caller passes to MAME   (set by this file)
#
# Sourced the same way ramsize.sh is, and for the same reason: a rule that lives in twenty
# runners is twenty homes for one fact. The mechanical check is the same one ramsize.sh
# documents — grep for the file that must be sourced, not for the policy:
#
#     grep -rl 'cfg_directory' harness/ | while read f; do
#         grep -q cfgdir.sh "$f" || echo "$f"
#     done

MAME_CFG_SRC="${MAME_CFG_SRC:-dist/mame-cfg/rgb}"
MAME_CFG_DIR="${MAME_CFG_DIR:-build/tmp/mame-cfg}"

mkdir -p "$MAME_CFG_DIR" 2>/dev/null
# Copy every time: the scratch may carry a previous run's rewrite, and the template is the
# only thing that is authoritative about the monitor mode.
cp -f "$MAME_CFG_SRC"/*.cfg "$MAME_CFG_DIR"/ 2>/dev/null

CFGOPT="-cfg_directory $MAME_CFG_DIR"
