* cel_plan.s — the per-beat block schedule.
* GENERATED by harness/tools/bake_scene.py — do not hand-edit.
*
* Ticked once per animation step by vm_beat_tick, in lockstep with the two
* character scripts because all three are derived from the same PLAN walk.
*
* SIG 0 MEANS 'NO ROTATING PAGE NEEDED', and it is a real state rather than a
* hole in the check: the song holds draw only pinned standing cels, so their
* block is free — which is exactly why a track read can land in it. A guard
* that demanded a page signature through a hold would refuse to draw for the
* whole six seconds. cel_pack ASSERTS that a beat marked this way really does
* draw only resident cels, so the marking cannot drift from the content.

* ★★ NO COLUMN PADDING INSIDE AN OPERAND, EVER. `fcb %-3d,$%02X` renders beat 0
* as `fcb 7  ,$0D` and lwasm TERMINATES THE OPERAND AT THE WHITESPACE: one byte
* emitted, not two, with no error and no warning. Rows then have two different
* lengths depending on whether the play count happened to be three digits, the
* five-byte stride walks into the middle of its neighbours, and what comes out is
* a schedule that maps block $00 and asks for page 109. Alignment goes in the
* COMMENT, which is what a comment is for.
cel_plan
                fcb     7,$0D
                fdb     $0000
                fcb     0               ; beat 0  Pstand       plays 7     pinned-only
                fcb     109,$0D
                fdb     $0000
                fcb     0               ; beat 1  s_Princess   plays 109   pinned-only
                fcb     9,$0D
                fdb     $A53C
                fcb     0               ; beat 2  Palert       plays 9   
                fcb     5,$0D
                fdb     $0000
                fcb     0               ; beat 3  (hold)       plays 5     pinned-only
                fcb     7,$0D
                fdb     $A53C
                fcb     0               ; beat 4  Vwalk        plays 7   
                fcb     4,$0D
                fdb     $A53C
                fcb     0               ; beat 5  Vstop        plays 4   
                fcb     51,$0D
                fdb     $0000
                fcb     0               ; beat 6  s_Vizier     plays 51    pinned-only
                fcb     4,$0D
                fdb     $0000
                fcb     0               ; beat 7  (hold)       plays 4     pinned-only
                fcb     29,$0D
                fdb     $A53C
                fcb     0               ; beat 8  Vwalk        plays 29  
                fcb     4,$0D
                fdb     $A53C
                fcb     0               ; beat 9  Vstop        plays 4   
                fcb     56,$0D
                fdb     $0000
                fcb     4               ; beat 10 s_Buildup    plays 56    pinned-only  READ page 3
                fcb     1,$0E
                fdb     $A64D
                fcb     0               ; beat 11 Vraise       plays 1   
                fcb     13,$0E
                fdb     $A64D
                fcb     0               ; beat 12 Pback        plays 13  
                fcb     5,$0E
                fdb     $A64D
                fcb     0               ; beat 13 (hold)       plays 5   
                fcb     17,$0F
                fdb     $A75E
                fcb     0               ; beat 14 Vexit        plays 17  
                fcb     12,$0D
                fdb     $A86F
                fcb     0               ; beat 15 (hold)       plays 12  
                fcb     28,$0D
                fdb     $A86F
                fcb     0               ; beat 16 Pslump       plays 28  
                fcb     0,$0D
                fdb     $0000
                fcb     0               ; beat 17 Vstand       plays 0     pinned-only
                fcb     0,0
                fdb     0
                fcb     0               ; terminator
cel_plan_end
* cel_plan_end exists so the stride can be CHECKED rather than trusted:
* bundle_offsets_check.py compares (cel_plan_end - cel_plan) against
* 5 x (beats + 1) out of the link map, and fails the build on any other
* answer. The bug above assembled cleanly and ran; nothing but a byte count
* could have caught it.
