* cel_pg2.s — one rotating page of the split image.
* GENERATED by harness/tools/bake_scene.py — do not hand-edit.
*
* Linked at $E000 (link/pop_cels_pg.link) — the SAME address as every
* other page, because only one of them is mapped at a time. That is what makes
* them separate link units rather than sections of one image.
*
* ★ THE FIRST TWO BYTES ARE THIS PAGE'S OWN SIGNATURE, AND THAT IS THE POINT.
* P3.77 put one magic at $C000 and its own uncertainty flag said what splitting
* would do to it: a single magic proves the PINNED page is mapped and says
* nothing about the rotating one — which is the half that changes, and so the
* half that can be wrong. Every page therefore says WHICH page it is, and the
* beat schedule carries the value this beat's pointers need. A shared magic, or
* a plausibility test, would pass on any of the five.
*
*   beats 12..12   block $0F   7,678 B of 7,680

                section prog
                export  cel_page2
cel_page2
                fdb     $A75E           ; the signature for THIS page

                include "content/cutscene/chars/p12_p1.s"
                include "content/cutscene/chars/p13_p2.s"
                include "content/cutscene/chars/p14_p1.s"
                include "content/cutscene/chars/p15_p3.s"
                include "content/cutscene/chars/p16_p1.s"
                include "content/cutscene/chars/v67_p0.s"
                include "content/cutscene/chars/v68_p0.s"
                include "content/cutscene/chars/v69_p0.s"
                include "content/cutscene/chars/v70_p2.s"
                include "content/cutscene/chars/v71_p1.s"
                include "content/cutscene/chars/v72_p0.s"
                include "content/cutscene/chars/v74_p1.s"
