* cel_pages.s — where each page of the split cel image lives on disk.
* GENERATED by harness/tools/bake_scene.py — do not hand-edit.
*
* Read by cutscene_room.s: the startup loader walks the STARTUP rows, and a
* mid-scene read indexes this table by the page number the beat schedule names.
* build.bat places the very same tracks from cel_pack.json, so the disk and this
* table cannot disagree without the build being re-run.
*
* ★ TWO ROWS' WORTH OF FACT PER PAGE, IN TWO BYTES: its first track, and the
* GIME block it belongs in. Everything else is a constant, because every unit is
* the same shape — two whole tracks, read in two calls, the second SKEWED so it
* ends exactly at the top of the window. cel_pack's read-geometry note has the
* whole argument; the short of it is that a plain two-track read into $E000
* overruns 1,536 bytes into the constant page and the I/O registers, and takes
* the GIME with it.
*
*   fcb first_track, block

CEL_N_PAGES     equ     4
CEL_N_READS     equ     1
CEL_SECS        equ     18              ; one track, and a read is always one
CEL_RES_BLOCK   equ     $0C
CEL_RES_TRK     equ     11
CEL_RES_LO      equ     $C000           ; track A lands here
CEL_RES_HI      equ     $CE00           ; track B, ending at $E000
CEL_PAGE_LO     equ     $E000
CEL_PAGE_HI     equ     $EC00           ; ending at $FE00 — the last byte the
*                                       ;   window owns before MC3 and I/O

cel_page_tab
                fcb     13,$0D             ; page 0, 7,290 B of 7,680
                fcb     15,$0E             ; page 1, 6,449 B of 7,680
                fcb     20,$0F             ; page 2, 7,203 B of 7,680
                fcb     22,$0D             ; page 3, 3,265 B of 7,680
cel_page_tab_end

* The pages that must be in RAM before the scene starts: one per block, the
* first user of each. The rest arrive in the song holds.
CEL_N_STARTUP   equ     3
cel_startup_tab
                fcb     0,1,2
