* cel_image.s — the scene's bake, and the lookup over it.
* GENERATED by harness/tools/bake_scene.py — do not hand-edit.
*
* LINKED AT $C000 AND READ OFF DISK INTO A GIME BANK (P3.69/P3.71). It is NOT
* part of the flame bundle any more: the bundle had reached 11,921 B against a
* 14,848 B window with five beats still to add, and the cels are the half of it
* that never executes, so they are the half that can live behind a window
* register. cutscene_room.s maps blocks at $FFA6/$FFA7 and re-applies that map
* after every swap (HAL_gfx_swap writes all four window registers, so the
* mapping cannot survive one — P3.68).
*
* THE FIRST TWO BYTES ARE THE BOUNDS, and they are load-bearing: char_draw.s
* reads WALK_LO/WALK_N from $C000/$C001 at run time because it links into a
* different object and cannot see these symbols.
*
* EIGHT SLOTS PER CEL: two facings x four phases (P3.65, piece G). The facing
* half is chosen by co_variant from CH_FACE; -1 is left and NORMAL, 0 is right
* and MIRRORED [FRAMEADV.S:1970]. Cels drawn at one facing leave the other half
* zero, which co_variant treats as 'fall back to the record's own pointer'.
*
* Which phases and facings each cel needs is DERIVED, not written: beat_recost
* walks the port's plan the way ANIMCHAR does. Nothing here may disagree with it.
*
*   cel 2   normal ph1
*   cel 3   normal ph1
*   cel 4   normal ph1
*   cel 5   normal ph2
*   cel 6   normal ph1
*   cel 7   normal ph0
*   cel 8   normal ph1
*   cel 9   normal ph3
*   cel 11  normal ph1, mirrored ph1
*   cel 48  normal ph1
*   cel 49  normal ph1
*   cel 50  normal ph1
*   cel 51  normal ph2
*   cel 52  normal ph0
*   cel 53  normal ph3
*   cel 54  normal ph3
*   cel 55  normal ph3
*   cel 56  normal ph3

                section prog
* EXPORTED because link/pop_cels.link names it as the entry. lwlink resolves
* `entry` against exported symbols only; a plain label gives
* "External symbol cel_image not found" at link time. The image is never
* executed -- the entry exists so the .bin carries a load address decb_to_raw
* can check against build.bat's --base.
                export  cel_image
cel_image
* --- THE SIGNATURE, and it must stay FIRST (P3.77) -----------------
*
* $C000/$C001 is the one address the engine trusts without being able to check
* it: char_draw reads the bounds and the cel table from there, and if the wrong
* GIME block is mapped underneath, every pointer stays valid-LOOKING and the VM
* draws whatever bytes are present. No crash -- garbage that reads as a
* rendering bug. That is exactly how the capture-05 corruption presented and it
* took three dispatches to attribute.
*
* So the image says who it is. char_draw checks these two bytes once per frame
* and refuses to draw from a window that is not the cel bank. The duplication is
* two bytes and it is the entire point of a magic number.
                fcb     $C3,$5A         ; CEL_MAGIC, read from $C000/$C001
* --- the self-describing bounds --------------------------------
                fcb     2              ; WALK_LO, read from $C002
                fcb     55              ; WALK_N,  read from $C003
* --- walk_tab at $C004: eight slots per cel, two facings x four phases ---
cel_walk_tab
                fdb     0,p2_p1,0,0,0,0,0,0   ; cel 2
                fdb     0,p3_p1,0,0,0,0,0,0   ; cel 3
                fdb     0,p4_p1,0,0,0,0,0,0   ; cel 4
                fdb     0,0,p5_p2,0,0,0,0,0   ; cel 5
                fdb     0,p6_p1,0,0,0,0,0,0   ; cel 6
                fdb     p7_p0,0,0,0,0,0,0,0   ; cel 7
                fdb     0,p8_p1,0,0,0,0,0,0   ; cel 8
                fdb     0,0,0,p9_p3,0,0,0,0   ; cel 9
                fdb     0,0,0,0,0,0,0,0   ; cel 10
                fdb     0,p11_p1,0,0,0,p11_m_p1,0,0   ; cel 11
                fdb     0,0,0,0,0,0,0,0   ; cel 12
                fdb     0,0,0,0,0,0,0,0   ; cel 13
                fdb     0,0,0,0,0,0,0,0   ; cel 14
                fdb     0,0,0,0,0,0,0,0   ; cel 15
                fdb     0,0,0,0,0,0,0,0   ; cel 16
                fdb     0,0,0,0,0,0,0,0   ; cel 17
                fdb     0,0,0,0,0,0,0,0   ; cel 18
                fdb     0,0,0,0,0,0,0,0   ; cel 19
                fdb     0,0,0,0,0,0,0,0   ; cel 20
                fdb     0,0,0,0,0,0,0,0   ; cel 21
                fdb     0,0,0,0,0,0,0,0   ; cel 22
                fdb     0,0,0,0,0,0,0,0   ; cel 23
                fdb     0,0,0,0,0,0,0,0   ; cel 24
                fdb     0,0,0,0,0,0,0,0   ; cel 25
                fdb     0,0,0,0,0,0,0,0   ; cel 26
                fdb     0,0,0,0,0,0,0,0   ; cel 27
                fdb     0,0,0,0,0,0,0,0   ; cel 28
                fdb     0,0,0,0,0,0,0,0   ; cel 29
                fdb     0,0,0,0,0,0,0,0   ; cel 30
                fdb     0,0,0,0,0,0,0,0   ; cel 31
                fdb     0,0,0,0,0,0,0,0   ; cel 32
                fdb     0,0,0,0,0,0,0,0   ; cel 33
                fdb     0,0,0,0,0,0,0,0   ; cel 34
                fdb     0,0,0,0,0,0,0,0   ; cel 35
                fdb     0,0,0,0,0,0,0,0   ; cel 36
                fdb     0,0,0,0,0,0,0,0   ; cel 37
                fdb     0,0,0,0,0,0,0,0   ; cel 38
                fdb     0,0,0,0,0,0,0,0   ; cel 39
                fdb     0,0,0,0,0,0,0,0   ; cel 40
                fdb     0,0,0,0,0,0,0,0   ; cel 41
                fdb     0,0,0,0,0,0,0,0   ; cel 42
                fdb     0,0,0,0,0,0,0,0   ; cel 43
                fdb     0,0,0,0,0,0,0,0   ; cel 44
                fdb     0,0,0,0,0,0,0,0   ; cel 45
                fdb     0,0,0,0,0,0,0,0   ; cel 46
                fdb     0,0,0,0,0,0,0,0   ; cel 47
                fdb     0,v48_p1,0,0,0,0,0,0   ; cel 48
                fdb     0,v49_p1,0,0,0,0,0,0   ; cel 49
                fdb     0,v50_p1,0,0,0,0,0,0   ; cel 50
                fdb     0,0,v51_p2,0,0,0,0,0   ; cel 51
                fdb     v52_p0,0,0,0,0,0,0,0   ; cel 52
                fdb     0,0,0,v53_p3,0,0,0,0   ; cel 53
                fdb     0,0,0,v54_p3,0,0,0,0   ; cel 54
                fdb     0,0,0,v55_p3,0,0,0,0   ; cel 55
                fdb     0,0,0,v56_p3,0,0,0,0   ; cel 56

                include "content/cutscene/chars/p2_p1.s"
                include "content/cutscene/chars/p3_p1.s"
                include "content/cutscene/chars/p4_p1.s"
                include "content/cutscene/chars/p5_p2.s"
                include "content/cutscene/chars/p6_p1.s"
                include "content/cutscene/chars/p7_p0.s"
                include "content/cutscene/chars/p8_p1.s"
                include "content/cutscene/chars/p9_p3.s"
                include "content/cutscene/chars/p11_p1.s"
                include "content/cutscene/chars/p11_m_p1.s"
                include "content/cutscene/chars/v48_p1.s"
                include "content/cutscene/chars/v49_p1.s"
                include "content/cutscene/chars/v50_p1.s"
                include "content/cutscene/chars/v51_p2.s"
                include "content/cutscene/chars/v52_p0.s"
                include "content/cutscene/chars/v53_p3.s"
                include "content/cutscene/chars/v54_p3.s"
                include "content/cutscene/chars/v55_p3.s"
                include "content/cutscene/chars/v56_p3.s"

