* v60_p1 — runtime-blit segment data, phase 1
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 48 rows x 8 bytes, 581 segment bytes
*
v60_p1:
        fcb     48,8  ; height, width in bytes
        fcb     $43,$C1,$F0,$0F,$81,$FF,$C1,$3F,$C0,$42,$00,$43
        fcb     $83,$FF,$FF,$FF,$42,$00,$42,$C1,$FC,$03,$83,$FF
        fcb     $FF,$FF,$C1,$3F,$C0,$41,$00,$42,$C1,$FC,$03,$83
        fcb     $FF,$FF,$FF,$C1,$3F,$C0,$41,$00,$42,$C1,$FC,$03
        fcb     $83,$FF,$FF,$FF,$C1,$3F,$C0,$41,$00,$43,$C1,$C0
        fcb     $3F,$82,$FF,$FF,$42,$00,$43,$C1,$FC,$03,$81,$FF
        fcb     $C1,$3F,$C0,$42,$00,$43,$C1,$F0,$0F,$81,$FF,$C1
        fcb     $03,$FC,$42,$00,$43,$83,$FF,$FF,$FF,$C1,$3F,$C0
        fcb     $41,$00,$42,$C1,$FC,$03,$83,$FF,$FF,$FF,$C1,$3F
        fcb     $C0,$41,$00,$42,$C1,$FC,$03,$83,$FF,$FF,$FF,$C1
        fcb     $3F,$C0,$41,$00,$42,$C1,$F0,$0F,$83,$FF,$FF,$FF
        fcb     $C1,$0F,$F0,$41,$00,$42,$C1,$F0,$0F,$83,$FF,$FF
        fcb     $FF,$C1,$0F,$F0,$41,$00,$42,$C1,$C0,$3F,$83,$FF
        fcb     $FF,$FF,$C1,$0F,$F0,$41,$00,$42,$C1,$C0,$3F,$83
        fcb     $FF,$FF,$FF,$C1,$0F,$F0,$41,$00,$42,$C1,$C0,$3F
        fcb     $83,$FF,$FF,$FF,$C1,$0F,$F0,$41,$00,$42,$84,$FF
        fcb     $FF,$FF,$FF,$C1,$0F,$F0,$41,$00,$42,$84,$FF,$FF
        fcb     $FF,$FF,$C1,$0F,$F0,$41,$00,$42,$84,$FF,$FF,$FF
        fcb     $FF,$C1,$0F,$F0,$41,$00,$41,$C1,$FC,$03,$84,$FF
        fcb     $FF,$FF,$FF,$C1,$0F,$F0,$41,$00,$41,$C1,$FC,$03
        fcb     $84,$FF,$FF,$FF,$FF,$C1,$0F,$F0,$41,$00,$41,$C1
        fcb     $FC,$03,$84,$FF,$FF,$FF,$FF,$C1,$0F,$F0,$41,$00
        fcb     $41,$C1,$F0,$0F,$84,$FF,$FF,$FF,$FF,$C1,$3F,$C0
        fcb     $41,$00,$41,$C1,$F0,$0F,$84,$FF,$FF,$FF,$FF,$C1
        fcb     $3F,$C0,$41,$00,$41,$C1,$C0,$3F,$84,$FF,$FF,$FF
        fcb     $FF,$C1,$3F,$C0,$41,$00,$41,$C1,$C0,$3F,$84,$FF
        fcb     $FF,$FF,$FF,$C1,$3F,$C0,$41,$00,$41,$C1,$C0,$3F
        fcb     $84,$FF,$FF,$FF,$FF,$C1,$3F,$C0,$41,$00,$41,$85
        fcb     $FF,$FF,$FF,$FF,$FF,$42,$00,$41,$C1,$C0,$3F,$84
        fcb     $FF,$FF,$FF,$FF,$42,$00,$41,$C1,$C0,$3F,$84,$FF
        fcb     $FF,$FF,$FF,$42,$00,$41,$C1,$C0,$3F,$84,$FF,$FF
        fcb     $FF,$FF,$42,$00,$41,$C1,$C0,$3F,$84,$FF,$FF,$FF
        fcb     $FF,$42,$00,$41,$C1,$C0,$3F,$84,$FF,$FF,$FF,$FF
        fcb     $42,$00,$41,$C1,$C0,$3F,$84,$FF,$FF,$FF,$FF,$42
        fcb     $00,$41,$C1,$F0,$0F,$83,$FF,$FF,$FF,$C1,$03,$FC
        fcb     $42,$00,$41,$C1,$F0,$0F,$83,$FF,$FF,$FF,$C1,$03
        fcb     $FC,$42,$00,$41,$C1,$F0,$0F,$83,$FF,$FF,$FF,$C1
        fcb     $03,$FC,$42,$00,$41,$C1,$F0,$0F,$83,$FF,$FF,$FF
        fcb     $C1,$03,$FC,$42,$00,$41,$C1,$FC,$03,$83,$FF,$FF
        fcb     $FF,$C1,$03,$FC,$42,$00,$41,$C1,$FC,$03,$83,$FF
        fcb     $FF,$FF,$C1,$03,$FC,$42,$00,$41,$C1,$FC,$03,$83
        fcb     $FF,$FF,$FF,$C1,$03,$FC,$42,$00,$41,$C1,$FC,$03
        fcb     $83,$FF,$FF,$FF,$C1,$03,$FC,$42,$00,$42,$83,$FF
        fcb     $FF,$FF,$C1,$03,$FC,$42,$00,$42,$C1,$F0,$0A,$82
        fcb     $AF,$FF,$C1,$03,$FC,$42,$00,$42,$C4,$F0,$0A,$03
        fcb     $A8,$FC,$03,$03,$FC,$42,$00,$42,$C2,$F0,$0F,$03
        fcb     $FC,$41,$81,$FF,$42,$00,$42,$81,$FF,$C1,$03,$FC
        fcb     $41,$C1,$03,$FC,$42,$00,$41,$C1,$F0,$0F,$81,$FF
        fcb     $C1,$03,$FC,$44,$00
