* v61_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 47 rows x 7 bytes, 515 segment bytes
*
v61_p0:
        fcb     47,7  ; height, width in bytes
        fcb     $44,$C1,$F0,$0F,$81,$FF,$41,$00,$44,$82,$FF,$FF
        fcb     $C1,$0F,$F0,$00,$43,$C1,$FC,$03,$82,$FF,$FF,$C1
        fcb     $03,$FC,$00,$43,$C1,$FC,$03,$82,$FF,$FF,$C1,$03
        fcb     $FC,$00,$43,$C1,$FC,$03,$82,$FF,$FF,$C1,$03,$FC
        fcb     $00,$44,$82,$FF,$FF,$C1,$03,$FC,$00,$44,$C1,$F0
        fcb     $0F,$81,$FF,$C1,$3F,$C0,$00,$43,$C1,$F0,$0F,$81
        fcb     $FF,$C1,$0F,$F0,$41,$00,$43,$C1,$C0,$3F,$81,$FF
        fcb     $C1,$03,$FC,$41,$00,$43,$C1,$C0,$3F,$82,$FF,$FF
        fcb     $C1,$0F,$F0,$00,$43,$83,$FF,$FF,$FF,$C1,$03,$FC
        fcb     $00,$42,$C1,$FC,$03,$83,$FF,$FF,$FF,$C1,$03,$FC
        fcb     $00,$42,$C1,$FC,$03,$83,$FF,$FF,$FF,$C1,$03,$FC
        fcb     $00,$42,$C1,$F0,$0F,$83,$FF,$FF,$FF,$C1,$03,$FC
        fcb     $00,$42,$C1,$F0,$0F,$83,$FF,$FF,$FF,$C1,$03,$FC
        fcb     $00,$42,$C1,$C0,$3F,$83,$FF,$FF,$FF,$C1,$03,$FC
        fcb     $00,$42,$84,$FF,$FF,$FF,$FF,$C1,$03,$FC,$00,$42
        fcb     $84,$FF,$FF,$FF,$FF,$C1,$03,$FC,$00,$41,$C1,$FC
        fcb     $03,$84,$FF,$FF,$FF,$FF,$C1,$03,$FC,$00,$41,$C1
        fcb     $FC,$03,$85,$FF,$FF,$FF,$FF,$FF,$00,$41,$C1,$F0
        fcb     $0F,$85,$FF,$FF,$FF,$FF,$FF,$00,$41,$C1,$F0,$0F
        fcb     $85,$FF,$FF,$FF,$FF,$FF,$00,$41,$C1,$C0,$3F,$85
        fcb     $FF,$FF,$FF,$FF,$FF,$00,$41,$C1,$C0,$3F,$85,$FF
        fcb     $FF,$FF,$FF,$FF,$00,$41,$C1,$C0,$3F,$85,$FF,$FF
        fcb     $FF,$FF,$FF,$00,$41,$86,$FF,$FF,$FF,$FF,$FF,$FF
        fcb     $00,$C1,$FC,$03,$86,$FF,$FF,$FF,$FF,$FF,$FF,$00
        fcb     $C1,$FC,$03,$85,$FF,$FF,$FF,$FF,$FF,$C1,$03,$FC
        fcb     $00,$C1,$F0,$0F,$85,$FF,$FF,$FF,$FF,$FF,$C1,$0F
        fcb     $F0,$00,$C1,$F0,$0F,$85,$FF,$FF,$FF,$FF,$FF,$C1
        fcb     $0F,$F0,$00,$C1,$F0,$0F,$85,$FF,$FF,$FF,$FF,$FF
        fcb     $C1,$3F,$C0,$00,$C1,$F0,$0F,$85,$FF,$FF,$FF,$FF
        fcb     $FF,$C1,$3F,$C0,$00,$C1,$F0,$0F,$85,$FF,$FF,$FF
        fcb     $FF,$FF,$C1,$3F,$C0,$00,$86,$FF,$FF,$FF,$FF,$7F
        fcb     $FF,$41,$00,$86,$FF,$FF,$FF,$FF,$7F,$FF,$41,$00
        fcb     $86,$FF,$FF,$FF,$FF,$7F,$FF,$41,$00,$C1,$F0,$0F
        fcb     $85,$FF,$FF,$FF,$FF,$FF,$41,$00,$85,$FF,$FF,$FF
        fcb     $FF,$7F,$C1,$03,$FC,$41,$00,$85,$FF,$FF,$FF,$FF
        fcb     $7F,$C1,$03,$FC,$41,$00,$42,$83,$FF,$FF,$AF,$C1
        fcb     $03,$FC,$41,$00,$42,$83,$FF,$FF,$AA,$C1,$03,$FC
        fcb     $41,$00,$42,$81,$FE,$C1,$3C,$83,$81,$FF,$C1,$03
        fcb     $FC,$41,$00,$42,$C1,$03,$FC,$41,$C2,$F0,$0F,$0F
        fcb     $F0,$41,$00,$41,$C2,$FC,$03,$03,$FC,$41,$C2,$FC
        fcb     $03,$0F,$F0,$41,$00,$41,$C2,$FC,$03,$03,$FC,$41
        fcb     $C2,$FC,$03,$0F,$F0,$41,$00,$44,$C2,$F0,$0F,$0F
        fcb     $F0,$41,$00,$44,$C2,$F0,$0F,$0F,$F0,$41,$00
