* v62_p1 — runtime-blit segment data, phase 1
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 48 rows x 10 bytes, 553 segment bytes
*
v62_p1:
        fcb     48,10  ; height, width in bytes
        fcb     $4A,$00,$46,$C1,$F0,$0F,$81,$FF,$42,$00,$45,$C1
        fcb     $FC,$03,$82,$FF,$FF,$C1,$3F,$C0,$41,$00,$45,$C1
        fcb     $FC,$03,$82,$FF,$FF,$C1,$0F,$F0,$41,$00,$45,$C1
        fcb     $F0,$0F,$82,$FF,$FF,$C1,$0F,$F0,$41,$00,$45,$C1
        fcb     $F0,$0F,$82,$FF,$FF,$C1,$0F,$F0,$41,$00,$45,$C1
        fcb     $FC,$03,$82,$FF,$FF,$C1,$3F,$C0,$41,$00,$46,$82
        fcb     $FF,$FF,$C1,$3F,$C0,$41,$00,$46,$C2,$F0,$0F,$03
        fcb     $FC,$42,$00,$46,$C1,$C0,$3F,$81,$FF,$42,$00,$45
        fcb     $C1,$FC,$03,$82,$FF,$FF,$42,$00,$45,$C1,$F0,$0F
        fcb     $82,$FF,$FF,$42,$00,$45,$C1,$C0,$3F,$82,$FF,$FF
        fcb     $42,$00,$45,$83,$FF,$FF,$FF,$C1,$3F,$C0,$41,$00
        fcb     $44,$C1,$FC,$03,$83,$FF,$FF,$FF,$C1,$3F,$C0,$41
        fcb     $00,$44,$C1,$FC,$03,$83,$FF,$FF,$FF,$C1,$3F,$C0
        fcb     $41,$00,$44,$C1,$F0,$0F,$83,$FF,$FF,$FF,$C1,$3F
        fcb     $C0,$41,$00,$44,$C1,$C0,$3F,$83,$FF,$FF,$FF,$C1
        fcb     $3F,$C0,$41,$00,$44,$C1,$C0,$3F,$83,$FF,$FF,$FF
        fcb     $C1,$3F,$C0,$41,$00,$44,$84,$FF,$FF,$FF,$FF,$C1
        fcb     $0F,$F0,$41,$00,$44,$84,$FF,$FF,$FF,$FF,$C1,$0F
        fcb     $F0,$41,$00,$43,$C1,$FC,$03,$84,$FF,$FF,$FF,$FF
        fcb     $C1,$0F,$F0,$41,$00,$43,$C1,$FC,$03,$84,$FF,$FF
        fcb     $FF,$FF,$C1,$0F,$F0,$41,$00,$43,$C1,$F0,$0F,$84
        fcb     $FF,$FF,$FF,$FF,$C1,$0F,$F0,$41,$00,$43,$C1,$F0
        fcb     $0F,$84,$FF,$FF,$FF,$FF,$C1,$0F,$F0,$41,$00,$43
        fcb     $C1,$C0,$3F,$84,$FF,$FF,$FF,$FF,$C1,$0F,$F0,$41
        fcb     $00,$43,$85,$FF,$FF,$FF,$FF,$FF,$C1,$0F,$F0,$41
        fcb     $00,$42,$C1,$F0,$0F,$85,$FF,$FF,$FF,$FF,$FF,$C1
        fcb     $3F,$C0,$41,$00,$42,$C1,$C0,$3F,$85,$FF,$FF,$FF
        fcb     $FF,$FF,$C1,$3F,$C0,$41,$00,$42,$86,$FF,$FF,$FF
        fcb     $FF,$FF,$FF,$C1,$3F,$C0,$41,$00,$41,$C1,$FC,$03
        fcb     $86,$FF,$FF,$FF,$FF,$FF,$FF,$C1,$3F,$C0,$41,$00
        fcb     $41,$C1,$F0,$0F,$86,$FF,$FF,$FF,$FF,$FF,$FF,$42
        fcb     $00,$41,$C1,$C0,$3F,$86,$FF,$FF,$FF,$FF,$FF,$FF
        fcb     $42,$00,$41,$87,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$42
        fcb     $00,$C1,$FC,$03,$86,$FF,$FF,$FF,$FF,$FF,$FF,$C1
        fcb     $03,$FC,$42,$00,$41,$86,$FF,$FF,$FF,$FF,$FF,$FF
        fcb     $C1,$03,$FC,$42,$00,$41,$C1,$C0,$3F,$85,$FF,$FF
        fcb     $FF,$FF,$FF,$C1,$0F,$F0,$42,$00,$41,$C1,$FC,$03
        fcb     $85,$FF,$FF,$FF,$FF,$FF,$C1,$0F,$F0,$42,$00,$42
        fcb     $85,$FF,$FF,$FF,$FF,$FF,$C1,$3F,$C0,$42,$00,$42
        fcb     $C1,$FC,$03,$84,$FF,$FF,$FF,$FF,$C1,$3F,$C0,$42
        fcb     $00,$43,$C1,$C0,$3F,$83,$FF,$FF,$FF,$C1,$3F,$C0
        fcb     $42,$00,$44,$83,$FF,$FF,$FF,$43,$00,$44,$C1,$C0
        fcb     $3F,$82,$FF,$FF,$43,$00,$44,$C1,$C0,$3F,$82,$FF
        fcb     $FF,$43,$00,$44,$C3,$C3,$3C,$C0,$3F,$03,$FC,$43
        fcb     $00,$45,$C2,$FC,$03,$03,$FC,$43,$00,$45,$C2,$FC
        fcb     $03,$03,$FC,$43,$00,$45,$C2,$FC,$03,$03,$FC,$43
        fcb     $00
