* v63_p2 — runtime-blit segment data, phase 2
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 47 rows x 10 bytes, 526 segment bytes
*
v63_p2:
        fcb     47,10  ; height, width in bytes
        fcb     $47,$C1,$C0,$3F,$42,$00,$46,$C1,$FC,$03,$81,$FF
        fcb     $C1,$03,$FC,$41,$00,$46,$C1,$C0,$3F,$82,$FF,$FF
        fcb     $41,$00,$46,$83,$FF,$FF,$FF,$41,$00,$46,$82,$FF
        fcb     $FF,$C1,$03,$FC,$41,$00,$46,$82,$FF,$FF,$C1,$0F
        fcb     $F0,$41,$00,$46,$C1,$F0,$0F,$81,$FF,$C1,$0F,$50
        fcb     $41,$00,$46,$C1,$FC,$03,$81,$FF,$C1,$0F,$50,$41
        fcb     $00,$46,$C1,$FC,$03,$81,$FF,$C1,$0F,$50,$41,$00
        fcb     $46,$C1,$C0,$3F,$81,$FF,$42,$00,$46,$82,$FF,$FF
        fcb     $42,$00,$46,$82,$FF,$FF,$42,$00,$45,$C1,$FC,$03
        fcb     $82,$FF,$FF,$42,$00,$45,$C1,$F0,$0F,$82,$FF,$FF
        fcb     $42,$00,$45,$C1,$F0,$0F,$82,$FF,$FF,$42,$00,$45
        fcb     $C1,$F0,$0F,$82,$FF,$FF,$42,$00,$45,$C1,$C0,$3F
        fcb     $82,$FF,$FF,$42,$00,$45,$C1,$C0,$3F,$82,$FF,$FF
        fcb     $42,$00,$45,$83,$FF,$FF,$FF,$42,$00,$45,$83,$FF
        fcb     $FF,$FF,$42,$00,$44,$C1,$FC,$03,$83,$FF,$FF,$FF
        fcb     $42,$00,$44,$C1,$FC,$03,$82,$FF,$FF,$C1,$03,$FC
        fcb     $42,$00,$44,$C1,$F0,$0F,$82,$FF,$FF,$C1,$03,$FC
        fcb     $42,$00,$44,$C1,$F0,$0F,$82,$FF,$FF,$C1,$03,$FC
        fcb     $42,$00,$44,$C1,$C0,$3F,$82,$FF,$FF,$C1,$03,$FC
        fcb     $42,$00,$44,$C1,$C0,$3F,$82,$FF,$FF,$C1,$03,$FC
        fcb     $42,$00,$43,$C1,$FC,$03,$83,$FF,$FF,$FF,$C1,$03
        fcb     $FC,$42,$00,$42,$C1,$FC,$03,$84,$FF,$FF,$FF,$FF
        fcb     $C1,$03,$FC,$42,$00,$42,$85,$FF,$FF,$FF,$FF,$FF
        fcb     $C1,$03,$FC,$42,$00,$41,$C1,$F0,$0F,$85,$FF,$FF
        fcb     $FF,$FF,$FF,$C1,$03,$E8,$42,$00,$41,$C1,$F0,$0F
        fcb     $86,$FF,$FF,$FF,$EA,$FF,$FF,$C1,$3F,$80,$41,$00
        fcb     $41,$C1,$F0,$0F,$86,$FF,$FF,$FF,$EA,$FF,$FF,$C1
        fcb     $3F,$80,$41,$00,$41,$C1,$FC,$03,$86,$FF,$FF,$FF
        fcb     $EA,$FF,$FF,$C1,$3F,$80,$41,$00,$41,$C1,$FC,$03
        fcb     $86,$FF,$FF,$FF,$EA,$FF,$FF,$C1,$3F,$80,$41,$00
        fcb     $41,$C1,$FC,$03,$86,$FF,$FF,$FE,$AA,$FF,$FF,$C1
        fcb     $3F,$80,$41,$00,$41,$C1,$FC,$03,$86,$FF,$FF,$FE
        fcb     $AA,$FF,$FF,$C1,$3F,$80,$41,$00,$41,$C1,$FC,$03
        fcb     $86,$FF,$FF,$FE,$AA,$FF,$FF,$C1,$3F,$80,$41,$00
        fcb     $42,$C1,$C0,$3F,$85,$FF,$FF,$FE,$AA,$FF,$C1,$3F
        fcb     $80,$41,$00,$42,$C1,$F0,$0F,$84,$FF,$FF,$FF,$FE
        fcb     $C1,$03,$A8,$42,$00,$43,$84,$FF,$FF,$FF,$EA,$C1
        fcb     $03,$A8,$42,$00,$43,$C1,$C0,$3F,$83,$FF,$EA,$FF
        fcb     $C1,$03,$A8,$42,$00,$43,$C1,$F0,$0F,$83,$FF,$EA
        fcb     $FF,$C1,$03,$A8,$42,$00,$44,$84,$FF,$FE,$AA,$AF
        fcb     $C1,$03,$FC,$41,$00,$44,$C1,$C0,$3F,$83,$AA,$FF
        fcb     $FE,$C1,$03,$FC,$41,$00,$44,$C1,$FC,$03,$82,$FE
        fcb     $AF,$C1,$03,$FC,$42,$00,$45,$C2,$F0,$0F,$0F,$F0
        fcb     $43,$00,$45,$C2,$F0,$0F,$03,$FC,$43,$00
