* v63_p2 — runtime-blit segment data, phase 2
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 47 rows x 9 bytes, 518 segment bytes
*
v63_p2:
        fcb     47,9  ; height, width in bytes
        fcb     $46,$C1,$C0,$3F,$42,$00,$45,$C1,$FC,$03,$81,$FF
        fcb     $C1,$03,$FC,$41,$00,$45,$C1,$C0,$3F,$82,$FF,$FF
        fcb     $41,$00,$45,$83,$FF,$FF,$FF,$41,$00,$45,$82,$FF
        fcb     $FF,$C1,$03,$FC,$41,$00,$45,$82,$FF,$FF,$C1,$0F
        fcb     $F0,$41,$00,$45,$C1,$F0,$0F,$81,$FF,$C1,$0F,$50
        fcb     $41,$00,$45,$C1,$FC,$03,$81,$FF,$C1,$0F,$50,$41
        fcb     $00,$45,$C1,$FC,$03,$81,$FF,$C1,$0F,$50,$41,$00
        fcb     $45,$C1,$C0,$3F,$81,$FF,$42,$00,$45,$82,$FF,$FF
        fcb     $42,$00,$45,$82,$FF,$FF,$42,$00,$44,$C1,$FC,$03
        fcb     $82,$FF,$FF,$42,$00,$44,$C1,$F0,$0F,$82,$FF,$FF
        fcb     $42,$00,$44,$C1,$F0,$0F,$82,$FF,$FF,$42,$00,$44
        fcb     $C1,$F0,$0F,$82,$FF,$FF,$42,$00,$44,$C1,$C0,$3F
        fcb     $82,$FF,$FF,$42,$00,$44,$C1,$C0,$3F,$82,$FF,$FF
        fcb     $42,$00,$44,$83,$FF,$FF,$FF,$42,$00,$44,$83,$FF
        fcb     $FF,$FF,$42,$00,$43,$C1,$FC,$03,$83,$FF,$FF,$FF
        fcb     $42,$00,$43,$C1,$FC,$03,$82,$FF,$FF,$C1,$03,$FC
        fcb     $42,$00,$43,$C1,$F0,$0F,$82,$FF,$FF,$C1,$03,$FC
        fcb     $42,$00,$43,$C1,$F0,$0F,$82,$FF,$FF,$C1,$03,$FC
        fcb     $42,$00,$43,$C1,$C0,$3F,$82,$FF,$FF,$C1,$03,$FC
        fcb     $42,$00,$43,$C1,$C0,$3F,$82,$FF,$FF,$C1,$03,$FC
        fcb     $42,$00,$42,$C1,$FC,$03,$83,$FF,$FF,$FF,$C1,$03
        fcb     $FC,$42,$00,$41,$C1,$FC,$03,$84,$FF,$FF,$FF,$FF
        fcb     $C1,$03,$FC,$42,$00,$41,$85,$FF,$FF,$FF,$FF,$FF
        fcb     $C1,$03,$FC,$42,$00,$C1,$F0,$0F,$85,$FF,$FF,$FF
        fcb     $FF,$FF,$C1,$03,$E8,$42,$00,$C1,$F0,$0F,$86,$FF
        fcb     $FF,$FF,$EA,$FF,$FF,$C1,$3F,$80,$41,$00,$C1,$F0
        fcb     $0F,$86,$FF,$FF,$FF,$EA,$FF,$FF,$C1,$3F,$80,$41
        fcb     $00,$C1,$FC,$03,$86,$FF,$FF,$FF,$EA,$FF,$FF,$C1
        fcb     $3F,$80,$41,$00,$C1,$FC,$03,$86,$FF,$FF,$FF,$EA
        fcb     $FF,$FF,$C1,$3F,$80,$41,$00,$C1,$FC,$03,$86,$FF
        fcb     $FF,$FE,$AA,$FF,$FF,$C1,$3F,$80,$41,$00,$C1,$FC
        fcb     $03,$86,$FF,$FF,$FE,$AA,$FF,$FF,$C1,$3F,$80,$41
        fcb     $00,$C1,$FC,$03,$86,$FF,$FF,$FE,$AA,$FF,$FF,$C1
        fcb     $3F,$80,$41,$00,$41,$C1,$C0,$3F,$85,$FF,$FF,$FE
        fcb     $AA,$FF,$C1,$3F,$80,$41,$00,$41,$C1,$F0,$0F,$84
        fcb     $FF,$FF,$FF,$FE,$C1,$03,$A8,$42,$00,$42,$84,$FF
        fcb     $FF,$FF,$EA,$C1,$03,$A8,$42,$00,$42,$C1,$C0,$3F
        fcb     $83,$FF,$EA,$FF,$C1,$03,$A8,$42,$00,$42,$C1,$F0
        fcb     $0F,$83,$FF,$EA,$FF,$C1,$03,$A8,$42,$00,$43,$84
        fcb     $FF,$FE,$AA,$AF,$C1,$03,$FC,$41,$00,$43,$C1,$C0
        fcb     $3F,$83,$AA,$FF,$FE,$C1,$03,$FC,$41,$00,$43,$C1
        fcb     $FC,$03,$82,$FE,$AF,$C1,$03,$FC,$42,$00,$44,$C2
        fcb     $F0,$0F,$0F,$F0,$43,$00,$44,$C2,$F0,$0F,$03,$FC
        fcb     $43,$00
