* v78_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 13 rows x 2 bytes, 75 segment bytes
*
v78_p0:
        fcb     13,2  ; height, width in bytes
        fcb     $01,$02,$00,$01,$02,$00,$01,$01,$03,$01,$03,$FC
        fcb     $00,$03,$02,$F0,$0A,$03,$A8,$00,$03,$02,$F0,$0A
        fcb     $03,$A8,$00,$01,$02,$00,$03,$01,$3F,$80,$01,$01
        fcb     $00,$01,$02,$00,$01,$01,$03,$01,$3F,$80,$00,$03
        fcb     $02,$F0,$0A,$3F,$80,$00,$03,$02,$F0,$0A,$3F,$80
        fcb     $00,$01,$01,$03,$01,$3F,$80,$00,$01,$01,$03,$01
        fcb     $3F,$80,$00
