* v78_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 13 rows x 2 bytes, 57 segment bytes
*
v78_p0:
        fcb     13,2  ; height, width in bytes
        fcb     $42,$00,$42,$00,$41,$C1,$03,$FC,$00,$C2,$F0,$0A
        fcb     $03,$A8,$00,$C2,$F0,$0A,$03,$A8,$00,$42,$00,$C1
        fcb     $3F,$80,$41,$00,$42,$00,$41,$C1,$3F,$80,$00,$C2
        fcb     $F0,$0A,$3F,$80,$00,$C2,$F0,$0A,$3F,$80,$00,$41
        fcb     $C1,$3F,$80,$00,$41,$C1,$3F,$80,$00
