* v79_p2 — runtime-blit segment data, phase 2
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 13 rows x 3 bytes, 52 segment bytes
*
v79_p2:
        fcb     13,3  ; height, width in bytes
        fcb     $43,$00,$43,$00,$43,$00,$43,$00,$43,$00,$43,$00
        fcb     $41,$C1,$F3,$08,$41,$00,$41,$C1,$03,$A8,$41,$00
        fcb     $43,$00,$41,$C2,$F0,$0A,$3F,$80,$00,$41,$81,$FE
        fcb     $C1,$3F,$80,$00,$41,$C1,$03,$A8,$41,$00,$41,$C1
        fcb     $F3,$08,$41,$00
