* v79_p2 — runtime-blit segment data, phase 2
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 13 rows x 3 bytes, 76 segment bytes
*
v79_p2:
        fcb     13,3  ; height, width in bytes
        fcb     $01,$03,$00,$01,$03,$00,$01,$03,$00,$01,$03,$00
        fcb     $01,$03,$00,$01,$03,$00,$01,$01,$03,$01,$F3,$08
        fcb     $01,$01,$00,$01,$01,$03,$01,$03,$A8,$01,$01,$00
        fcb     $01,$03,$00,$01,$01,$03,$02,$F0,$0A,$3F,$80,$00
        fcb     $01,$01,$02,$01,$FE,$03,$01,$3F,$80,$00,$01,$01
        fcb     $03,$01,$03,$A8,$01,$01,$00,$01,$01,$03,$01,$F3
        fcb     $08,$01,$01,$00
