* v81_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 48 rows x 5 bytes, 414 segment bytes
*
v81_p0:
        fcb     48,5  ; height, width in bytes
        fcb     $42,$C2,$F0,$0F,$3F,$C0,$41,$00,$42,$82,$FF,$FF
        fcb     $41,$00,$41,$C1,$FC,$03,$82,$FF,$FF,$C1,$0F,$F0
        fcb     $00,$41,$C1,$FC,$03,$82,$FF,$FF,$C1,$03,$FC,$00
        fcb     $42,$C1,$C0,$3F,$81,$FF,$C1,$03,$FC,$00,$42,$C1
        fcb     $FC,$03,$81,$FF,$C1,$03,$FC,$00,$42,$C1,$C0,$15
        fcb     $81,$7F,$C1,$0F,$F0,$00,$42,$C1,$C0,$15,$81,$7F
        fcb     $41,$00,$42,$82,$F7,$FF,$41,$00,$42,$C1,$3F,$80
        fcb     $81,$FF,$C1,$0F,$F0,$00,$43,$81,$FF,$C1,$0F,$F0
        fcb     $00,$42,$C1,$FC,$03,$81,$FF,$C1,$03,$FC,$00,$42
        fcb     $C1,$FC,$03,$81,$FF,$C1,$03,$FC,$00,$42,$C1,$F0
        fcb     $0F,$81,$FF,$C1,$03,$FC,$00,$42,$C1,$F0,$0F,$81
        fcb     $FF,$C1,$03,$FC,$00,$42,$C1,$F0,$0F,$81,$FF,$C1
        fcb     $03,$FC,$00,$42,$C1,$F0,$0F,$81,$FF,$C1,$03,$FC
        fcb     $00,$42,$C1,$F0,$0A,$81,$FF,$C1,$03,$FC,$00,$42
        fcb     $83,$FF,$FF,$AA,$00,$41,$C1,$F0,$0A,$83,$FF,$FF
        fcb     $AA,$00,$C1,$FC,$03,$84,$EA,$AA,$FF,$FF,$00,$C1
        fcb     $C0,$17,$84,$EA,$AA,$FF,$FF,$00,$C3,$C0,$17,$3F
        fcb     $C0,$F0,$0A,$82,$FF,$FF,$00,$C1,$CF,$10,$41,$C1
        fcb     $F0,$0A,$82,$FF,$FF,$00,$42,$C1,$F0,$0A,$82,$FF
        fcb     $FF,$00,$42,$C1,$F0,$0A,$82,$FF,$FF,$00,$42,$C1
        fcb     $F0,$0A,$82,$FF,$FF,$00,$42,$C1,$F0,$0A,$82,$FF
        fcb     $FF,$00,$42,$C1,$F0,$0A,$82,$FF,$FF,$00,$42,$C1
        fcb     $F0,$0A,$82,$FF,$FF,$00,$42,$C1,$F0,$0A,$82,$FF
        fcb     $FF,$00,$42,$C1,$F0,$0A,$82,$AF,$FF,$00,$42,$C1
        fcb     $F0,$0A,$82,$AF,$FF,$00,$42,$C1,$F0,$0A,$82,$AF
        fcb     $FF,$00,$42,$C1,$F0,$0A,$82,$AF,$FF,$00,$42,$C1
        fcb     $F0,$0A,$82,$AF,$FF,$00,$42,$C1,$F0,$0A,$82,$AF
        fcb     $FF,$00,$42,$C1,$F0,$0A,$81,$AF,$C1,$03,$FC,$00
        fcb     $42,$C1,$F0,$0A,$81,$AF,$C1,$03,$FC,$00,$42,$C1
        fcb     $F0,$0A,$81,$AF,$C1,$03,$FC,$00,$43,$81,$AF,$C1
        fcb     $03,$FC,$00,$43,$81,$AF,$C1,$03,$FC,$00,$43,$81
        fcb     $AF,$C1,$03,$FC,$00,$43,$81,$AF,$C1,$03,$FC,$00
        fcb     $43,$81,$AF,$C1,$03,$FC,$00,$43,$81,$FE,$C1,$03
        fcb     $FC,$00,$42,$C1,$F0,$0F,$82,$FE,$FF,$00,$42,$82
        fcb     $FF,$FF,$C1,$3F,$C0,$00
