* v82_p3 — runtime-blit segment data, phase 3
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 13 rows x 3 bytes, 78 segment bytes
*
v82_p3:
        fcb     13,3  ; height, width in bytes
        fcb     $41,$C1,$FC,$01,$41,$00,$41,$C1,$FC,$01,$41,$00
        fcb     $41,$C1,$FC,$01,$41,$00,$42,$C1,$CF,$10,$00,$41
        fcb     $C2,$FC,$01,$0F,$50,$00,$41,$C1,$C0,$15,$41,$00
        fcb     $41,$C1,$FC,$01,$41,$00,$41,$C1,$FC,$01,$41,$00
        fcb     $41,$C1,$C0,$15,$41,$00,$41,$C1,$C0,$3F,$41,$00
        fcb     $41,$C1,$FC,$01,$41,$00,$41,$C1,$FC,$01,$41,$00
        fcb     $41,$C1,$FC,$01,$41,$00
