* v83_p3 — runtime-blit segment data, phase 3
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 13 rows x 3 bytes, 85 segment bytes
*
v83_p3:
        fcb     13,3  ; height, width in bytes
        fcb     $01,$03,$00,$01,$03,$00,$01,$03,$00,$01,$03,$00
        fcb     $01,$02,$03,$01,$CF,$10,$00,$01,$03,$00,$01,$01
        fcb     $03,$02,$FC,$01,$0F,$50,$00,$01,$01,$03,$02,$FC
        fcb     $01,$0F,$50,$00,$01,$01,$03,$02,$C0,$15,$0F,$50
        fcb     $00,$01,$01,$03,$02,$C0,$15,$0F,$50,$00,$01,$01
        fcb     $03,$01,$C0,$15,$01,$01,$00,$01,$01,$03,$01,$C0
        fcb     $15,$01,$01,$00,$01,$01,$03,$02,$FC,$01,$0F,$50
        fcb     $00
