* v85_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 13 rows x 2 bytes, 76 segment bytes
*
v85_p0:
        fcb     13,2  ; height, width in bytes
        fcb     $01,$02,$00,$01,$02,$00,$01,$02,$00,$01,$02,$00
        fcb     $01,$01,$03,$01,$F3,$08,$00,$03,$02,$F0,$0A,$03
        fcb     $A8,$00,$02,$01,$AA,$03,$01,$03,$A8,$00,$03,$02
        fcb     $3F,$80,$03,$A8,$00,$01,$01,$03,$01,$03,$A8,$00
        fcb     $03,$02,$F0,$0A,$3F,$80,$00,$03,$02,$F0,$0A,$3F
        fcb     $80,$00,$03,$02,$F0,$0A,$3F,$80,$00,$01,$01,$03
        fcb     $01,$3F,$80,$00
