* walk_scripts.s — the scene's scripts. The CELS are in cel_image.s.
* GENERATED by harness/tools/bake_scene.py — do not hand-edit.

* THE SCENE SCRIPTS: (sequence, plays), derived from bake_scene.PLAN.
* A count of 0 means the sequence holds and the script is finished.
* `play N` advances BOTH characters [SUBS.S:876], so the vizier's leading Vstand
* is exactly as long as the princess's opening — he waits at the door while she
* hears it.
viz_script
                fdb     viz_stand
                fcb     9
                fdb     viz_walk
                fcb     30
                fdb     viz_stop
                fcb     0               ; hold
pri_script
                fdb     pri_alert
                fcb     0               ; hold
