* walk_scripts.s — the scene's scripts. The CELS are in the split image.
* GENERATED by harness/tools/bake_scene.py — do not hand-edit.

* THE SCENE SCRIPTS: (sequence, plays), derived from bake_scene.PLAN.
* A count of 0 means the sequence holds and the script is finished.
* `play N` advances BOTH characters [SUBS.S:876], so the vizier's leading Vstand
* is exactly as long as the princess's opening — he waits at the door while she
* hears it.
viz_script
                fdb     viz_stand
                fcb     140
                fdb     viz_walk
                fcb     7
                fdb     viz_stop
                fcb     59
                fdb     viz_walk
                fcb     29
                fdb     viz_stop
                fcb     60
                fdb     viz_raise
                fcb     35
                fdb     viz_exit
                fcb     0               ; hold
pri_script
                fdb     pri_stand
                fcb     116
                fdb     pri_alert
                fcb     180
                fdb     pri_back
                fcb     63
                fdb     pri_slump
                fcb     0               ; hold

* --- the per-beat block schedule, from the same PLAN -----------------
                include "content/cutscene/chars/cel_plan.s"
