* frame_table.s — the gameplay FRAME table (P5.29).
* GENERATED by harness/tools/gen_frame_table.py from FRAMEDEF.S -- do not hand-edit.
*
* Row (n - <tab>_first) = frame n:  +0 image  +1 Fdx  +2 Fdy  +3 Fcheck (RAW)  +4 slot
* cel_table.s's shape (P3.65): the table carries the FACT, the engine the RULE --
*     ODD X iff bit7(Fcheck) == bit7(CharFace)      [CTRLSUBS.S:833-839]
* The Apple width is per CEL, in char_cels.s; it is not repeated here.
FRAME_ENTSZ     equ     5

fdef_tab_first    equ     1
fdef_tab_n        equ     240
fdef_tab
        fcb     1,1,0,$C4,0      ;   1  CHTAB1 #1  dx 1 dy 0  Fcheck b7=1
        fcb     2,1,0,$44,0      ;   2  CHTAB1 #2  dx 1 dy 0  Fcheck b7=0
        fcb     3,3,0,$47,0      ;   3  CHTAB1 #3  dx 3 dy 0  Fcheck b7=0
        fcb     4,4,0,$48,0      ;   4  CHTAB1 #4  dx 4 dy 0  Fcheck b7=0
        fcb     5,0,0,$E6,0      ;   5  CHTAB1 #5  dx 0 dy 0  Fcheck b7=1
        fcb     6,0,0,$49,0      ;   6  CHTAB1 #6  dx 0 dy 0  Fcheck b7=0
        fcb     7,0,0,$4A,0      ;   7  CHTAB1 #7  dx 0 dy 0  Fcheck b7=0
        fcb     8,0,0,$C5,0      ;   8  CHTAB1 #8  dx 0 dy 0  Fcheck b7=1
        fcb     9,0,0,$44,0      ;   9  CHTAB1 #9  dx 0 dy 0  Fcheck b7=0
        fcb     10,0,0,$47,0      ;  10  CHTAB1 #10  dx 0 dy 0  Fcheck b7=0
        fcb     11,0,0,$4B,0      ;  11  CHTAB1 #11  dx 0 dy 0  Fcheck b7=0
        fcb     12,0,0,$43,0      ;  12  CHTAB1 #12  dx 0 dy 0  Fcheck b7=0
        fcb     13,0,0,$C3,0      ;  13  CHTAB1 #13  dx 0 dy 0  Fcheck b7=1
        fcb     14,0,0,$47,0      ;  14  CHTAB1 #14  dx 0 dy 0  Fcheck b7=0
        fcb     15,0,0,$43,0      ;  15  CHTAB1 #15  dx 0 dy 0  Fcheck b7=0
        fcb     16,0,0,$C3,0      ;  16  CHTAB1 #16  dx 0 dy 0  Fcheck b7=1
        fcb     17,0,0,$44,0      ;  17  CHTAB1 #17  dx 0 dy 0  Fcheck b7=0
        fcb     18,0,0,$46,0      ;  18  CHTAB1 #18  dx 0 dy 0  Fcheck b7=0
        fcb     19,0,0,$48,0      ;  19  CHTAB1 #19  dx 0 dy 0  Fcheck b7=0
        fcb     20,0,0,$89,0      ;  20  CHTAB1 #20  dx 0 dy 0  Fcheck b7=1
        fcb     21,0,0,$0B,0      ;  21  CHTAB1 #21  dx 0 dy 0  Fcheck b7=0
        fcb     22,0,0,$8B,0      ;  22  CHTAB1 #22  dx 0 dy 0  Fcheck b7=1
        fcb     23,0,0,$11,0      ;  23  CHTAB1 #23  dx 0 dy 0  Fcheck b7=0
        fcb     24,0,0,$07,0      ;  24  CHTAB1 #24  dx 0 dy 0  Fcheck b7=0
        fcb     25,0,0,$05,0      ;  25  CHTAB1 #25  dx 0 dy 0  Fcheck b7=0
        fcb     26,0,0,$C1,0      ;  26  CHTAB1 #26  dx 0 dy 0  Fcheck b7=1
        fcb     27,0,0,$C6,0      ;  27  CHTAB1 #27  dx 0 dy 0  Fcheck b7=1
        fcb     28,0,0,$43,0      ;  28  CHTAB1 #28  dx 0 dy 0  Fcheck b7=0
        fcb     29,0,0,$48,0      ;  29  CHTAB1 #29  dx 0 dy 0  Fcheck b7=0
        fcb     30,0,0,$42,0      ;  30  CHTAB1 #30  dx 0 dy 0  Fcheck b7=0
        fcb     31,0,0,$42,0      ;  31  CHTAB1 #31  dx 0 dy 0  Fcheck b7=0
        fcb     32,0,0,$C2,0      ;  32  CHTAB1 #32  dx 0 dy 0  Fcheck b7=1
        fcb     33,0,0,$C2,0      ;  33  CHTAB1 #33  dx 0 dy 0  Fcheck b7=1
        fcb     34,0,0,$43,0      ;  34  CHTAB1 #34  dx 0 dy 0  Fcheck b7=0
        fcb     35,0,0,$48,0      ;  35  CHTAB1 #35  dx 0 dy 0  Fcheck b7=0
        fcb     36,0,0,$CE,0      ;  36  CHTAB1 #36  dx 0 dy 0  Fcheck b7=1
        fcb     37,0,0,$C1,0      ;  37  CHTAB1 #37  dx 0 dy 0  Fcheck b7=1
        fcb     38,0,0,$45,0      ;  38  CHTAB1 #38  dx 0 dy 0  Fcheck b7=0
        fcb     39,0,0,$8E,0      ;  39  CHTAB1 #39  dx 0 dy 0  Fcheck b7=1
        fcb     40,0,0,$0B,0      ;  40  CHTAB1 #40  dx 0 dy 0  Fcheck b7=0
        fcb     41,0,0,$8B,0      ;  41  CHTAB1 #41  dx 0 dy 0  Fcheck b7=1
        fcb     42,0,0,$8A,0      ;  42  CHTAB1 #42  dx 0 dy 0  Fcheck b7=1
        fcb     43,0,0,$01,0      ;  43  CHTAB1 #43  dx 0 dy 0  Fcheck b7=0
        fcb     44,0,0,$C4,0      ;  44  CHTAB1 #44  dx 0 dy 0  Fcheck b7=1
        fcb     45,0,0,$C3,0      ;  45  CHTAB1 #45  dx 0 dy 0  Fcheck b7=1
        fcb     46,0,0,$C3,0      ;  46  CHTAB1 #46  dx 0 dy 0  Fcheck b7=1
        fcb     47,0,0,$A5,0      ;  47  CHTAB1 #47  dx 0 dy 0  Fcheck b7=1
        fcb     48,0,0,$A4,0      ;  48  CHTAB1 #48  dx 0 dy 0  Fcheck b7=1
        fcb     49,0,0,$66,0      ;  49  CHTAB1 #49  dx 0 dy 0  Fcheck b7=0
        fcb     50,4,0,$67,0      ;  50  CHTAB1 #50  dx 4 dy 0  Fcheck b7=0
        fcb     51,3,0,$66,0      ;  51  CHTAB1 #51  dx 3 dy 0  Fcheck b7=0
        fcb     52,1,0,$44,0      ;  52  CHTAB1 #52  dx 1 dy 0  Fcheck b7=0
        fcb     1,0,0,$C2,1      ;  53  CHTAB2 #1  dx 0 dy 0  Fcheck b7=1
        fcb     2,0,0,$41,1      ;  54  CHTAB2 #2  dx 0 dy 0  Fcheck b7=0
        fcb     3,0,0,$42,1      ;  55  CHTAB2 #3  dx 0 dy 0  Fcheck b7=0
        fcb     4,0,0,$00,1      ;  56  CHTAB2 #4  dx 0 dy 0  Fcheck b7=0
        fcb     5,0,0,$00,1      ;  57  CHTAB2 #5  dx 0 dy 0  Fcheck b7=0
        fcb     6,0,0,$80,1      ;  58  CHTAB2 #6  dx 0 dy 0  Fcheck b7=1
        fcb     7,0,0,$00,1      ;  59  CHTAB2 #7  dx 0 dy 0  Fcheck b7=0
        fcb     8,0,0,$80,1      ;  60  CHTAB2 #8  dx 0 dy 0  Fcheck b7=1
        fcb     9,0,0,$00,1      ;  61  CHTAB2 #9  dx 0 dy 0  Fcheck b7=0
        fcb     10,0,0,$80,1      ;  62  CHTAB2 #10  dx 0 dy 0  Fcheck b7=1
        fcb     11,0,0,$00,1      ;  63  CHTAB2 #11  dx 0 dy 0  Fcheck b7=0
        fcb     12,0,0,$00,1      ;  64  CHTAB2 #12  dx 0 dy 0  Fcheck b7=0
        fcb     13,0,0,$80,1      ;  65  CHTAB2 #13  dx 0 dy 0  Fcheck b7=1
        fcb     0,0,0,0,0           ;  66 (blank)
        fcb     17,254,0,$41,1      ;  67  CHTAB2 #17  dx -2 dy 0  Fcheck b7=0
        fcb     18,254,0,$41,1      ;  68  CHTAB2 #18  dx -2 dy 0  Fcheck b7=0
        fcb     19,255,0,$C2,1      ;  69  CHTAB2 #19  dx -1 dy 0  Fcheck b7=1
        fcb     20,254,0,$42,1      ;  70  CHTAB2 #20  dx -2 dy 0  Fcheck b7=0
        fcb     21,254,0,$41,1      ;  71  CHTAB2 #21  dx -2 dy 0  Fcheck b7=0
        fcb     22,254,0,$41,1      ;  72  CHTAB2 #22  dx -2 dy 0  Fcheck b7=0
        fcb     23,254,0,$41,1      ;  73  CHTAB2 #23  dx -2 dy 0  Fcheck b7=0
        fcb     24,255,0,$07,1      ;  74  CHTAB2 #24  dx -1 dy 0  Fcheck b7=0
        fcb     25,255,0,$05,1      ;  75  CHTAB2 #25  dx -1 dy 0  Fcheck b7=0
        fcb     26,2,0,$07,1      ;  76  CHTAB2 #26  dx 2 dy 0  Fcheck b7=0
        fcb     27,2,0,$07,1      ;  77  CHTAB2 #27  dx 2 dy 0  Fcheck b7=0
        fcb     28,2,253,$00,1      ;  78  CHTAB2 #28  dx 2 dy -3  Fcheck b7=0
        fcb     29,2,246,$00,1      ;  79  CHTAB2 #29  dx 2 dy -10  Fcheck b7=0
        fcb     30,2,245,$80,1      ;  80  CHTAB2 #30  dx 2 dy -11  Fcheck b7=1
        fcb     31,3,254,$43,1      ;  81  CHTAB2 #31  dx 3 dy -2  Fcheck b7=0
        fcb     32,3,0,$C3,1      ;  82  CHTAB2 #32  dx 3 dy 0  Fcheck b7=1
        fcb     33,3,0,$C3,1      ;  83  CHTAB2 #33  dx 3 dy 0  Fcheck b7=1
        fcb     34,3,0,$63,1      ;  84  CHTAB2 #34  dx 3 dy 0  Fcheck b7=0
        fcb     35,4,0,$E3,1      ;  85  CHTAB2 #35  dx 4 dy 0  Fcheck b7=1
        fcb     29,0,0,$00,0      ;  86  CHTAB1 #29  dx 0 dy 0  Fcheck b7=0
        fcb     37,7,242,$80,1      ;  87  CHTAB2 #37  dx 7 dy -14  Fcheck b7=1
        fcb     38,7,244,$80,1      ;  88  CHTAB2 #38  dx 7 dy -12  Fcheck b7=1
        fcb     39,4,244,$00,1      ;  89  CHTAB2 #39  dx 4 dy -12  Fcheck b7=0
        fcb     40,3,246,$80,1      ;  90  CHTAB2 #40  dx 3 dy -10  Fcheck b7=1
        fcb     41,2,246,$80,1      ;  91  CHTAB2 #41  dx 2 dy -10  Fcheck b7=1
        fcb     42,1,246,$80,1      ;  92  CHTAB2 #42  dx 1 dy -10  Fcheck b7=1
        fcb     43,0,245,$00,1      ;  93  CHTAB2 #43  dx 0 dy -11  Fcheck b7=0
        fcb     44,255,244,$00,1      ;  94  CHTAB2 #44  dx -1 dy -12  Fcheck b7=0
        fcb     45,255,242,$00,1      ;  95  CHTAB2 #45  dx -1 dy -14  Fcheck b7=0
        fcb     46,255,242,$00,1      ;  96  CHTAB2 #46  dx -1 dy -14  Fcheck b7=0
        fcb     47,255,241,$80,1      ;  97  CHTAB2 #47  dx -1 dy -15  Fcheck b7=1
        fcb     48,255,241,$80,1      ;  98  CHTAB2 #48  dx -1 dy -15  Fcheck b7=1
        fcb     49,0,241,$00,1      ;  99  CHTAB2 #49  dx 0 dy -15  Fcheck b7=0
        fcb     0,0,0,0,0           ; 100 (blank)
        fcb     0,0,0,0,0           ; 101 (blank)
        fcb     50,0,0,$C6,1      ; 102  CHTAB2 #50  dx 0 dy 0  Fcheck b7=1
        fcb     51,0,0,$46,1      ; 103  CHTAB2 #51  dx 0 dy 0  Fcheck b7=0
        fcb     52,0,0,$C5,1      ; 104  CHTAB2 #52  dx 0 dy 0  Fcheck b7=1
        fcb     53,0,0,$45,1      ; 105  CHTAB2 #53  dx 0 dy 0  Fcheck b7=0
        fcb     54,0,0,$C2,1      ; 106  CHTAB2 #54  dx 0 dy 0  Fcheck b7=1
        fcb     55,0,0,$C4,1      ; 107  CHTAB2 #55  dx 0 dy 0  Fcheck b7=1
        fcb     56,0,0,$C5,1      ; 108  CHTAB2 #56  dx 0 dy 0  Fcheck b7=1
        fcb     57,0,0,$46,1      ; 109  CHTAB2 #57  dx 0 dy 0  Fcheck b7=0
        fcb     58,0,0,$47,1      ; 110  CHTAB2 #58  dx 0 dy 0  Fcheck b7=0
        fcb     59,0,0,$47,1      ; 111  CHTAB2 #59  dx 0 dy 0  Fcheck b7=0
        fcb     60,0,0,$49,1      ; 112  CHTAB2 #60  dx 0 dy 0  Fcheck b7=0
        fcb     61,0,0,$C8,1      ; 113  CHTAB2 #61  dx 0 dy 0  Fcheck b7=1
        fcb     62,0,0,$C9,1      ; 114  CHTAB2 #62  dx 0 dy 0  Fcheck b7=1
        fcb     63,0,0,$49,1      ; 115  CHTAB2 #63  dx 0 dy 0  Fcheck b7=0
        fcb     64,0,0,$45,1      ; 116  CHTAB2 #64  dx 0 dy 0  Fcheck b7=0
        fcb     65,2,0,$45,1      ; 117  CHTAB2 #65  dx 2 dy 0  Fcheck b7=0
        fcb     66,2,0,$C5,1      ; 118  CHTAB2 #66  dx 2 dy 0  Fcheck b7=1
        fcb     67,0,0,$C3,1      ; 119  CHTAB2 #67  dx 0 dy 0  Fcheck b7=1
        fcb     0,0,0,0,0           ; 120 (blank)
        fcb     1,0,0,$43,2      ; 121  CHTAB3 #1  dx 0 dy 0  Fcheck b7=0
        fcb     2,0,0,$C4,2      ; 122  CHTAB3 #2  dx 0 dy 0  Fcheck b7=1
        fcb     3,0,0,$C5,2      ; 123  CHTAB3 #3  dx 0 dy 0  Fcheck b7=1
        fcb     4,0,0,$48,2      ; 124  CHTAB3 #4  dx 0 dy 0  Fcheck b7=0
        fcb     5,0,0,$6C,2      ; 125  CHTAB3 #5  dx 0 dy 0  Fcheck b7=0
        fcb     6,0,0,$EF,2      ; 126  CHTAB3 #6  dx 0 dy 0  Fcheck b7=1
        fcb     7,0,0,$63,2      ; 127  CHTAB3 #7  dx 0 dy 0  Fcheck b7=0
        fcb     8,0,0,$C3,2      ; 128  CHTAB3 #8  dx 0 dy 0  Fcheck b7=1
        fcb     9,0,0,$43,2      ; 129  CHTAB3 #9  dx 0 dy 0  Fcheck b7=0
        fcb     10,0,0,$43,2      ; 130  CHTAB3 #10  dx 0 dy 0  Fcheck b7=0
        fcb     11,0,0,$44,2      ; 131  CHTAB3 #11  dx 0 dy 0  Fcheck b7=0
        fcb     12,0,0,$44,2      ; 132  CHTAB3 #12  dx 0 dy 0  Fcheck b7=0
        fcb     62,0,1,$C1,2      ; 133  CHTAB3 #62  dx 0 dy 1  Fcheck b7=1
        fcb     63,0,1,$C7,2      ; 134  CHTAB3 #63  dx 0 dy 1  Fcheck b7=1
        fcb     13,0,244,$01,2      ; 135  CHTAB3 #13  dx 0 dy -12  Fcheck b7=0
        fcb     14,0,235,$00,2      ; 136  CHTAB3 #14  dx 0 dy -21  Fcheck b7=0
        fcb     15,1,230,$80,2      ; 137  CHTAB3 #15  dx 1 dy -26  Fcheck b7=1
        fcb     16,4,224,$80,2      ; 138  CHTAB3 #16  dx 4 dy -32  Fcheck b7=1
        fcb     17,6,220,$81,2      ; 139  CHTAB3 #17  dx 6 dy -36  Fcheck b7=1
        fcb     18,7,215,$82,2      ; 140  CHTAB3 #18  dx 7 dy -41  Fcheck b7=1
        fcb     19,2,17,$42,2      ; 141  CHTAB3 #19  dx 2 dy 17  Fcheck b7=0
        fcb     20,4,9,$C4,2      ; 142  CHTAB3 #20  dx 4 dy 9  Fcheck b7=1
        fcb     21,4,5,$C9,2      ; 143  CHTAB3 #21  dx 4 dy 5  Fcheck b7=1
        fcb     22,4,4,$C8,2      ; 144  CHTAB3 #22  dx 4 dy 4  Fcheck b7=1
        fcb     23,5,0,$69,2      ; 145  CHTAB3 #23  dx 5 dy 0  Fcheck b7=0
        fcb     24,5,0,$E9,2      ; 146  CHTAB3 #24  dx 5 dy 0  Fcheck b7=1
        fcb     25,5,0,$E8,2      ; 147  CHTAB3 #25  dx 5 dy 0  Fcheck b7=1
        fcb     26,5,0,$69,2      ; 148  CHTAB3 #26  dx 5 dy 0  Fcheck b7=0
        fcb     27,5,0,$69,2      ; 149  CHTAB3 #27  dx 5 dy 0  Fcheck b7=0
        fcb     11,0,2,$80,4      ; 150  CHTAB5 #11  dx 0 dy 2  Fcheck b7=1
        fcb     1,0,2,$80,4      ; 151  CHTAB5 #1  dx 0 dy 2  Fcheck b7=1
        fcb     2,3,2,$00,4      ; 152  CHTAB5 #2  dx 3 dy 2  Fcheck b7=0
        fcb     3,7,2,$C4,4      ; 153  CHTAB5 #3  dx 7 dy 2  Fcheck b7=1
        fcb     4,10,2,$00,4      ; 154  CHTAB5 #4  dx 10 dy 2  Fcheck b7=0
        fcb     5,7,2,$80,4      ; 155  CHTAB5 #5  dx 7 dy 2  Fcheck b7=1
        fcb     6,4,2,$80,4      ; 156  CHTAB5 #6  dx 4 dy 2  Fcheck b7=1
        fcb     7,0,2,$CE,4      ; 157  CHTAB5 #7  dx 0 dy 2  Fcheck b7=1
        fcb     8,0,2,$CD,4      ; 158  CHTAB5 #8  dx 0 dy 2  Fcheck b7=1
        fcb     9,3,2,$00,4      ; 159  CHTAB5 #9  dx 3 dy 2  Fcheck b7=0
        fcb     10,3,2,$00,4      ; 160  CHTAB5 #10  dx 3 dy 2  Fcheck b7=0
        fcb     11,0,2,$80,4      ; 161  CHTAB5 #11  dx 0 dy 2  Fcheck b7=1
        fcb     12,0,2,$80,4      ; 162  CHTAB5 #12  dx 0 dy 2  Fcheck b7=1
        fcb     13,0,2,$00,4      ; 163  CHTAB5 #13  dx 0 dy 2  Fcheck b7=0
        fcb     14,0,2,$80,4      ; 164  CHTAB5 #14  dx 0 dy 2  Fcheck b7=1
        fcb     15,2,2,$C3,4      ; 165  CHTAB5 #15  dx 2 dy 2  Fcheck b7=1
        fcb     15,0,0,$43,0      ; 166  CHTAB1 #15  dx 0 dy 0  Fcheck b7=0
        fcb     17,7,2,$80,4      ; 167  CHTAB5 #17  dx 7 dy 2  Fcheck b7=1
        fcb     18,1,2,$80,4      ; 168  CHTAB5 #18  dx 1 dy 2  Fcheck b7=1
        fcb     19,0,2,$80,4      ; 169  CHTAB5 #19  dx 0 dy 2  Fcheck b7=1
        fcb     8,0,2,$CD,4      ; 170  CHTAB5 #8  dx 0 dy 2  Fcheck b7=1
        fcb     8,0,2,$CD,4      ; 171  CHTAB5 #8  dx 0 dy 2  Fcheck b7=1
        fcb     50,0,0,$C6,1      ; 172  CHTAB2 #50  dx 0 dy 0  Fcheck b7=1
        fcb     51,0,0,$46,1      ; 173  CHTAB2 #51  dx 0 dy 0  Fcheck b7=0
        fcb     52,0,0,$C5,1      ; 174  CHTAB2 #52  dx 0 dy 0  Fcheck b7=1
        fcb     53,0,0,$45,1      ; 175  CHTAB2 #53  dx 0 dy 0  Fcheck b7=0
        fcb     52,0,0,$C5,1      ; 176  CHTAB2 #52  dx 0 dy 0  Fcheck b7=1
        fcb     15,0,3,$8A,1      ; 177  CHTAB2 #15  dx 0 dy 3  Fcheck b7=1
        fcb     14,4,3,$87,1      ; 178  CHTAB2 #14  dx 4 dy 3  Fcheck b7=1
        fcb     40,0,1,$44,4      ; 179  CHTAB5 #40  dx 0 dy 1  Fcheck b7=0
        fcb     41,0,1,$44,4      ; 180  CHTAB5 #41  dx 0 dy 1  Fcheck b7=0
        fcb     42,0,1,$44,4      ; 181  CHTAB5 #42  dx 0 dy 1  Fcheck b7=0
        fcb     43,0,1,$47,4      ; 182  CHTAB5 #43  dx 0 dy 1  Fcheck b7=0
        fcb     44,0,7,$4B,4      ; 183  CHTAB5 #44  dx 0 dy 7  Fcheck b7=0
        fcb     0,0,0,0,0           ; 184 (blank)
        fcb     16,4,7,$49,1      ; 185  CHTAB2 #16  dx 4 dy 7  Fcheck b7=0
        fcb     68,0,0,$44,1      ; 186  CHTAB2 #68  dx 0 dy 0  Fcheck b7=0
        fcb     69,0,0,$44,1      ; 187  CHTAB2 #69  dx 0 dy 0  Fcheck b7=0
        fcb     70,0,2,$44,1      ; 188  CHTAB2 #70  dx 0 dy 2  Fcheck b7=0
        fcb     0,0,0,0,0           ; 189 (blank)
        fcb     0,0,0,0,0           ; 190 (blank)
        fcb     20,0,0,$00,4      ; 191  CHTAB5 #20  dx 0 dy 0  Fcheck b7=0
        fcb     21,0,1,$00,4      ; 192  CHTAB5 #21  dx 0 dy 1  Fcheck b7=0
        fcb     22,0,0,$80,4      ; 193  CHTAB5 #22  dx 0 dy 0  Fcheck b7=1
        fcb     23,0,0,$00,4      ; 194  CHTAB5 #23  dx 0 dy 0  Fcheck b7=0
        fcb     24,255,0,$00,4      ; 195  CHTAB5 #24  dx -1 dy 0  Fcheck b7=0
        fcb     25,255,0,$00,4      ; 196  CHTAB5 #25  dx -1 dy 0  Fcheck b7=0
        fcb     26,255,0,$00,4      ; 197  CHTAB5 #26  dx -1 dy 0  Fcheck b7=0
        fcb     27,252,0,$00,4      ; 198  CHTAB5 #27  dx -4 dy 0  Fcheck b7=0
        fcb     28,252,0,$80,4      ; 199  CHTAB5 #28  dx -4 dy 0  Fcheck b7=1
        fcb     29,252,0,$00,4      ; 200  CHTAB5 #29  dx -4 dy 0  Fcheck b7=0
        fcb     30,252,0,$00,4      ; 201  CHTAB5 #30  dx -4 dy 0  Fcheck b7=0
        fcb     31,252,0,$00,4      ; 202  CHTAB5 #31  dx -4 dy 0  Fcheck b7=0
        fcb     32,252,0,$00,4      ; 203  CHTAB5 #32  dx -4 dy 0  Fcheck b7=0
        fcb     33,251,0,$00,4      ; 204  CHTAB5 #33  dx -5 dy 0  Fcheck b7=0
        fcb     34,251,0,$00,4      ; 205  CHTAB5 #34  dx -5 dy 0  Fcheck b7=0
        fcb     35,0,0,$00,4      ; 206  CHTAB5 #35  dx 0 dy 0  Fcheck b7=0
        fcb     36,0,1,$46,4      ; 207  CHTAB5 #36  dx 0 dy 1  Fcheck b7=0
        fcb     37,0,1,$C6,4      ; 208  CHTAB5 #37  dx 0 dy 1  Fcheck b7=1
        fcb     38,0,1,$C8,4      ; 209  CHTAB5 #38  dx 0 dy 1  Fcheck b7=1
        fcb     39,0,1,$4A,4      ; 210  CHTAB5 #39  dx 0 dy 1  Fcheck b7=0
        fcb     0,0,0,0,0           ; 211 (blank)
        fcb     0,0,0,0,0           ; 212 (blank)
        fcb     0,0,0,0,0           ; 213 (blank)
        fcb     0,0,0,0,0           ; 214 (blank)
        fcb     0,0,0,0,0           ; 215 (blank)
        fcb     0,0,0,0,0           ; 216 (blank)
        fcb     53,0,0,$80,0      ; 217  CHTAB1 #53  dx 0 dy 0  Fcheck b7=1
        fcb     54,0,0,$00,0      ; 218  CHTAB1 #54  dx 0 dy 0  Fcheck b7=0
        fcb     55,0,0,$00,0      ; 219  CHTAB1 #55  dx 0 dy 0  Fcheck b7=0
        fcb     56,0,0,$00,0      ; 220  CHTAB1 #56  dx 0 dy 0  Fcheck b7=0
        fcb     57,0,0,$80,0      ; 221  CHTAB1 #57  dx 0 dy 0  Fcheck b7=1
        fcb     58,0,0,$00,0      ; 222  CHTAB1 #58  dx 0 dy 0  Fcheck b7=0
        fcb     59,0,0,$00,0      ; 223  CHTAB1 #59  dx 0 dy 0  Fcheck b7=0
        fcb     60,0,0,$00,0      ; 224  CHTAB1 #60  dx 0 dy 0  Fcheck b7=0
        fcb     61,0,0,$80,0      ; 225  CHTAB1 #61  dx 0 dy 0  Fcheck b7=1
        fcb     62,0,0,$00,0      ; 226  CHTAB1 #62  dx 0 dy 0  Fcheck b7=0
        fcb     63,0,0,$80,0      ; 227  CHTAB1 #63  dx 0 dy 0  Fcheck b7=1
        fcb     64,0,0,$00,0      ; 228  CHTAB1 #64  dx 0 dy 0  Fcheck b7=0
        fcb     50,1,1,$C3,2      ; 229  CHTAB3 #50  dx 1 dy 1  Fcheck b7=1
        fcb     51,0,1,$49,2      ; 230  CHTAB3 #51  dx 0 dy 1  Fcheck b7=0
        fcb     52,0,1,$C3,2      ; 231  CHTAB3 #52  dx 0 dy 1  Fcheck b7=1
        fcb     53,0,1,$49,2      ; 232  CHTAB3 #53  dx 0 dy 1  Fcheck b7=0
        fcb     54,0,1,$C3,2      ; 233  CHTAB3 #54  dx 0 dy 1  Fcheck b7=1
        fcb     55,1,1,$49,2      ; 234  CHTAB3 #55  dx 1 dy 1  Fcheck b7=0
        fcb     56,1,1,$43,2      ; 235  CHTAB3 #56  dx 1 dy 1  Fcheck b7=0
        fcb     57,1,1,$C9,2      ; 236  CHTAB3 #57  dx 1 dy 1  Fcheck b7=1
        fcb     58,4,1,$C6,2      ; 237  CHTAB3 #58  dx 4 dy 1  Fcheck b7=1
        fcb     59,3,1,$CA,2      ; 238  CHTAB3 #59  dx 3 dy 1  Fcheck b7=1
        fcb     60,1,1,$43,2      ; 239  CHTAB3 #60  dx 1 dy 1  Fcheck b7=0
        fcb     61,1,1,$C8,2      ; 240  CHTAB3 #61  dx 1 dy 1  Fcheck b7=1

alt1_tab_first    equ     150
alt1_tab_n        equ     40
alt1_tab
        fcb     11,2,1,$00,3      ; 150  CHTAB4 #11  dx 2 dy 1  Fcheck b7=0
        fcb     1,3,1,$00,3      ; 151  CHTAB4 #1  dx 3 dy 1  Fcheck b7=0
        fcb     2,4,1,$00,3      ; 152  CHTAB4 #2  dx 4 dy 1  Fcheck b7=0
        fcb     3,7,1,$44,3      ; 153  CHTAB4 #3  dx 7 dy 1  Fcheck b7=0
        fcb     4,10,1,$00,3      ; 154  CHTAB4 #4  dx 10 dy 1  Fcheck b7=0
        fcb     5,7,1,$80,3      ; 155  CHTAB4 #5  dx 7 dy 1  Fcheck b7=1
        fcb     6,4,1,$80,3      ; 156  CHTAB4 #6  dx 4 dy 1  Fcheck b7=1
        fcb     7,0,1,$80,3      ; 157  CHTAB4 #7  dx 0 dy 1  Fcheck b7=1
        fcb     8,0,1,$CD,3      ; 158  CHTAB4 #8  dx 0 dy 1  Fcheck b7=1
        fcb     9,7,1,$80,3      ; 159  CHTAB4 #9  dx 7 dy 1  Fcheck b7=1
        fcb     10,3,1,$00,3      ; 160  CHTAB4 #10  dx 3 dy 1  Fcheck b7=0
        fcb     11,2,1,$00,3      ; 161  CHTAB4 #11  dx 2 dy 1  Fcheck b7=0
        fcb     12,2,1,$00,3      ; 162  CHTAB4 #12  dx 2 dy 1  Fcheck b7=0
        fcb     13,0,1,$00,3      ; 163  CHTAB4 #13  dx 0 dy 1  Fcheck b7=0
        fcb     14,0,1,$80,3      ; 164  CHTAB4 #14  dx 0 dy 1  Fcheck b7=1
        fcb     15,2,1,$C3,3      ; 165  CHTAB4 #15  dx 2 dy 1  Fcheck b7=1
        fcb     16,255,1,$48,3      ; 166  CHTAB4 #16  dx -1 dy 1  Fcheck b7=0
        fcb     17,7,1,$80,3      ; 167  CHTAB4 #17  dx 7 dy 1  Fcheck b7=1
        fcb     18,3,1,$80,3      ; 168  CHTAB4 #18  dx 3 dy 1  Fcheck b7=1
        fcb     8,0,1,$80,3      ; 169  CHTAB4 #8  dx 0 dy 1  Fcheck b7=1
        fcb     19,0,1,$CD,3      ; 170  CHTAB4 #19  dx 0 dy 1  Fcheck b7=1
        fcb     20,0,1,$CD,3      ; 171  CHTAB4 #20  dx 0 dy 1  Fcheck b7=1
        fcb     21,0,0,$C6,3      ; 172  CHTAB4 #21  dx 0 dy 0  Fcheck b7=1
        fcb     22,0,0,$46,3      ; 173  CHTAB4 #22  dx 0 dy 0  Fcheck b7=0
        fcb     23,0,0,$C5,3      ; 174  CHTAB4 #23  dx 0 dy 0  Fcheck b7=1
        fcb     23,0,0,$C5,3      ; 175  CHTAB4 #23  dx 0 dy 0  Fcheck b7=1
        fcb     23,0,0,$C5,3      ; 176  CHTAB4 #23  dx 0 dy 0  Fcheck b7=1
        fcb     25,0,3,$8A,3      ; 177  CHTAB4 #25  dx 0 dy 3  Fcheck b7=1
        fcb     26,4,4,$87,3      ; 178  CHTAB4 #26  dx 4 dy 4  Fcheck b7=1
        fcb     27,254,1,$44,3      ; 179  CHTAB4 #27  dx -2 dy 1  Fcheck b7=0
        fcb     28,254,1,$44,3      ; 180  CHTAB4 #28  dx -2 dy 1  Fcheck b7=0
        fcb     29,254,1,$44,3      ; 181  CHTAB4 #29  dx -2 dy 1  Fcheck b7=0
        fcb     30,254,2,$47,3      ; 182  CHTAB4 #30  dx -2 dy 2  Fcheck b7=0
        fcb     31,254,2,$4A,3      ; 183  CHTAB4 #31  dx -2 dy 2  Fcheck b7=0
        fcb     0,0,0,0,0           ; 184 (blank)
        fcb     32,3,4,$C9,3      ; 185  CHTAB4 #32  dx 3 dy 4  Fcheck b7=1
        fcb     0,0,0,0,0           ; 186 (blank)
        fcb     0,0,0,0,0           ; 187 (blank)
        fcb     0,0,0,0,0           ; 188 (blank)
        fcb     0,0,0,0,0           ; 189 (blank)
