* chtab4shad_026_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 12 rows x 14 bytes, 201 segment bytes
*
chtab4shad_026_p0:
        fcb     12,14  ; height, width in bytes
        fcb     $43,$C2,$F0,$0A,$3F,$80,$49,$00,$42,$C1,$FC,$03
        fcb     $81,$EA,$C1,$3F,$80,$49,$00,$42,$C1,$FC,$03,$81
        fcb     $FE,$C1,$03,$A8,$42,$C1,$C0,$3F,$46,$00,$42,$C1
        fcb     $F0,$0F,$82,$FF,$EA,$C1,$3F,$80,$41,$C2,$C0,$3F
        fcb     $0F,$F0,$45,$00,$C1,$FC,$03,$84,$FF,$FF,$FF,$EA
        fcb     $C2,$3F,$80,$FC,$03,$82,$FF,$FF,$C1,$0F,$F0,$44
        fcb     $00,$C1,$F0,$0F,$84,$FE,$AF,$FF,$EA,$C2,$3F,$80
        fcb     $F0,$0F,$83,$FF,$FF,$FF,$44,$00,$85,$FE,$AF,$FE
        fcb     $AA,$FF,$C2,$3F,$80,$F0,$0F,$84,$FF,$FF,$FF,$FF
        fcb     $C1,$3F,$C0,$42,$00,$8D,$FF,$FF,$EA,$FF,$AA,$AF
        fcb     $FF,$FF,$EA,$AA,$FE,$AA,$FF,$41,$00,$8D,$FF,$FF
        fcb     $EA,$FF,$AA,$AF,$FF,$FF,$EA,$AF,$FE,$AA,$FF,$41
        fcb     $00,$8D,$FF,$FF,$FE,$AF,$AA,$AF,$FF,$FF,$EA,$AF
        fcb     $FE,$AA,$7F,$C1,$03,$FC,$00,$43,$C1,$F0,$0A,$82
        fcb     $AF,$FE,$C1,$03,$A8,$41,$85,$FF,$FF,$FE,$AF,$FF
        fcb     $C1,$03,$FC,$00,$42,$C1,$F0,$0A,$82,$AA,$AA,$C1
        fcb     $3F,$80,$81,$AA,$C1,$3F,$80,$46,$00
