* chtab4shad_025_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 27 rows x 11 bytes, 372 segment bytes
*
chtab4shad_025_p0:
        fcb     27,11  ; height, width in bytes
        fcb     $45,$C1,$F0,$03,$81,$FF,$44,$00,$44,$C1,$FC,$00
        fcb     $82,$FF,$EA,$C1,$0F,$80,$43,$00,$44,$83,$EF,$EA
        fcb     $3F,$C1,$03,$F0,$43,$00,$43,$C1,$FC,$00,$84,$FF
        fcb     $FE,$AA,$FC,$43,$00,$43,$C1,$F0,$03,$84,$FF,$FE
        fcb     $AA,$FC,$43,$00,$43,$C1,$F0,$03,$84,$FF,$FE,$AA
        fcb     $FC,$43,$00,$43,$C1,$F0,$03,$84,$FF,$FE,$AA,$FF
        fcb     $C1,$3F,$00,$42,$00,$43,$C1,$FC,$00,$84,$FF,$F7
        fcb     $EA,$FF,$C1,$3F,$00,$42,$00,$44,$84,$3F,$EF,$EA
        fcb     $FF,$C1,$0F,$C0,$42,$00,$44,$C1,$C0,$0A,$83,$EA
        fcb     $FF,$AF,$C1,$0F,$C0,$42,$00,$44,$C2,$C0,$0A,$30
        fcb     $83,$82,$EA,$FF,$C1,$0F,$C0,$42,$00,$44,$C2,$C0
        fcb     $0A,$30,$83,$82,$EA,$FF,$C1,$0F,$C0,$42,$00,$44
        fcb     $C1,$C0,$0A,$83,$EA,$FF,$FF,$C1,$03,$F0,$42,$00
        fcb     $44,$84,$3F,$FF,$EA,$FF,$C1,$03,$F0,$42,$00,$43
        fcb     $C1,$F0,$0F,$84,$FF,$FF,$EA,$FF,$C1,$03,$F0,$42
        fcb     $00,$43,$85,$FF,$FF,$EA,$FF,$3F,$C1,$03,$F0,$42
        fcb     $00,$42,$C1,$F0,$03,$85,$FF,$FF,$EA,$FF,$FF,$C2
        fcb     $03,$F0,$03,$10,$41,$00,$42,$C1,$F0,$03,$82,$FF
        fcb     $FF,$C1,$3C,$C0,$84,$AA,$FF,$F0,$FC,$41,$00,$42
        fcb     $C1,$F0,$03,$82,$FF,$E8,$41,$C1,$C0,$0A,$83,$F0
        fcb     $FF,$FF,$C1,$0F,$C0,$00,$42,$C1,$C0,$0A,$81,$FC
        fcb     $C1,$C0,$08,$41,$C1,$C0,$0A,$82,$FF,$F0,$C2,$0C
        fcb     $80,$0F,$80,$00,$C2,$F0,$01,$3C,$00,$81,$A8,$41
        fcb     $C1,$C0,$08,$41,$C1,$C0,$0A,$82,$FF,$FF,$C1,$0F
        fcb     $C0,$41,$00,$C1,$F0,$03,$81,$FF,$C1,$03,$F0,$41
        fcb     $C1,$C0,$08,$41,$C1,$F0,$03,$82,$FF,$FF,$C1,$0F
        fcb     $C0,$41,$00,$C1,$FC,$00,$81,$FF,$C1,$0F,$C0,$44
        fcb     $82,$FF,$FF,$C1,$0F,$C0,$41,$00,$41,$81,$3F,$C1
        fcb     $0F,$C0,$44,$82,$FF,$FF,$C1,$0F,$C0,$41,$00,$47
        fcb     $82,$3F,$FF,$C1,$3F,$00,$41,$00,$47,$C2,$C0,$0F
        fcb     $03,$FC,$42,$00,$47,$C2,$F0,$03,$03,$F0,$42,$00
