* chtab4shad_030_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 22 rows x 6 bytes, 225 segment bytes
*
chtab4shad_030_p0:
        fcb     22,6  ; height, width in bytes
        fcb     $C1,$F0,$01,$81,$7F,$C1,$03,$F0,$43,$00,$C1,$F0
        fcb     $03,$82,$FF,$FC,$43,$00,$C1,$F0,$03,$82,$FF,$FF
        fcb     $C1,$3F,$00,$42,$00,$C1,$F0,$03,$82,$FF,$FF,$C1
        fcb     $3F,$00,$42,$00,$41,$82,$3F,$FF,$C1,$3F,$00,$42
        fcb     $00,$41,$C1,$FC,$03,$81,$FF,$C1,$3F,$00,$42,$00
        fcb     $41,$82,$15,$7F,$C1,$0F,$F0,$42,$00,$41,$83,$57
        fcb     $FC,$15,$42,$00,$41,$83,$57,$FF,$15,$C1,$3F,$00
        fcb     $41,$00,$42,$82,$17,$FF,$C1,$0F,$C0,$41,$00,$41
        fcb     $C1,$FC,$00,$82,$FF,$FF,$C1,$0F,$C0,$41,$00,$41
        fcb     $C1,$FC,$03,$82,$FF,$FF,$C1,$03,$F0,$41,$00,$41
        fcb     $C1,$FC,$01,$83,$FF,$FC,$57,$41,$00,$41,$C1,$FC
        fcb     $01,$83,$FF,$FC,$57,$41,$00,$42,$83,$7F,$FF,$15
        fcb     $C1,$3F,$00,$00,$42,$83,$7F,$FF,$15,$C1,$3F,$00
        fcb     $00,$41,$C1,$FC,$00,$83,$7F,$FF,$F5,$C1,$3F,$C0
        fcb     $00,$41,$C1,$C0,$0F,$83,$7F,$FF,$F5,$C1,$3F,$C0
        fcb     $00,$41,$84,$3F,$F5,$57,$FF,$C1,$3F,$00,$00,$C1
        fcb     $FC,$00,$84,$FF,$F5,$57,$FF,$C1,$3F,$00,$00,$C1
        fcb     $F0,$03,$84,$F5,$55,$7F,$FC,$41,$00,$C1,$FC,$00
        fcb     $83,$7F,$FF,$F5,$C1,$3F,$00,$41,$00
