* chtab4shad_028_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 33 rows x 4 bytes, 283 segment bytes
*
chtab4shad_028_p0:
        fcb     33,4  ; height, width in bytes
        fcb     $C2,$F0,$0F,$0F,$F0,$42,$00,$81,$FF,$C1,$03,$FC
        fcb     $42,$00,$82,$FF,$FF,$42,$00,$C1,$FC,$03,$81,$FF
        fcb     $42,$00,$C1,$C0,$15,$81,$7F,$42,$00,$C1,$C0,$15
        fcb     $81,$7F,$42,$00,$C1,$C0,$17,$81,$FF,$42,$00,$C1
        fcb     $FC,$01,$81,$7F,$C1,$0F,$F0,$41,$00,$C1,$FC,$01
        fcb     $81,$7F,$C1,$0F,$F0,$41,$00,$C1,$FC,$01,$81,$7F
        fcb     $C1,$03,$FC,$41,$00,$C1,$FC,$01,$81,$7F,$C1,$03
        fcb     $FC,$41,$00,$C1,$FC,$01,$82,$7F,$FF,$41,$00,$C1
        fcb     $FC,$01,$82,$7F,$FF,$41,$00,$C1,$FC,$01,$82,$7F
        fcb     $FF,$41,$00,$C1,$FC,$01,$82,$7F,$FF,$C1,$3F,$C0
        fcb     $00,$C1,$FC,$01,$82,$7F,$FF,$C1,$0F,$F0,$00,$C1
        fcb     $FC,$01,$82,$7F,$FF,$C1,$3F,$C0,$00,$C1,$FC,$01
        fcb     $82,$7F,$FF,$C1,$3F,$C0,$00,$C1,$FC,$01,$82,$7F
        fcb     $FF,$C1,$0F,$F0,$00,$C1,$FC,$01,$82,$7F,$FF,$C1
        fcb     $0F,$F0,$00,$C1,$FC,$01,$82,$7F,$FF,$C1,$3F,$C0
        fcb     $00,$C1,$FC,$01,$82,$7F,$FF,$C1,$3F,$C0,$00,$C1
        fcb     $FC,$03,$82,$FF,$FF,$41,$00,$C1,$F0,$0F,$81,$FF
        fcb     $C1,$03,$FC,$41,$00,$C1,$F0,$0F,$81,$FF,$C1,$0F
        fcb     $F0,$41,$00,$82,$7F,$FF,$C1,$3F,$C0,$41,$00,$82
        fcb     $7F,$FF,$C1,$3F,$C0,$41,$00,$82,$FF,$FF,$C1,$0F
        fcb     $F0,$41,$00,$82,$7F,$FF,$C1,$03,$FC,$41,$00,$C1
        fcb     $FC,$03,$81,$FF,$C1,$03,$FC,$41,$00,$41,$C2,$C0
        fcb     $3F,$03,$FC,$41,$00,$41,$C1,$C0,$3F,$81,$FF,$41
        fcb     $00,$41,$82,$FF,$FF,$41,$00
