* chtab4shad_031_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 19 rows x 10 bytes, 241 segment bytes
*
chtab4shad_031_p0:
        fcb     19,10  ; height, width in bytes
        fcb     $44,$C2,$F0,$0A,$3F,$80,$44,$00,$44,$C2,$F0,$0A
        fcb     $3F,$80,$44,$00,$44,$C1,$F0,$0A,$81,$F5,$44,$00
        fcb     $45,$C1,$C0,$15,$44,$00,$45,$C2,$C0,$15,$0F,$50
        fcb     $43,$00,$45,$C1,$C0,$15,$81,$55,$43,$00,$45,$C1
        fcb     $FC,$01,$81,$55,$43,$00,$46,$C1,$C0,$3E,$81,$AF
        fcb     $C1,$0F,$F0,$41,$00,$45,$C1,$FC,$03,$83,$AF,$FF
        fcb     $FE,$C1,$3F,$C0,$00,$45,$C1,$FC,$03,$83,$AF,$FF
        fcb     $FE,$C1,$0F,$F0,$00,$45,$C1,$F0,$0F,$83,$AF,$FF
        fcb     $FE,$C1,$0F,$F0,$00,$45,$84,$FF,$EA,$AF,$FF,$C1
        fcb     $0F,$F0,$00,$41,$C2,$FC,$03,$0F,$F0,$41,$C1,$CF
        fcb     $10,$84,$FF,$EA,$AF,$FF,$C1,$3F,$C0,$00,$41,$C1
        fcb     $FC,$03,$81,$FF,$C2,$FC,$01,$0F,$50,$81,$FF,$41
        fcb     $C1,$C0,$3F,$81,$FF,$41,$00,$42,$C1,$FC,$01,$83
        fcb     $57,$FF,$55,$C3,$03,$FC,$C0,$3F,$0F,$F0,$41,$00
        fcb     $42,$C1,$C0,$15,$82,$55,$57,$C2,$03,$FC,$C0,$3F
        fcb     $81,$FF,$C1,$03,$FC,$41,$00,$41,$C1,$F0,$0F,$86
        fcb     $55,$55,$7F,$FF,$55,$55,$C1,$03,$FC,$41,$00,$41
        fcb     $C1,$F0,$0F,$81,$F7,$C2,$03,$E8,$C0,$15,$83,$57
        fcb     $FF,$55,$C1,$03,$FC,$41,$00,$42,$C1,$C0,$17,$83
        fcb     $F5,$55,$EA,$C1,$0F,$50,$81,$FF,$C1,$3F,$C0,$41
        fcb     $00
