* chtab4shad_005_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 35 rows x 11 bytes, 428 segment bytes
*
chtab4shad_005_p0:
        fcb     35,11  ; height, width in bytes
        fcb     $42,$C1,$FC,$03,$81,$FF,$47,$00,$42,$C1,$C0,$3F
        fcb     $81,$FF,$C1,$3F,$C0,$46,$00,$42,$C1,$C0,$3F,$81
        fcb     $FF,$C1,$3F,$C0,$46,$00,$42,$C1,$FC,$03,$81,$FF
        fcb     $C1,$3F,$C0,$46,$00,$42,$C1,$F0,$0A,$81,$AF,$C1
        fcb     $3F,$C0,$46,$00,$42,$C2,$F0,$0A,$03,$A8,$47,$00
        fcb     $42,$C1,$F0,$0A,$81,$AF,$C1,$03,$FC,$46,$00,$43
        fcb     $82,$AF,$FF,$C1,$3F,$C0,$45,$00,$43,$C1,$F0,$0A
        fcb     $81,$AF,$C1,$03,$FC,$45,$00,$43,$C1,$F0,$0A,$82
        fcb     $AF,$FE,$C1,$3F,$80,$44,$00,$43,$C1,$F0,$0A,$82
        fcb     $AA,$FE,$C1,$03,$A8,$44,$00,$43,$C1,$F0,$0A,$82
        fcb     $AA,$FF,$C1,$03,$E8,$44,$00,$44,$83,$FF,$EA,$AA
        fcb     $C1,$3F,$80,$43,$00,$44,$82,$AA,$AF,$C2,$3F,$C0
        fcb     $03,$A8,$43,$00,$44,$82,$AA,$AF,$C2,$0F,$F0,$03
        fcb     $A8,$43,$00,$43,$84,$AA,$AA,$AF,$FE,$C1,$03,$A8
        fcb     $43,$00,$43,$84,$AA,$AA,$FF,$FF,$44,$00,$43,$84
        fcb     $AA,$FF,$FF,$FF,$C1,$3F,$C0,$43,$00,$43,$C1,$F0
        fcb     $0F,$83,$FF,$FF,$FF,$C1,$3F,$C0,$43,$00,$43,$84
        fcb     $FF,$FF,$FF,$FF,$C1,$3F,$C0,$43,$00,$42,$C1,$FC
        fcb     $03,$84,$FF,$FF,$FF,$FF,$44,$00,$42,$C1,$F0,$0F
        fcb     $83,$FF,$FF,$FF,$C2,$3F,$C0,$0F,$F0,$43,$00,$42
        fcb     $C1,$C0,$3F,$82,$FF,$FF,$41,$C2,$C0,$3F,$0F,$F0
        fcb     $43,$00,$42,$C1,$C0,$3F,$81,$FF,$42,$81,$FF,$C1
        fcb     $0F,$F0,$43,$00,$42,$81,$FF,$C1,$0F,$F0,$42,$82
        fcb     $FF,$FF,$43,$00,$42,$81,$FF,$C1,$0F,$F0,$42,$C1
        fcb     $C0,$3F,$81,$FF,$C1,$0F,$F0,$42,$00,$42,$81,$FF
        fcb     $C1,$0F,$F0,$42,$C1,$F0,$0F,$82,$FF,$FF,$C1,$3F
        fcb     $C0,$41,$00,$42,$81,$FF,$C1,$3F,$C0,$42,$C1,$FC
        fcb     $03,$83,$FF,$FF,$FF,$C1,$3F,$C0,$00,$41,$C1,$FC
        fcb     $03,$81,$FF,$44,$83,$FF,$FF,$FF,$C1,$0F,$F0,$00
        fcb     $41,$C1,$FC,$03,$81,$FF,$45,$C1,$FC,$03,$81,$FF
        fcb     $C1,$0F,$F0,$00,$41,$C1,$F0,$0F,$81,$FF,$46,$C2
        fcb     $F0,$0F,$0F,$F0,$00,$41,$C2,$F0,$0F,$03,$FC,$46
        fcb     $C2,$F0,$0F,$0F,$F0,$00,$C1,$FC,$03,$81,$FF,$C1
        fcb     $03,$FC,$46,$C2,$FC,$03,$0F,$F0,$00,$C1,$FC,$03
        fcb     $81,$FF,$C1,$03,$FC,$46,$C2,$FC,$03,$3F,$C0,$00
        fcb     $41,$C2,$C0,$3F,$3F,$C0,$48,$00
