* chtab4shad_009_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 33 rows x 11 bytes, 407 segment bytes
*
chtab4shad_009_p0:
        fcb     33,11  ; height, width in bytes
        fcb     $43,$C1,$FC,$03,$81,$FF,$46,$00,$43,$C1,$C0,$3F
        fcb     $81,$FF,$C1,$3F,$C0,$45,$00,$43,$C1,$C0,$3F,$81
        fcb     $FF,$C1,$3F,$C0,$45,$00,$43,$C1,$FC,$03,$81,$FF
        fcb     $C1,$3F,$C0,$45,$00,$43,$C1,$F0,$0A,$81,$AF,$C1
        fcb     $3F,$C0,$45,$00,$43,$C1,$F0,$0A,$81,$AF,$C1,$03
        fcb     $FC,$45,$00,$44,$82,$FF,$FF,$C1,$3F,$C0,$44,$00
        fcb     $41,$81,$AA,$C2,$3F,$80,$F0,$0A,$82,$AA,$FF,$C1
        fcb     $03,$E8,$44,$00,$41,$C1,$F0,$0A,$84,$AA,$AA,$AA
        fcb     $FF,$C1,$03,$E8,$44,$00,$41,$C1,$F0,$0A,$85,$AA
        fcb     $AA,$FF,$FE,$AA,$C1,$3F,$80,$43,$00,$43,$84,$AA
        fcb     $AA,$FF,$FE,$C1,$3F,$80,$43,$00,$44,$C1,$F0,$0F
        fcb     $82,$FF,$FF,$C1,$3F,$C0,$43,$00,$44,$C1,$F0,$0F
        fcb     $82,$FF,$FF,$44,$00,$44,$C1,$F0,$0F,$82,$FF,$FF
        fcb     $44,$00,$44,$C1,$FC,$03,$82,$FF,$FF,$44,$00,$44
        fcb     $C1,$FC,$03,$82,$FF,$FF,$C1,$3F,$C0,$43,$00,$44
        fcb     $C1,$FC,$03,$82,$FF,$FF,$C1,$0F,$F0,$43,$00,$44
        fcb     $C1,$F0,$0F,$82,$FF,$FF,$C1,$0F,$F0,$43,$00,$44
        fcb     $83,$FF,$FF,$FF,$C1,$0F,$F0,$43,$00,$43,$C1,$C0
        fcb     $3F,$83,$FF,$FF,$FF,$C1,$0F,$F0,$43,$00,$43,$84
        fcb     $FF,$FF,$FF,$FF,$C1,$0F,$F0,$43,$00,$42,$C1,$FC
        fcb     $03,$83,$FF,$FF,$FF,$C2,$F0,$0F,$0F,$F0,$43,$00
        fcb     $42,$C1,$F0,$0F,$82,$FF,$FF,$C1,$3F,$C0,$81,$FF
        fcb     $C1,$0F,$F0,$43,$00,$42,$C1,$F0,$0F,$81,$FF,$42
        fcb     $81,$FF,$C1,$0F,$F0,$43,$00,$42,$C2,$F0,$0F,$03
        fcb     $FC,$42,$81,$FF,$C1,$0F,$F0,$43,$00,$42,$C2,$F0
        fcb     $0F,$03,$FC,$42,$C1,$C0,$3F,$81,$FF,$C1,$0F,$F0
        fcb     $42,$00,$42,$C2,$C0,$3F,$03,$FC,$42,$C1,$C0,$3F
        fcb     $82,$FF,$FF,$C1,$3F,$C0,$41,$00,$42,$C2,$C0,$3F
        fcb     $0F,$F0,$42,$C1,$FC,$03,$82,$FF,$FF,$C1,$03,$FC
        fcb     $41,$00,$42,$C2,$C0,$3F,$3F,$C0,$43,$C1,$FC,$03
        fcb     $82,$FF,$EF,$C1,$3F,$C0,$00,$42,$C2,$C0,$3F,$3F
        fcb     $C0,$45,$81,$AF,$C1,$3F,$C0,$00,$42,$81,$AF,$46
        fcb     $C1,$F0,$0F,$41,$00,$41,$C1,$F0,$0A,$81,$FF,$46
        fcb     $C1,$C0,$3F,$41,$00,$41,$82,$FF,$FF,$48,$00
