* chtab4shad_027_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 38 rows x 4 bytes, 333 segment bytes
*
chtab4shad_027_p0:
        fcb     38,4  ; height, width in bytes
        fcb     $C2,$F0,$0F,$03,$FC,$42,$00,$82,$FF,$FF,$42,$00
        fcb     $82,$FF,$FF,$C1,$3F,$C0,$41,$00,$C1,$FC,$03,$81
        fcb     $FF,$C1,$3F,$C0,$41,$00,$C1,$C0,$17,$81,$FF,$42
        fcb     $00,$C1,$C0,$15,$81,$7F,$42,$00,$C2,$C0,$15,$0F
        fcb     $50,$42,$00,$C1,$FC,$03,$81,$FF,$42,$00,$C1,$FC
        fcb     $01,$81,$7F,$42,$00,$C1,$FC,$01,$81,$7F,$C1,$3F
        fcb     $C0,$41,$00,$C1,$FC,$01,$81,$7F,$C1,$0F,$F0,$41
        fcb     $00,$C1,$FC,$01,$81,$7F,$C1,$03,$FC,$41,$00,$C1
        fcb     $FC,$01,$81,$7F,$C1,$03,$FC,$41,$00,$C1,$FC,$01
        fcb     $81,$7F,$C1,$03,$FC,$41,$00,$C1,$FC,$01,$82,$7F
        fcb     $FF,$41,$00,$C1,$FC,$01,$82,$7F,$FF,$41,$00,$C1
        fcb     $FC,$01,$82,$7F,$FF,$41,$00,$C1,$FC,$01,$82,$7F
        fcb     $FF,$C1,$3F,$C0,$00,$C1,$FC,$01,$82,$7F,$FF,$C1
        fcb     $3F,$C0,$00,$C1,$FC,$01,$82,$7F,$FF,$41,$00,$C1
        fcb     $FC,$01,$82,$7F,$FF,$C1,$3F,$C0,$00,$C1,$FC,$01
        fcb     $82,$7F,$FF,$C1,$3F,$C0,$00,$C1,$FC,$01,$82,$7F
        fcb     $FF,$C1,$3F,$C0,$00,$C1,$FC,$03,$82,$FF,$FF,$C1
        fcb     $3F,$C0,$00,$C1,$FC,$03,$82,$FF,$FF,$41,$00,$C1
        fcb     $FC,$03,$81,$FF,$C1,$03,$FC,$41,$00,$C1,$FC,$03
        fcb     $81,$FF,$C1,$0F,$F0,$41,$00,$C1,$FC,$03,$81,$FF
        fcb     $C1,$0F,$F0,$41,$00,$C1,$F0,$0F,$81,$FF,$C1,$3F
        fcb     $C0,$41,$00,$C1,$F0,$0F,$81,$FF,$C1,$3F,$C0,$41
        fcb     $00,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$41,$00,$C1
        fcb     $FC,$03,$81,$FF,$C1,$0F,$F0,$41,$00,$41,$81,$FF
        fcb     $C1,$03,$FC,$41,$00,$41,$81,$FF,$C1,$03,$FC,$41
        fcb     $00,$41,$C2,$C0,$3F,$03,$FC,$41,$00,$41,$C2,$FC
        fcb     $03,$03,$FC,$41,$00,$41,$C1,$C0,$3F,$81,$FF,$41
        fcb     $00,$41,$C1,$F0,$0F,$81,$FF,$41,$00
