* chtab4shad_032_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 10 rows x 11 bytes, 164 segment bytes
*
chtab4shad_032_p0:
        fcb     10,11  ; height, width in bytes
        fcb     $45,$C1,$F0,$01,$82,$7F,$FC,$43,$00,$44,$C1,$F0
        fcb     $01,$83,$7F,$FF,$55,$C1,$3F,$00,$42,$00,$44,$C1
        fcb     $F0,$01,$85,$7F,$FF,$0F,$FC,$55,$41,$00,$43,$C1
        fcb     $F0,$01,$86,$FF,$FE,$FF,$FF,$55,$57,$C1,$3F,$00
        fcb     $00,$42,$88,$F5,$7F,$FF,$FF,$15,$55,$55,$7F,$C1
        fcb     $0F,$C0,$00,$41,$89,$F5,$7E,$FF,$FF,$55,$55,$55
        fcb     $7F,$3F,$C1,$0F,$C0,$00,$41,$81,$3F,$C1,$0F,$C0
        fcb     $41,$C2,$03,$10,$C0,$3F,$84,$FF,$FE,$AF,$FF,$C1
        fcb     $0F,$C0,$00,$C1,$F0,$03,$82,$FF,$55,$C1,$0C,$50
        fcb     $81,$A8,$C1,$C0,$3F,$84,$FF,$F0,$AF,$FF,$C1,$0F
        fcb     $C0,$00,$C1,$F0,$03,$82,$FF,$55,$C1,$0C,$50,$81
        fcb     $A8,$C1,$C0,$10,$84,$FF,$F0,$AF,$FF,$C1,$3F,$00
        fcb     $00,$C2,$F0,$01,$3C,$01,$86,$55,$57,$FF,$FC,$55
        fcb     $55,$C1,$C0,$0F,$81,$FC,$41,$00
