* chtab4shad_025_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 27 rows x 11 bytes, 376 segment bytes
*
chtab4shad_025_p0:
        fcb     27,11  ; height, width in bytes
        fcb     $45,$C1,$FC,$03,$81,$FF,$44,$00,$45,$82,$FF,$EA
        fcb     $C1,$3F,$80,$43,$00,$44,$C1,$C0,$3F,$82,$EF,$EA
        fcb     $C1,$0F,$F0,$43,$00,$44,$83,$FE,$AA,$FF,$C1,$03
        fcb     $FC,$43,$00,$43,$C1,$FC,$03,$83,$FE,$AA,$FF,$C1
        fcb     $03,$FC,$43,$00,$43,$C1,$FC,$03,$83,$FE,$AA,$FF
        fcb     $C1,$03,$FC,$43,$00,$43,$C1,$FC,$03,$84,$FF,$FE
        fcb     $AA,$FF,$43,$00,$44,$84,$FF,$F7,$EA,$FF,$43,$00
        fcb     $44,$C1,$C0,$3F,$83,$EA,$FF,$EF,$C1,$3F,$C0,$42
        fcb     $00,$44,$C1,$F0,$0A,$83,$EA,$FF,$AF,$C1,$3F,$C0
        fcb     $42,$00,$44,$C2,$F0,$0A,$3C,$83,$82,$EA,$FF,$C1
        fcb     $3F,$C0,$42,$00,$44,$C2,$F0,$0A,$3C,$83,$82,$EA
        fcb     $FF,$C1,$3F,$C0,$42,$00,$44,$C1,$F0,$0A,$83,$EA
        fcb     $FF,$FF,$C1,$0F,$F0,$42,$00,$44,$C1,$C0,$3F,$83
        fcb     $EA,$FF,$FF,$C1,$0F,$F0,$42,$00,$43,$C1,$F0,$0F
        fcb     $84,$FF,$FF,$EA,$FF,$C1,$0F,$F0,$42,$00,$43,$C1
        fcb     $C0,$3F,$84,$FF,$FF,$EA,$FF,$C1,$0F,$F0,$42,$00
        fcb     $42,$C1,$FC,$03,$85,$FF,$FF,$EA,$FF,$FF,$C2,$0F
        fcb     $F0,$CF,$10,$41,$00,$42,$C1,$FC,$03,$82,$FF,$FF
        fcb     $C1,$3F,$C0,$82,$AA,$FF,$C2,$0F,$F0,$03,$FC,$41
        fcb     $00,$42,$C1,$FC,$03,$81,$FF,$C1,$03,$E8,$41,$C1
        fcb     $F0,$0A,$81,$FF,$C1,$0F,$F0,$81,$FF,$C1,$3F,$C0
        fcb     $00,$42,$C3,$F0,$0A,$03,$FC,$F3,$08,$41,$C1,$F0
        fcb     $0A,$81,$FF,$C3,$0F,$F0,$3F,$80,$3F,$80,$00,$C1
        fcb     $FC,$01,$41,$C1,$03,$A8,$41,$C1,$F3,$08,$41,$C1
        fcb     $F0,$0A,$82,$FF,$FF,$C1,$3F,$C0,$41,$00,$C1,$FC
        fcb     $03,$81,$FF,$C1,$0F,$F0,$41,$C1,$F3,$08,$41,$C1
        fcb     $FC,$03,$82,$FF,$FF,$C1,$3F,$C0,$41,$00,$41,$81
        fcb     $FF,$C1,$3F,$C0,$44,$82,$FF,$FF,$C1,$3F,$C0,$41
        fcb     $00,$41,$C2,$C0,$3F,$3F,$C0,$44,$82,$FF,$FF,$C1
        fcb     $3F,$C0,$41,$00,$47,$C1,$C0,$3F,$81,$FF,$42,$00
        fcb     $47,$C2,$F0,$0F,$03,$FC,$42,$00,$47,$C2,$FC,$03
        fcb     $0F,$F0,$42,$00
