* chtab3_040_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 6 rows x 6 bytes, 49 segment bytes
*
chtab3_040_p0:
        fcb     6,6  ; height, width in bytes
        fcb     $44,$C2,$C0,$0F,$3F,$00,$00,$44,$C2,$F0,$03,$3F
        fcb     $C0,$00,$43,$C1,$F0,$0F,$81,$FF,$C1,$3F,$C0,$00
        fcb     $42,$C1,$C0,$0F,$81,$FC,$C2,$F0,$03,$3F,$C0,$00
        fcb     $41,$82,$3F,$FC,$43,$00,$81,$7F,$C1,$03,$F0,$44
        fcb     $00
