* chtab3_039_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 18 rows x 6 bytes, 141 segment bytes
*
chtab3_039_p0:
        fcb     18,6  ; height, width in bytes
        fcb     $C2,$FC,$00,$0F,$80,$44,$00,$C2,$FC,$00,$0F,$80
        fcb     $44,$00,$41,$C1,$03,$10,$44,$00,$41,$C1,$03,$10
        fcb     $44,$00,$41,$C1,$03,$3C,$44,$00,$41,$C1,$03,$3C
        fcb     $44,$00,$41,$C2,$C0,$0F,$3F,$00,$43,$00,$41,$C2
        fcb     $C0,$0F,$3F,$00,$43,$00,$41,$C2,$FC,$03,$0F,$C0
        fcb     $43,$00,$41,$C2,$FC,$03,$0F,$C0,$43,$00,$41,$C2
        fcb     $FC,$00,$03,$F0,$43,$00,$41,$C2,$FC,$00,$03,$F0
        fcb     $43,$00,$41,$C1,$FC,$00,$81,$FC,$41,$C2,$FC,$00
        fcb     $3F,$80,$00,$42,$81,$3C,$41,$C2,$FC,$00,$3F,$80
        fcb     $00,$42,$81,$3F,$C1,$3F,$00,$42,$00,$42,$C2,$C0
        fcb     $0F,$0F,$C0,$42,$00,$42,$C1,$C0,$0F,$81,$FC,$42
        fcb     $00,$42,$81,$3F,$C1,$0F,$C0,$42,$00
