* chtab3_041_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 12 rows x 5 bytes, 89 segment bytes
*
chtab3_041_p0:
        fcb     12,5  ; height, width in bytes
        fcb     $43,$81,$3F,$C1,$3F,$00,$00,$43,$81,$3F,$C1,$0F
        fcb     $C0,$00,$42,$C1,$FC,$00,$81,$FF,$C1,$3F,$00,$00
        fcb     $42,$C2,$F0,$03,$0F,$C0,$41,$00,$42,$C2,$C0,$0F
        fcb     $3F,$00,$41,$00,$41,$C1,$FC,$00,$81,$FC,$42,$00
        fcb     $41,$C2,$FC,$03,$03,$F0,$42,$00,$41,$C2,$C0,$0F
        fcb     $3F,$00,$42,$00,$41,$C1,$03,$10,$43,$00,$C2,$FC
        fcb     $00,$0F,$80,$43,$00,$C2,$F0,$01,$3F,$00,$43,$00
        fcb     $C1,$C0,$08,$44,$00
