* chtab3_046_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 4 rows x 3 bytes, 25 segment bytes
*
chtab3_046_p0:
        fcb     4,3  ; height, width in bytes
        fcb     $42,$C1,$CF,$10,$00,$41,$C2,$FC,$03,$3F,$C0,$00
        fcb     $41,$C1,$C0,$3F,$41,$00,$C2,$FC,$03,$03,$FC,$41
        fcb     $00
