* chtab3_029_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 9 rows x 2 bytes, 48 segment bytes
*
chtab3_029_p0:
        fcb     9,2  ; height, width in bytes
        fcb     $C2,$F0,$03,$0F,$C0,$00,$C2,$F0,$03,$0F,$C0,$00
        fcb     $C2,$C0,$0F,$3F,$00,$00,$C2,$C0,$0F,$3F,$00,$00
        fcb     $81,$7C,$41,$00,$C1,$03,$10,$41,$00,$C1,$03,$F0
        fcb     $41,$00,$C1,$0F,$80,$41,$00,$C1,$0F,$80,$41,$00
