* chtab3_034_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 7 rows x 2 bytes, 38 segment bytes
*
chtab3_034_p0:
        fcb     7,2  ; height, width in bytes
        fcb     $41,$C1,$C3,$08,$00,$41,$C1,$03,$3C,$00,$C2,$FC
        fcb     $00,$03,$F0,$00,$C2,$FC,$00,$0F,$80,$00,$C2,$F0
        fcb     $03,$0F,$C0,$00,$C2,$C0,$0F,$3F,$00,$00,$81,$FC
        fcb     $41,$00
