* chtab3_026_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 31 rows x 7 bytes, 310 segment bytes
*
chtab3_026_p0:
        fcb     31,7  ; height, width in bytes
        fcb     $81,$7F,$C1,$03,$FC,$45,$00,$82,$FF,$FF,$45,$00
        fcb     $82,$FF,$FF,$45,$00,$83,$FF,$FF,$F7,$C1,$3F,$C0
        fcb     $43,$00,$85,$57,$FF,$FF,$FF,$F5,$42,$00,$C1,$FC
        fcb     $01,$84,$7F,$57,$FF,$FF,$C1,$0F,$F0,$41,$00,$41
        fcb     $C1,$F0,$0F,$84,$57,$FF,$FF,$FF,$41,$00,$41,$C1
        fcb     $F0,$0F,$84,$57,$FF,$FF,$FF,$C1,$3F,$C0,$00,$42
        fcb     $C1,$C0,$17,$83,$FF,$FF,$FF,$C1,$3F,$C0,$00,$42
        fcb     $C1,$C0,$17,$83,$FF,$FF,$FF,$C1,$3F,$C0,$00,$42
        fcb     $C1,$C0,$17,$83,$FF,$FF,$FF,$C1,$3F,$C0,$00,$42
        fcb     $C1,$C0,$15,$41,$82,$FF,$FF,$C1,$3F,$C0,$00,$42
        fcb     $C1,$C0,$15,$41,$82,$FF,$FF,$41,$00,$42,$C1,$C0
        fcb     $15,$41,$82,$FF,$FF,$41,$00,$42,$C1,$C0,$15,$41
        fcb     $82,$FF,$FF,$41,$00,$42,$C2,$FC,$01,$FC,$03,$81
        fcb     $FF,$C1,$03,$FC,$41,$00,$42,$C2,$FC,$01,$FC,$03
        fcb     $81,$FF,$C1,$03,$FC,$41,$00,$42,$C2,$FC,$01,$FC
        fcb     $03,$81,$FF,$C1,$03,$FC,$41,$00,$42,$C2,$FC,$01
        fcb     $FC,$03,$81,$FF,$C1,$03,$FC,$41,$00,$42,$C2,$FC
        fcb     $01,$FC,$03,$81,$FF,$C1,$03,$FC,$41,$00,$42,$C1
        fcb     $FC,$01,$41,$81,$FF,$C1,$03,$FC,$41,$00,$42,$C1
        fcb     $FC,$01,$41,$81,$FF,$C1,$03,$FC,$41,$00,$44,$82
        fcb     $FF,$FF,$41,$00,$44,$82,$FF,$FF,$41,$00,$44,$82
        fcb     $FF,$FF,$41,$00,$44,$C1,$C0,$3F,$81,$FF,$41,$00
        fcb     $44,$C1,$C0,$3F,$81,$FF,$C1,$3F,$C0,$00,$44,$C1
        fcb     $C0,$3F,$81,$FF,$C1,$0F,$F0,$00,$44,$C1,$C0,$3F
        fcb     $81,$FF,$C1,$3F,$C0,$00,$44,$81,$FF,$C1,$0F,$F0
        fcb     $41,$00,$44,$81,$FF,$C1,$3F,$C0,$41,$00
