* chtab3_069_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 3 rows x 7 bytes, 25 segment bytes
*
chtab3_069_p0:
        fcb     3,7  ; height, width in bytes
        fcb     $C1,$F0,$03,$82,$FF,$FF,$C1,$0F,$F0,$43,$00,$43
        fcb     $84,$3F,$FF,$FF,$55,$00,$45,$C1,$C0,$15,$81,$7C
        fcb     $00
