* chtab3_038_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 16 rows x 5 bytes, 113 segment bytes
*
chtab3_038_p0:
        fcb     16,5  ; height, width in bytes
        fcb     $C1,$03,$10,$44,$00,$C1,$C0,$08,$44,$00,$C2,$F0
        fcb     $01,$3F,$00,$43,$00,$C2,$F0,$01,$3F,$00,$43,$00
        fcb     $C2,$FC,$00,$0F,$80,$43,$00,$41,$C1,$03,$10,$43
        fcb     $00,$41,$C1,$C3,$08,$43,$00,$41,$C2,$FC,$01,$3F
        fcb     $00,$42,$00,$41,$C2,$FC,$03,$0F,$C0,$42,$00,$41
        fcb     $C2,$FC,$00,$03,$F0,$42,$00,$42,$81,$3C,$42,$00
        fcb     $42,$81,$3C,$42,$00,$42,$C2,$C0,$0F,$3F,$00,$41
        fcb     $00,$42,$C1,$F0,$03,$81,$C1,$C1,$3F,$00,$00,$42
        fcb     $C1,$FC,$00,$81,$FF,$C1,$3F,$00,$00,$42,$C1,$F0
        fcb     $03,$81,$FC,$41,$00
