* chtab3_041_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 12 rows x 5 bytes, 74 segment bytes
*
chtab3_041_p0:
        fcb     12,5  ; height, width in bytes
        fcb     $43,$C1,$C0,$3F,$41,$00,$43,$C2,$C0,$3F,$3F,$C0
        fcb     $00,$43,$81,$FF,$41,$00,$42,$C2,$FC,$03,$3F,$C0
        fcb     $41,$00,$42,$C1,$F0,$0F,$42,$00,$42,$C1,$03,$FC
        fcb     $42,$00,$41,$C2,$FC,$03,$0F,$F0,$42,$00,$41,$C1
        fcb     $F0,$0F,$43,$00,$41,$C1,$CF,$10,$43,$00,$41,$C1
        fcb     $3F,$80,$43,$00,$C1,$FC,$01,$44,$00,$C1,$F3,$08
        fcb     $44,$00
