* chtab3_076_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 7 rows x 6 bytes, 59 segment bytes
*
chtab3_076_p0:
        fcb     7,6  ; height, width in bytes
        fcb     $C2,$C0,$0F,$03,$F0,$44,$00,$41,$81,$3F,$C1,$0F
        fcb     $C0,$43,$00,$41,$C1,$FC,$00,$81,$FF,$C1,$3F,$00
        fcb     $42,$00,$42,$C1,$F0,$03,$81,$FC,$42,$00,$43,$C1
        fcb     $F0,$0F,$81,$E8,$41,$00,$43,$C1,$FC,$00,$81,$AF
        fcb     $C1,$3F,$00,$00,$44,$C2,$C0,$0F,$3F,$00,$00
