* chtab3_039_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 18 rows x 6 bytes, 124 segment bytes
*
chtab3_039_p0:
        fcb     18,6  ; height, width in bytes
        fcb     $41,$C1,$3F,$80,$44,$00,$41,$C1,$3F,$80,$44,$00
        fcb     $41,$C1,$CF,$10,$44,$00,$41,$C1,$CF,$10,$44,$00
        fcb     $41,$C1,$C3,$3C,$44,$00,$41,$C1,$C3,$3C,$44,$00
        fcb     $41,$C1,$F0,$0F,$44,$00,$41,$C1,$F0,$0F,$44,$00
        fcb     $41,$C2,$FC,$03,$3F,$C0,$43,$00,$41,$C2,$FC,$03
        fcb     $3F,$C0,$43,$00,$42,$C1,$0F,$F0,$43,$00,$42,$C1
        fcb     $0F,$F0,$43,$00,$42,$C1,$03,$FC,$42,$C1,$3F,$80
        fcb     $00,$42,$C1,$C3,$3C,$42,$C1,$3F,$80,$00,$42,$C1
        fcb     $C0,$3F,$43,$00,$42,$C2,$F0,$0F,$3F,$C0,$42,$00
        fcb     $42,$C2,$F0,$0F,$03,$FC,$42,$00,$42,$C2,$C0,$3F
        fcb     $3F,$C0,$42,$00
