* chtab3_067_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 15 rows x 4 bytes, 92 segment bytes
*
chtab3_067_p0:
        fcb     15,4  ; height, width in bytes
        fcb     $C1,$0F,$F0,$43,$00,$C1,$CF,$10,$43,$00,$C1,$03
        fcb     $7C,$43,$00,$C1,$F0,$0F,$43,$00,$C1,$FC,$01,$43
        fcb     $00,$C2,$FC,$03,$3F,$C0,$42,$00,$41,$C1,$0F,$F0
        fcb     $42,$00,$41,$C1,$0F,$F0,$42,$00,$41,$C1,$C3,$3C
        fcb     $42,$00,$41,$C1,$F0,$0F,$42,$00,$41,$C1,$F0,$0F
        fcb     $42,$00,$41,$C2,$FC,$01,$0F,$50,$41,$00,$41,$C1
        fcb     $FC,$01,$81,$55,$C1,$0F,$50,$00,$42,$C1,$C0,$15
        fcb     $41,$00,$42,$C1,$C3,$3C,$41,$00
