* chtab3_075_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 10 rows x 6 bytes, 71 segment bytes
*
chtab3_075_p0:
        fcb     10,6  ; height, width in bytes
        fcb     $44,$C1,$C0,$08,$41,$00,$44,$C2,$C0,$0F,$3F,$00
        fcb     $00,$44,$C2,$C0,$0F,$3F,$C0,$00,$43,$C1,$FC,$00
        fcb     $81,$FC,$41,$00,$43,$C2,$F0,$0F,$0F,$C0,$41,$00
        fcb     $42,$C1,$FC,$00,$81,$FC,$42,$00,$42,$C2,$C0,$0F
        fcb     $0F,$C0,$42,$00,$42,$81,$3C,$43,$00,$41,$C2,$FC
        fcb     $03,$0F,$C0,$43,$00,$41,$C1,$03,$3C,$44,$00
