* chtab3_068_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 8 rows x 7 bytes, 59 segment bytes
*
chtab3_068_p0:
        fcb     8,7  ; height, width in bytes
        fcb     $C2,$FC,$03,$0F,$F0,$45,$00,$41,$C1,$C0,$3F,$45
        fcb     $00,$41,$C2,$FC,$03,$03,$FC,$44,$00,$42,$C2,$F0
        fcb     $0F,$0F,$F0,$43,$00,$43,$81,$FF,$43,$00,$43,$C1
        fcb     $FC,$03,$82,$FE,$AA,$C1,$03,$A8,$00,$44,$C2,$F0
        fcb     $0A,$03,$A8,$41,$00,$45,$C1,$C3,$3C,$41,$00
