* chtab3_025_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 28 rows x 7 bytes, 319 segment bytes
*
chtab3_025_p0:
        fcb     28,7  ; height, width in bytes
        fcb     $C2,$F0,$0F,$03,$FC,$45,$00,$82,$FF,$FF,$41,$C1
        fcb     $C0,$3F,$82,$FF,$FF,$41,$00,$86,$7F,$FF,$FF,$FF
        fcb     $FF,$FF,$C1,$3F,$C0,$00,$86,$FF,$FF,$FF,$FF,$FF
        fcb     $FF,$C1,$0F,$F0,$00,$86,$EA,$FF,$FF,$FF,$FE,$AF
        fcb     $C1,$0F,$F0,$00,$86,$EA,$FF,$FF,$FF,$FE,$AF,$C1
        fcb     $03,$FC,$00,$C1,$3F,$80,$41,$84,$AA,$FF,$FF,$FF
        fcb     $C1,$0F,$F0,$00,$42,$C2,$03,$A8,$C0,$3F,$82,$F7
        fcb     $FF,$C1,$0F,$F0,$00,$42,$C1,$03,$A8,$41,$C1,$C0
        fcb     $17,$81,$FF,$C1,$0F,$F0,$00,$42,$C1,$03,$A8,$41
        fcb     $C1,$C0,$3F,$81,$FF,$C1,$3F,$C0,$00,$42,$81,$AA
        fcb     $C1,$3F,$80,$82,$FF,$FF,$C1,$3F,$C0,$00,$42,$81
        fcb     $AA,$C1,$3F,$80,$82,$FF,$FF,$41,$00,$42,$81,$AA
        fcb     $C1,$3F,$80,$82,$FF,$FF,$41,$00,$42,$81,$AA,$C1
        fcb     $3C,$83,$81,$FF,$C1,$03,$FC,$41,$00,$42,$C2,$3F
        fcb     $80,$3C,$83,$81,$FF,$C1,$03,$FC,$41,$00,$42,$C2
        fcb     $3F,$80,$3C,$83,$81,$FF,$C1,$03,$FC,$41,$00,$42
        fcb     $C2,$3F,$80,$3C,$83,$81,$FF,$C1,$03,$FC,$41,$00
        fcb     $42,$C2,$3F,$80,$3C,$83,$81,$FF,$C1,$03,$FC,$41
        fcb     $00,$42,$C2,$3F,$80,$FC,$03,$82,$FF,$FF,$41,$00
        fcb     $42,$C2,$3F,$80,$FC,$03,$82,$FF,$FF,$41,$00,$42
        fcb     $C1,$3F,$80,$41,$82,$FF,$FF,$C1,$3F,$C0,$00,$42
        fcb     $C1,$3F,$80,$41,$C1,$C0,$3F,$81,$FF,$C1,$3F,$C0
        fcb     $00,$44,$C1,$C0,$3F,$81,$FF,$C1,$3F,$C0,$00,$44
        fcb     $C1,$C0,$3F,$81,$FF,$C1,$0F,$F0,$00,$44,$C1,$C0
        fcb     $3F,$81,$FF,$C1,$0F,$F0,$00,$44,$82,$FF,$FF,$C1
        fcb     $0F,$F0,$00,$43,$C1,$FC,$03,$81,$FF,$42,$00,$43
        fcb     $C2,$C0,$3F,$0F,$F0,$42,$00
