* chtab3_033_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 7 rows x 5 bytes, 45 segment bytes
*
chtab3_033_p0:
        fcb     7,5  ; height, width in bytes
        fcb     $C1,$03,$FC,$44,$00,$C2,$F0,$0F,$0F,$F0,$43,$00
        fcb     $41,$C2,$C0,$3F,$3F,$C0,$42,$00,$42,$81,$FF,$42
        fcb     $00,$42,$C2,$FC,$03,$03,$FC,$41,$00,$43,$C2,$C0
        fcb     $3F,$03,$FC,$00,$44,$C1,$03,$FC,$00
