* chtab3_069_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 3 rows x 7 bytes, 27 segment bytes
*
chtab3_069_p0:
        fcb     3,7  ; height, width in bytes
        fcb     $C1,$FC,$03,$82,$FF,$FF,$C1,$0F,$F0,$43,$00,$43
        fcb     $C1,$C0,$3F,$83,$FF,$55,$FF,$00,$45,$C2,$C0,$15
        fcb     $03,$7C,$00
