* chtab3_027_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 34 rows x 6 bytes, 319 segment bytes
*
chtab3_027_p0:
        fcb     34,6  ; height, width in bytes
        fcb     $C1,$F0,$0F,$81,$FF,$44,$00,$82,$FF,$FF,$C1,$3F
        fcb     $C0,$43,$00,$82,$FF,$FF,$C1,$3F,$C0,$43,$00,$C1
        fcb     $C0,$17,$81,$FF,$C1,$0F,$F0,$43,$00,$C1,$C0,$15
        fcb     $81,$57,$C1,$0F,$F0,$43,$00,$C1,$FC,$01,$81,$57
        fcb     $C1,$0F,$F0,$43,$00,$C1,$FC,$01,$83,$FF,$FF,$7F
        fcb     $C1,$3F,$C0,$41,$00,$41,$C1,$FC,$01,$83,$FF,$FF
        fcb     $7F,$41,$00,$41,$C1,$FC,$01,$83,$FF,$FF,$57,$C1
        fcb     $3F,$C0,$00,$41,$C1,$FC,$01,$83,$FF,$FF,$57,$C1
        fcb     $0F,$F0,$00,$42,$C1,$C0,$17,$82,$FF,$FF,$C1,$03
        fcb     $FC,$00,$42,$C1,$C0,$15,$82,$7F,$FF,$C1,$03,$FC
        fcb     $00,$42,$C1,$FC,$01,$83,$FF,$FF,$7F,$00,$42,$C1
        fcb     $FC,$01,$83,$FF,$FF,$7F,$00,$42,$C1,$FC,$01,$82
        fcb     $7F,$FF,$C1,$03,$FC,$00,$42,$C1,$FC,$01,$82,$7F
        fcb     $FF,$C1,$03,$FC,$00,$42,$C1,$FC,$01,$82,$7F,$FF
        fcb     $C1,$03,$FC,$00,$42,$C1,$FC,$01,$82,$7F,$FF,$C1
        fcb     $03,$FC,$00,$42,$C1,$FC,$01,$82,$7F,$FF,$C1,$0F
        fcb     $F0,$00,$42,$C2,$FC,$01,$F0,$0F,$81,$FF,$C1,$0F
        fcb     $F0,$00,$43,$C1,$C0,$3F,$81,$FF,$C1,$3F,$C0,$00
        fcb     $43,$C1,$C0,$3F,$81,$FF,$C1,$3F,$C0,$00,$43,$C1
        fcb     $F0,$0F,$81,$FF,$C1,$3F,$C0,$00,$43,$C1,$F0,$0F
        fcb     $81,$FF,$41,$00,$43,$C1,$FC,$03,$81,$FF,$C1,$3F
        fcb     $C0,$00,$43,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$00
        fcb     $44,$81,$FF,$C1,$0F,$F0,$00,$44,$81,$FF,$C1,$0F
        fcb     $F0,$00,$44,$C2,$F0,$0F,$03,$FC,$00,$44,$C2,$FC
        fcb     $03,$03,$FC,$00,$44,$C2,$FC,$03,$03,$FC,$00,$44
        fcb     $C1,$FC,$03,$81,$FF,$00,$44,$C2,$F0,$0F,$0F,$F0
        fcb     $00,$44,$C1,$C0,$3F,$41,$00
