* chtab3_044_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 8 rows x 5 bytes, 47 segment bytes
*
chtab3_044_p0:
        fcb     8,5  ; height, width in bytes
        fcb     $C1,$0F,$F0,$44,$00,$C1,$F0,$0F,$44,$00,$41,$C1
        fcb     $0F,$F0,$43,$00,$41,$C1,$F0,$0F,$43,$00,$42,$C1
        fcb     $0F,$F0,$42,$00,$42,$C1,$F0,$0F,$42,$00,$43,$C1
        fcb     $03,$FC,$41,$00,$43,$C2,$F0,$0F,$3F,$C0,$00
