* chtab3_048_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 7 rows x 4 bytes, 44 segment bytes
*
chtab3_048_p0:
        fcb     7,4  ; height, width in bytes
        fcb     $81,$7F,$43,$00,$C2,$FC,$03,$3F,$C0,$42,$00,$41
        fcb     $C1,$03,$FC,$42,$00,$41,$C1,$F0,$0F,$42,$00,$41
        fcb     $C2,$FC,$03,$0F,$F0,$41,$00,$42,$C1,$C3,$3C,$41
        fcb     $00,$42,$C2,$F0,$0F,$0F,$F0,$00
