* chtab3_020_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 22 rows x 8 bytes, 255 segment bytes
*
chtab3_020_p0:
        fcb     22,8  ; height, width in bytes
        fcb     $42,$C1,$F0,$03,$82,$FF,$FF,$C1,$03,$F0,$42,$00
        fcb     $C1,$C0,$0F,$85,$FF,$FF,$FF,$FC,$FE,$42,$00,$86
        fcb     $FF,$FF,$FF,$FF,$FF,$FF,$C1,$3F,$00,$41,$00,$86
        fcb     $FE,$AF,$FF,$FF,$FF,$FF,$C1,$0F,$C0,$41,$00,$86
        fcb     $FE,$AF,$FF,$FF,$FF,$EA,$C1,$0F,$C0,$41,$00,$81
        fcb     $FE,$C2,$03,$A8,$C0,$0A,$83,$FF,$FF,$AA,$C1,$03
        fcb     $F0,$41,$00,$81,$FE,$C2,$03,$A8,$FC,$00,$83,$F7
        fcb     $FF,$AA,$C1,$03,$F0,$41,$00,$C1,$0F,$80,$41,$C1
        fcb     $FC,$00,$83,$F7,$FF,$AA,$C1,$03,$F0,$41,$00,$43
        fcb     $C1,$F0,$0A,$82,$83,$FF,$C1,$03,$F0,$41,$00,$43
        fcb     $C2,$F0,$0A,$0C,$80,$81,$FF,$C1,$0F,$C0,$41,$00
        fcb     $42,$C1,$FC,$00,$81,$AA,$C1,$0C,$80,$81,$FF,$C1
        fcb     $03,$F0,$41,$00,$42,$C1,$FC,$00,$81,$A8,$41,$C1
        fcb     $C0,$3F,$81,$FC,$41,$00,$42,$C2,$C0,$0A,$0F,$80
        fcb     $41,$C1,$C0,$3F,$81,$FF,$41,$00,$42,$C2,$C0,$0A
        fcb     $0F,$80,$41,$C1,$C0,$0F,$81,$FF,$41,$00,$41,$C1
        fcb     $FC,$00,$81,$A8,$42,$C1,$F0,$03,$81,$FF,$C1,$0F
        fcb     $C0,$00,$41,$C2,$FC,$00,$0F,$80,$42,$C1,$FC,$00
        fcb     $81,$FF,$C1,$0F,$C0,$00,$46,$81,$3F,$C1,$0F,$C0
        fcb     $00,$46,$C2,$F0,$01,$C0,$08,$00,$47,$81,$FC,$00
        fcb     $47,$81,$FC,$00,$47,$81,$FC,$00,$46,$C2,$F0,$03
        fcb     $03,$F0,$00
