* chtab3_022_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 24 rows x 8 bytes, 273 segment bytes
*
chtab3_022_p0:
        fcb     24,8  ; height, width in bytes
        fcb     $44,$82,$FF,$FF,$42,$00,$43,$C1,$C0,$3F,$82,$FF
        fcb     $FF,$C1,$3F,$C0,$41,$00,$42,$C1,$FC,$03,$83,$F7
        fcb     $FF,$FF,$C1,$3F,$C0,$41,$00,$42,$C1,$F0,$0F,$83
        fcb     $FF,$FF,$FF,$C1,$3F,$C0,$41,$00,$42,$84,$FF,$FE
        fcb     $FF,$FF,$C1,$3F,$C0,$41,$00,$83,$FF,$EA,$7F,$C1
        fcb     $3C,$83,$82,$FF,$FF,$42,$00,$85,$FF,$EA,$AF,$FF
        fcb     $7F,$C1,$03,$FC,$42,$00,$85,$EA,$AA,$FF,$FF,$FF
        fcb     $C1,$3F,$C0,$42,$00,$81,$FF,$C2,$03,$E8,$F0,$0A
        fcb     $81,$FF,$C1,$03,$FC,$43,$00,$81,$FE,$C2,$03,$A8
        fcb     $F0,$0A,$81,$AF,$C1,$03,$FC,$43,$00,$C1,$03,$FC
        fcb     $41,$C1,$F0,$0A,$82,$AF,$FF,$43,$00,$C1,$3F,$80
        fcb     $41,$C2,$F0,$0A,$3C,$83,$81,$FF,$C1,$3F,$C0,$42
        fcb     $00,$42,$C2,$F3,$08,$F0,$0A,$81,$FF,$C1,$0F,$F0
        fcb     $42,$00,$42,$C4,$F3,$08,$F3,$08,$C0,$3F,$0F,$F0
        fcb     $42,$00,$42,$C4,$F3,$08,$F3,$08,$F0,$0F,$3F,$C0
        fcb     $42,$00,$42,$C2,$F3,$08,$F3,$08,$41,$81,$AF,$42
        fcb     $00,$42,$C1,$F3,$08,$41,$C1,$3F,$80,$81,$FF,$C1
        fcb     $3F,$C0,$41,$00,$42,$C1,$F3,$08,$41,$C3,$3C,$83
        fcb     $03,$FC,$C0,$3F,$41,$00,$42,$C1,$03,$A8,$41,$81
        fcb     $AF,$C1,$3F,$C0,$81,$FF,$C1,$03,$FC,$00,$46,$C2
        fcb     $C0,$3E,$03,$FC,$00,$46,$C2,$FC,$03,$03,$FC,$00
        fcb     $46,$C2,$FC,$03,$0F,$F0,$00,$46,$C2,$FC,$03,$0F
        fcb     $F0,$00,$46,$C2,$FC,$03,$0F,$F0,$00
