* chtab3_065_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 18 rows x 4 bytes, 115 segment bytes
*
chtab3_065_p0:
        fcb     18,4  ; height, width in bytes
        fcb     $41,$C1,$F3,$08,$42,$00,$41,$C1,$F3,$08,$42,$00
        fcb     $41,$C1,$F0,$0F,$42,$00,$41,$C1,$FC,$01,$42,$00
        fcb     $41,$C2,$FC,$03,$3F,$C0,$41,$00,$41,$C2,$FC,$03
        fcb     $3F,$C0,$41,$00,$42,$C1,$3F,$80,$41,$00,$42,$C1
        fcb     $0F,$F0,$41,$00,$42,$C1,$0F,$F0,$41,$00,$42,$C1
        fcb     $CF,$10,$41,$00,$42,$C1,$C3,$3C,$41,$00,$42,$C1
        fcb     $C3,$3C,$41,$00,$42,$C1,$F0,$0F,$41,$00,$42,$C1
        fcb     $F0,$0F,$41,$00,$42,$C2,$F0,$0F,$3F,$C0,$00,$42
        fcb     $C2,$FC,$01,$0F,$50,$00,$42,$C2,$FC,$01,$0F,$50
        fcb     $00,$42,$C1,$FC,$01,$41,$00
