* chtab3_064_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 18 rows x 2 bytes, 79 segment bytes
*
chtab3_064_p0:
        fcb     18,2  ; height, width in bytes
        fcb     $C1,$3F,$80,$41,$00,$C1,$0F,$F0,$41,$00,$C1,$CF
        fcb     $10,$41,$00,$C1,$03,$7C,$41,$00,$C1,$F3,$08,$41
        fcb     $00,$C1,$F0,$0F,$41,$00,$C1,$FC,$01,$41,$00,$C2
        fcb     $FC,$03,$3F,$C0,$00,$41,$C1,$3F,$80,$00,$41,$C1
        fcb     $0F,$F0,$00,$41,$C1,$CF,$10,$00,$41,$C1,$C3,$3C
        fcb     $00,$41,$C1,$F3,$08,$00,$41,$C1,$F3,$08,$00,$42
        fcb     $00,$42,$00,$42,$00,$42,$00
