* chtab3_037_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 10 rows x 5 bytes, 59 segment bytes
*
chtab3_037_p0:
        fcb     10,5  ; height, width in bytes
        fcb     $C1,$0F,$F0,$44,$00,$C1,$F0,$0F,$44,$00,$41,$C1
        fcb     $0F,$F0,$43,$00,$41,$C1,$F0,$0F,$43,$00,$42,$C1
        fcb     $03,$FC,$42,$00,$42,$C2,$F0,$0F,$3F,$C0,$41,$00
        fcb     $43,$C1,$03,$FC,$41,$00,$43,$C2,$F0,$0F,$0F,$F0
        fcb     $00,$44,$C1,$03,$FC,$00,$44,$C1,$3F,$80,$00
