* chtab3_032_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 4 rows x 6 bytes, 34 segment bytes
*
chtab3_032_p0:
        fcb     4,6  ; height, width in bytes
        fcb     $82,$FF,$FF,$C1,$0F,$C0,$43,$00,$85,$FF,$FF,$FF
        fcb     $FF,$FF,$C1,$3F,$00,$00,$83,$FF,$FF,$7F,$C1,$0F
        fcb     $C0,$42,$00,$81,$7F,$C1,$0F,$C0,$44,$00
