* chtab3_019_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 28 rows x 6 bytes, 254 segment bytes
*
chtab3_019_p0:
        fcb     28,6  ; height, width in bytes
        fcb     $42,$C1,$C0,$3F,$81,$FF,$C1,$03,$FC,$41,$00,$85
        fcb     $F7,$FF,$FF,$FF,$7F,$C1,$3F,$C0,$00,$85,$FF,$FF
        fcb     $FF,$FF,$7F,$C1,$0F,$F0,$00,$85,$FF,$F7,$FF,$FF
        fcb     $FF,$C1,$03,$FC,$00,$81,$FF,$C1,$0F,$50,$83,$7F
        fcb     $FF,$F5,$C1,$03,$FC,$00,$81,$F5,$C2,$0F,$50,$C0
        fcb     $15,$82,$7F,$FF,$C1,$03,$FC,$00,$C1,$3F,$80,$41
        fcb     $C1,$FC,$01,$82,$7F,$FF,$C1,$03,$FC,$00,$42,$C1
        fcb     $FC,$01,$82,$7F,$FF,$C1,$0F,$F0,$00,$42,$C2,$FC
        fcb     $01,$FC,$03,$81,$FF,$C1,$0F,$F0,$00,$42,$C2,$C0
        fcb     $15,$FC,$03,$81,$FF,$C1,$3F,$C0,$00,$C1,$FC,$01
        fcb     $82,$55,$55,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$00
        fcb     $C2,$FC,$01,$0F,$50,$41,$C1,$FC,$03,$81,$FF,$C1
        fcb     $3F,$C0,$00,$43,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0
        fcb     $00,$43,$C1,$FC,$03,$81,$FF,$41,$00,$43,$C1,$FC
        fcb     $03,$81,$FF,$41,$00,$44,$81,$FF,$41,$00,$44,$81
        fcb     $FF,$41,$00,$44,$81,$FF,$41,$00,$44,$81,$FF,$41
        fcb     $00,$44,$81,$FF,$C1,$3F,$C0,$00,$44,$81,$FF,$C1
        fcb     $3F,$C0,$00,$44,$C2,$C0,$3F,$3F,$C0,$00,$44,$C2
        fcb     $F0,$0F,$0F,$F0,$00,$44,$C2,$FC,$03,$0F,$F0,$00
        fcb     $44,$C2,$FC,$03,$0F,$F0,$00,$44,$C2,$F0,$0F,$0F
        fcb     $F0,$00,$44,$C2,$C0,$3F,$3F,$C0,$00,$44,$81,$FF
        fcb     $41,$00
