* chtab3_047_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 4 rows x 6 bytes, 29 segment bytes
*
chtab3_047_p0:
        fcb     4,6  ; height, width in bytes
        fcb     $43,$82,$3F,$FF,$C1,$3F,$00,$00,$42,$82,$3F,$FC
        fcb     $42,$00,$41,$81,$3F,$C1,$0F,$C0,$43,$00,$81,$7F
        fcb     $C1,$0F,$C0,$44,$00
