* chtab3_078_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 8 rows x 4 bytes, 55 segment bytes
*
chtab3_078_p0:
        fcb     8,4  ; height, width in bytes
        fcb     $42,$C2,$C0,$0F,$0F,$50,$00,$42,$81,$3F,$C1,$3F
        fcb     $00,$00,$42,$81,$3C,$41,$00,$41,$C2,$FC,$00,$03
        fcb     $F0,$41,$00,$41,$C2,$FC,$03,$0F,$C0,$41,$00,$41
        fcb     $C2,$C0,$0F,$3F,$00,$41,$00,$41,$C1,$03,$3C,$42
        fcb     $00,$41,$C1,$03,$10,$42,$00
