* chtab3_030_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 2 rows x 3 bytes, 14 segment bytes
*
chtab3_030_p0:
        fcb     2,3  ; height, width in bytes
        fcb     $81,$FF,$C1,$0F,$F0,$41,$00,$41,$81,$FF,$C1,$03
        fcb     $FC,$00
