* chtab3_044_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 8 rows x 5 bytes, 58 segment bytes
*
chtab3_044_p0:
        fcb     8,5  ; height, width in bytes
        fcb     $C1,$03,$F0,$44,$00,$C2,$C0,$0F,$3F,$00,$43,$00
        fcb     $C2,$FC,$00,$03,$F0,$43,$00,$41,$C2,$C0,$0F,$3F
        fcb     $00,$42,$00,$41,$C2,$FC,$00,$03,$F0,$42,$00,$42
        fcb     $C2,$C0,$0F,$3F,$00,$41,$00,$42,$C1,$FC,$00,$81
        fcb     $FC,$41,$00,$43,$C2,$F0,$0F,$0F,$C0,$00
