* chtab3_024_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 24 rows x 7 bytes, 306 segment bytes
*
chtab3_024_p0:
        fcb     24,7  ; height, width in bytes
        fcb     $44,$C2,$C0,$0F,$03,$F0,$41,$00,$C1,$C0,$0F,$81
        fcb     $FF,$C2,$3F,$00,$F0,$03,$82,$FF,$FF,$C1,$0F,$C0
        fcb     $00,$86,$C3,$FF,$FF,$FF,$7F,$FF,$C1,$03,$F0,$00
        fcb     $86,$FF,$FF,$FF,$FF,$FF,$FF,$C1,$03,$F0,$00,$86
        fcb     $EA,$FF,$FF,$FF,$FF,$FF,$C1,$03,$F0,$00,$86,$EA
        fcb     $FF,$FF,$FF,$FF,$EF,$C1,$0F,$C0,$00,$81,$FE,$C2
        fcb     $03,$A8,$C0,$08,$83,$FF,$FF,$3F,$C1,$0F,$C0,$00
        fcb     $C1,$0F,$80,$41,$C1,$C0,$08,$83,$3F,$FF,$3C,$C1
        fcb     $3F,$00,$00,$42,$C1,$C0,$08,$41,$82,$3F,$FF,$C1
        fcb     $3F,$00,$00,$42,$C2,$C0,$08,$FC,$00,$81,$FF,$C1
        fcb     $03,$F0,$41,$00,$42,$C1,$C0,$0A,$82,$AF,$FF,$C1
        fcb     $3F,$C0,$41,$00,$42,$C1,$C0,$0A,$82,$FF,$FF,$C1
        fcb     $3F,$C0,$41,$00,$41,$C1,$FC,$00,$83,$FF,$FF,$AA
        fcb     $C1,$3F,$00,$41,$00,$41,$C1,$FC,$00,$83,$83,$FF
        fcb     $AA,$C1,$3F,$00,$41,$00,$41,$C2,$FC,$00,$0C,$80
        fcb     $82,$83,$FF,$C1,$3F,$C0,$41,$00,$41,$C3,$FC,$00
        fcb     $0C,$80,$0C,$80,$81,$FF,$C1,$3F,$C0,$41,$00,$41
        fcb     $C3,$FC,$00,$0C,$80,$0C,$F0,$81,$FF,$C1,$03,$F0
        fcb     $41,$00,$41,$C5,$FC,$00,$0C,$80,$0F,$F0,$C0,$0F
        fcb     $03,$F0,$41,$00,$41,$C4,$FC,$00,$0C,$80,$0F,$80
        fcb     $F0,$03,$81,$FC,$41,$00,$41,$C2,$FC,$00,$0F,$80
        fcb     $41,$C1,$FC,$00,$81,$FF,$C1,$3F,$00,$00,$41,$C2
        fcb     $FC,$00,$0F,$80,$41,$C1,$FC,$00,$81,$FF,$C1,$3F
        fcb     $00,$00,$44,$C1,$FC,$00,$81,$FF,$C1,$3F,$00,$00
        fcb     $44,$C1,$F0,$03,$81,$FF,$C1,$0F,$C0,$00,$44,$C2
        fcb     $F0,$01,$03,$50,$41,$00
