* chtab3_049_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 2 rows x 6 bytes, 19 segment bytes
*
chtab3_049_p0:
        fcb     2,6  ; height, width in bytes
        fcb     $44,$C2,$FC,$03,$3F,$C0,$00,$C1,$F0,$0F,$84,$FF
        fcb     $FF,$FF,$FF,$C1,$3F,$C0,$00
