* chtab3_029_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 9 rows x 2 bytes, 47 segment bytes
*
chtab3_029_p0:
        fcb     9,2  ; height, width in bytes
        fcb     $C2,$FC,$03,$3F,$C0,$00,$C2,$FC,$03,$3F,$C0,$00
        fcb     $C1,$F0,$0F,$41,$00,$C1,$F0,$0F,$41,$00,$C1,$03
        fcb     $7C,$41,$00,$C1,$CF,$10,$41,$00,$C1,$0F,$F0,$41
        fcb     $00,$C1,$3F,$80,$41,$00,$C1,$3F,$80,$41,$00
