* chtab3_033_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 7 rows x 5 bytes, 50 segment bytes
*
chtab3_033_p0:
        fcb     7,5  ; height, width in bytes
        fcb     $81,$FC,$44,$00,$C2,$C0,$0F,$03,$F0,$43,$00,$41
        fcb     $81,$3F,$C1,$0F,$C0,$42,$00,$41,$C1,$FC,$00,$81
        fcb     $FF,$C1,$3F,$00,$41,$00,$42,$C1,$F0,$03,$81,$FC
        fcb     $41,$00,$43,$82,$3F,$FC,$00,$43,$C1,$FC,$00,$81
        fcb     $FC,$00
