* chtab3_052_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 40 rows x 5 bytes, 396 segment bytes
*
chtab3_052_p0:
        fcb     40,5  ; height, width in bytes
        fcb     $42,$C1,$FC,$03,$81,$FF,$41,$00,$42,$C1,$C0,$3F
        fcb     $81,$FF,$C1,$3F,$C0,$00,$42,$C1,$C0,$3F,$81,$FF
        fcb     $C1,$3F,$C0,$00,$42,$C1,$FC,$03,$81,$FF,$C1,$3F
        fcb     $C0,$00,$42,$C1,$F0,$0A,$81,$AF,$C1,$3F,$C0,$00
        fcb     $42,$C1,$F0,$0A,$81,$AF,$C1,$3F,$C0,$00,$42,$C1
        fcb     $F0,$0A,$81,$AF,$41,$00,$C1,$3F,$80,$42,$C1,$03
        fcb     $A8,$41,$00,$81,$AA,$C1,$3F,$80,$41,$81,$AA,$C1
        fcb     $3F,$80,$00,$C1,$F0,$0A,$83,$AA,$AA,$AA,$C1,$0F
        fcb     $F0,$00,$41,$C1,$F0,$0A,$82,$AA,$AA,$C1,$0F,$F0
        fcb     $00,$42,$C1,$F0,$0A,$81,$AA,$C1,$0F,$F0,$00,$42
        fcb     $C3,$C0,$3F,$3F,$C0,$3F,$80,$00,$42,$C1,$C0,$3F
        fcb     $81,$FF,$C1,$3F,$C0,$00,$42,$C1,$C0,$3F,$81,$FF
        fcb     $C1,$3F,$C0,$00,$42,$C1,$C0,$3F,$81,$FF,$41,$00
        fcb     $42,$C1,$C0,$3F,$81,$FF,$41,$00,$42,$82,$FF,$FF
        fcb     $C1,$3F,$C0,$00,$42,$82,$FF,$FF,$C1,$3F,$C0,$00
        fcb     $42,$82,$FF,$FF,$C1,$3F,$C0,$00,$42,$82,$FF,$FF
        fcb     $C1,$3F,$C0,$00,$42,$82,$FF,$FF,$C1,$3F,$C0,$00
        fcb     $41,$C1,$FC,$03,$82,$FF,$FF,$C1,$3F,$C0,$00,$41
        fcb     $C1,$FC,$03,$82,$FF,$FF,$C1,$3F,$C0,$00,$41,$C1
        fcb     $FC,$03,$82,$FF,$FF,$C1,$3F,$C0,$00,$41,$C1,$FC
        fcb     $03,$82,$FF,$FF,$C1,$3F,$C0,$00,$41,$C1,$F0,$0F
        fcb     $82,$FF,$FF,$C1,$0F,$F0,$00,$41,$C1,$F0,$0F,$82
        fcb     $FE,$FF,$C1,$0F,$F0,$00,$41,$C4,$F0,$0F,$03,$FC
        fcb     $C0,$3F,$0F,$F0,$00,$41,$C4,$F0,$0F,$03,$FC,$C0
        fcb     $3F,$03,$FC,$00,$41,$C4,$F0,$0F,$03,$FC,$C0,$3F
        fcb     $03,$FC,$00,$41,$C4,$C0,$3F,$03,$FC,$F0,$0F,$03
        fcb     $FC,$00,$41,$C3,$C0,$3F,$03,$FC,$F0,$0F,$81,$FF
        fcb     $00,$41,$C3,$C0,$3F,$0F,$F0,$F0,$0F,$81,$FF,$00
        fcb     $41,$C3,$C0,$3F,$0F,$F0,$FC,$03,$81,$FF,$00,$41
        fcb     $C3,$F0,$0F,$3F,$C0,$FC,$03,$81,$FF,$00,$41,$C2
        fcb     $C0,$3F,$3F,$C0,$41,$C1,$C0,$3F,$00,$C1,$F0,$0F
        fcb     $81,$FF,$C1,$3F,$C0,$41,$C1,$C0,$3F,$00,$C1,$FC
        fcb     $03,$81,$FF,$42,$C1,$C0,$3F,$00,$44,$81,$FF,$00
