* chtab3_034_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 7 rows x 2 bytes, 36 segment bytes
*
chtab3_034_p0:
        fcb     7,2  ; height, width in bytes
        fcb     $41,$C1,$F3,$08,$00,$41,$C1,$C3,$3C,$00,$41,$C1
        fcb     $0F,$F0,$00,$41,$C1,$3F,$80,$00,$C2,$FC,$03,$3F
        fcb     $C0,$00,$C1,$F0,$0F,$41,$00,$C1,$03,$FC,$41,$00
