* chtab3_040_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 6 rows x 6 bytes, 49 segment bytes
*
chtab3_040_p0:
        fcb     6,6  ; height, width in bytes
        fcb     $44,$C1,$F0,$0F,$41,$00,$44,$C2,$FC,$03,$3F,$C0
        fcb     $00,$43,$C1,$F0,$0F,$81,$FF,$C1,$3F,$C0,$00,$42
        fcb     $C4,$F0,$0F,$03,$FC,$FC,$03,$3F,$C0,$00,$41,$C2
        fcb     $C0,$3F,$03,$FC,$43,$00,$81,$7F,$C1,$0F,$F0,$44
        fcb     $00
