* chtab3_048_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 7 rows x 4 bytes, 49 segment bytes
*
chtab3_048_p0:
        fcb     7,4  ; height, width in bytes
        fcb     $81,$7F,$C1,$3F,$00,$42,$00,$C2,$F0,$03,$0F,$C0
        fcb     $42,$00,$C2,$FC,$00,$03,$FC,$42,$00,$41,$C2,$C0
        fcb     $0F,$3F,$00,$41,$00,$41,$C2,$FC,$03,$03,$F0,$41
        fcb     $00,$42,$81,$3C,$41,$00,$42,$C2,$C0,$0F,$0F,$F0
        fcb     $00
