* chtab3_045_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 11 rows x 3 bytes, 62 segment bytes
*
chtab3_045_p0:
        fcb     11,3  ; height, width in bytes
        fcb     $C1,$CF,$10,$42,$00,$C1,$CF,$10,$42,$00,$C1,$F3
        fcb     $08,$42,$00,$C1,$FC,$01,$42,$00,$C1,$FC,$01,$42
        fcb     $00,$41,$C1,$3F,$80,$41,$00,$41,$C1,$CF,$10,$41
        fcb     $00,$41,$C1,$CF,$10,$41,$00,$41,$C1,$C3,$3C,$41
        fcb     $00,$41,$C1,$C0,$3F,$41,$00,$41,$C2,$F0,$0F,$3F
        fcb     $C0,$00
