* chtab3_062_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 38 rows x 5 bytes, 398 segment bytes
*
chtab3_062_p0:
        fcb     38,5  ; height, width in bytes
        fcb     $41,$81,$FF,$C1,$3F,$C0,$42,$00,$C1,$F0,$0F,$81
        fcb     $FF,$C1,$0F,$F0,$42,$00,$C1,$F0,$0F,$81,$FF,$C1
        fcb     $0F,$F0,$42,$00,$C1,$F0,$0F,$81,$FF,$C1,$0F,$F0
        fcb     $42,$00,$C1,$F0,$0F,$81,$EA,$C1,$0F,$F0,$42,$00
        fcb     $41,$81,$AA,$C1,$03,$FC,$42,$00,$41,$82,$AA,$FE
        fcb     $C1,$3F,$80,$41,$00,$41,$82,$AF,$FE,$C1,$3F,$80
        fcb     $41,$00,$C1,$F0,$0A,$82,$AF,$FE,$C1,$03,$A8,$41
        fcb     $00,$C1,$F0,$0A,$82,$FF,$FE,$C1,$03,$A8,$41,$00
        fcb     $83,$FF,$FF,$AA,$C1,$F3,$08,$41,$00,$83,$FF,$FF
        fcb     $AF,$C1,$F3,$08,$41,$00,$C1,$F0,$0A,$82,$FF,$FF
        fcb     $C2,$F0,$0A,$3F,$80,$00,$41,$82,$AF,$FF,$41,$C1
        fcb     $3F,$80,$00,$41,$82,$AF,$FF,$41,$C1,$3F,$80,$00
        fcb     $41,$C1,$F0,$0F,$81,$FF,$C2,$3F,$C0,$3F,$80,$00
        fcb     $41,$C1,$C0,$3F,$81,$FF,$C2,$3F,$C0,$03,$A8,$00
        fcb     $41,$C1,$C0,$3F,$81,$FF,$C2,$3F,$C0,$F3,$08,$00
        fcb     $41,$82,$FF,$FF,$C2,$3F,$C0,$F3,$08,$00,$41,$82
        fcb     $FF,$FF,$C2,$3F,$C0,$F3,$08,$00,$41,$82,$FF,$FF
        fcb     $C2,$0F,$F0,$F3,$08,$00,$C1,$FC,$03,$82,$FF,$FF
        fcb     $C1,$0F,$F0,$41,$00,$C1,$FC,$03,$82,$FF,$FF,$C1
        fcb     $0F,$F0,$41,$00,$C1,$FC,$03,$82,$FF,$FF,$C1,$0F
        fcb     $F0,$41,$00,$C1,$FC,$03,$82,$FF,$FF,$C1,$03,$FC
        fcb     $41,$00,$C1,$F0,$0F,$82,$FF,$7F,$C1,$03,$FC,$41
        fcb     $00,$C1,$F0,$0F,$82,$FF,$7F,$C1,$03,$FC,$41,$00
        fcb     $C4,$F0,$0F,$03,$FC,$F0,$0F,$03,$FC,$41,$00,$C3
        fcb     $F0,$0F,$03,$FC,$F0,$0F,$81,$FF,$41,$00,$C3,$F0
        fcb     $0F,$03,$FC,$F0,$0F,$81,$FF,$41,$00,$C3,$F0,$0F
        fcb     $03,$FC,$FC,$03,$81,$FF,$41,$00,$C2,$F0,$0F,$03
        fcb     $FC,$41,$81,$FF,$C1,$3F,$C0,$00,$C2,$F0,$0F,$0F
        fcb     $F0,$41,$81,$FF,$C1,$3F,$C0,$00,$C2,$FC,$03,$0F
        fcb     $F0,$41,$C1,$C0,$3F,$41,$00,$C2,$F0,$0F,$0F,$F0
        fcb     $41,$C2,$C0,$3F,$3F,$C0,$00,$81,$FF,$C1,$0F,$F0
        fcb     $41,$C2,$F0,$0F,$0F,$F0,$00,$81,$FF,$C1,$3F,$C0
        fcb     $41,$C2,$F0,$0F,$03,$FC,$00,$43,$C2,$F0,$0F,$03
        fcb     $FC,$00
