* chtab3_035_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 5 rows x 5 bytes, 38 segment bytes
*
chtab3_035_p0:
        fcb     5,5  ; height, width in bytes
        fcb     $44,$C1,$F0,$0F,$00,$43,$C1,$FC,$03,$81,$FF,$00
        fcb     $42,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$00,$41,$C1
        fcb     $FC,$03,$81,$FF,$C1,$3F,$C0,$41,$00,$41,$81,$FF
        fcb     $43,$00
