* chtab3_031_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 3 rows x 5 bytes, 26 segment bytes
*
chtab3_031_p0:
        fcb     3,5  ; height, width in bytes
        fcb     $81,$7F,$C1,$03,$FC,$43,$00,$41,$C1,$C0,$0F,$81
        fcb     $FF,$C1,$0F,$F0,$41,$00,$42,$C1,$FC,$00,$82,$FF
        fcb     $FC,$00
