* chtab3_023_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 22 rows x 7 bytes, 259 segment bytes
*
chtab3_023_p0:
        fcb     22,7  ; height, width in bytes
        fcb     $43,$83,$FF,$FC,$3F,$41,$00,$42,$C1,$F0,$03,$83
        fcb     $FF,$FF,$FF,$C1,$0F,$C0,$00,$42,$84,$3F,$FF,$FF
        fcb     $FF,$C1,$03,$F0,$00,$86,$FF,$FF,$FF,$FF,$7F,$F7
        fcb     $C1,$03,$F0,$00,$86,$C3,$FF,$FF,$FF,$FF,$FF,$C1
        fcb     $03,$F0,$00,$81,$FF,$C1,$03,$FC,$84,$17,$EF,$FF
        fcb     $FF,$C1,$0F,$C0,$00,$86,$55,$7F,$FF,$FF,$FF,$FF
        fcb     $C1,$3F,$00,$00,$82,$F5,$55,$C1,$03,$50,$83,$FF
        fcb     $FC,$3F,$41,$00,$81,$F5,$C1,$3C,$01,$83,$FF,$FF
        fcb     $57,$C1,$03,$F0,$41,$00,$42,$83,$FF,$FF,$17,$C1
        fcb     $3F,$C0,$41,$00,$42,$83,$FF,$FC,$17,$42,$00,$42
        fcb     $84,$17,$FF,$F7,$FF,$C1,$3F,$00,$00,$41,$C1,$FC
        fcb     $01,$85,$FF,$F7,$FF,$FF,$7F,$00,$41,$C1,$FC,$01
        fcb     $85,$FF,$FE,$FF,$FF,$50,$00,$41,$C2,$FC,$01,$03
        fcb     $50,$84,$3F,$FF,$7F,$FF,$00,$41,$C3,$FC,$01,$3F
        fcb     $00,$F0,$0F,$81,$FF,$C1,$3C,$00,$81,$FF,$00,$41
        fcb     $C3,$FC,$01,$3F,$00,$F0,$03,$81,$FF,$C1,$3C,$C0
        fcb     $81,$FF,$00,$41,$C3,$FC,$01,$3C,$00,$0C,$80,$83
        fcb     $F0,$FC,$FF,$00,$41,$C4,$FC,$01,$3C,$00,$0F,$F0
        fcb     $F0,$03,$81,$FC,$C1,$03,$10,$00,$41,$C4,$FC,$01
        fcb     $3C,$00,$0F,$F0,$C0,$0F,$81,$FF,$C1,$3F,$00,$00
        fcb     $42,$C2,$FC,$00,$0F,$80,$82,$3F,$FC,$41,$00,$44
        fcb     $C2,$C0,$0F,$3F,$00,$41,$00
