* chtab3_047_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 4 rows x 5 bytes, 30 segment bytes
*
chtab3_047_p0:
        fcb     4,5  ; height, width in bytes
        fcb     $43,$C1,$C0,$3F,$81,$FF,$00,$42,$C2,$C0,$3F,$03
        fcb     $FC,$41,$00,$41,$C2,$C0,$3F,$3F,$C0,$42,$00,$81
        fcb     $7F,$C1,$3F,$C0,$43,$00
