* chtab3_076_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 7 rows x 5 bytes, 44 segment bytes
*
chtab3_076_p0:
        fcb     7,5  ; height, width in bytes
        fcb     $C2,$F0,$0F,$0F,$F0,$43,$00,$41,$C2,$C0,$3F,$3F
        fcb     $C0,$42,$00,$42,$81,$FF,$42,$00,$42,$C2,$FC,$03
        fcb     $03,$FC,$41,$00,$43,$C2,$F0,$0F,$03,$E8,$00,$44
        fcb     $81,$AF,$00,$44,$C1,$F0,$0F,$00
