* chtab3_020_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 22 rows x 8 bytes, 242 segment bytes
*
chtab3_020_p0:
        fcb     22,8  ; height, width in bytes
        fcb     $42,$C1,$FC,$03,$82,$FF,$FF,$C1,$0F,$F0,$42,$00
        fcb     $C1,$F0,$0F,$84,$FE,$FF,$FF,$FF,$C1,$03,$FC,$42
        fcb     $00,$86,$FF,$FF,$FF,$FF,$FF,$FF,$42,$00,$86,$FE
        fcb     $AF,$FF,$FF,$FF,$FF,$C1,$3F,$C0,$41,$00,$86,$FE
        fcb     $AF,$FF,$FF,$FF,$EA,$C1,$3F,$C0,$41,$00,$81,$FE
        fcb     $C2,$03,$A8,$F0,$0A,$83,$FF,$FF,$AA,$C1,$0F,$F0
        fcb     $41,$00,$81,$FE,$C1,$03,$A8,$41,$83,$F7,$FF,$AA
        fcb     $C1,$0F,$F0,$41,$00,$C1,$3F,$80,$42,$83,$F7,$FF
        fcb     $AA,$C1,$0F,$F0,$41,$00,$43,$C2,$F0,$0A,$3C,$83
        fcb     $81,$FF,$C1,$0F,$F0,$41,$00,$43,$C2,$F0,$0A,$3F
        fcb     $80,$81,$FF,$C1,$3F,$C0,$41,$00,$43,$81,$AA,$C1
        fcb     $3F,$80,$81,$FF,$C1,$0F,$F0,$41,$00,$43,$C1,$03
        fcb     $A8,$41,$C2,$C0,$3F,$03,$FC,$41,$00,$42,$C2,$F0
        fcb     $0A,$3F,$80,$41,$C1,$C0,$3F,$81,$FF,$41,$00,$42
        fcb     $C2,$F0,$0A,$3F,$80,$41,$C1,$F0,$0F,$81,$FF,$41
        fcb     $00,$42,$C1,$03,$A8,$42,$C1,$FC,$03,$81,$FF,$C1
        fcb     $3F,$C0,$00,$42,$C1,$3F,$80,$43,$81,$FF,$C1,$3F
        fcb     $C0,$00,$46,$C2,$C0,$3F,$3F,$C0,$00,$46,$C2,$FC
        fcb     $01,$F3,$08,$00,$47,$C1,$03,$FC,$00,$47,$C1,$03
        fcb     $FC,$00,$47,$C1,$03,$FC,$00,$46,$C2,$FC,$03,$0F
        fcb     $F0,$00
