* chtab3_014_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 44 rows x 3 bytes, 350 segment bytes
*
chtab3_014_p0:
        fcb     44,3  ; height, width in bytes
        fcb     $C1,$C0,$15,$42,$00,$C1,$FC,$01,$81,$7F,$C1,$3F
        fcb     $C0,$00,$C1,$FC,$01,$81,$7F,$C1,$0F,$F0,$00,$C1
        fcb     $FC,$01,$81,$7F,$C1,$0F,$F0,$00,$C1,$FC,$01,$81
        fcb     $7F,$C1,$0F,$F0,$00,$C1,$FC,$01,$81,$7F,$C1,$3F
        fcb     $C0,$00,$C2,$FC,$01,$FC,$01,$41,$00,$C1,$FC,$01
        fcb     $81,$55,$C1,$03,$7C,$00,$C1,$FC,$01,$82,$55,$7F
        fcb     $00,$C1,$FC,$01,$82,$55,$7F,$00,$C1,$FC,$01,$82
        fcb     $57,$FF,$00,$C1,$FC,$01,$82,$57,$FF,$00,$41,$82
        fcb     $FF,$FF,$00,$41,$81,$FF,$C1,$03,$FC,$00,$41,$81
        fcb     $FF,$C1,$03,$FC,$00,$41,$81,$FF,$C1,$03,$FC,$00
        fcb     $C1,$FC,$03,$81,$FF,$C1,$03,$FC,$00,$C1,$FC,$03
        fcb     $81,$FF,$C1,$0F,$F0,$00,$C1,$FC,$03,$81,$FF,$C1
        fcb     $0F,$F0,$00,$C1,$FC,$03,$81,$FF,$C1,$0F,$F0,$00
        fcb     $C1,$FC,$03,$81,$FF,$C1,$0F,$F0,$00,$C1,$FC,$03
        fcb     $81,$FF,$C1,$0F,$F0,$00,$C1,$FC,$03,$81,$FF,$C1
        fcb     $3F,$C0,$00,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$00
        fcb     $C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$00,$C1,$FC,$03
        fcb     $81,$FF,$C1,$3F,$C0,$00,$C1,$F0,$0F,$81,$FF,$C1
        fcb     $3F,$C0,$00,$C1,$F0,$0F,$81,$FF,$C1,$3F,$C0,$00
        fcb     $C1,$F0,$0F,$81,$FF,$C1,$0F,$F0,$00,$C1,$F0,$0F
        fcb     $81,$FF,$C1,$0F,$F0,$00,$C1,$F0,$0F,$81,$FF,$C1
        fcb     $0F,$F0,$00,$C1,$F0,$0F,$81,$FF,$C1,$0F,$F0,$00
        fcb     $C1,$FC,$03,$81,$FF,$C1,$0F,$F0,$00,$C1,$FC,$03
        fcb     $81,$FF,$C1,$0F,$F0,$00,$C1,$FC,$03,$81,$FF,$C1
        fcb     $0F,$F0,$00,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$00
        fcb     $41,$81,$FF,$41,$00,$41,$C1,$C0,$15,$41,$00,$41
        fcb     $C2,$C0,$17,$3F,$C0,$00,$41,$C2,$C0,$17,$0F,$F0
        fcb     $00,$41,$C2,$C0,$3F,$0F,$F0,$00,$41,$C2,$C0,$3F
        fcb     $3F,$C0,$00,$41,$81,$FF,$41,$00,$41,$C1,$0F,$F0
        fcb     $41,$00
