* chtab3_071_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 11 rows x 4 bytes, 75 segment bytes
*
chtab3_071_p0:
        fcb     11,4  ; height, width in bytes
        fcb     $42,$C1,$C3,$3C,$41,$00,$42,$81,$AA,$C1,$3F,$80
        fcb     $00,$42,$C1,$03,$A8,$41,$00,$42,$C1,$0F,$F0,$41
        fcb     $00,$41,$C2,$FC,$03,$0F,$F0,$41,$00,$41,$C2,$FC
        fcb     $03,$3F,$C0,$41,$00,$41,$C2,$FC,$03,$3F,$C0,$41
        fcb     $00,$41,$C2,$F0,$0F,$3F,$C0,$41,$00,$41,$C1,$F0
        fcb     $0F,$42,$00,$41,$C1,$C0,$3F,$42,$00,$41,$C1,$C0
        fcb     $3F,$42,$00
