* chtab3_068_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 8 rows x 7 bytes, 65 segment bytes
*
chtab3_068_p0:
        fcb     8,7  ; height, width in bytes
        fcb     $C2,$F0,$03,$03,$F0,$45,$00,$41,$81,$3F,$C1,$3F
        fcb     $00,$44,$00,$41,$C1,$FC,$03,$81,$FC,$44,$00,$42
        fcb     $C2,$C0,$0F,$0F,$F0,$43,$00,$42,$C1,$FC,$00,$81
        fcb     $FF,$C1,$3F,$00,$42,$00,$43,$C1,$F0,$03,$83,$AA
        fcb     $A8,$FE,$00,$44,$C1,$C0,$0A,$81,$A8,$41,$00,$45
        fcb     $C1,$C0,$3C,$41,$00
