* chtab3_017_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 39 rows x 6 bytes, 367 segment bytes
*
chtab3_017_p0:
        fcb     39,6  ; height, width in bytes
        fcb     $C1,$FC,$03,$81,$FF,$44,$00,$82,$7F,$FF,$C1,$3F
        fcb     $C0,$43,$00,$83,$FF,$FF,$FF,$C1,$3F,$C0,$42,$00
        fcb     $83,$FF,$FF,$FE,$C1,$0F,$F0,$42,$00,$C1,$F0,$0A
        fcb     $83,$EA,$FF,$AF,$42,$00,$C1,$F0,$0A,$83,$EA,$FF
        fcb     $AF,$C1,$3F,$C0,$41,$00,$42,$82,$AA,$FF,$C1,$0F
        fcb     $F0,$41,$00,$42,$C1,$F0,$0A,$81,$FF,$C1,$0F,$F0
        fcb     $41,$00,$42,$82,$AA,$FF,$C1,$0F,$F0,$41,$00,$42
        fcb     $82,$AA,$FF,$C1,$03,$FC,$41,$00,$42,$C2,$03,$A8
        fcb     $C0,$3F,$81,$FF,$41,$00,$42,$C2,$03,$A8,$C0,$3F
        fcb     $81,$FF,$C1,$3F,$C0,$00,$43,$C1,$F0,$0F,$81,$FF
        fcb     $C1,$0F,$F0,$00,$43,$C1,$F0,$0F,$81,$FF,$C1,$0F
        fcb     $F0,$00,$43,$C1,$F0,$0F,$81,$FF,$C1,$03,$FC,$00
        fcb     $43,$C1,$F0,$0F,$81,$FF,$C1,$03,$FC,$00,$43,$C1
        fcb     $FC,$03,$82,$FF,$FF,$00,$43,$C1,$FC,$03,$81,$FF
        fcb     $C1,$03,$FC,$00,$43,$C1,$FC,$03,$81,$FF,$C1,$03
        fcb     $FC,$00,$43,$C1,$FC,$03,$81,$FF,$C1,$03,$FC,$00
        fcb     $43,$C1,$FC,$03,$81,$FF,$C1,$03,$FC,$00,$43,$C1
        fcb     $FC,$03,$81,$FF,$C1,$0F,$F0,$00,$43,$C1,$FC,$03
        fcb     $81,$FF,$C1,$0F,$F0,$00,$43,$C1,$FC,$03,$81,$FF
        fcb     $C1,$0F,$F0,$00,$43,$C1,$FC,$03,$81,$FF,$C1,$3F
        fcb     $C0,$00,$43,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$00
        fcb     $43,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$00,$43,$C1
        fcb     $FC,$03,$81,$FF,$C1,$3F,$C0,$00,$43,$C1,$FC,$03
        fcb     $81,$FF,$C1,$3F,$C0,$00,$43,$C1,$FC,$03,$81,$FF
        fcb     $C1,$3F,$C0,$00,$43,$C1,$FC,$03,$81,$FF,$C1,$3F
        fcb     $C0,$00,$43,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$00
        fcb     $43,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$00,$43,$C1
        fcb     $FC,$03,$81,$FF,$C1,$3F,$C0,$00,$44,$81,$FF,$C1
        fcb     $3F,$C0,$00,$44,$C2,$C0,$3F,$3F,$C0,$00,$44,$81
        fcb     $FF,$41,$00,$43,$C1,$FC,$03,$81,$FF,$41,$00,$43
        fcb     $C2,$F0,$0F,$0F,$F0,$41,$00
