* chtab3_045_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 11 rows x 3 bytes, 68 segment bytes
*
chtab3_045_p0:
        fcb     11,3  ; height, width in bytes
        fcb     $C1,$03,$10,$42,$00,$C1,$03,$10,$42,$00,$C1,$C0
        fcb     $08,$42,$00,$C2,$F0,$01,$3F,$00,$41,$00,$C2,$F0
        fcb     $01,$3F,$00,$41,$00,$C2,$FC,$00,$0F,$80,$41,$00
        fcb     $41,$C1,$03,$10,$41,$00,$41,$C1,$03,$10,$41,$00
        fcb     $41,$C1,$03,$3C,$41,$00,$41,$81,$3F,$C1,$3F,$00
        fcb     $00,$41,$C2,$C0,$0F,$0F,$C0,$00
