* chtab3_077_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 4 rows x 4 bytes, 29 segment bytes
*
chtab3_077_p0:
        fcb     4,4  ; height, width in bytes
        fcb     $C1,$FC,$00,$81,$FF,$C1,$3F,$00,$41,$00,$41,$C1
        fcb     $FC,$03,$81,$FF,$C1,$3F,$00,$00,$42,$C2,$F0,$03
        fcb     $0F,$F0,$00,$44,$00
