* chtab3_046_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 4 rows x 3 bytes, 26 segment bytes
*
chtab3_046_p0:
        fcb     4,3  ; height, width in bytes
        fcb     $42,$C1,$03,$10,$00,$41,$C2,$FC,$03,$0F,$C0,$00
        fcb     $41,$81,$3F,$C1,$3F,$00,$00,$C2,$F0,$03,$03,$FC
        fcb     $41,$00
