* chtab3_038_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 16 rows x 4 bytes, 94 segment bytes
*
chtab3_038_p0:
        fcb     16,4  ; height, width in bytes
        fcb     $C1,$CF,$10,$43,$00,$C1,$F3,$08,$43,$00,$C1,$FC
        fcb     $01,$43,$00,$C1,$FC,$01,$43,$00,$41,$C1,$3F,$80
        fcb     $42,$00,$41,$C1,$CF,$10,$42,$00,$41,$C1,$F3,$08
        fcb     $42,$00,$41,$C1,$FC,$01,$42,$00,$41,$C2,$FC,$03
        fcb     $3F,$C0,$41,$00,$42,$C1,$0F,$F0,$41,$00,$42,$C1
        fcb     $C3,$3C,$41,$00,$42,$C1,$C3,$3C,$41,$00,$42,$C1
        fcb     $F0,$0F,$41,$00,$42,$C2,$FC,$03,$3C,$C1,$00,$43
        fcb     $81,$FF,$00,$42,$C2,$FC,$03,$03,$FC,$00
