* chtab3_065_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 18 rows x 4 bytes, 126 segment bytes
*
chtab3_065_p0:
        fcb     18,4  ; height, width in bytes
        fcb     $41,$C1,$C3,$08,$42,$00,$41,$C1,$C3,$08,$42,$00
        fcb     $41,$C2,$C0,$0F,$3F,$00,$41,$00,$41,$C2,$FC,$01
        fcb     $3F,$00,$41,$00,$41,$C2,$FC,$03,$0F,$C0,$41,$00
        fcb     $41,$C2,$FC,$03,$0F,$C0,$41,$00,$41,$C2,$FC,$00
        fcb     $0F,$80,$41,$00,$41,$C2,$FC,$00,$03,$F0,$41,$00
        fcb     $41,$C2,$FC,$00,$03,$F0,$41,$00,$42,$C1,$03,$10
        fcb     $41,$00,$42,$81,$3C,$41,$00,$42,$81,$3C,$41,$00
        fcb     $42,$C2,$C0,$0F,$3F,$00,$00,$42,$C2,$C0,$0F,$3F
        fcb     $00,$00,$42,$C2,$C0,$0F,$0F,$C0,$00,$42,$C2,$F0
        fcb     $01,$0F,$50,$00,$42,$C2,$F0,$01,$0F,$50,$00,$42
        fcb     $C2,$F0,$01,$3F,$00,$00
