* chtab3_075_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 10 rows x 6 bytes, 67 segment bytes
*
chtab3_075_p0:
        fcb     10,6  ; height, width in bytes
        fcb     $44,$C1,$F3,$08,$41,$00,$44,$C1,$F0,$0F,$41,$00
        fcb     $44,$C2,$F0,$0F,$3F,$C0,$00,$44,$C1,$03,$FC,$41
        fcb     $00,$43,$C2,$F0,$0F,$3F,$C0,$41,$00,$43,$C1,$03
        fcb     $FC,$42,$00,$42,$C2,$F0,$0F,$3F,$C0,$42,$00,$42
        fcb     $C1,$C3,$3C,$43,$00,$41,$C2,$FC,$03,$3F,$C0,$43
        fcb     $00,$41,$C1,$C3,$3C,$44,$00
