* chtab3_056_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 38 rows x 5 bytes, 365 segment bytes
*
chtab3_056_p0:
        fcb     38,5  ; height, width in bytes
        fcb     $42,$81,$FF,$C1,$3F,$C0,$41,$00,$41,$C1,$F0,$0F
        fcb     $81,$FF,$C1,$0F,$F0,$41,$00,$41,$C1,$F0,$0F,$81
        fcb     $FF,$C1,$03,$FC,$41,$00,$41,$C1,$FC,$01,$81,$57
        fcb     $C1,$03,$FC,$41,$00,$41,$C1,$FC,$01,$81,$55,$C1
        fcb     $03,$7C,$41,$00,$42,$C1,$C0,$15,$42,$00,$42,$C1
        fcb     $C0,$15,$81,$7F,$C1,$3F,$C0,$00,$C1,$FC,$01,$83
        fcb     $F7,$FF,$57,$C1,$0F,$50,$00,$C1,$C0,$15,$83,$F7
        fcb     $FF,$57,$C1,$0F,$50,$00,$42,$82,$FF,$FF,$C1,$0F
        fcb     $50,$00,$42,$82,$FF,$FF,$C1,$0F,$50,$00,$42,$82
        fcb     $FF,$FF,$C1,$0F,$50,$00,$42,$83,$FF,$55,$FF,$00
        fcb     $41,$C1,$FC,$03,$83,$FF,$F5,$FF,$00,$41,$C1,$FC
        fcb     $03,$83,$FF,$F5,$FF,$00,$41,$C1,$FC,$03,$83,$FF
        fcb     $F5,$FF,$00,$42,$83,$FF,$F5,$FF,$00,$42,$83,$FF
        fcb     $F5,$FF,$00,$42,$83,$FF,$F5,$FF,$00,$41,$C1,$FC
        fcb     $03,$83,$FF,$F5,$FF,$00,$41,$C1,$FC,$03,$83,$FF
        fcb     $F5,$FF,$00,$41,$C1,$FC,$03,$83,$FF,$F5,$FF,$00
        fcb     $41,$C1,$FC,$03,$82,$FF,$FF,$C1,$3F,$C0,$00,$41
        fcb     $C1,$F0,$0F,$82,$FF,$FF,$C1,$3F,$C0,$00,$41,$C1
        fcb     $F0,$0F,$82,$FF,$FF,$C1,$3F,$C0,$00,$41,$C1,$F0
        fcb     $0F,$82,$FF,$FF,$C1,$0F,$F0,$00,$41,$C1,$C0,$3F
        fcb     $82,$FE,$FF,$C1,$0F,$F0,$00,$41,$C1,$C0,$3F,$82
        fcb     $FE,$FF,$C1,$03,$FC,$00,$41,$C4,$C0,$3F,$03,$FC
        fcb     $C0,$3F,$03,$FC,$00,$41,$C3,$C0,$3F,$0F,$F0,$C0
        fcb     $3F,$81,$FF,$00,$41,$C3,$C0,$3F,$0F,$F0,$F0,$0F
        fcb     $81,$FF,$00,$41,$C3,$C0,$3F,$0F,$F0,$F0,$0F,$81
        fcb     $FF,$00,$41,$C3,$C0,$3F,$0F,$F0,$F0,$0F,$81,$FF
        fcb     $00,$41,$C3,$F0,$0F,$3F,$C0,$FC,$03,$81,$FF,$00
        fcb     $41,$C2,$C0,$3F,$3F,$C0,$41,$C1,$C0,$3F,$00,$C1
        fcb     $FC,$03,$81,$FF,$C1,$0F,$F0,$41,$C1,$C0,$3F,$00
        fcb     $C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$41,$C1,$C0,$3F
        fcb     $00,$44,$81,$FF,$00
