* chtab3_025_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 28 rows x 7 bytes, 338 segment bytes
*
chtab3_025_p0:
        fcb     28,7  ; height, width in bytes
        fcb     $C2,$C0,$0F,$03,$FC,$45,$00,$82,$FF,$FF,$C1,$3F
        fcb     $00,$83,$FF,$FF,$3F,$C1,$3F,$00,$00,$86,$7F,$FF
        fcb     $FF,$FF,$FF,$FF,$C1,$0F,$C0,$00,$86,$FF,$FF,$FF
        fcb     $FF,$FF,$FF,$C1,$03,$F0,$00,$86,$EA,$FF,$FF,$FF
        fcb     $FE,$AF,$C1,$03,$F0,$00,$87,$FF,$FF,$FF,$FC,$AF
        fcb     $EA,$FE,$00,$C2,$0F,$80,$FC,$00,$84,$AA,$FF,$FF
        fcb     $FF,$C1,$03,$F0,$00,$41,$C1,$FC,$00,$84,$A8,$3F
        fcb     $F7,$FF,$C1,$03,$F0,$00,$41,$C1,$FC,$00,$81,$A8
        fcb     $41,$82,$17,$FF,$C1,$03,$F0,$00,$41,$C1,$FC,$00
        fcb     $81,$A8,$41,$82,$3F,$FF,$C1,$0F,$C0,$00,$41,$C1
        fcb     $FC,$00,$81,$AA,$C1,$0C,$80,$82,$FF,$FF,$C1,$0F
        fcb     $C0,$00,$41,$C1,$FC,$00,$81,$AA,$C1,$0C,$80,$82
        fcb     $FF,$FF,$C1,$3F,$00,$00,$41,$C1,$FC,$00,$81,$AA
        fcb     $C1,$0C,$80,$82,$FF,$FF,$C1,$3F,$00,$00,$41,$C1
        fcb     $FC,$00,$84,$AA,$83,$FF,$FC,$41,$00,$41,$C2,$FC
        fcb     $00,$0C,$80,$83,$FF,$FC,$83,$41,$00,$41,$C2,$FC
        fcb     $00,$0C,$80,$83,$FF,$FC,$83,$41,$00,$41,$C2,$FC
        fcb     $00,$0C,$80,$83,$FF,$FC,$83,$41,$00,$41,$C2,$FC
        fcb     $00,$0C,$80,$83,$FF,$FC,$83,$41,$00,$41,$C3,$FC
        fcb     $00,$0F,$80,$F0,$03,$82,$FF,$FF,$C1,$3F,$00,$00
        fcb     $41,$C3,$FC,$00,$0F,$80,$F0,$03,$82,$FF,$FF,$C1
        fcb     $3F,$00,$00,$41,$C3,$FC,$00,$0F,$80,$FC,$00,$82
        fcb     $FF,$FF,$C1,$0F,$C0,$00,$41,$C2,$FC,$00,$0F,$80
        fcb     $41,$82,$3F,$FF,$C1,$0F,$C0,$00,$44,$82,$3F,$FF
        fcb     $C1,$0F,$C0,$00,$44,$82,$3F,$FF,$C1,$03,$F0,$00
        fcb     $44,$82,$3F,$FF,$C1,$03,$F0,$00,$43,$C1,$FC,$00
        fcb     $82,$FF,$FF,$C1,$03,$F0,$00,$43,$C1,$F0,$03,$81
        fcb     $FF,$C1,$3F,$00,$41,$00,$43,$81,$3F,$C1,$03,$F0
        fcb     $42,$00
