* chtab3_074_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 7 rows x 4 bytes, 43 segment bytes
*
chtab3_074_p0:
        fcb     7,4  ; height, width in bytes
        fcb     $42,$C2,$FC,$03,$3F,$C0,$00,$42,$C1,$C0,$3F,$41
        fcb     $00,$41,$C2,$FC,$03,$0F,$F0,$41,$00,$41,$C1,$F0
        fcb     $0F,$42,$00,$41,$C1,$0F,$F0,$42,$00,$C1,$F0,$0F
        fcb     $43,$00,$C1,$0F,$F0,$43,$00
