* chtab3_077_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 4 rows x 4 bytes, 22 segment bytes
*
chtab3_077_p0:
        fcb     4,4  ; height, width in bytes
        fcb     $41,$81,$FF,$42,$00,$41,$C1,$FC,$03,$81,$FF,$41
        fcb     $00,$42,$C2,$FC,$03,$0F,$F0,$00,$44,$00
