* chtab3_043_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 3 rows x 7 bytes, 21 segment bytes
*
chtab3_043_p0:
        fcb     3,7  ; height, width in bytes
        fcb     $46,$C1,$F0,$0F,$00,$41,$C1,$F0,$0F,$85,$FF,$FF
        fcb     $FF,$FF,$FF,$00,$46,$C1,$03,$FC,$00
