* chtab3_035_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 5 rows x 6 bytes, 49 segment bytes
*
chtab3_035_p0:
        fcb     5,6  ; height, width in bytes
        fcb     $44,$C2,$C0,$0F,$3F,$00,$00,$43,$C1,$F0,$03,$81
        fcb     $FF,$C1,$3F,$00,$00,$42,$C1,$F0,$03,$81,$FF,$C1
        fcb     $0F,$C0,$41,$00,$41,$C1,$FC,$03,$81,$FF,$C1,$0F
        fcb     $C0,$42,$00,$C1,$FC,$00,$81,$FF,$C1,$3F,$00,$43
        fcb     $00
