* chtab3_042_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 4 rows x 7 bytes, 37 segment bytes
*
chtab3_042_p0:
        fcb     4,7  ; height, width in bytes
        fcb     $C1,$F0,$03,$82,$FF,$FC,$44,$00,$42,$82,$3F,$FF
        fcb     $C3,$0F,$C0,$C0,$0F,$3F,$00,$00,$43,$C1,$F0,$03
        fcb     $82,$FF,$FF,$C1,$3F,$00,$00,$45,$C1,$C0,$3C,$41
        fcb     $00
