* chtab3_022_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 24 rows x 8 bytes, 278 segment bytes
*
chtab3_022_p0:
        fcb     24,8  ; height, width in bytes
        fcb     $43,$C1,$FC,$00,$82,$FF,$FF,$C1,$3F,$00,$41,$00
        fcb     $43,$83,$FF,$FF,$3F,$C1,$0F,$C0,$41,$00,$42,$C1
        fcb     $F0,$03,$83,$F7,$FF,$FF,$C1,$0F,$C0,$41,$00,$42
        fcb     $C1,$C0,$0F,$83,$FF,$FF,$FF,$C1,$0F,$C0,$41,$00
        fcb     $41,$C1,$FC,$00,$84,$FF,$FE,$FF,$FF,$C1,$0F,$C0
        fcb     $41,$00,$86,$EA,$83,$FF,$FF,$7F,$FF,$C1,$3F,$00
        fcb     $41,$00,$86,$EA,$AF,$FF,$FC,$7F,$FF,$42,$00,$85
        fcb     $EA,$AA,$FF,$FF,$FF,$C1,$3F,$C0,$42,$00,$81,$FF
        fcb     $C2,$03,$E8,$C0,$0A,$82,$FF,$FC,$43,$00,$81,$FE
        fcb     $C2,$03,$A8,$C0,$0A,$82,$AF,$FC,$43,$00,$81,$FC
        fcb     $41,$C1,$C0,$0A,$82,$AF,$FF,$C1,$3F,$00,$42,$00
        fcb     $C1,$0F,$80,$41,$C1,$C0,$0A,$82,$83,$FF,$C1,$3F
        fcb     $C0,$42,$00,$42,$C2,$C0,$08,$F0,$0A,$81,$FF,$C1
        fcb     $03,$F0,$42,$00,$42,$C2,$C0,$08,$F0,$08,$81,$3F
        fcb     $C1,$03,$F0,$42,$00,$42,$C4,$C0,$08,$F0,$08,$C0
        fcb     $0F,$3F,$C0,$42,$00,$42,$C3,$C0,$08,$F0,$08,$FC
        fcb     $00,$81,$AF,$C1,$3F,$00,$41,$00,$42,$C3,$C0,$08
        fcb     $FC,$00,$0C,$80,$81,$FF,$C1,$0F,$C0,$41,$00,$42
        fcb     $C2,$C0,$08,$FC,$00,$83,$FC,$3F,$83,$41,$00,$41
        fcb     $C1,$FC,$00,$81,$A8,$C1,$FC,$00,$81,$AF,$C1,$3C
        fcb     $C0,$82,$FF,$FC,$00,$46,$82,$3E,$FC,$00,$46,$C1
        fcb     $F0,$03,$81,$FC,$00,$46,$C2,$F0,$03,$03,$F0,$00
        fcb     $46,$C2,$F0,$03,$03,$F0,$00,$46,$C2,$F0,$03,$03
        fcb     $F0,$00
