* chtab3_066_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 19 rows x 4 bytes, 144 segment bytes
*
chtab3_066_p0:
        fcb     19,4  ; height, width in bytes
        fcb     $41,$C1,$03,$3C,$42,$00,$41,$C1,$C3,$08,$42,$00
        fcb     $41,$C1,$C3,$08,$42,$00,$41,$C2,$C0,$0F,$3F,$00
        fcb     $41,$00,$41,$C2,$C0,$0F,$3F,$00,$41,$00,$41,$C2
        fcb     $FC,$01,$3F,$00,$41,$00,$41,$C2,$FC,$01,$3F,$00
        fcb     $41,$00,$41,$C2,$FC,$03,$0F,$C0,$41,$00,$41,$C2
        fcb     $FC,$03,$0F,$C0,$41,$00,$41,$C2,$FC,$00,$0F,$80
        fcb     $41,$00,$41,$C2,$FC,$00,$0F,$80,$41,$00,$41,$C2
        fcb     $FC,$00,$0F,$80,$41,$00,$41,$C2,$FC,$00,$03,$F0
        fcb     $41,$00,$41,$C2,$FC,$00,$03,$F0,$41,$00,$41,$C2
        fcb     $FC,$00,$03,$F0,$41,$00,$41,$C1,$FC,$00,$81,$A8
        fcb     $41,$00,$41,$C1,$FC,$00,$81,$AA,$C1,$0F,$80,$00
        fcb     $42,$81,$3E,$C1,$0F,$80,$00,$42,$81,$3C,$41,$00
