* chtab3_064_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 18 rows x 2 bytes, 82 segment bytes
*
chtab3_064_p0:
        fcb     18,2  ; height, width in bytes
        fcb     $C1,$0F,$80,$41,$00,$C1,$03,$F0,$41,$00,$C1,$03
        fcb     $10,$41,$00,$81,$7C,$41,$00,$C1,$C0,$08,$41,$00
        fcb     $C2,$C0,$0F,$3F,$00,$00,$C2,$F0,$01,$3F,$00,$00
        fcb     $C2,$F0,$03,$0F,$C0,$00,$C2,$FC,$00,$0F,$80,$00
        fcb     $C2,$FC,$00,$03,$F0,$00,$41,$C1,$03,$10,$00,$41
        fcb     $C1,$03,$3C,$00,$41,$C1,$C3,$08,$00,$41,$C1,$C3
        fcb     $08,$00,$42,$00,$42,$00,$42,$00,$42,$00
