* chtab3_072_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 7 rows x 4 bytes, 39 segment bytes
*
chtab3_072_p0:
        fcb     7,4  ; height, width in bytes
        fcb     $81,$7F,$43,$00,$C2,$FC,$03,$0F,$F0,$42,$00,$41
        fcb     $C1,$C0,$3F,$42,$00,$41,$C2,$FC,$03,$03,$FC,$41
        fcb     $00,$42,$C2,$C0,$3F,$3F,$C0,$00,$43,$C1,$3F,$80
        fcb     $00,$44,$00
