* chtab4gd_031_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 19 rows x 8 bytes, 218 segment bytes
*
chtab4gd_031_p0:
        fcb     19,8  ; height, width in bytes
        fcb     $42,$C2,$FC,$01,$0F,$50,$44,$00,$42,$C2,$FC,$01
        fcb     $0F,$50,$44,$00,$42,$C1,$FC,$01,$81,$7E,$C1,$3F
        fcb     $80,$43,$00,$43,$C2,$F0,$0A,$3F,$80,$43,$00,$43
        fcb     $C2,$F0,$0A,$03,$A8,$43,$00,$43,$C1,$F0,$0A,$81
        fcb     $AA,$C1,$3F,$80,$42,$00,$44,$81,$AA,$C1,$3F,$80
        fcb     $42,$00,$44,$C1,$F0,$0F,$81,$57,$C1,$03,$FC,$41
        fcb     $00,$44,$83,$57,$FF,$FF,$C1,$0F,$F0,$00,$44,$83
        fcb     $57,$FF,$FF,$C1,$03,$FC,$00,$43,$C1,$FC,$03,$83
        fcb     $57,$FF,$FF,$C1,$03,$FC,$00,$43,$C1,$C0,$3F,$83
        fcb     $57,$FF,$F5,$C1,$03,$FC,$00,$C1,$03,$FC,$41,$C2
        fcb     $F3,$08,$C0,$3F,$83,$57,$FF,$F5,$C1,$0F,$F0,$00
        fcb     $81,$FF,$C5,$3F,$C0,$03,$A8,$C0,$3F,$3F,$C0,$F0
        fcb     $0F,$81,$FF,$C1,$3F,$C0,$00,$41,$84,$AA,$AA,$FF
        fcb     $FF,$C2,$F0,$0F,$03,$FC,$41,$00,$C1,$F0,$0A,$83
        fcb     $AA,$FF,$AA,$C1,$F0,$0F,$82,$FF,$FF,$41,$00,$87
        fcb     $AA,$AF,$FF,$FF,$AA,$AA,$AA,$41,$00,$82,$FE,$F5
        fcb     $C1,$F0,$0A,$84,$AA,$AA,$FF,$FF,$41,$00,$C1,$F0
        fcb     $0A,$83,$7E,$AA,$F5,$C3,$03,$A8,$C0,$3F,$0F,$F0
        fcb     $41,$00
