* chtab4gd_032_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 11 rows x 11 bytes, 180 segment bytes
*
chtab4gd_032_p0:
        fcb     11,11  ; height, width in bytes
        fcb     $46,$C2,$C0,$3F,$03,$FC,$43,$00,$44,$C1,$FC,$01
        fcb     $83,$FF,$FF,$57,$43,$00,$44,$C1,$C0,$15,$83,$7F
        fcb     $FF,$55,$C2,$3C,$C3,$0F,$F0,$41,$00,$44,$C1,$C0
        fcb     $15,$85,$7F,$FF,$FF,$FF,$55,$41,$00,$43,$C1,$FC
        fcb     $01,$86,$FF,$FF,$FF,$FF,$55,$57,$41,$00,$42,$C1
        fcb     $C0,$15,$87,$FF,$FE,$FF,$FF,$55,$7F,$55,$C1,$3F
        fcb     $C0,$00,$41,$C1,$C0,$3F,$88,$FF,$FE,$FF,$FF,$55
        fcb     $55,$55,$7F,$C1,$3F,$C0,$00,$41,$C2,$C0,$3F,$3F
        fcb     $C0,$41,$C2,$CF,$10,$C0,$3F,$84,$FF,$FE,$AF,$FF
        fcb     $C1,$3F,$C0,$00,$C1,$FC,$03,$82,$FF,$55,$C3,$0F
        fcb     $50,$03,$A8,$C0,$3F,$81,$FF,$C1,$0F,$F0,$82,$AF
        fcb     $FF,$C1,$3F,$C0,$00,$C1,$FC,$03,$82,$FF,$55,$C3
        fcb     $0F,$50,$03,$A8,$CF,$10,$81,$FF,$C1,$0F,$F0,$82
        fcb     $AF,$FF,$41,$00,$C2,$FC,$01,$FC,$01,$85,$55,$55
        fcb     $57,$FF,$55,$C3,$03,$FC,$FC,$03,$03,$FC,$41,$00
