* chtab4gd_030_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 22 rows x 6 bytes, 232 segment bytes
*
chtab4gd_030_p0:
        fcb     22,6  ; height, width in bytes
        fcb     $C3,$C0,$15,$F0,$0F,$03,$FC,$43,$00,$C1,$C0,$17
        fcb     $82,$FF,$FF,$C1,$0F,$F0,$42,$00,$C1,$FC,$03,$82
        fcb     $FF,$FF,$C1,$03,$FC,$42,$00,$C1,$FC,$01,$82,$7F
        fcb     $FF,$C1,$03,$FC,$42,$00,$41,$82,$AF,$FF,$C1,$03
        fcb     $FC,$42,$00,$41,$C1,$FC,$03,$81,$FF,$C1,$0F,$F0
        fcb     $42,$00,$41,$C1,$C0,$15,$81,$7F,$C1,$3F,$C0,$42
        fcb     $00,$41,$C1,$C0,$15,$81,$7E,$C1,$03,$FC,$42,$00
        fcb     $41,$C3,$C0,$15,$0F,$50,$C0,$3F,$42,$00,$42,$C1
        fcb     $C0,$17,$81,$FF,$C1,$3F,$C0,$41,$00,$42,$82,$FF
        fcb     $FF,$C1,$3F,$C0,$41,$00,$41,$C1,$FC,$03,$82,$FF
        fcb     $FF,$C1,$0F,$F0,$41,$00,$41,$C1,$FC,$03,$82,$FF
        fcb     $FF,$C1,$0F,$F0,$41,$00,$41,$C1,$FC,$03,$83,$FF
        fcb     $F5,$FF,$41,$00,$41,$C1,$FC,$03,$83,$FF,$F5,$EA
        fcb     $41,$00,$42,$C1,$F0,$0A,$82,$AF,$57,$C1,$3F,$C0
        fcb     $00,$42,$83,$AF,$57,$AA,$C1,$3F,$C0,$00,$41,$84
        fcb     $AA,$FE,$AA,$FF,$C1,$3F,$C0,$00,$C1,$F0,$0A,$84
        fcb     $AA,$FE,$AA,$FF,$41,$00,$C1,$F0,$0A,$84,$AA,$AA
        fcb     $AA,$FF,$41,$00,$C1,$F0,$0A,$81,$F5,$C1,$F0,$0A
        fcb     $81,$AF,$C1,$03,$FC,$41,$00,$C1,$F0,$0A,$83,$7E
        fcb     $AF,$F5,$42,$00
