* chtab4gd_029_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 32 rows x 6 bytes, 317 segment bytes
*
chtab4gd_029_p0:
        fcb     32,6  ; height, width in bytes
        fcb     $41,$81,$FF,$C1,$3F,$C0,$43,$00,$C1,$F0,$0F,$82
        fcb     $FF,$FF,$43,$00,$C1,$F0,$0F,$82,$FF,$FF,$C1,$3F
        fcb     $C0,$42,$00,$C1,$FC,$03,$82,$FF,$FF,$C1,$3F,$C0
        fcb     $42,$00,$C1,$F0,$0A,$82,$FF,$FF,$C1,$3F,$C0,$42
        fcb     $00,$41,$C1,$C0,$3F,$81,$FF,$43,$00,$C1,$FC,$01
        fcb     $81,$57,$C1,$03,$FC,$43,$00,$C1,$FC,$01,$81,$57
        fcb     $C1,$3F,$C0,$43,$00,$C1,$FC,$01,$81,$55,$44,$00
        fcb     $41,$81,$FF,$C1,$03,$FC,$43,$00,$41,$82,$FF,$FF
        fcb     $43,$00,$C1,$FC,$03,$82,$FF,$FF,$C1,$3F,$C0,$42
        fcb     $00,$41,$82,$AA,$FF,$C1,$0F,$F0,$42,$00,$41,$82
        fcb     $AA,$FF,$C1,$0F,$F0,$42,$00,$41,$82,$AA,$FF,$C1
        fcb     $0F,$F0,$42,$00,$41,$82,$AA,$FF,$C1,$0F,$50,$42
        fcb     $00,$41,$C3,$03,$A8,$C0,$15,$0F,$50,$42,$00,$C1
        fcb     $FC,$03,$81,$EA,$C2,$3C,$81,$0F,$50,$42,$00,$C1
        fcb     $C0,$17,$82,$EA,$AF,$C1,$03,$FC,$42,$00,$C2,$CF
        fcb     $10,$F0,$0A,$82,$AF,$FF,$C1,$3F,$C0,$41,$00,$41
        fcb     $C1,$F0,$0A,$82,$AF,$FF,$C1,$3F,$C0,$41,$00,$41
        fcb     $C1,$F0,$0A,$82,$AF,$FF,$C1,$03,$FC,$41,$00,$41
        fcb     $C1,$F0,$0A,$83,$FF,$FF,$AF,$C1,$3F,$C0,$00,$41
        fcb     $C1,$FC,$01,$83,$FF,$FF,$7F,$C1,$3F,$C0,$00,$41
        fcb     $C1,$FC,$01,$83,$FF,$FF,$7E,$41,$00,$41,$C1,$3C
        fcb     $81,$82,$7E,$FF,$C1,$0F,$F0,$41,$00,$41,$C1,$3C
        fcb     $81,$82,$7E,$FF,$C1,$3F,$C0,$41,$00,$41,$82,$AA
        fcb     $AA,$C1,$03,$A8,$42,$00,$41,$82,$AA,$AA,$C1,$3F
        fcb     $80,$42,$00,$41,$82,$AA,$AA,$C1,$3F,$80,$42,$00
        fcb     $41,$82,$AA,$AA,$C1,$0F,$F0,$42,$00,$41,$C2,$F0
        fcb     $0A,$3F,$80,$43,$00
