* chtab4gd_027_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 40 rows x 4 bytes, 352 segment bytes
*
chtab4gd_027_p0:
        fcb     40,4  ; height, width in bytes
        fcb     $C2,$C0,$0F,$03,$FC,$42,$00,$82,$FF,$FF,$C1,$03
        fcb     $F0,$41,$00,$83,$FF,$FC,$FF,$41,$00,$83,$FF,$FC
        fcb     $7F,$41,$00,$83,$FF,$FC,$AF,$41,$00,$C1,$F0,$03
        fcb     $81,$FF,$C1,$03,$F0,$41,$00,$82,$15,$7F,$C1,$0F
        fcb     $C0,$41,$00,$81,$15,$C1,$03,$7C,$42,$00,$81,$15
        fcb     $C1,$03,$50,$42,$00,$C1,$F0,$03,$81,$FF,$C1,$3F
        fcb     $00,$41,$00,$C1,$C0,$0F,$81,$FF,$C1,$0F,$C0,$41
        fcb     $00,$82,$7F,$FF,$C1,$03,$F0,$41,$00,$82,$7F,$FF
        fcb     $C1,$03,$F0,$41,$00,$83,$FF,$FC,$7F,$41,$00,$83
        fcb     $FF,$FC,$7F,$41,$00,$C1,$C0,$0A,$81,$AF,$C1,$03
        fcb     $F0,$41,$00,$C3,$C0,$0A,$0C,$81,$03,$50,$41,$00
        fcb     $C3,$C0,$0A,$0C,$81,$03,$50,$41,$00,$C2,$C0,$0A
        fcb     $0C,$83,$81,$FC,$41,$00,$C1,$C0,$0A,$82,$AF,$FC
        fcb     $41,$00,$C1,$C0,$0A,$82,$AA,$FF,$C1,$3F,$00,$00
        fcb     $C1,$C0,$0A,$82,$AA,$FF,$C1,$3F,$00,$00,$C1,$F0
        fcb     $01,$82,$7E,$FF,$C1,$0F,$C0,$00,$C1,$F0,$01,$82
        fcb     $7E,$FF,$C1,$0F,$C0,$00,$C1,$F0,$01,$82,$7E,$FF
        fcb     $C1,$0F,$C0,$00,$C1,$FC,$00,$82,$AA,$FF,$C1,$0F
        fcb     $C0,$00,$C1,$FC,$00,$82,$AA,$FF,$C1,$0F,$C0,$00
        fcb     $C1,$FC,$00,$82,$AA,$FF,$C1,$0F,$C0,$00,$C1,$FC
        fcb     $00,$82,$AA,$FF,$C1,$0F,$C0,$00,$C1,$FC,$00,$82
        fcb     $AA,$FF,$C1,$3F,$00,$00,$C1,$C0,$0A,$82,$AA,$FF
        fcb     $C1,$3F,$00,$00,$C1,$C0,$0A,$82,$AA,$FF,$C1,$3F
        fcb     $00,$00,$C1,$C0,$0A,$82,$AA,$FF,$C1,$3F,$00,$00
        fcb     $C1,$C0,$0A,$82,$AA,$AF,$C1,$0F,$C0,$00,$C1,$FC
        fcb     $00,$82,$AA,$AF,$C1,$0F,$C0,$00,$C1,$FC,$00,$82
        fcb     $AA,$AF,$C1,$0F,$C0,$00,$41,$C1,$C0,$0A,$81,$A8
        fcb     $41,$00,$41,$C1,$FC,$03,$81,$FC,$41,$00,$41,$82
        fcb     $3F,$FF,$C1,$3F,$00,$00,$41,$C1,$C0,$0F,$81,$FF
        fcb     $C1,$3F,$00,$00
