* chtab4gd_029_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 32 rows x 6 bytes, 342 segment bytes
*
chtab4gd_029_p0:
        fcb     32,6  ; height, width in bytes
        fcb     $C1,$FC,$00,$81,$FF,$C1,$0F,$C0,$43,$00,$C1,$C0
        fcb     $0F,$82,$FF,$FF,$C1,$3F,$00,$42,$00,$C1,$C0,$0F
        fcb     $82,$FF,$FF,$C1,$0F,$C0,$42,$00,$C1,$F0,$03,$82
        fcb     $FF,$FF,$C1,$0F,$C0,$42,$00,$C1,$C0,$0A,$82,$FF
        fcb     $FF,$C1,$0F,$C0,$42,$00,$41,$82,$3F,$FF,$C1,$3F
        fcb     $00,$42,$00,$C1,$F0,$01,$82,$57,$FC,$43,$00,$C1
        fcb     $F0,$01,$81,$57,$C1,$0F,$C0,$43,$00,$C1,$F0,$01
        fcb     $81,$55,$C1,$3F,$00,$43,$00,$C1,$FC,$00,$82,$FF
        fcb     $FC,$43,$00,$C1,$FC,$00,$82,$FF,$FF,$C1,$3F,$00
        fcb     $42,$00,$C1,$F0,$03,$82,$FF,$FF,$C1,$0F,$C0,$42
        fcb     $00,$C1,$FC,$00,$82,$AA,$FF,$C1,$0F,$F0,$42,$00
        fcb     $C1,$FC,$00,$82,$AA,$FF,$C1,$0F,$F0,$42,$00,$C1
        fcb     $FC,$00,$82,$AA,$FF,$C1,$0F,$F0,$42,$00,$C1,$FC
        fcb     $00,$82,$AA,$FF,$C1,$0F,$50,$42,$00,$C2,$FC,$00
        fcb     $03,$A8,$81,$15,$C1,$0F,$50,$42,$00,$C1,$F0,$03
        fcb     $82,$EA,$81,$C1,$0F,$50,$42,$00,$84,$17,$EA,$AF
        fcb     $FC,$42,$00,$C2,$03,$10,$C0,$0A,$82,$AF,$FF,$C1
        fcb     $0F,$C0,$41,$00,$41,$C1,$C0,$0A,$82,$AF,$FF,$C1
        fcb     $0F,$C0,$41,$00,$41,$C1,$C0,$0A,$83,$FF,$FC,$AF
        fcb     $41,$00,$41,$C1,$C0,$0A,$83,$FF,$FF,$AF,$C1,$3F
        fcb     $C0,$00,$41,$C1,$FC,$01,$83,$FF,$FF,$7F,$C1,$3F
        fcb     $C0,$00,$41,$C1,$FC,$01,$83,$FF,$FF,$7E,$C1,$3F
        fcb     $00,$00,$C2,$FC,$00,$0C,$81,$82,$7E,$FF,$C1,$03
        fcb     $F0,$41,$00,$C2,$FC,$00,$0C,$81,$82,$7E,$FF,$C1
        fcb     $0F,$C0,$41,$00,$C1,$FC,$00,$83,$AA,$A8,$AA,$42
        fcb     $00,$C1,$FC,$00,$82,$AA,$AA,$C1,$0F,$80,$42,$00
        fcb     $C1,$FC,$00,$82,$AA,$AA,$C1,$0F,$80,$42,$00,$C1
        fcb     $FC,$00,$82,$AA,$AA,$C1,$0F,$F0,$42,$00,$41,$C2
        fcb     $C0,$0A,$0F,$80,$43,$00
