* chtab4gd_032_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 11 rows x 11 bytes, 174 segment bytes
*
chtab4gd_032_p0:
        fcb     11,11  ; height, width in bytes
        fcb     $46,$82,$3F,$FC,$43,$00,$44,$C1,$F0,$01,$83,$FF
        fcb     $FF,$57,$C1,$3F,$00,$42,$00,$44,$84,$15,$55,$7F
        fcb     $FF,$C2,$0C,$C3,$03,$F0,$41,$00,$44,$86,$7F,$FF
        fcb     $FF,$FF,$15,$55,$C1,$3F,$00,$00,$43,$C1,$F0,$01
        fcb     $86,$FF,$FF,$FF,$FF,$55,$57,$C1,$3F,$00,$00,$42
        fcb     $88,$FF,$FE,$FF,$FF,$15,$55,$55,$7F,$C1,$0F,$C0
        fcb     $00,$41,$89,$FF,$FE,$FF,$FF,$55,$55,$55,$7F,$3F
        fcb     $C1,$0F,$C0,$00,$41,$81,$3F,$C1,$0F,$C0,$41,$C2
        fcb     $03,$10,$C0,$3F,$84,$FF,$FE,$AF,$FF,$C1,$0F,$C0
        fcb     $00,$C1,$F0,$03,$82,$FF,$55,$C1,$0C,$50,$81,$A8
        fcb     $C1,$C0,$3F,$84,$FF,$F0,$AF,$FF,$C1,$0F,$C0,$00
        fcb     $C1,$F0,$03,$82,$FF,$55,$C1,$0C,$50,$81,$A8,$C1
        fcb     $C0,$10,$84,$FF,$F0,$AF,$FF,$C1,$3F,$00,$00,$C2
        fcb     $F0,$01,$3C,$01,$86,$55,$57,$FF,$FC,$55,$55,$C1
        fcb     $FC,$03,$81,$FC,$41,$00
