* chtab4gd_028_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 35 rows x 5 bytes, 312 segment bytes
*
chtab4gd_028_p0:
        fcb     35,5  ; height, width in bytes
        fcb     $C2,$C0,$0F,$03,$FC,$43,$00,$82,$FF,$FF,$C1,$03
        fcb     $F0,$42,$00,$83,$FF,$FC,$FF,$42,$00,$83,$FF,$FC
        fcb     $7F,$42,$00,$83,$FF,$FC,$AF,$42,$00,$C1,$F0,$03
        fcb     $81,$FF,$C1,$03,$F0,$42,$00,$82,$15,$7F,$C1,$0F
        fcb     $C0,$42,$00,$81,$15,$C1,$03,$7C,$43,$00,$81,$15
        fcb     $C1,$03,$50,$43,$00,$C1,$F0,$03,$81,$FF,$C1,$0F
        fcb     $C0,$42,$00,$C1,$C0,$0F,$81,$FF,$C1,$03,$F0,$42
        fcb     $00,$83,$FF,$FC,$7F,$42,$00,$83,$FF,$FC,$7F,$42
        fcb     $00,$C1,$C0,$0A,$82,$AF,$FC,$42,$00,$C1,$C0,$0A
        fcb     $81,$AF,$C1,$03,$50,$42,$00,$C1,$C0,$0A,$81,$AF
        fcb     $C1,$03,$50,$42,$00,$C1,$C0,$0A,$82,$AF,$7F,$C1
        fcb     $3F,$00,$41,$00,$C1,$C0,$0A,$82,$AA,$FF,$C1,$3F
        fcb     $00,$41,$00,$C1,$FC,$00,$82,$AA,$FF,$C1,$3F,$00
        fcb     $41,$00,$C1,$FC,$00,$82,$AA,$FF,$C1,$0F,$C0,$41
        fcb     $00,$C1,$F0,$03,$82,$EA,$FF,$C1,$0F,$C0,$41,$00
        fcb     $C1,$F0,$01,$82,$7E,$AF,$C1,$0F,$F0,$41,$00,$C1
        fcb     $F0,$01,$82,$7E,$AA,$C1,$0F,$F0,$41,$00,$C1,$F0
        fcb     $01,$82,$7E,$AA,$C1,$0F,$F0,$41,$00,$C1,$C0,$0A
        fcb     $82,$AA,$A8,$C1,$0F,$10,$41,$00,$84,$AA,$AA,$AA
        fcb     $FC,$41,$00,$84,$AA,$AA,$83,$FC,$41,$00,$84,$AA
        fcb     $AA,$AF,$FF,$C1,$03,$F0,$00,$84,$AA,$AA,$83,$FF
        fcb     $C1,$0F,$C0,$00,$82,$AA,$AA,$C1,$0F,$80,$81,$3F
        fcb     $C1,$3F,$00,$00,$C1,$C0,$0A,$82,$AA,$A8,$42,$00
        fcb     $C1,$C0,$0A,$82,$AA,$A8,$42,$00,$41,$C1,$C0,$0A
        fcb     $81,$FC,$42,$00,$41,$82,$3F,$FF,$C1,$3F,$00,$41
        fcb     $00,$C1,$FC,$00,$82,$FF,$FF,$C1,$3F,$00,$41,$00
