* chtab4gd_028_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 35 rows x 5 bytes, 318 segment bytes
*
chtab4gd_028_p0:
        fcb     35,5  ; height, width in bytes
        fcb     $C2,$F0,$0F,$03,$FC,$43,$00,$82,$FF,$FF,$C1,$0F
        fcb     $F0,$42,$00,$82,$FF,$FF,$C1,$03,$FC,$42,$00,$82
        fcb     $7F,$FF,$C1,$03,$FC,$42,$00,$82,$AF,$FF,$C1,$03
        fcb     $FC,$42,$00,$C1,$FC,$03,$81,$FF,$C1,$0F,$F0,$42
        fcb     $00,$C1,$C0,$15,$81,$7F,$C1,$3F,$C0,$42,$00,$C2
        fcb     $C0,$15,$03,$7C,$43,$00,$C2,$C0,$15,$0F,$50,$43
        fcb     $00,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$42,$00,$C1
        fcb     $F0,$0F,$81,$FF,$C1,$0F,$F0,$42,$00,$82,$7F,$FF
        fcb     $C1,$03,$FC,$42,$00,$82,$7F,$FF,$C1,$03,$FC,$42
        fcb     $00,$C1,$F0,$0A,$81,$AF,$C1,$03,$FC,$42,$00,$C1
        fcb     $F0,$0A,$81,$AF,$C1,$0F,$50,$42,$00,$C1,$F0,$0A
        fcb     $81,$AF,$C1,$0F,$50,$42,$00,$C1,$F0,$0A,$82,$AF
        fcb     $7F,$42,$00,$C1,$F0,$0A,$82,$AA,$FF,$42,$00,$41
        fcb     $82,$AA,$FF,$42,$00,$41,$82,$AA,$FF,$C1,$3F,$C0
        fcb     $41,$00,$C1,$FC,$03,$82,$EA,$FF,$C1,$3F,$C0,$41
        fcb     $00,$C1,$FC,$01,$82,$7E,$AF,$C1,$0F,$F0,$41,$00
        fcb     $C1,$FC,$01,$82,$7E,$AA,$C1,$0F,$F0,$41,$00,$C1
        fcb     $FC,$01,$82,$7E,$AA,$C1,$0F,$F0,$41,$00,$C1,$F0
        fcb     $0A,$81,$AA,$C2,$03,$A8,$CF,$10,$41,$00,$83,$AA
        fcb     $AA,$AA,$C1,$03,$FC,$41,$00,$82,$AA,$AA,$C2,$3C
        fcb     $83,$03,$FC,$41,$00,$84,$AA,$AA,$AF,$FF,$C1,$0F
        fcb     $F0,$00,$82,$AA,$AA,$C1,$3C,$83,$81,$FF,$C1,$3F
        fcb     $C0,$00,$82,$AA,$AA,$C2,$3F,$80,$C0,$3F,$41,$00
        fcb     $C1,$F0,$0A,$81,$AA,$C1,$03,$A8,$42,$00,$C1,$F0
        fcb     $0A,$81,$AA,$C1,$03,$A8,$42,$00,$41,$C2,$F0,$0A
        fcb     $03,$FC,$42,$00,$41,$C1,$C0,$3F,$81,$FF,$42,$00
        fcb     $41,$82,$FF,$FF,$42,$00
