* chtab4gd_031_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 19 rows x 8 bytes, 207 segment bytes
*
chtab4gd_031_p0:
        fcb     19,8  ; height, width in bytes
        fcb     $42,$C2,$F0,$01,$0F,$50,$44,$00,$42,$C2,$F0,$01
        fcb     $0F,$50,$44,$00,$42,$C1,$F0,$01,$81,$7E,$C1,$0F
        fcb     $80,$43,$00,$43,$C2,$F0,$0A,$0F,$80,$43,$00,$43
        fcb     $C1,$F0,$0A,$81,$A8,$43,$00,$43,$C1,$F0,$0A,$81
        fcb     $AA,$C1,$3F,$80,$42,$00,$43,$C1,$FC,$00,$81,$AA
        fcb     $C1,$3F,$80,$42,$00,$44,$C1,$C0,$0F,$82,$57,$FC
        fcb     $41,$00,$43,$C1,$FC,$00,$83,$57,$FF,$FF,$C1,$03
        fcb     $F0,$00,$43,$C1,$FC,$00,$84,$FF,$57,$FF,$FC,$00
        fcb     $43,$C1,$F0,$03,$84,$FF,$57,$FF,$FC,$00,$43,$85
        fcb     $F5,$57,$FF,$FC,$3F,$00,$81,$FC,$41,$C1,$C0,$08
        fcb     $84,$3F,$F5,$57,$FF,$C1,$03,$F0,$00,$81,$FF,$C1
        fcb     $0C,$C0,$82,$A8,$3F,$C2,$0F,$C0,$C0,$0F,$81,$FF
        fcb     $C1,$0F,$C0,$00,$C1,$FC,$00,$86,$FF,$FF,$0F,$FC
        fcb     $AA,$AA,$41,$00,$C1,$C0,$0A,$86,$FF,$0F,$FF,$FF
        fcb     $AA,$AA,$41,$00,$87,$AA,$AF,$FF,$FF,$AA,$AA,$AA
        fcb     $41,$00,$87,$AA,$AA,$FF,$FF,$F5,$0A,$FE,$41,$00
        fcb     $C1,$C0,$0A,$84,$F5,$7E,$AA,$A8,$C2,$C0,$3F,$03
        fcb     $F0,$41,$00
