#!/usr/bin/env python3
r"""cel_table.py — P3.78 second pass: build the walk table from the pages' LINK MAPS.

WHY THIS IS A SECOND PASS AND NOT PART OF THE BAKE. walk_tab holds ABSOLUTE pointers.
Before the split every one of them named a label in the same link unit, so `fdb v67_p0`
was a thing lwlink could resolve. After the split most of them point into a DIFFERENT
link unit -- every rotating page links at $E000 as its own object -- and lwlink resolves
nothing across that boundary. It does not fail either; a missing external is a link
error, but a table that simply never got written is silence.

So the addresses come from the linker itself. Each page is linked first and its map read
here: `Symbol: v67_p0 (build/obj/cel_pg2.o) = E1C3`. That is the artifact's own account
of where it put something, which is the difference between measuring the binary and
predicting it (a distinction this project has paid for more than once).

AND THE SAME PASS IS WHERE THE PAGES ARE CHECKED AGAINST THE BLOCK. The packer sizes a
page from cel_blit_prep's segment-byte count; the linker's `length` is what actually
shipped. If those disagree the pack is wrong and the failure would be a page whose tail
runs past $FDFF into the constant page and the I/O registers -- silent, and exactly the
class the bank guard exists for. Checked here, loudly, before anything is placed on disk.

    python cel_table.py --pack content/cutscene/chars/cel_pack.json \
                        --map build/obj/cel_pg0.map ... --out build/obj/cel_walk_tab.s
"""
import argparse
import json
import pathlib
import re
import sys

ROOT = pathlib.Path("C:/Projects/POP3_port")
sys.path.insert(0, str(ROOT / "harness/tools"))
import cel_pack as K                                           # noqa: E402

SYM = re.compile(r"^Symbol:\s+(\S+)\s+\(.*?\)\s+=\s+([0-9A-Fa-f]+)\s*$")
SEC = re.compile(r"^Section:\s+\S+\s+\(.*?\)\s+load at ([0-9A-Fa-f]+), length ([0-9A-Fa-f]+)")


def read_map(path):
    syms, load, length = {}, None, None
    for line in pathlib.Path(path).read_text(encoding="utf-8", errors="replace").splitlines():
        m = SYM.match(line)
        if m:
            syms[m.group(1)] = int(m.group(2), 16)
            continue
        m = SEC.match(line)
        if m:
            load, length = int(m.group(1), 16), int(m.group(2), 16)
    return syms, load, length


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pack", required=True)
    ap.add_argument("--map", action="append", default=[],
                    help="a page link map, in page order")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    man = json.loads(pathlib.Path(a.pack).read_text(encoding="utf-8"))
    pages = man["pages"]
    if len(a.map) != len(pages):
        print("*** cel_table: %d maps for %d pages ***" % (len(a.map), len(pages)))
        return 1

    addr = {}                      # label -> absolute address, or None = same unit
    for lab in (l for _k, l in man["resident"]):
        addr[lab] = None           # resident: let the linker resolve it by name
    bad = 0
    for pg, mp in zip(pages, a.map):
        syms, load, length = read_map(mp)
        if load != man["rot_base"]:
            print("*** page %d linked at $%04X, not $%04X (%s) ***"
                  % (pg["index"], load or 0, man["rot_base"], mp))
            bad += 1
        # ★ THE PAGE MUST FIT THE BLOCK, measured on the LINKED artifact.
        if length > K.ROT_CAP:
            print("*** page %d is %d B linked, against a %d B block "
                  "($E000..$FDFF; the top 512 B is constant RAM + I/O) ***"
                  % (pg["index"], length, K.ROT_CAP))
            bad += 1
        # ...and it must actually be the page it says it is.
        for k, lab in pg["cels"]:
            if lab not in syms:
                print("*** page %d map has no symbol %s ***" % (pg["index"], lab))
                bad += 1
                continue
            addr[lab] = syms[lab]
        print("  page %d: linked $%04X length %s B (%s B spare), %d cels"
              % (pg["index"], load or 0, format(length or 0, ","),
                 format(K.ROT_CAP - (length or 0), ","), len(pg["cels"])))
    if bad:
        print("*** cel_table: %d problem(s) — NOT writing the table ***" % bad)
        return 1

    lo, n = man["walk_lo"], man["walk_n"]
    where = {}                     # (cel, facing, phase) -> label
    for k, lab in man["resident"]:
        where[(k[1], k[2], k[3])] = lab
    for pg in pages:
        for k, lab in pg["cels"]:
            where[(k[1], k[2], k[3])] = lab

    L = ["* cel_walk_tab.s " + chr(0x2014) + " the [cel][facing][phase] lookup, at $C004.",
         "* GENERATED by harness/tools/cel_table.py from the pages' LINK MAPS.",
         "* Do not hand-edit and do not commit: it is a build artifact, regenerated",
         "* every build from the maps of the objects it points into.",
         "*",
         "* EIGHT SLOTS PER CEL: two facings x four phases. Facing is chosen by",
         "* co_variant from CH_FACE; -1 is left and NORMAL, 0 is right and MIRRORED",
         "* [FRAMEADV.S:1970]. A 0 slot means the scene never puts this cel on this",
         "* phase, and co_variant falls back to the record's own pointer.",
         "*",
         "* A BARE `fdb label` IS A RESIDENT CEL (this link unit resolves it); a bare",
         "* `fdb $Exxx` IS A CEL IN A ROTATING PAGE, whose address no linker here can",
         "* resolve because it lives in a different unit at the same address as four",
         "* others. Which one is mapped is the beat schedule's job, and the page's own",
         "* signature is what proves the answer at run time.",
         "",
         "cel_walk_tab"]
    n_res = n_rot = n_zero = 0
    for cel in range(lo, lo + n):
        row, note = [], []
        for f in (0, 1):
            for ph in range(4):
                lab = where.get((cel, f, ph))
                if lab is None:
                    row.append("0")
                    n_zero += 1
                elif addr.get(lab) is None:
                    row.append(lab)
                    n_res += 1
                    note.append("%s pinned" % lab)
                else:
                    row.append("$%04X" % addr[lab])
                    n_rot += 1
                    note.append("%s $%04X" % (lab, addr[lab]))
        L.append("                fdb     " + ",".join(row) + "   ; cel %d%s"
                 % (cel, ("  " + ", ".join(note)) if note else ""))
    pathlib.Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    pathlib.Path(a.out).write_text("\n".join(L) + "\n", encoding="utf-8")
    print("  cel_walk_tab.s: %d cels x 8 slots = %d B  (%d pinned, %d paged, %d empty)"
          % (n, n * 16, n_res, n_rot, n_zero))
    return 0


if __name__ == "__main__":
    sys.exit(main())
