#!/usr/bin/env python3
r"""gen_frame_table.py — P5.29: the gameplay FRAME table, carrying Fcheck where a draw is selected.

The shipped cutscene's content/cutscene/cel_table.s (gen_cel_table.py) is the precedent: one
5-byte row per frame, +0 image, +1 Fdx, +2 Fdy, +3 Fcheck (RAW -- "the table carries the FACT
and the engine carries the RULE", P3.65), +4 the Apple width. P5.27 took the width for
gameplay as a per-CEL side table (content/chars/char_cels.s). This is the other half, in the
SAME row shape, so a gameplay draw can apply the rule [CTRLSUBS.S:833-839] at run time:

    ODD X  iff  bit7(Fcheck) == bit7(CharFace)

Rows, for every frame of the two GAMEPLAY frame tables (ALTSET2 is the cutscene's):
    fdef_tab     Fdef, frames 1..N      the kid's and the guard's main set
    alt1_tab     ALTSET1, frames 1..N   the guard's (usealtsets [CTRLSUBS.S:1680-1707])
  +0  image   (Fimage & $7F, 1-based)
  +1  Fdx     (signed)
  +2  Fdy     (signed)
  +3  Fcheck  RAW
  +4  table slot (decodeim: 0..4 = CHTAB1/2/3/4/5) -- where cel_table.s has the width, because a
      gameplay frame's TABLE varies (Fsword's top bits) and the cutscene's never did; the width
      is per cel, in char_cels.s, and is not duplicated here.
A blank slot (Fimage = Fsword = 0) is five zero bytes.

Every field is EVALUATED from FRAMEDEF.S (cel_parity_rule.frame_table), not regex-sliced: the
regex the cutscene side uses skips expression fields such as `-5+5,51-63` (P5.29 §3B).

  python harness/tools/gen_frame_table.py --out content/chars/frame_table.s
"""
import argparse
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import cel_parity_rule as R                                 # noqa: E402

ENTSZ = 5


def rows(name):
    """Rows from the table's FIRST frame number: Fdef is numbered 1..240, ALTSET1 by the game
    frames it stands in for, 150..189 (getaltframe1 indexes it by frame-149)."""
    ft = R.frame_table(name)
    out = []
    for n in range(min(ft), max(ft) + 1):
        fi, fs, fdx, fdy, fc = ft.get(n, (0, 0, 0, 0, 0))
        if fi == 0 and fs == 0:
            out.append((n, None))
            continue
        slot, img = R.decode_table(fi, fs)
        out.append((n, (img, fdx & 0xFF, fdy & 0xFF, fc, slot, fdx, fdy)))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    L = ["* frame_table.s — the gameplay FRAME table (P5.29).",
         "* GENERATED by harness/tools/gen_frame_table.py from FRAMEDEF.S -- do not hand-edit.",
         "*",
         "* Row (n - <tab>_first) = frame n:  +0 image  +1 Fdx  +2 Fdy  +3 Fcheck (RAW)  +4 slot",
         "* cel_table.s's shape (P3.65): the table carries the FACT, the engine the RULE --",
         "*     ODD X iff bit7(Fcheck) == bit7(CharFace)      [CTRLSUBS.S:833-839]",
         "* The Apple width is per CEL, in char_cels.s; it is not repeated here.",
         "FRAME_ENTSZ     equ     %d" % ENTSZ,
         ""]
    total = 0
    for name, lab in (("Fdef", "fdef_tab"), ("ALTSET1", "alt1_tab")):
        rs = rows(name)
        L.append("%s_first    equ     %d" % (lab, rs[0][0]))
        L.append("%s_n        equ     %d" % (lab, len(rs)))
        L.append(lab)
        for n, r in rs:
            if r is None:
                L.append("        fcb     0,0,0,0,0           ; %3d (blank)" % n)
            else:
                img, dx, dy, fc, slot, sdx, sdy = r
                L.append("        fcb     %d,%d,%d,$%02X,%d      ; %3d  CHTAB%d #%d  dx %d dy %d  Fcheck b7=%d"
                         % (img, dx, dy, fc, slot, n, slot + 1, img, sdx, sdy, fc >> 7))
        L.append("")
        total += len(rs) * ENTSZ
    pathlib.Path(a.out).write_text("\n".join(L), encoding="utf-8", newline="\n")
    print("gen_frame_table: Fdef + ALTSET1, %d B -> %s" % (total, a.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
