#!/usr/bin/env python3
r"""xf_tables.py — P5.28: xf_blit's tables as a LINKABLE section, for an engine program.

The probe gets its tables from xform_probe_gen.tables_asm(), as absolute `org` blocks at its
own addresses. An engine link places them where its map says instead, so this emits the same
bytes, in the same order, as one relocatable section:

    M (256, natural)  T1 (256, permuted)  T2 (256, permuted)  9 pairs x (F 256, C 256)

5,376 B. The section must load PAGE-ALIGNED: xf_blit patches the LOW byte of an `andb >XF_M`
operand with the index, so M's high byte must be the whole of its page. The build passes the
section's load address as XF_M and derives the rest (XF_T1 = XF_M+$100, XF_T2 = +$200,
XF_TABS = +$300); this file states that layout and the link map is checked against it.

★ NOT A SECOND GENERATOR. Every byte comes from xform_probe_gen's own M/T/shl/shr/permuted,
and --check compares the emitted bytes with tables_asm()'s, value for value -- the tables
P5.20 and P5.27 measured byte-exact on 6,688 cases.

  python harness/tools/xf_tables.py --out build/gen/xf_tables.s
"""
import argparse
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import xform_probe_gen as G                                 # noqa: E402

SIZE = 256 * 3 + 9 * 512


def table_bytes():
    out = [G.M(b) for b in range(256)]
    out += G.permuted(lambda b: G.T(b, False))
    out += G.permuted(lambda b: G.T(b, True))
    for k in (1, 2, 3):
        for t in (0, 1, 2):
            if t == 0:
                F = (lambda b, k=k: G.shr(b, k))
                C = (lambda b, k=k: G.shl(b, k))
            else:
                F = (lambda b, k=k, s=(t == 2): G.shl(G.T(b, s), k))
                C = (lambda b, k=k, s=(t == 2): G.shr(G.T(b, s), k))
            out += G.permuted(F)
            out += G.permuted(C)
    assert len(out) == SIZE
    return out


def probe_bytes():
    """The probe's own tables, read back out of tables_asm()'s fcb lines, in order."""
    vals = []
    for line in G.tables_asm():
        s = line.strip()
        if s.startswith("fcb"):
            vals += [int(t.strip()[1:], 16) for t in s[3:].split(",")]
    return vals


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    mine = table_bytes()
    ref = probe_bytes()
    if mine != ref:
        bad = [i for i, (x, y) in enumerate(zip(mine, ref)) if x != y]
        raise SystemExit("xf_tables: %d B differ from the probe's tables (first at %d); %d vs %d B"
                         % (len(bad), bad[0] if bad else -1, len(mine), len(ref)))
    L = ["* GENERATED by harness/tools/xf_tables.py -- do not hand-edit.",
         "* xf_blit's tables: M, T1, T2, then 9 (k,t) pairs of F,C. %d B. LOAD PAGE-ALIGNED." % SIZE,
         "                ifdef   OBJTARGET",
         "                section xftab",
         "                export  xf_tables",
         "                endc",
         "xf_tables"]
    L += G.fcb(mine)
    L += ["xf_tables_end"]
    pathlib.Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    pathlib.Path(a.out).write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    print("xf_tables: %d B, identical to the probe's tables_asm() -> %s" % (SIZE, a.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
