#!/usr/bin/env python3
r"""xform_probe_gen.py — P5.20: the probe's tables, its cases, and the GENERATED reference.

There is no shipped oracle for a runtime shift or mirror over gameplay cels, so the reference
is produced by the tools the bake itself uses, through the same files:

  facing 0, phase k : sprite_convert (start_col S)                      -> cel_blit_prep --phase k
  facing 1, phase k : sprite_convert (start_col S, --mirror, and --flip-parity iff 7*apple_w
                      is EVEN -- bake_scene.py:626-631's per-cel rule)  -> cel_blit_prep --phase k

and drawn by cel_blit_prep.simulate (the independent 6809-semantics replay) over the probe's
background. The probe draws ONLY the facing-0 phase-0 stream, transformed at run time, and
the checker compares the two framebuffers byte for byte.

REGISTRATION. A mirrored frame reverses all 4w of its pixels; sprite_convert's --mirror
reverses only the 7*apple_w it converted. The difference is the frame's pad,
d = 4*w0 - 7*apple_w (w0 = the stored width after trailing trim, so d can be negative), and
the runtime draw sits d pixels LEFT of the reference to put the same pixel in the same place.
That is placement arithmetic, the caller's, exactly as the phase is.

Each case is a 10-byte record: fn, stream, dest, A, B, dump length. Case 0 is always the
calibration case (fn = xp_null): the bracket's own cost, subtracted from every other.

--baked (P5.27): the probe draws the COMMITTED bake (content/chars/<tab>/<tab>_<nnn>_p0.s, with
apple_w read from content/chars/char_cels.s) in place of the stream generated here. Nothing
else moves -- the reference, the columns and the flags are computed exactly as before -- so
the run asks P5.20's question of the shipping artifact. bake_chars_check.py confirms the case
records are unchanged and compares every verdict and cycle count with P5.20's own logs.
"""
import argparse
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE / "sprite_tool"))
import sprite_convert as SC                                 # noqa: E402
import cel_blit_prep as P                                   # noqa: E402
from celio import Cel                                       # noqa: E402

IMG = ROOT / "oracle/source/01 POP Source/Images"
OUT = ROOT / "build/xform"

# --- the probe's fixed layout (src/harness/xform_probe.s says the same) -------------
XP_CASES = 0x4200
XP_BUF = 0x6C00
XP_BUF_END = 0x8000
REC = 12                        # fn, stream, dest, A, B, dump length, fill seed, pad (P5.21)
SEED = 0x5B                     # the P5.20 background; P5.21's erase cases use ERASE_SEED
ERASE_SEED = 0xA7
XP_PEEL_CAP = 0x0400            # src/harness/xform_probe.s XP_PEEL..XP_PEEL_END
C_REF = 8                       # the reference's byte column; leaves room for d < 0 and > 0
STRIDE = 80
SWAP = (0, 2, 1, 3)


def bg(n, seed=SEED):
    return [(seed + 0x9D * o) & 0xFF for o in range(n)]


# ------------------------------------------------------------------ tables
def px4(b):
    return [(b >> 6) & 3, (b >> 4) & 3, (b >> 2) & 3, b & 3]


def pk4(p):
    return (p[0] << 6) | (p[1] << 4) | (p[2] << 2) | p[3]


def T(b, swap):
    p = px4(b)[::-1]
    if swap:
        p = [SWAP[v] for v in p]
    return pk4(p)


def shr(b, k):
    return b >> (2 * k)


def shl(b, k):
    return (b << (8 - 2 * k)) & 0xFF


def M(b):
    return pk4([3 if v == 0 else 0 for v in px4(b)])


def permuted(f):
    """Stored so that base+128 indexed by a SIGNED byte b reaches f(b) (shift_row.s item 2)."""
    return [f(j ^ 0x80) for j in range(256)]


def tables_asm():
    L = ["* GENERATED by harness/tools/xform_probe_gen.py -- do not hand-edit.",
         "                org     $2D00",
         "* M: natural order, reached by a patched extended operand"]
    L += fcb(M(b) for b in range(256))
    L += ["                org     $2E00", "* T1: mirror (permuted)"]
    L += fcb(permuted(lambda b: T(b, False)))
    L += ["                org     $2F00", "* T2: mirror + blue<->orange (permuted)"]
    L += fcb(permuted(lambda b: T(b, True)))
    L += ["                org     $3000"]
    for k in (1, 2, 3):
        for t in (0, 1, 2):
            if t == 0:
                F = (lambda b, k=k: shr(b, k))
                C = (lambda b, k=k: shl(b, k))
            else:
                F = (lambda b, k=k, s=(t == 2): shl(T(b, s), k))
                C = (lambda b, k=k, s=(t == 2): shr(T(b, s), k))
            L.append("* pair k=%d t=%d: F then C (permuted)" % (k, t))
            L += fcb(permuted(F))
            L += fcb(permuted(C))
    return L


def fcb(vals):
    vals = list(vals)
    return ["                fcb     " + ",".join("$%02X" % v for v in vals[i:i + 16])
            for i in range(0, len(vals), 16)]


# ------------------------------------------------------------------ cels
def convert(table, idx, start_col, mirror, flip, label):
    path = OUT / "cels" / ("%s.s" % label)
    path.parent.mkdir(parents=True, exist_ok=True)
    SC.convert_one(IMG / table, idx, path, label, start_col, flip, mirror, trim=True, quiet=True)
    return Cel(str(path))


def stream(cel, phase):
    rows, w = P.shift_pixels(cel, phase)
    segs = []
    for r in range(cel.h):
        segs += P.encode_row(rows[r], w)
    bad = P.verify(cel, phase, segs)
    if bad:
        raise SystemExit("reference stream failed its own replay: %r" % (bad[:3],))
    return [cel.h, w] + segs


def nseg(s):
    """Segments (excluding row ends) in a stream -- the unit blit_cel pays its overhead in."""
    n, p = 0, 2
    for _ in range(s[0]):
        while s[p] != P.SEG_END:
            op, c = s[p] >> P.SEG_SHIFT, s[p] & P.SEG_MAX_RUN
            p += 1 + (c if op == P.SEG_BLAST else 2 * c if op == P.SEG_MERGE else 0)
            n += 1
        p += 1
    return n


def expect(ref, h):
    """The reference stream drawn at row 1, column C_REF, over the background."""
    n = STRIDE * (h + 2)
    base = STRIDE + C_REF
    init = {o - base: v for o, v in enumerate(bg(n))}
    fb = P.simulate(ref[2:], ref[0], ref[1], STRIDE, initial=init)
    return [fb[o - base] for o in range(n)]


BAKED = ROOT / "content/chars"


def baked_registry():
    """P5.27: content/chars/char_cels.s -> {(tab, image): apple_w}. Parsed from the file the
    bake emits, so a probe run with --baked exercises the REGISTRY as well as the streams."""
    reg, tab, i = {}, None, 0
    for line in (BAKED / "char_cels.s").read_text(encoding="utf-8").splitlines():
        s = line.split(";")[0].strip()
        if s.endswith("_aw") and " " not in s:
            tab, i = s[:-3], 0
        elif tab and s.lower().startswith("fcb"):
            i += 1
            reg[(tab, i)] = int(s[3:].strip())
        elif s and not s.startswith("*") and "equ" not in s:
            tab = None
    return reg


def baked_stream(table, idx):
    """P5.27: the BAKED facing-0 phase-0 stream, as its committed .s assembles."""
    t = table.replace("IMG.", "").replace(".", "").lower()
    return fcb_values(BAKED / t / ("%s_%03d_p0.s" % (t, idx)))


def cel_cases(table, idx, start_col, tag, baseline=True, baked=None, pl=None, draw="p520"):
    """All (facing, phase) cases for one cel. Returns (streams, cases, meta).

    baked (P5.27): None, or the registry from baked_registry(). When given, the stream the
    probe DRAWS is the committed content/chars bake and apple_w comes from the registry;
    the REFERENCE is still generated here.

    ★★ pl (P5.29): the ORACLE's colour phase for this use of the cel -- the parity of the
    draw X facing LEFT, from cel_parity_rule.gameplay_uses() (bit7(Fcheck) vs CharFace, plus
    SWORDTAB's dx for a sword). None reproduces P5.20's reference exactly: both facings
    coloured at `start_col`, the mirror flipped iff 7*apple_w is even. P5.28's gate showed
    that reference is wrong against the oracle (the mirrored kid blue, not orange) and that
    every check built on it agreed with the wrong colour. With pl, the reference is coloured
    the way the shipped cutscene is (bake_scene.convert_src, Jay-gated at P3.72h on an
    ODD-width mirror), from where the ORACLE draws it:
        facing 0: sprite_convert at a column of parity PL
        facing 1: the oracle's X is the OTHER parity (the face bit flips the comparison), and
                  MLayGen lays the mirror 7*apple_w px left of it [HIRES.S:1202-1208;
                  cel_parity_rule.draw_x], so its left column has parity
                  (1 - PL) XOR (apple_w odd); sprite_convert --mirror there, flipped iff
                  7*apple_w is even (bake_scene.py:626-631).
    Nothing here reads the bake's colouring or the draw's flag: the reference's only parity
    input is the ORACLE's Fcheck, through cel_parity_rule.

    draw: the swap flag the CALLER hands xf_blit, i.e. the half of the draw that is
    placement arithmetic.
        "p520"   P5.20's: facing 0 never swaps; facing 1 swaps iff 7*apple_w is even
        "oracle" P5.29's: swap = PL in BOTH facings. Derived: the stored cel is coloured at
                 even; facing 0 wants parity PL, so swap iff PL; facing 1 wants
                 [(1-PL) xor aw_odd] then the even-width flip [aw_even], and
                 aw_odd xor aw_even = 1, so swap iff PL again.
    """
    raw = SC.get_cel(IMG / table, idx)
    aw, h = raw["w"], raw["h"]
    if baked is not None:
        aw = baked[(table.replace("IMG.", "").replace(".", "").lower(), idx)]
    W = 7 * aw
    flip = (W % 2 == 0)
    if pl is None:
        sc0 = sc1 = start_col
    else:
        sc0 = pl
        sc1 = (1 - pl) ^ (aw & 1)
    src = convert(table, idx, sc0, False, False, "%s_f0" % tag)
    mir = convert(table, idx, sc1, True, flip, "%s_f1" % tag)
    if draw == "p520":
        swap0, swap1 = False, flip
    else:
        swap0 = swap1 = bool(pl)
    # The DRAWN stream is the STORED colouring -- the bake's, at `start_col` -- never the
    # reference's: a draw fed the reference's colouring would agree with it by construction.
    if baked is not None:
        streams = {"%s_src" % tag: baked_stream(table, idx)}
    elif pl is None:
        streams = {"%s_src" % tag: stream(src, 0)}
    else:
        stored = convert(table, idx, start_col, False, False, "%s_st" % tag)
        streams = {"%s_src" % tag: stream(stored, 0)}
    w0 = streams["%s_src" % tag][1]
    d = 4 * w0 - W
    cases = []
    for f in (0, 1):
        for k in range(4):
            ref = stream(src if f == 0 else mir, k)
            want = expect(ref, h)
            refname = "%s_r%d%d" % (tag, f, k)
            if baseline:
                streams[refname] = ref
                cases.append(dict(tag=tag, f=f, k=k, mode="base", fn="blit_cel_full",
                                  stream=refname, col=C_REF, a=0, b=0, h=h, want=want,
                                  nseg=nseg(ref), sbytes=len(ref)))
            if f == 0:
                col, a, b = C_REF, k, (2 if swap0 else 0)
            else:
                p = 4 * C_REF + k - d
                col, a, b = p // 4, p % 4, 1 | (2 if swap1 else 0)
            src0 = streams["%s_src" % tag]
            cases.append(dict(tag=tag, f=f, k=k, mode="xform", fn="xf_blit",
                              stream="%s_src" % tag, col=col, a=a, b=b, h=h, want=want,
                              nseg=nseg(src0), sbytes=len(src0)))
    meta = dict(tag=tag, table=table, idx=idx, start_col=start_col, apple_w=aw, W=W, h=h,
                w0=w0, d=d, flip=flip, footprint=((W + 3) // 4) * h, stored=w0 * h,
                src_bytes=len(streams["%s_src" % tag]), pl=pl, draw=draw)
    return streams, cases, meta


def fcb_values(path):
    """Every byte a cel_blit_prep-emitted .s file assembles to, in order."""
    vals = []
    for line in pathlib.Path(path).read_text().splitlines():
        s = line.split(";")[0].strip()
        if s.lower().startswith("fcb"):
            for tok in s[3:].split(","):
                tok = tok.strip()
                vals.append(int(tok[1:], 16) if tok.startswith("$") else int(tok))
    return vals


def shipped_cases(stem):
    """THE SHIPPED CROSS-CHECK. content/cutscene/chars holds, for a few cels, the bake's own
    facing-0 source AND its baked streams at both facings (P3.65). The runtime transform of
    <stem>_src.s is compared against every shipped <stem>_p<k>.s / <stem>_m_p<k>.s -- an
    oracle the dispatch did not know existed (cel_pack.json's `resident` list holds them)."""
    import re
    d = ROOT / "content/cutscene/chars"
    src_path = d / ("%s_src.s" % stem)
    src = Cel(str(src_path))
    hdr = src_path.read_text()
    m = re.search(r"POP cel: #\d+ \((\d+)x(\d+) bytes\)", hdr)
    aw = int(m.group(1))
    W = 7 * aw
    sc0 = int(re.search(r"start_col=(\d+)", hdr).group(1))
    msrc = d / ("%s_m_src.s" % stem)
    scm = int(re.search(r"start_col=(\d+)", msrc.read_text()).group(1)) if msrc.exists() else sc0
    # the bake flips iff W is even; the runtime must ALSO account for the two facings having
    # been coloured at render columns of different parity, which a same-start_col reference
    # never exercises. Here they are stated, not assumed.
    flip = (W % 2 == 0) ^ ((sc0 - scm) % 2 == 1)
    tag = "ship_%s" % stem
    streams = {"%s_src" % tag: stream(src, 0)}
    d_pad = 4 * src.w - W
    # ONLY what the manifest ships. content/cutscene/chars also holds stale bakes in the
    # pre-P3.85 two-byte format (p11_m_p2.s, last committed at P3.78) that nothing references;
    # a file on disk is not the oracle, the manifest is.
    pack = json.load(open(d / "cel_pack.json"))
    shipped = {lab for _, lab in pack["resident"]}
    for pg in pack["pages"]:
        shipped |= {lab for _, lab in pg["cels"]}
    cases = []
    for f, pat in ((0, "%s_p%d"), (1, "%s_m_p%d")):
        for k in range(4):
            if (pat % (stem, k)) not in shipped:
                continue
            p = d / ((pat % (stem, k)) + ".s")
            ref = fcb_values(p)
            want = expect(ref, src.h)
            if f == 0:
                col, a, b = C_REF, k, 0
            else:
                pp = 4 * C_REF + k - d_pad
                col, a, b = pp // 4, pp % 4, 1 | (2 if flip else 0)
            refname = "%s_r%d%d" % (tag, f, k)
            streams[refname] = ref
            cases.append(dict(tag=tag, f=f, k=k, mode="base", fn="blit_cel_full", stream=refname,
                              col=C_REF, a=0, b=0, h=src.h, want=want, nseg=nseg(ref), sbytes=len(ref)))
            cases.append(dict(tag=tag, f=f, k=k, mode="xform", fn="xf_blit", stream="%s_src" % tag,
                              col=col, a=a, b=b, h=src.h, want=want,
                              nseg=nseg(streams["%s_src" % tag]), sbytes=len(streams["%s_src" % tag])))
    meta = dict(tag=tag, table="shipped:" + stem, idx=0, start_col=sc0, start_col_m=scm, apple_w=aw,
                W=W, h=src.h, w0=src.w, d=d_pad, flip=flip, footprint=((W + 3) // 4) * src.h,
                stored=src.w * src.h, src_bytes=len(streams["%s_src" % tag]))
    return streams, cases, meta


def peel_cases(table, idx, start_col, tag, seen):
    """P5.21: the PEEL every pose of one cel needs, under BOTH storage models.

    blit_save/blit_erase cost depends only on (rows, bytes per row), so a case is emitted for
    each (rows, width) pair not already `seen`; the cel's own record lists which pair each of
    its eight poses uses. A peel covers the frame the draw wrote:
      baked        facing 0: w0 (+1 at phase > 0)      facing 1: the MIRRORED bake's own width
                   (+1) -- its trailing trim differs, so it is a different width, not w0
      transformed  facing 0: as baked                  facing 1: the runtime frame, w0 (+1 when
                   the phase actually drawn, (k - pad) mod 4, is > 0)
    Every pair is a SAVE (onto the P5.20 background) then an ERASE onto a different one, and
    the erase is checked: everything keeps the erase background except the footprint, which
    must come back as what the save took."""
    raw = SC.get_cel(IMG / table, idx)
    aw, h = raw["w"], raw["h"]
    W = 7 * aw
    src = convert(table, idx, start_col, False, False, "%s_f0" % tag)
    mir = convert(table, idx, start_col, True, W % 2 == 0, "%s_f1" % tag)
    w0, wm = src.w, mir.w
    d = 4 * w0 - W
    baked, xf = [], []
    for f in (0, 1):
        for k in range(4):
            baked.append((w0 if f == 0 else wm) + (1 if k else 0))
            kk = k if f == 0 else (k - d) % 4
            xf.append(w0 + (1 if kk else 0))
    cases = []
    n = STRIDE * (h + 2)
    for wd in sorted(set(baked) | set(xf)):
        if (h, wd) in seen:
            continue
        seen.add((h, wd))
        if h * wd > XP_PEEL_CAP:
            raise SystemExit("%s: a %dx%d peel overruns the probe's buffer" % (tag, h, wd))
        ptag = "peel_h%d_w%d" % (h, wd)
        want_e = bg(n, ERASE_SEED)
        save_bg = bg(n, SEED)
        for r in range(h):
            for c in range(wd):
                o = STRIDE * (r + 1) + C_REF + c
                want_e[o] = save_bg[o]
        common = dict(tag=ptag, f=0, k=0, fn=None, stream="0", col=C_REF, a=h, b=wd, h=h)
        cases.append(dict(common, mode="save", fn="blit_save_full", seed=SEED, want=save_bg))
        cases.append(dict(common, mode="erase", fn="blit_erase_full", seed=ERASE_SEED, want=want_e))
    meta = dict(tag=tag, table=table, idx=idx, apple_w=aw, W=W, h=h, w0=w0, wm=wm, d=d,
                footprint=((W + 3) // 4) * h, peel_baked=baked, peel_xf=xf)
    return cases, meta


def lz_case(spec, i):
    """P5.22: time the SHIPPED lz_unpack on a real blob. spec = PATH:OFFSET:LEN of the RAW
    input; it is packed here with the shipped packer and decoded by the 6809 into the checked
    buffer, so the case is byte-verified AND timed. The output must fit the dump window."""
    import lz_pack as LZ
    path, off, n = spec.rsplit(":", 2)
    raw = pathlib.Path(path).read_bytes()[int(off):int(off) + int(n)]
    stream_ = LZ.compress(raw)
    assert LZ.decompress(stream_, len(raw)) == raw
    # THE SHIPPED BLOB FORMAT, not the bare stream: lz_unpack reads a 6-byte header first --
    # $00 unpacked length, $02 packed length, $04 stream offset [lz_pack.pack]. The first cut
    # of this case passed the bare stream and lz_unpack took its first two bytes as a length.
    # Source and destination do not overlap here, so the stream follows the header directly.
    import struct
    blob = struct.pack(">HHH", len(raw), len(stream_), 6) + stream_
    h = -(-(len(raw) + C_REF) // STRIDE)
    total = STRIDE * (h + 2)
    if XP_BUF + total > XP_BUF_END:
        raise SystemExit("%s: %d B does not fit the dump window" % (spec, len(raw)))
    want = bg(total)
    o = STRIDE + C_REF
    want[o:o + len(raw)] = list(raw)
    tag = "lz_%d" % i
    case = dict(tag=tag, f=0, k=0, mode="lz", fn="lz_unpack", stream="%s_blob" % tag, col=C_REF,
                a=0, b=0, h=h, want=want, raw_bytes=len(raw), lz_bytes=len(blob), src=spec)
    return {"%s_blob" % tag: list(blob)}, [case], dict(tag=tag, footprint=len(raw), h=h)


def batch_asm(streams, cases, hmax):
    buflen = STRIDE * (hmax + 2)
    assert XP_BUF + buflen <= XP_BUF_END, "a cel of %d rows does not fit the buffer" % hmax
    L = ["* GENERATED by harness/tools/xform_probe_gen.py -- do not hand-edit.",
         "XP_BUFLEN       equ     %d" % buflen]
    L += tables_asm()
    L += ["                org     $%04X" % XP_CASES,
          "xp_cases"]
    L.append("                fdb     xp_null,0,$%04X,$0000,%d" % (XP_BUF, STRIDE))
    L.append("                fcb     $%02X,0" % SEED)
    for c in cases:
        dest = XP_BUF + STRIDE + c["col"]
        L.append("                fdb     %s,%s,$%04X" % (c["fn"], c["stream"], dest))
        L.append("                fcb     %d,%d" % (c["a"], c["b"]))
        L.append("                fdb     %d" % (STRIDE * (c["h"] + 2)))
        L.append("                fcb     $%02X,0" % c.get("seed", SEED))
    L.append("                fdb     0")
    for name, data in streams.items():
        L.append(name)
        L += fcb(data)
    L += ["xp_data_end",
          "                ifgt    xp_data_end-$%04X" % XP_BUF,
          "                error   \"cases and streams overrun the buffer\"",
          "                endc"]
    return L


def main():
    ap = argparse.ArgumentParser(description="P5.20 probe generator")
    ap.add_argument("--cel", action="append", default=[],
                    help="TABLE:INDEX[:START_COL]  e.g. IMG.CHTAB1:64")
    ap.add_argument("--all-gameplay", action="store_true",
                    help="every non-empty cel of CHTAB1/2/3/4.GD/5")
    ap.add_argument("--no-baseline", action="store_true")
    ap.add_argument("--shipped", action="append", default=[],
                    help="a content/cutscene/chars stem with _src.s and shipped bakes, e.g. p11")
    ap.add_argument("--out-prefix", default="b", help="batch file prefix (keeps runs apart)")
    ap.add_argument("--lz", action="append", default=[],
                    help="P5.22: PATH:OFFSET:LEN -- time lz_unpack on that slice of a raw file")
    ap.add_argument("--peel", action="store_true",
                    help="P5.21: blit_save/blit_erase at every pose's (rows, width), not draws")
    ap.add_argument("--all-guards", action="store_true",
                    help="P5.27: every non-empty cel of CHTAB4.FAT/SHAD/SKEL/VIZ")
    ap.add_argument("--baked", action="store_true",
                    help="P5.27: draw the committed content/chars streams (apple_w from its "
                         "registry) instead of generating them; the reference is unchanged")
    ap.add_argument("--parity", choices=("oracle", "even"), default="oracle",
                    help="P5.29: the REFERENCE's colour phase. oracle = per USE, from the oracle's "
                         "Fcheck (cel_parity_rule.gameplay_uses); even = P5.20's, every cel at "
                         "--start-col (shown wrong by Jay at P5.28)")
    ap.add_argument("--draw", choices=("oracle", "p520"), default="oracle",
                    help="P5.29: the swap flag the caller gives xf_blit. p520 = the UNCHANGED draw "
                         "(swap only with the mirror, iff 7*apple_w even); oracle = swap = PL")
    ap.add_argument("--start-col", type=int, default=0)
    ap.add_argument("--cap", type=int, default=XP_BUF - XP_CASES - 64,
                    help="bytes of case records + streams per batch")
    a = ap.parse_args()

    sel = []
    for s in a.cel:
        parts = s.split(":")
        sel.append((parts[0], int(parts[1]), int(parts[2]) if len(parts) > 2 else a.start_col))
    if a.all_gameplay:
        for t in ("IMG.CHTAB1", "IMG.CHTAB2", "IMG.CHTAB3", "IMG.CHTAB4.GD", "IMG.CHTAB5"):
            for c in SC.load_chtable(IMG / t):
                if c is not None and c["w"] and c["h"]:
                    sel.append((t, c["idx"], a.start_col))
    if a.all_guards:
        for t in ("IMG.CHTAB4.FAT", "IMG.CHTAB4.SHAD", "IMG.CHTAB4.SKEL", "IMG.CHTAB4.VIZ"):
            for c in SC.load_chtable(IMG / t):
                if c is not None and c["w"] and c["h"]:
                    sel.append((t, c["idx"], a.start_col))
    reg = baked_registry() if a.baked else None

    # ★ P5.29: THE UNIT BECOMES THE (cel, PL) USE. A cel the oracle draws at both colour phases
    # gets two units, tagged _pl0/_pl1; a cel no frame table names keeps one unit at PL 0 (P5.20's
    # reference, said so in the case file). So `--all-gameplay` is no longer 290 x 16 = 4,640
    # cases, and the new count is not comparable with the old under the same name.
    unused = []
    if a.parity == "oracle" and not a.peel:
        sys.path.insert(0, str(HERE))
        import cel_parity_rule as R
        uses = R.gameplay_uses()
        slot = {"IMG.CHTAB1": 0, "IMG.CHTAB2": 1, "IMG.CHTAB3": 2, "IMG.CHTAB5": 4}
        exp = []
        for t, i, sc in sel:
            s = 3 if t.startswith("IMG.CHTAB4") else slot[t]
            pls = sorted(uses.get((s, i), {}))
            if not pls:
                unused.append("%s:%d" % (t, i))
                pls = [0]
            for p in pls:
                exp.append((t, i, sc, p, len(pls) > 1))
        sel = exp
        print("xform_probe_gen: parity=oracle draw=%s -> %d (cel, PL) units; %d cel(s) no frame "
              "table names (reference at PL 0): %s" % (a.draw, len(sel), len(unused), " ".join(unused)))
    else:
        sel = [(t, i, sc, None, False) for t, i, sc in sel]

    OUT.mkdir(parents=True, exist_ok=True)
    pre = a.out_prefix
    for pat in ("%s[0-9][0-9][0-9]_gen.s", "%s[0-9][0-9][0-9]_cases.json",
                "%s[0-9][0-9][0-9].log", "%s[0-9][0-9][0-9].log.json"):
        for old in OUT.glob(pat % pre):
            old.unlink()

    units = [("cel", s) for s in sel] + [("ship", s) for s in a.shipped] + \
            [("lz", (s, i)) for i, s in enumerate(a.lz)]
    batches, cur = [], None
    seen, peel_metas = set(), []
    for kind, u in units:
        if kind == "cel" and a.peel:
            table, idx, sc = u[:3]
            tag = "c_%s_%d" % (table.replace("IMG.", "").replace(".", "").lower(), idx)
            cases, pm = peel_cases(table, idx, sc, tag, seen)
            peel_metas.append(pm)
            streams = {}
            meta = dict(tag=tag, footprint=pm["footprint"], h=pm["h"])
            # the checker keys its table by tag; give each (rows, width) pair a meta of its own
            pair_metas = [dict(tag=c["tag"], footprint=c["a"] * c["b"], h=c["h"])
                          for c in cases if c["mode"] == "save"]
        elif kind == "lz":
            streams, cases, meta = lz_case(*u)
        elif kind == "cel":
            table, idx, sc, pl, dual = u
            tag = "c_%s_%d" % (table.replace("IMG.", "").replace(".", "").lower(), idx)
            if dual:
                tag += "_pl%d" % pl
            streams, cases, meta = cel_cases(table, idx, sc, tag, baseline=not a.no_baseline,
                                             baked=reg, pl=pl, draw=a.draw)
        else:
            streams, cases, meta = shipped_cases(u)
        size = sum(len(v) for v in streams.values()) + REC * len(cases)
        if size > a.cap:
            raise SystemExit("%s alone needs %d B, over the %d B batch" % (meta["tag"], size, a.cap))
        if cur is None or cur["size"] + size > a.cap:
            cur = dict(streams={}, cases=[], metas=[], size=REC + 2, hmax=0)
            batches.append(cur)
        cur["streams"].update(streams)
        cur["cases"] += cases
        if kind == "cel" and a.peel:
            cur["metas"] += pair_metas
        else:
            cur["metas"].append(meta)
        cur["size"] += size
        cur["hmax"] = max(cur["hmax"], meta["h"])

    for i, b in enumerate(batches):
        (OUT / ("%s%03d_gen.s" % (pre, i))).write_text(
            "\n".join(batch_asm(b["streams"], b["cases"], b["hmax"])) + "\n", newline="\n")
        recs = [dict(tag="calib", mode="null", dlen=STRIDE)] + [
            {k: v for k, v in c.items()} for c in b["cases"]]
        (OUT / ("%s%03d_cases.json" % (pre, i))).write_text(json.dumps(dict(cels=b["metas"], cases=recs)))
    if a.peel:
        (OUT / ("%s_peel_poses.json" % pre)).write_text(json.dumps(peel_metas))
    print("xform_probe_gen: %d units -> %d batch(es) '%s': %s"
          % (len(units), len(batches), pre,
             ", ".join("%d cases/%d B" % (len(b["cases"]), b["size"]) for b in batches)))


if __name__ == "__main__":
    main()
