* chtab1_020_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 31 rows x 7 bytes, 281 segment bytes
*
chtab1_020_p0:
        fcb     31,7  ; height, width in bytes
        fcb     $C1,$FC,$03,$81,$FF,$45,$00,$82,$7F,$FF,$C1,$3F
        fcb     $C0,$44,$00,$82,$7F,$FF,$C1,$3F,$C0,$44,$00,$C1
        fcb     $FC,$03,$81,$FF,$C1,$3F,$C0,$44,$00,$C1,$F0,$0A
        fcb     $83,$FF,$FF,$AF,$C1,$03,$FC,$42,$00,$C1,$F0,$0A
        fcb     $84,$AF,$FF,$FF,$FF,$C1,$3F,$C0,$41,$00,$C2,$F0
        fcb     $0A,$3C,$83,$84,$FF,$EA,$AA,$AA,$C1,$03,$A8,$00
        fcb     $41,$C1,$FC,$03,$84,$EA,$AA,$AA,$AA,$C1,$03,$A8
        fcb     $00,$42,$C3,$F0,$0A,$3F,$80,$F0,$0F,$81,$FF,$C1
        fcb     $3F,$C0,$00,$44,$C1,$C0,$3F,$81,$FF,$C1,$3F,$C0
        fcb     $00,$44,$C1,$C0,$3F,$81,$FF,$C1,$3F,$C0,$00,$44
        fcb     $C1,$F0,$0F,$81,$FF,$C1,$3F,$C0,$00,$44,$C1,$F0
        fcb     $0F,$81,$FF,$C1,$3F,$C0,$00,$44,$C1,$F0,$0F,$81
        fcb     $FF,$41,$00,$44,$C1,$C0,$3F,$81,$FF,$41,$00,$44
        fcb     $C1,$C0,$3F,$81,$FF,$41,$00,$44,$C1,$C0,$3F,$81
        fcb     $FF,$41,$00,$44,$82,$FF,$FF,$41,$00,$44,$82,$FF
        fcb     $FF,$41,$00,$44,$82,$FF,$FF,$41,$00,$44,$82,$FF
        fcb     $FF,$41,$00,$44,$82,$FF,$FF,$41,$00,$44,$C1,$C0
        fcb     $3F,$81,$FF,$C1,$3F,$C0,$00,$44,$C1,$C0,$3F,$81
        fcb     $FF,$C1,$3F,$C0,$00,$44,$C1,$F0,$0F,$81,$FF,$41
        fcb     $00,$45,$81,$FF,$C1,$3F,$C0,$00,$45,$81,$FF,$C1
        fcb     $3F,$C0,$00,$44,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0
        fcb     $00,$44,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$00,$44
        fcb     $C1,$F0,$0F,$81,$FF,$C1,$3F,$C0,$00,$44,$81,$FF
        fcb     $C1,$03,$FC,$41,$00
