* chtab1_042_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 27 rows x 11 bytes, 373 segment bytes
*
chtab1_042_p0:
        fcb     27,11  ; height, width in bytes
        fcb     $44,$C2,$C0,$3F,$3F,$C0,$45,$00,$43,$C1,$FC,$03
        fcb     $82,$FF,$F7,$C1,$03,$FC,$44,$00,$43,$C1,$FC,$03
        fcb     $83,$EF,$EA,$FF,$C1,$3F,$80,$43,$00,$43,$C1,$FC
        fcb     $03,$83,$AF,$EA,$FE,$C1,$03,$A8,$43,$00,$43,$C1
        fcb     $FC,$03,$84,$FE,$AF,$EA,$AA,$C1,$3F,$80,$42,$00
        fcb     $43,$C1,$FC,$03,$84,$EA,$AF,$FF,$EA,$C1,$03,$A8
        fcb     $42,$00,$45,$C1,$FC,$03,$82,$FF,$FE,$C1,$03,$A8
        fcb     $42,$00,$45,$C1,$FC,$03,$83,$FF,$EA,$FF,$C1,$3F
        fcb     $80,$41,$00,$45,$C1,$FC,$03,$82,$FF,$FF,$C2,$3F
        fcb     $C0,$03,$A8,$41,$00,$46,$82,$FF,$FF,$C2,$3F,$C0
        fcb     $03,$A8,$41,$00,$46,$82,$FF,$FF,$C3,$3F,$C0,$F0
        fcb     $0A,$3F,$80,$00,$46,$82,$FF,$FF,$C3,$3F,$C0,$F0
        fcb     $0A,$3F,$80,$00,$45,$83,$FF,$FF,$FF,$C1,$0F,$F0
        fcb     $42,$00,$44,$84,$FF,$FF,$FF,$FF,$C1,$0F,$F0,$42
        fcb     $00,$43,$C1,$F0,$0F,$84,$FF,$FF,$FF,$FF,$C1,$0F
        fcb     $F0,$42,$00,$42,$C1,$FC,$03,$85,$FF,$FF,$FF,$FF
        fcb     $FF,$C1,$0F,$F0,$42,$00,$42,$C1,$F0,$0F,$85,$FF
        fcb     $FF,$FF,$FF,$FF,$C2,$0F,$F0,$CF,$10,$41,$00,$42
        fcb     $C1,$FC,$03,$82,$FF,$FF,$C1,$0F,$F0,$82,$FF,$FF
        fcb     $C2,$0F,$F0,$03,$FC,$41,$00,$42,$C1,$FC,$03,$81
        fcb     $FF,$42,$C1,$C0,$3F,$81,$FF,$C1,$0F,$F0,$81,$FF
        fcb     $C1,$3F,$C0,$00,$C1,$F3,$08,$41,$C2,$F0,$0A,$0F
        fcb     $F0,$42,$C1,$F0,$0F,$81,$FF,$C3,$0F,$F0,$0F,$F0
        fcb     $3F,$80,$00,$C1,$FC,$01,$41,$C1,$C3,$3C,$43,$C1
        fcb     $FC,$03,$82,$FF,$FF,$42,$00,$C1,$FC,$03,$81,$FF
        fcb     $C1,$0F,$F0,$43,$C1,$FC,$03,$82,$FF,$FF,$C1,$3F
        fcb     $C0,$41,$00,$41,$81,$FF,$C1,$3F,$C0,$44,$82,$FF
        fcb     $FF,$C1,$3F,$C0,$41,$00,$41,$C2,$C0,$3F,$3F,$C0
        fcb     $44,$82,$FF,$FF,$C1,$3F,$C0,$41,$00,$41,$C1,$CF
        fcb     $10,$45,$C1,$C0,$3F,$81,$FF,$42,$00,$47,$C2,$F0
        fcb     $0F,$03,$FC,$42,$00,$47,$C2,$FC,$03,$0F,$F0,$42
        fcb     $00
