* chtab1_027_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 26 rows x 9 bytes, 301 segment bytes
*
chtab1_027_p0:
        fcb     26,9  ; height, width in bytes
        fcb     $41,$C2,$FC,$03,$03,$FC,$46,$00,$41,$C1,$C0,$3F
        fcb     $81,$FF,$C1,$3F,$C0,$45,$00,$41,$C1,$C0,$3F,$81
        fcb     $FF,$C1,$3F,$C0,$45,$00,$41,$82,$FF,$FF,$C1,$0F
        fcb     $F0,$45,$00,$41,$C1,$CF,$10,$83,$FF,$FF,$AA,$C1
        fcb     $0F,$F0,$43,$00,$42,$C2,$03,$A8,$C0,$3F,$82,$FF
        fcb     $FF,$43,$00,$42,$C2,$F3,$08,$C0,$3E,$82,$AF,$FF
        fcb     $C1,$0F,$F0,$42,$00,$43,$C1,$C0,$3E,$82,$AA,$FF
        fcb     $C1,$03,$FC,$42,$00,$44,$83,$AF,$FF,$AA,$42,$00
        fcb     $44,$C1,$F0,$0A,$82,$AF,$FF,$C1,$3F,$C0,$41,$00
        fcb     $45,$82,$AA,$FF,$C1,$3F,$C0,$41,$00,$44,$C1,$C0
        fcb     $3F,$82,$EA,$AF,$C1,$3F,$C0,$41,$00,$44,$82,$FF
        fcb     $FE,$C1,$03,$A8,$42,$00,$43,$C1,$FC,$03,$83,$FF
        fcb     $EA,$FF,$C1,$3F,$80,$41,$00,$43,$C1,$F0,$0F,$83
        fcb     $FF,$FE,$FF,$C1,$03,$A8,$41,$00,$43,$C1,$C0,$3F
        fcb     $83,$FF,$FE,$FF,$C1,$03,$A8,$41,$00,$43,$C1,$C0
        fcb     $3F,$82,$FF,$FF,$C1,$03,$FC,$42,$00,$43,$C1,$C0
        fcb     $3F,$82,$FF,$FF,$C1,$3F,$C0,$42,$00,$43,$83,$FF
        fcb     $FF,$FF,$41,$C2,$C0,$3F,$3F,$C0,$00,$43,$85,$EF
        fcb     $FF,$FF,$FF,$FF,$C1,$3F,$C0,$00,$43,$C2,$F0,$0F
        fcb     $F0,$0F,$81,$FF,$C3,$0F,$F0,$C0,$3F,$3F,$C0,$00
        fcb     $43,$C2,$F0,$0F,$FC,$03,$81,$FF,$C3,$3F,$C0,$F0
        fcb     $0F,$3F,$C0,$00,$43,$C1,$F0,$0F,$43,$C2,$F0,$0F
        fcb     $3F,$C0,$00,$43,$C1,$C0,$3F,$43,$C2,$F0,$0F,$3F
        fcb     $C0,$00,$42,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$42
        fcb     $C1,$F3,$08,$41,$00,$42,$C1,$F0,$0F,$81,$FF,$45
        fcb     $00
