* chtab1_062_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 30 rows x 3 bytes, 242 segment bytes
*
chtab1_062_p0:
        fcb     30,3  ; height, width in bytes
        fcb     $41,$C2,$FC,$03,$0F,$F0,$00,$41,$C2,$F0,$0F,$03
        fcb     $FC,$00,$41,$81,$FF,$C1,$03,$FC,$00,$C1,$FC,$03
        fcb     $81,$FF,$C1,$03,$FC,$00,$C1,$FC,$03,$81,$FF,$C1
        fcb     $03,$FC,$00,$C1,$C0,$17,$81,$FF,$C1,$03,$FC,$00
        fcb     $C1,$C0,$17,$81,$FF,$C1,$03,$FC,$00,$C1,$C0,$17
        fcb     $81,$FF,$C1,$03,$FC,$00,$C1,$FC,$03,$81,$FF,$C1
        fcb     $03,$FC,$00,$C1,$F0,$0F,$81,$FF,$C1,$03,$FC,$00
        fcb     $C1,$F0,$0F,$81,$FF,$C1,$03,$FC,$00,$C1,$F0,$0F
        fcb     $81,$FF,$C1,$03,$FC,$00,$C1,$F0,$0F,$81,$FF,$C1
        fcb     $0F,$F0,$00,$C1,$F0,$0F,$81,$FF,$C1,$0F,$F0,$00
        fcb     $C1,$FC,$03,$81,$FF,$C1,$0F,$F0,$00,$C1,$FC,$03
        fcb     $81,$FF,$C1,$0F,$F0,$00,$C1,$FC,$03,$81,$FF,$C1
        fcb     $0F,$F0,$00,$41,$81,$FF,$C1,$0F,$F0,$00,$41,$81
        fcb     $FF,$C1,$0F,$F0,$00,$41,$81,$FF,$C1,$0F,$F0,$00
        fcb     $41,$81,$FF,$C1,$0F,$F0,$00,$41,$81,$FF,$C1,$3F
        fcb     $C0,$00,$C1,$FC,$03,$81,$FF,$C1,$03,$FC,$00,$C1
        fcb     $F0,$0F,$81,$FF,$C1,$03,$FC,$00,$C2,$F0,$0F,$03
        fcb     $FC,$41,$00,$C2,$F0,$0F,$0F,$F0,$41,$00,$C2,$F0
        fcb     $0F,$3F,$C0,$41,$00,$81,$7F,$C1,$3F,$C0,$41,$00
        fcb     $C2,$F0,$0F,$3F,$C0,$41,$00,$C2,$FC,$03,$0F,$F0
        fcb     $41,$00
