* chtab1_026_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 27 rows x 11 bytes, 332 segment bytes
*
chtab1_026_p0:
        fcb     27,11  ; height, width in bytes
        fcb     $41,$81,$3F,$C1,$0F,$C0,$48,$00,$C1,$F0,$03,$82
        fcb     $FF,$FC,$48,$00,$C1,$F0,$03,$82,$FF,$FC,$48,$00
        fcb     $C1,$C0,$0F,$83,$FF,$FF,$FF,$C1,$03,$F0,$46,$00
        fcb     $C1,$F0,$01,$84,$0A,$AF,$EA,$FF,$C1,$3F,$00,$45
        fcb     $00,$41,$C1,$C0,$0A,$83,$EA,$AF,$AF,$C1,$3F,$C0
        fcb     $45,$00,$41,$C3,$FC,$00,$0C,$80,$0C,$80,$81,$AF
        fcb     $C1,$03,$F0,$45,$00,$43,$C1,$FC,$00,$82,$AF,$FC
        fcb     $45,$00,$43,$C1,$FC,$00,$82,$AF,$FF,$C1,$3F,$00
        fcb     $44,$00,$43,$C1,$FC,$00,$82,$AF,$FF,$C1,$3F,$00
        fcb     $44,$00,$43,$C1,$FC,$00,$82,$AF,$FF,$C1,$0F,$C0
        fcb     $44,$00,$43,$C1,$F0,$0A,$82,$AF,$FF,$C1,$0F,$C0
        fcb     $44,$00,$43,$C1,$F0,$0A,$82,$FF,$FF,$C1,$0F,$C0
        fcb     $44,$00,$43,$83,$FF,$FF,$3F,$C1,$0F,$C0,$44,$00
        fcb     $42,$C1,$FC,$00,$83,$FF,$FF,$FF,$C1,$03,$F0,$44
        fcb     $00,$42,$C1,$C0,$0F,$83,$FF,$FF,$FF,$C1,$03,$F0
        fcb     $44,$00,$42,$85,$FF,$0F,$FF,$FC,$3F,$44,$00,$41
        fcb     $C1,$FC,$00,$82,$FF,$FF,$C1,$30,$03,$82,$FF,$FC
        fcb     $44,$00,$41,$C1,$FC,$03,$81,$FF,$C2,$0F,$F0,$FC
        fcb     $00,$83,$FF,$FF,$FF,$C1,$03,$F0,$81,$3F,$C1,$0F
        fcb     $C0,$00,$41,$C1,$FC,$03,$81,$FF,$C1,$3F,$00,$41
        fcb     $C1,$C0,$3F,$84,$FF,$FF,$FF,$FF,$C1,$0F,$C0,$00
        fcb     $41,$C1,$C0,$0F,$81,$FC,$42,$C1,$C0,$0F,$82,$FF
        fcb     $FF,$C3,$03,$F0,$C0,$0F,$0F,$C0,$00,$41,$C1,$C0
        fcb     $0F,$81,$FC,$43,$82,$3F,$FF,$C3,$3F,$00,$F0,$03
        fcb     $0F,$C0,$00,$41,$C2,$C0,$0F,$03,$F0,$46,$C2,$FC
        fcb     $00,$0F,$80,$00,$C2,$FC,$00,$03,$FC,$49,$00,$81
        fcb     $FF,$C1,$03,$FC,$49,$00,$81,$FF,$C1,$03,$F0,$49
        fcb     $00,$C2,$C0,$0F,$03,$F0,$49,$00
