* chtab1_058_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 34 rows x 5 bytes, 314 segment bytes
*
chtab1_058_p0:
        fcb     34,5  ; height, width in bytes
        fcb     $43,$81,$FF,$C1,$3F,$C0,$00,$42,$C1,$F0,$0F,$81
        fcb     $FF,$C1,$3F,$C0,$00,$42,$C2,$F0,$0F,$03,$FC,$41
        fcb     $00,$42,$C1,$F0,$0F,$81,$F5,$41,$00,$42,$C1,$F0
        fcb     $0F,$81,$F5,$41,$00,$42,$C1,$F0,$0F,$81,$F5,$41
        fcb     $00,$41,$C1,$FC,$03,$82,$FF,$FF,$41,$00,$41,$C1
        fcb     $FC,$03,$81,$FF,$C1,$0F,$50,$41,$00,$41,$C1,$FC
        fcb     $03,$81,$FF,$C1,$0F,$50,$41,$00,$41,$C1,$F0,$0F
        fcb     $81,$FF,$C1,$0F,$50,$41,$00,$41,$C1,$F0,$0F,$81
        fcb     $FF,$C1,$0F,$50,$41,$00,$41,$C1,$C0,$3F,$81,$FF
        fcb     $C1,$0F,$50,$41,$00,$41,$C1,$C0,$3F,$81,$FF,$C1
        fcb     $0F,$50,$41,$00,$41,$83,$FF,$55,$FF,$41,$00,$41
        fcb     $83,$FF,$F5,$FF,$41,$00,$41,$82,$FF,$FF,$C1,$0F
        fcb     $F0,$41,$00,$C1,$FC,$03,$82,$FF,$FF,$C1,$0F,$F0
        fcb     $41,$00,$C1,$FC,$03,$83,$FF,$FF,$FF,$41,$00,$41
        fcb     $83,$FF,$FF,$FF,$C1,$3F,$C0,$00,$41,$83,$FF,$FF
        fcb     $FF,$C1,$0F,$F0,$00,$41,$83,$FF,$FF,$FF,$C1,$3F
        fcb     $C0,$00,$41,$83,$F7,$FF,$FF,$C1,$3F,$C0,$00,$41
        fcb     $81,$FF,$C1,$3C,$C3,$81,$FF,$41,$00,$41,$82,$FF
        fcb     $EF,$C1,$03,$FC,$41,$00,$41,$82,$FF,$FF,$C1,$0F
        fcb     $F0,$41,$00,$41,$82,$FF,$FF,$C1,$3F,$C0,$41,$00
        fcb     $C1,$FC,$03,$82,$FF,$FF,$C1,$0F,$F0,$41,$00,$C1
        fcb     $FC,$03,$82,$FF,$FF,$C1,$03,$FC,$41,$00,$C1,$F0
        fcb     $0F,$81,$FF,$41,$C1,$3F,$80,$41,$00,$C2,$F0,$0F
        fcb     $03,$FC,$43,$00,$C2,$F0,$0F,$03,$FC,$43,$00,$C2
        fcb     $F0,$0F,$0F,$F0,$43,$00,$C1,$F0,$0F,$81,$FF,$C1
        fcb     $3F,$C0,$42,$00,$C1,$F0,$0F,$81,$FF,$C1,$3F,$C0
        fcb     $42,$00
