* chtab1_046_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 39 rows x 4 bytes, 332 segment bytes
*
chtab1_046_p0:
        fcb     39,4  ; height, width in bytes
        fcb     $41,$C1,$FC,$03,$81,$FF,$41,$00,$41,$C1,$C0,$3F
        fcb     $81,$FF,$C1,$3F,$C0,$00,$41,$C1,$C0,$3F,$81,$FF
        fcb     $C1,$3F,$C0,$00,$42,$C2,$F0,$0F,$3F,$C0,$00,$41
        fcb     $C1,$F0,$0A,$81,$AF,$C1,$3F,$C0,$00,$41,$C1,$F0
        fcb     $0A,$81,$AF,$C1,$3F,$C0,$00,$41,$C1,$F0,$0A,$81
        fcb     $AF,$41,$00,$C1,$FC,$03,$81,$FF,$C1,$03,$E8,$41
        fcb     $00,$41,$82,$FF,$EF,$C1,$3F,$C0,$00,$C1,$F0,$0A
        fcb     $82,$FF,$EF,$C1,$0F,$F0,$00,$C1,$F0,$0A,$82,$FF
        fcb     $FF,$C1,$3F,$C0,$00,$C1,$F0,$0A,$82,$FF,$FF,$C1
        fcb     $3F,$C0,$00,$C1,$F0,$0A,$82,$FF,$FF,$41,$00,$C1
        fcb     $F0,$0A,$82,$FF,$FF,$41,$00,$C1,$F0,$0A,$82,$AF
        fcb     $FF,$41,$00,$C1,$F0,$0A,$82,$AF,$FF,$C1,$3F,$C0
        fcb     $00,$41,$82,$AA,$FF,$C1,$3F,$C0,$00,$C1,$F0,$0F
        fcb     $82,$EA,$FF,$C1,$3F,$C0,$00,$C1,$F0,$0F,$82,$FE
        fcb     $AA,$C1,$3F,$80,$00,$C1,$F0,$0F,$82,$FF,$EA,$C1
        fcb     $3F,$80,$00,$C1,$F0,$0F,$82,$FF,$EA,$C1,$3F,$80
        fcb     $00,$C1,$FC,$03,$82,$FF,$FF,$41,$00,$C1,$FC,$03
        fcb     $82,$FF,$FF,$41,$00,$C1,$FC,$03,$82,$FF,$FF,$41
        fcb     $00,$41,$82,$FF,$FF,$41,$00,$41,$82,$FF,$FF,$41
        fcb     $00,$41,$C1,$C0,$3F,$81,$FF,$C1,$3F,$C0,$00,$41
        fcb     $C1,$F0,$0F,$81,$FF,$C1,$3F,$C0,$00,$41,$C1,$F0
        fcb     $0F,$81,$FF,$C1,$3F,$C0,$00,$41,$C1,$F0,$0F,$81
        fcb     $FF,$41,$00,$41,$C1,$C0,$3F,$81,$FF,$41,$00,$41
        fcb     $C1,$C0,$3F,$81,$FF,$41,$00,$41,$C1,$C0,$3F,$81
        fcb     $FF,$41,$00,$41,$C1,$C0,$3F,$42,$00,$41,$81,$FF
        fcb     $42,$00,$41,$81,$FF,$42,$00,$C1,$FC,$03,$81,$FF
        fcb     $42,$00,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$41,$00
        fcb     $41,$81,$FF,$C1,$0F,$F0,$41,$00
