* chtab1_060_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 31 rows x 4 bytes, 257 segment bytes
*
chtab1_060_p0:
        fcb     31,4  ; height, width in bytes
        fcb     $42,$C2,$F0,$0F,$03,$FC,$00,$42,$C2,$C0,$3F,$03
        fcb     $FC,$00,$42,$C2,$C0,$3F,$0F,$F0,$00,$42,$C2,$C0
        fcb     $3F,$0F,$50,$00,$42,$C2,$C0,$3F,$0F,$50,$00,$42
        fcb     $81,$FF,$41,$00,$41,$C1,$F0,$0F,$81,$FF,$C1,$3F
        fcb     $C0,$00,$41,$C1,$C0,$3F,$81,$FF,$C1,$0F,$F0,$00
        fcb     $41,$C1,$C0,$3F,$81,$FF,$C1,$0F,$50,$00,$C1,$FC
        fcb     $01,$82,$7F,$FF,$C1,$0F,$50,$00,$C1,$FC,$01,$82
        fcb     $7F,$F5,$41,$00,$C1,$FC,$03,$82,$FF,$F5,$41,$00
        fcb     $C1,$FC,$03,$82,$FF,$F5,$41,$00,$C1,$FC,$03,$82
        fcb     $FF,$F5,$C1,$0F,$50,$00,$C1,$F0,$0F,$82,$FF,$FF
        fcb     $C1,$0F,$50,$00,$C1,$F0,$0F,$81,$FF,$C2,$03,$FC
        fcb     $C0,$15,$00,$C1,$F0,$0F,$81,$FF,$C2,$03,$FC,$CF
        fcb     $10,$00,$C1,$FC,$03,$82,$FF,$FF,$41,$00,$C1,$FC
        fcb     $03,$82,$FF,$FF,$41,$00,$41,$82,$FF,$FF,$C1,$3F
        fcb     $C0,$00,$41,$82,$FF,$FF,$C1,$3F,$C0,$00,$41,$82
        fcb     $FF,$FF,$C1,$0F,$F0,$00,$41,$82,$FF,$FF,$C1,$3F
        fcb     $C0,$00,$C1,$FC,$03,$82,$FF,$FF,$C1,$3F,$C0,$00
        fcb     $C1,$FC,$03,$82,$FE,$FF,$C1,$3F,$C0,$00,$83,$F7
        fcb     $FF,$7F,$41,$00,$81,$FF,$41,$81,$FF,$41,$00,$81
        fcb     $FF,$41,$C1,$03,$FC,$41,$00,$81,$7F,$41,$81,$FF
        fcb     $C1,$3F,$C0,$00,$C1,$03,$7C,$41,$81,$FF,$41,$00
        fcb     $C1,$F3,$08,$43,$00
