* chtab1_046_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 39 rows x 4 bytes, 371 segment bytes
*
chtab1_046_p0:
        fcb     39,4  ; height, width in bytes
        fcb     $41,$C1,$FC,$03,$81,$FF,$C1,$3F,$00,$00,$41,$82
        fcb     $3F,$FF,$C1,$0F,$C0,$00,$41,$82,$3F,$FF,$C1,$0F
        fcb     $C0,$00,$42,$C2,$C0,$0F,$0F,$C0,$00,$41,$C1,$C0
        fcb     $0A,$81,$AF,$C1,$0F,$C0,$00,$41,$C1,$C0,$0A,$81
        fcb     $AF,$C1,$0F,$C0,$00,$41,$C1,$C0,$0A,$81,$AF,$C1
        fcb     $3F,$00,$00,$C1,$F0,$03,$82,$FF,$E8,$41,$00,$C1
        fcb     $FC,$00,$82,$FF,$EF,$C1,$0F,$C0,$00,$C1,$C0,$0A
        fcb     $82,$FF,$EF,$C1,$0F,$F0,$00,$C1,$C0,$0A,$82,$FF
        fcb     $FF,$C1,$0F,$C0,$00,$C1,$C0,$0A,$82,$FF,$FF,$C1
        fcb     $0F,$C0,$00,$C1,$C0,$0A,$82,$FF,$FF,$C1,$3F,$00
        fcb     $00,$C1,$C0,$0A,$82,$FF,$FF,$C1,$3F,$00,$00,$C1
        fcb     $C0,$0A,$82,$AF,$FF,$C1,$3F,$00,$00,$C1,$C0,$0A
        fcb     $82,$AF,$FF,$C1,$0F,$C0,$00,$C1,$FC,$00,$82,$AA
        fcb     $FF,$C1,$0F,$C0,$00,$C1,$C0,$0F,$82,$EA,$FF,$C1
        fcb     $0F,$C0,$00,$C1,$C0,$0F,$82,$FE,$AA,$C1,$0F,$80
        fcb     $00,$C1,$C0,$0F,$82,$FF,$EA,$C1,$0F,$80,$00,$C1
        fcb     $C0,$0F,$82,$FF,$EA,$C1,$0F,$80,$00,$C1,$F0,$03
        fcb     $82,$FF,$FF,$C1,$3F,$00,$00,$C1,$F0,$03,$82,$FF
        fcb     $FF,$C1,$3F,$00,$00,$C1,$F0,$03,$82,$FF,$FF,$C1
        fcb     $3F,$00,$00,$C1,$FC,$00,$82,$FF,$FF,$C1,$3F,$00
        fcb     $00,$C1,$FC,$00,$82,$FF,$FF,$C1,$3F,$00,$00,$41
        fcb     $82,$3F,$FF,$C1,$0F,$C0,$00,$41,$C1,$C0,$0F,$81
        fcb     $FF,$C1,$0F,$C0,$00,$41,$C1,$C0,$0F,$81,$FF,$C1
        fcb     $0F,$C0,$00,$41,$C1,$C0,$0F,$81,$FF,$C1,$3F,$00
        fcb     $00,$41,$82,$3F,$FF,$C1,$3F,$00,$00,$41,$82,$3F
        fcb     $FF,$C1,$3F,$00,$00,$41,$82,$3F,$FF,$C1,$3F,$00
        fcb     $00,$41,$81,$3F,$C1,$3F,$00,$41,$00,$C1,$FC,$00
        fcb     $81,$FF,$C1,$3F,$00,$41,$00,$C1,$FC,$00,$81,$FF
        fcb     $C1,$3F,$00,$41,$00,$C1,$F0,$03,$81,$FF,$C1,$3F
        fcb     $00,$41,$00,$C1,$F0,$03,$81,$FF,$C1,$0F,$C0,$41
        fcb     $00,$C1,$FC,$00,$81,$FF,$C1,$03,$F0,$41,$00
