* chtab1_061_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 33 rows x 4 bytes, 266 segment bytes
*
chtab1_061_p0:
        fcb     33,4  ; height, width in bytes
        fcb     $42,$C1,$FC,$03,$81,$FF,$00,$42,$C1,$C0,$3F,$81
        fcb     $FF,$00,$42,$C2,$C0,$3F,$03,$FC,$00,$42,$C2,$C0
        fcb     $3F,$03,$E8,$00,$42,$C2,$C0,$3F,$03,$E8,$00,$42
        fcb     $C2,$C0,$3F,$3F,$C0,$00,$41,$C1,$F0,$0F,$81,$FF
        fcb     $C1,$03,$FC,$00,$41,$C1,$C0,$3F,$81,$FF,$C1,$03
        fcb     $E8,$00,$41,$82,$FF,$FF,$C1,$03,$E8,$00,$C1,$F0
        fcb     $0A,$82,$FF,$FF,$C1,$03,$E8,$00,$C1,$F0,$0A,$82
        fcb     $FF,$FF,$C1,$03,$E8,$00,$41,$82,$FF,$FF,$C1,$03
        fcb     $E8,$00,$41,$82,$FF,$FF,$C1,$3F,$C0,$00,$41,$82
        fcb     $FF,$FF,$C1,$3F,$C0,$00,$41,$82,$FF,$FF,$C1,$3F
        fcb     $C0,$00,$41,$82,$FF,$FF,$41,$00,$41,$82,$FF,$FF
        fcb     $41,$00,$41,$C1,$C0,$3F,$81,$FF,$41,$00,$41,$C1
        fcb     $F0,$0F,$81,$FF,$41,$00,$41,$C1,$FC,$03,$81,$FF
        fcb     $41,$00,$41,$C1,$FC,$03,$81,$FF,$41,$00,$41,$C1
        fcb     $FC,$03,$81,$FF,$41,$00,$41,$C1,$FC,$03,$81,$FF
        fcb     $C1,$3F,$C0,$00,$41,$C1,$FC,$03,$81,$FF,$C1,$3F
        fcb     $C0,$00,$41,$C1,$FC,$03,$81,$FF,$41,$00,$41,$C1
        fcb     $FC,$03,$81,$FF,$41,$00,$41,$C1,$F0,$0F,$81,$FF
        fcb     $41,$00,$41,$C2,$F0,$0F,$03,$FC,$41,$00,$41,$C2
        fcb     $F0,$0F,$03,$FC,$41,$00,$41,$C2,$F0,$0F,$0F,$F0
        fcb     $41,$00,$41,$C2,$F0,$0F,$3F,$C0,$41,$00,$41,$C2
        fcb     $C0,$3F,$03,$FC,$41,$00,$41,$C2,$F0,$0F,$03,$FC
        fcb     $41,$00
