* chtab1_064_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 24 rows x 2 bytes, 144 segment bytes
*
chtab1_064_p0:
        fcb     24,2  ; height, width in bytes
        fcb     $C2,$F0,$03,$0F,$C0,$00,$81,$17,$C1,$0F,$C0,$00
        fcb     $81,$17,$C1,$0F,$C0,$00,$81,$17,$C1,$0F,$C0,$00
        fcb     $C2,$C0,$0F,$0F,$C0,$00,$C2,$C0,$0F,$0F,$C0,$00
        fcb     $C2,$C0,$0F,$0F,$C0,$00,$C2,$C0,$0F,$0F,$C0,$00
        fcb     $C2,$C0,$0F,$0F,$C0,$00,$C2,$C0,$0F,$0F,$C0,$00
        fcb     $C2,$C0,$0F,$0F,$C0,$00,$C2,$C0,$0F,$0F,$C0,$00
        fcb     $C2,$F0,$03,$0F,$C0,$00,$C2,$F0,$03,$0F,$C0,$00
        fcb     $C2,$F0,$03,$0F,$C0,$00,$C2,$F0,$03,$0F,$C0,$00
        fcb     $C2,$C0,$0F,$0F,$C0,$00,$C2,$C0,$0F,$0F,$C0,$00
        fcb     $C2,$C0,$0F,$0F,$C0,$00,$C2,$C0,$0F,$0F,$C0,$00
        fcb     $C2,$C0,$0F,$0F,$C0,$00,$C2,$C0,$0F,$3F,$00,$00
        fcb     $81,$7F,$C1,$0F,$C0,$00,$C2,$F0,$03,$0F,$C0,$00
