* chtab1_063_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 24 rows x 2 bytes, 128 segment bytes
*
chtab1_063_p0:
        fcb     24,2  ; height, width in bytes
        fcb     $41,$C1,$FC,$01,$00,$41,$C1,$C0,$3F,$00,$41,$81
        fcb     $FF,$00,$C1,$F0,$0A,$81,$FF,$00,$C1,$F0,$0A,$81
        fcb     $FF,$00,$C1,$F0,$0A,$81,$FF,$00,$C1,$F0,$0A,$81
        fcb     $FF,$00,$C1,$F0,$0A,$81,$FF,$00,$C1,$FC,$03,$81
        fcb     $FF,$00,$C1,$FC,$03,$81,$FF,$00,$C1,$FC,$03,$81
        fcb     $FF,$00,$C1,$FC,$03,$81,$FF,$00,$C1,$FC,$03,$81
        fcb     $FF,$00,$41,$81,$FF,$00,$41,$C1,$F0,$0F,$00,$41
        fcb     $C1,$FC,$01,$00,$41,$C1,$FC,$01,$00,$41,$C1,$F0
        fcb     $0F,$00,$41,$C1,$C0,$3F,$00,$41,$81,$FF,$00,$C1
        fcb     $FC,$03,$81,$FF,$00,$41,$C1,$03,$FC,$00,$41,$C1
        fcb     $C0,$3F,$00,$41,$C1,$F0,$0F,$00
