* chtab1_026_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 27 rows x 11 bytes, 314 segment bytes
*
chtab1_026_p0:
        fcb     27,11  ; height, width in bytes
        fcb     $41,$C2,$C0,$3F,$3F,$C0,$48,$00,$C1,$FC,$03,$81
        fcb     $FF,$C1,$03,$FC,$48,$00,$C1,$FC,$03,$81,$FF,$C1
        fcb     $03,$FC,$48,$00,$C1,$F0,$0F,$83,$FF,$FF,$FF,$C1
        fcb     $0F,$F0,$46,$00,$C2,$FC,$01,$F0,$0A,$83,$EA,$FF
        fcb     $AF,$46,$00,$41,$C1,$F0,$0A,$83,$EA,$AF,$AF,$C1
        fcb     $3F,$C0,$45,$00,$42,$C2,$3F,$80,$3F,$80,$81,$AF
        fcb     $C1,$0F,$F0,$45,$00,$44,$81,$AF,$C1,$03,$FC,$45
        fcb     $00,$44,$82,$AF,$FF,$45,$00,$44,$82,$AF,$FF,$45
        fcb     $00,$44,$82,$AF,$FF,$C1,$3F,$C0,$44,$00,$43,$C1
        fcb     $F0,$0A,$82,$AF,$FF,$C1,$3F,$C0,$44,$00,$43,$C1
        fcb     $F0,$0A,$82,$FF,$FF,$C1,$3F,$C0,$44,$00,$43,$C1
        fcb     $C0,$3F,$82,$FF,$FF,$C1,$3F,$C0,$44,$00,$43,$83
        fcb     $FF,$FF,$FF,$C1,$0F,$F0,$44,$00,$42,$C1,$F0,$0F
        fcb     $83,$FF,$FF,$FF,$C1,$0F,$F0,$44,$00,$42,$C1,$C0
        fcb     $3F,$81,$FF,$C1,$F0,$0F,$81,$FF,$C1,$03,$FC,$44
        fcb     $00,$42,$82,$FF,$FF,$C1,$FC,$03,$81,$FF,$C1,$03
        fcb     $FC,$44,$00,$41,$C1,$FC,$03,$81,$FF,$C1,$0F,$F0
        fcb     $41,$83,$FF,$FF,$FF,$C3,$0F,$F0,$C0,$3F,$3F,$C0
        fcb     $00,$41,$C1,$FC,$03,$81,$FF,$42,$C1,$C0,$3F,$84
        fcb     $FF,$FF,$FF,$FF,$C1,$3F,$C0,$00,$41,$C2,$F0,$0F
        fcb     $03,$FC,$42,$C1,$F0,$0F,$82,$FF,$FF,$C3,$0F,$F0
        fcb     $F0,$0F,$3F,$C0,$00,$41,$C2,$F0,$0F,$03,$FC,$43
        fcb     $C1,$C0,$3F,$81,$FF,$41,$C2,$FC,$03,$3F,$C0,$00
        fcb     $41,$C2,$F0,$0F,$0F,$F0,$47,$C1,$3F,$80,$00,$41
        fcb     $C1,$03,$FC,$49,$00,$81,$FF,$C1,$03,$FC,$49,$00
        fcb     $81,$FF,$C1,$0F,$F0,$49,$00,$C2,$F0,$0F,$0F,$F0
        fcb     $49,$00
