* chtab1_028_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 25 rows x 6 bytes, 228 segment bytes
*
chtab1_028_p0:
        fcb     25,6  ; height, width in bytes
        fcb     $C2,$F0,$0F,$03,$FC,$44,$00,$82,$FF,$FF,$44,$00
        fcb     $82,$FF,$FF,$44,$00,$C1,$F0,$0F,$81,$FF,$44,$00
        fcb     $C1,$C0,$15,$81,$7F,$C1,$03,$FC,$43,$00,$C1,$C0
        fcb     $15,$82,$7F,$FF,$C1,$03,$FC,$42,$00,$C2,$C0,$15
        fcb     $0F,$50,$82,$FF,$FF,$C1,$3F,$C0,$41,$00,$41,$C1
        fcb     $FC,$01,$82,$7F,$FF,$C1,$03,$FC,$41,$00,$41,$C1
        fcb     $FC,$01,$83,$FF,$FF,$7F,$41,$00,$41,$C1,$FC,$01
        fcb     $83,$FF,$FF,$57,$C1,$3F,$C0,$00,$42,$C1,$C0,$17
        fcb     $82,$FF,$FF,$C1,$3F,$C0,$00,$42,$C1,$C0,$17,$82
        fcb     $FF,$FF,$C1,$3F,$C0,$00,$41,$C1,$F0,$0F,$83,$7F
        fcb     $FF,$55,$C1,$3F,$C0,$00,$41,$84,$FF,$F5,$7F,$FF
        fcb     $C1,$3F,$C0,$00,$41,$82,$FF,$F5,$C2,$F0,$0F,$0F
        fcb     $F0,$41,$00,$41,$81,$FF,$C2,$3C,$C1,$0F,$50,$42
        fcb     $00,$41,$81,$FF,$C2,$FC,$01,$0F,$50,$42,$00,$41
        fcb     $81,$FF,$C2,$3F,$C0,$CF,$10,$42,$00,$41,$C3,$F0
        fcb     $0F,$0F,$F0,$C0,$15,$42,$00,$43,$C1,$C0,$15,$42
        fcb     $00,$42,$C2,$CF,$10,$FC,$01,$42,$00,$42,$C1,$03
        fcb     $FC,$43,$00,$42,$81,$FF,$43,$00,$41,$C1,$C0,$3F
        fcb     $81,$FF,$43,$00,$C1,$FC,$03,$82,$FF,$FF,$43,$00
