* chtab1_062_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 30 rows x 3 bytes, 224 segment bytes
*
chtab1_062_p0:
        fcb     30,3  ; height, width in bytes
        fcb     $41,$C2,$FC,$03,$03,$F0,$00,$41,$C1,$C0,$0F,$81
        fcb     $FC,$00,$C1,$FC,$00,$82,$FF,$FC,$00,$C1,$F0,$03
        fcb     $82,$FF,$FC,$00,$C1,$F0,$03,$82,$FF,$FC,$00,$83
        fcb     $FF,$FC,$17,$00,$83,$FF,$FC,$17,$00,$83,$FF,$FC
        fcb     $17,$00,$C1,$F0,$03,$82,$FF,$FC,$00,$C1,$C0,$0F
        fcb     $82,$FF,$FC,$00,$C1,$C0,$0F,$82,$FF,$FC,$00,$C1
        fcb     $C0,$0F,$82,$FF,$FC,$00,$C1,$C0,$0F,$81,$FF,$C1
        fcb     $03,$F0,$00,$C1,$C0,$0F,$81,$FF,$C1,$03,$F0,$00
        fcb     $C1,$F0,$03,$81,$FF,$C1,$03,$F0,$00,$C1,$F0,$03
        fcb     $81,$FF,$C1,$03,$F0,$00,$C1,$F0,$03,$81,$FF,$C1
        fcb     $03,$F0,$00,$C1,$FC,$00,$81,$FF,$C1,$03,$F0,$00
        fcb     $C1,$FC,$00,$81,$FF,$C1,$03,$F0,$00,$C1,$FC,$00
        fcb     $81,$FF,$C1,$03,$F0,$00,$C1,$FC,$00,$81,$FF,$C1
        fcb     $03,$F0,$00,$C1,$FC,$00,$81,$FF,$C1,$0F,$C0,$00
        fcb     $C1,$F0,$03,$82,$FF,$FC,$00,$C1,$C0,$0F,$82,$FF
        fcb     $FC,$00,$C2,$C0,$0F,$03,$FC,$41,$00,$C2,$C0,$0F
        fcb     $03,$F0,$41,$00,$C2,$C0,$0F,$0F,$C0,$41,$00,$81
        fcb     $7F,$C1,$0F,$C0,$41,$00,$C2,$C0,$0F,$0F,$C0,$41
        fcb     $00,$C2,$F0,$03,$03,$F0,$41,$00
