* chtab1_020_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 31 rows x 7 bytes, 306 segment bytes
*
chtab1_020_p0:
        fcb     31,7  ; height, width in bytes
        fcb     $C1,$F0,$03,$81,$FF,$C1,$3F,$00,$44,$00,$82,$7F
        fcb     $FF,$C1,$0F,$C0,$44,$00,$82,$7F,$FF,$C1,$0F,$C0
        fcb     $44,$00,$C1,$F0,$03,$81,$FF,$C1,$0F,$C0,$44,$00
        fcb     $C1,$C0,$0A,$84,$AF,$FF,$FF,$FC,$42,$00,$C1,$C0
        fcb     $0A,$84,$AF,$FF,$FF,$FF,$C1,$3F,$C0,$41,$00,$C2
        fcb     $C0,$0A,$0C,$83,$85,$EA,$AA,$AA,$A8,$FF,$00,$41
        fcb     $C1,$FC,$03,$85,$AA,$AA,$AA,$A8,$EA,$00,$42,$C3
        fcb     $C0,$0A,$0F,$80,$C0,$0F,$81,$FF,$C1,$0F,$C0,$00
        fcb     $44,$82,$3F,$FF,$C1,$0F,$C0,$00,$44,$82,$3F,$FF
        fcb     $C1,$0F,$C0,$00,$44,$C1,$C0,$0F,$81,$FF,$C1,$0F
        fcb     $C0,$00,$44,$C1,$C0,$0F,$81,$FF,$C1,$0F,$C0,$00
        fcb     $44,$C1,$C0,$0F,$81,$FF,$C1,$3F,$00,$00,$44,$82
        fcb     $3F,$FF,$C1,$3F,$00,$00,$44,$82,$3F,$FF,$C1,$3F
        fcb     $00,$00,$44,$82,$3F,$FF,$C1,$3F,$00,$00,$43,$C1
        fcb     $FC,$00,$82,$FF,$FF,$C1,$3F,$00,$00,$43,$C1,$FC
        fcb     $00,$82,$FF,$FF,$C1,$3F,$00,$00,$43,$C1,$FC,$00
        fcb     $82,$FF,$FF,$C1,$3F,$00,$00,$43,$C1,$FC,$00,$82
        fcb     $FF,$FF,$C1,$3F,$00,$00,$43,$C1,$FC,$00,$82,$FF
        fcb     $FF,$C1,$3F,$00,$00,$44,$82,$3F,$FF,$C1,$0F,$C0
        fcb     $00,$44,$82,$3F,$FF,$C1,$0F,$C0,$00,$44,$C1,$C0
        fcb     $0F,$81,$FF,$C1,$3F,$00,$00,$44,$C1,$FC,$00,$81
        fcb     $FF,$C1,$0F,$C0,$00,$44,$C1,$FC,$00,$81,$FF,$C1
        fcb     $0F,$C0,$00,$44,$C1,$F0,$03,$81,$FF,$C1,$0F,$C0
        fcb     $00,$44,$C1,$F0,$03,$81,$FF,$C1,$0F,$C0,$00,$44
        fcb     $C1,$C0,$0F,$81,$FF,$C1,$0F,$C0,$00,$43,$C1,$FC
        fcb     $00,$82,$FF,$FC,$41,$00
