* chtab1_063_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 24 rows x 3 bytes, 196 segment bytes
*
chtab1_063_p0:
        fcb     24,3  ; height, width in bytes
        fcb     $41,$C2,$FC,$01,$3F,$00,$00,$41,$81,$3F,$C1,$3F
        fcb     $00,$00,$C1,$FC,$00,$81,$FF,$C1,$3F,$00,$00,$C1
        fcb     $C0,$0A,$81,$FF,$C1,$3F,$00,$00,$C1,$C0,$0A,$81
        fcb     $FF,$C1,$3F,$00,$00,$C1,$C0,$0A,$81,$FF,$C1,$3F
        fcb     $00,$00,$C1,$C0,$0A,$81,$FF,$C1,$3F,$00,$00,$C1
        fcb     $C0,$0A,$81,$FF,$C1,$3F,$00,$00,$C1,$F0,$03,$81
        fcb     $FF,$C1,$3F,$00,$00,$C1,$F0,$03,$81,$FF,$C1,$3F
        fcb     $00,$00,$C1,$F0,$03,$81,$FF,$C1,$3F,$00,$00,$C1
        fcb     $F0,$03,$81,$FF,$C1,$3F,$00,$00,$C1,$F0,$03,$81
        fcb     $FF,$C1,$3F,$00,$00,$C1,$FC,$00,$81,$FF,$C1,$3F
        fcb     $00,$00,$41,$C2,$C0,$0F,$3F,$00,$00,$41,$C2,$FC
        fcb     $01,$3F,$00,$00,$41,$C2,$FC,$01,$3F,$00,$00,$41
        fcb     $C2,$C0,$0F,$3F,$00,$00,$41,$81,$3F,$C1,$3F,$00
        fcb     $00,$C1,$FC,$00,$81,$FF,$C1,$3F,$00,$00,$C1,$F0
        fcb     $03,$81,$FF,$C1,$3F,$00,$00,$C2,$FC,$00,$03,$FC
        fcb     $41,$00,$41,$81,$3F,$C1,$3F,$00,$00,$41,$C2,$C0
        fcb     $0F,$3F,$00,$00
