* chtab1_045_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 39 rows x 3 bytes, 300 segment bytes
*
chtab1_045_p0:
        fcb     39,3  ; height, width in bytes
        fcb     $41,$C2,$C0,$3F,$0F,$F0,$00,$41,$82,$FF,$FF,$00
        fcb     $41,$82,$FF,$FF,$00,$41,$81,$FF,$C1,$0F,$F0,$00
        fcb     $41,$81,$FE,$C1,$03,$A8,$00,$41,$C2,$C0,$3E,$03
        fcb     $A8,$00,$41,$C2,$F0,$0A,$03,$A8,$00,$41,$C2,$C0
        fcb     $3E,$3F,$80,$00,$41,$81,$FF,$C1,$3F,$C0,$00,$C3
        fcb     $FC,$03,$0F,$F0,$0F,$F0,$00,$C1,$FC,$03,$81,$EA
        fcb     $C1,$0F,$F0,$00,$C1,$F0,$0F,$81,$EA,$C1,$0F,$F0
        fcb     $00,$C1,$F0,$0F,$81,$EA,$C1,$0F,$F0,$00,$C1,$F0
        fcb     $0F,$81,$EA,$C1,$0F,$F0,$00,$C1,$F0,$0F,$81,$EA
        fcb     $C1,$0F,$F0,$00,$C1,$F0,$0F,$81,$EA,$C1,$0F,$F0
        fcb     $00,$C1,$F0,$0F,$81,$EA,$C1,$0F,$F0,$00,$C1,$F0
        fcb     $0F,$81,$EA,$C1,$0F,$F0,$00,$82,$7F,$FE,$C1,$0F
        fcb     $F0,$00,$82,$7F,$FE,$C1,$0F,$F0,$00,$82,$7F,$FE
        fcb     $C1,$3F,$80,$00,$82,$7F,$FE,$C1,$3F,$80,$00,$C1
        fcb     $F0,$0F,$81,$FF,$C1,$03,$E8,$00,$C1,$F0,$0F,$81
        fcb     $FF,$C1,$03,$E8,$00,$C1,$F0,$0F,$81,$FF,$C1,$0F
        fcb     $F0,$00,$C1,$FC,$03,$81,$FF,$C1,$0F,$F0,$00,$C1
        fcb     $FC,$03,$81,$FF,$C1,$03,$FC,$00,$C1,$FC,$03,$81
        fcb     $FF,$C1,$03,$FC,$00,$41,$81,$FF,$C1,$03,$FC,$00
        fcb     $41,$81,$FF,$C1,$03,$FC,$00,$41,$81,$FF,$C1,$0F
        fcb     $F0,$00,$C1,$FC,$03,$81,$FF,$C1,$0F,$F0,$00,$C1
        fcb     $FC,$03,$81,$FF,$C1,$3F,$C0,$00,$C1,$FC,$03,$81
        fcb     $FF,$41,$00,$C2,$F0,$0F,$0F,$F0,$41,$00,$C2,$F0
        fcb     $0F,$0F,$F0,$41,$00,$81,$7F,$C1,$0F,$F0,$41,$00
        fcb     $82,$7F,$FF,$41,$00,$82,$7F,$FF,$C1,$3F,$C0,$00
