* chtab1_041_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 30 rows x 13 bytes, 393 segment bytes
*
chtab1_041_p0:
        fcb     30,13  ; height, width in bytes
        fcb     $44,$81,$3F,$C1,$03,$F0,$47,$00,$43,$C1,$F0,$03
        fcb     $83,$FF,$FC,$FF,$46,$00,$43,$C1,$F0,$03,$83,$FF
        fcb     $FF,$FF,$C1,$0F,$C0,$45,$00,$43,$C1,$F0,$03,$83
        fcb     $AF,$FE,$FE,$C1,$03,$F0,$45,$00,$43,$C1,$F0,$03
        fcb     $84,$FE,$AF,$EA,$FC,$45,$00,$43,$C1,$F0,$03,$84
        fcb     $EA,$AF,$EA,$FF,$C1,$3F,$00,$44,$00,$45,$C1,$C0
        fcb     $0A,$82,$AA,$FF,$C1,$0F,$C0,$44,$00,$45,$C1,$C0
        fcb     $0A,$82,$AF,$FF,$C1,$0F,$C0,$44,$00,$44,$C1,$FC
        fcb     $00,$83,$FF,$FF,$AA,$C1,$0F,$C0,$44,$00,$44,$C2
        fcb     $C0,$0A,$3C,$80,$82,$FF,$FF,$C1,$03,$F0,$44,$00
        fcb     $45,$C1,$FC,$00,$82,$FF,$FF,$C1,$03,$F0,$44,$00
        fcb     $45,$C1,$FC,$00,$82,$FF,$FF,$C1,$03,$FC,$44,$00
        fcb     $46,$82,$3F,$FF,$C1,$03,$FC,$44,$00,$43,$C1,$F0
        fcb     $0F,$84,$FF,$FF,$FF,$FF,$C1,$03,$FC,$44,$00,$42
        fcb     $C1,$FC,$00,$85,$FF,$FF,$FF,$FF,$FF,$C1,$03,$FC
        fcb     $44,$00,$42,$C1,$F0,$03,$86,$FF,$FF,$FF,$FF,$FF
        fcb     $FF,$C1,$3F,$00,$43,$00,$42,$C1,$C0,$0F,$86,$FF
        fcb     $FF,$FF,$FF,$FF,$FF,$C1,$3F,$00,$43,$00,$42,$C1
        fcb     $C0,$0F,$81,$FF,$C2,$3F,$00,$C0,$0F,$83,$FF,$FF
        fcb     $FF,$C1,$3F,$00,$43,$00,$42,$81,$3F,$C1,$0F,$C0
        fcb     $42,$83,$FF,$FF,$3F,$C1,$3F,$00,$43,$00,$81,$FC
        fcb     $C1,$FC,$03,$81,$FC,$43,$C1,$C0,$0F,$82,$FF,$FF
        fcb     $C1,$3F,$00,$43,$00,$82,$7F,$FF,$C1,$0F,$C0,$44
        fcb     $82,$FF,$FF,$C1,$3F,$00,$43,$00,$C2,$C0,$0F,$03
        fcb     $FC,$45,$82,$3F,$FF,$C1,$0F,$C0,$43,$00,$C2,$F0
        fcb     $03,$0F,$C0,$45,$C1,$C0,$0F,$81,$FF,$C1,$03,$F0
        fcb     $43,$00,$47,$C1,$F0,$03,$82,$FF,$FF,$C1,$0F,$C0
        fcb     $81,$3C,$41,$00,$48,$84,$3F,$FF,$F7,$FF,$C1,$3F
        fcb     $00,$00,$48,$C1,$C0,$0F,$83,$FF,$FF,$FF,$C1,$3F
        fcb     $C0,$00,$48,$C1,$FC,$03,$81,$FF,$C1,$0F,$C0,$81
        fcb     $3F,$C1,$03,$F0,$00,$48,$C1,$FC,$00,$81,$FF,$C2
        fcb     $3F,$00,$FC,$00,$81,$FC,$00,$49,$C1,$C0,$08,$42
        fcb     $C1,$C0,$3C,$00,$4C,$C1,$C0,$08,$00
