* chtab1_027_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 26 rows x 9 bytes, 303 segment bytes
*
chtab1_027_p0:
        fcb     26,9  ; height, width in bytes
        fcb     $41,$C1,$FC,$03,$81,$FC,$46,$00,$41,$82,$3F,$FF
        fcb     $C1,$0F,$C0,$45,$00,$41,$82,$3F,$FF,$C1,$0F,$C0
        fcb     $45,$00,$C1,$FC,$00,$82,$FF,$FF,$C1,$0F,$F0,$45
        fcb     $00,$41,$84,$10,$AA,$FF,$FF,$C1,$03,$F0,$43,$00
        fcb     $41,$C1,$FC,$00,$84,$A8,$3F,$FF,$FF,$C1,$3F,$00
        fcb     $42,$00,$42,$C1,$C0,$08,$83,$AF,$FF,$3E,$C1,$03
        fcb     $F0,$42,$00,$43,$84,$3E,$AA,$FF,$FC,$42,$00,$43
        fcb     $C1,$FC,$00,$83,$AF,$FF,$AA,$42,$00,$44,$C1,$C0
        fcb     $0A,$82,$AF,$FF,$C1,$0F,$C0,$41,$00,$44,$C1,$FC
        fcb     $00,$82,$AA,$FF,$C1,$0F,$C0,$41,$00,$44,$83,$EA
        fcb     $AF,$3F,$C1,$0F,$C0,$41,$00,$43,$C1,$FC,$00,$83
        fcb     $FE,$A8,$FF,$42,$00,$43,$C1,$F0,$03,$83,$FF,$EA
        fcb     $FF,$C1,$0F,$80,$41,$00,$43,$C1,$F0,$0F,$84,$FF
        fcb     $FF,$FE,$A8,$41,$00,$43,$85,$FF,$FF,$FE,$A8,$3F
        fcb     $41,$00,$43,$84,$3F,$FF,$FF,$FC,$42,$00,$43,$83
        fcb     $FF,$FF,$3F,$C1,$0F,$C0,$42,$00,$42,$C1,$FC,$00
        fcb     $83,$FF,$FF,$FF,$C1,$3F,$00,$81,$3F,$C1,$0F,$C0
        fcb     $00,$42,$C1,$FC,$00,$85,$EF,$FF,$FF,$FF,$FF,$C1
        fcb     $0F,$C0,$00,$43,$C1,$F0,$0F,$82,$0F,$FF,$C1,$03
        fcb     $F0,$81,$3F,$C1,$0F,$C0,$00,$43,$C2,$F0,$0F,$30
        fcb     $03,$81,$FF,$C3,$0F,$C0,$C0,$0F,$0F,$C0,$00,$43
        fcb     $C2,$F0,$0F,$3F,$00,$42,$C2,$C0,$0F,$0F,$C0,$00
        fcb     $43,$81,$3F,$C1,$3F,$00,$42,$C2,$C0,$0F,$0F,$C0
        fcb     $00,$42,$C1,$F0,$03,$81,$FF,$C1,$0F,$C0,$42,$C1
        fcb     $C0,$08,$41,$00,$42,$C1,$C0,$0F,$81,$FF,$C1,$3F
        fcb     $00,$44,$00
