* chtab1_058_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 34 rows x 5 bytes, 345 segment bytes
*
chtab1_058_p0:
        fcb     34,5  ; height, width in bytes
        fcb     $42,$C1,$FC,$00,$81,$FF,$C1,$0F,$C0,$00,$42,$C1
        fcb     $C0,$0F,$81,$FF,$C1,$0F,$C0,$00,$42,$C1,$C0,$0F
        fcb     $81,$FC,$41,$00,$42,$C1,$C0,$0F,$81,$F5,$C1,$3F
        fcb     $00,$00,$42,$C1,$C0,$0F,$81,$F5,$C1,$3F,$00,$00
        fcb     $42,$C1,$C0,$0F,$81,$F5,$C1,$3F,$00,$00,$41,$C1
        fcb     $FC,$03,$82,$FF,$FF,$C1,$3F,$00,$00,$41,$C1,$FC
        fcb     $03,$81,$FF,$C1,$0F,$50,$41,$00,$41,$C1,$FC,$03
        fcb     $81,$FF,$C1,$0F,$50,$41,$00,$41,$C1,$C0,$0F,$81
        fcb     $FF,$C1,$0F,$50,$41,$00,$41,$C1,$C0,$0F,$81,$FF
        fcb     $C1,$0F,$50,$41,$00,$41,$82,$3F,$FF,$C1,$0F,$50
        fcb     $41,$00,$41,$82,$3F,$FF,$C1,$0F,$50,$41,$00,$C1
        fcb     $FC,$00,$83,$FF,$55,$FF,$C1,$3F,$00,$00,$C1,$FC
        fcb     $00,$83,$FF,$F5,$FF,$C1,$3F,$00,$00,$C1,$FC,$00
        fcb     $82,$FF,$FF,$C1,$0F,$F0,$41,$00,$C1,$F0,$03,$82
        fcb     $FF,$FF,$C1,$0F,$F0,$41,$00,$C1,$F0,$03,$83,$FF
        fcb     $FF,$FF,$C1,$3F,$00,$00,$C1,$FC,$00,$83,$FF,$FF
        fcb     $FF,$C1,$0F,$C0,$00,$C1,$FC,$00,$83,$FF,$FF,$FF
        fcb     $C1,$03,$F0,$00,$C1,$FC,$00,$83,$FF,$FF,$FF,$C1
        fcb     $0F,$C0,$00,$C1,$FC,$00,$83,$F7,$FF,$FF,$C1,$0F
        fcb     $C0,$00,$C1,$FC,$00,$83,$C3,$FF,$FF,$C1,$3F,$00
        fcb     $00,$C1,$FC,$00,$83,$EF,$FC,$FF,$41,$00,$C1,$FC
        fcb     $00,$82,$FF,$FF,$C1,$0F,$F0,$41,$00,$C1,$FC,$00
        fcb     $82,$FF,$FF,$C1,$0F,$C0,$41,$00,$C1,$F0,$03,$82
        fcb     $FF,$FF,$C1,$0F,$F0,$41,$00,$C1,$F0,$03,$83,$FF
        fcb     $FC,$FF,$41,$00,$C1,$C0,$0F,$81,$FF,$C2,$3C,$00
        fcb     $0F,$80,$41,$00,$C2,$C0,$0F,$03,$FC,$43,$00,$C2
        fcb     $C0,$0F,$03,$FC,$43,$00,$C2,$C0,$0F,$03,$F0,$43
        fcb     $00,$C1,$C0,$0F,$81,$FF,$C1,$0F,$C0,$42,$00,$C1
        fcb     $C0,$0F,$81,$FF,$C1,$0F,$C0,$42,$00
