* chtab4viz_004_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 33 rows x 13 bytes, 452 segment bytes
*
chtab4viz_004_p0:
        fcb     33,13  ; height, width in bytes
        fcb     $44,$C2,$C0,$3F,$03,$FC,$47,$00,$43,$C1,$FC,$03
        fcb     $82,$FF,$FF,$C1,$3F,$C0,$46,$00,$43,$C1,$FC,$03
        fcb     $82,$FF,$FF,$C1,$0F,$F0,$46,$00,$44,$C1,$C0,$3F
        fcb     $81,$FF,$C1,$03,$FC,$46,$00,$45,$81,$FF,$C1,$03
        fcb     $FC,$46,$00,$44,$C1,$C0,$17,$81,$FF,$C1,$0F,$F0
        fcb     $46,$00,$C1,$FC,$01,$81,$7F,$42,$82,$F7,$FF,$47
        fcb     $00,$C1,$FC,$01,$82,$7F,$FE,$C1,$3F,$80,$83,$FF
        fcb     $FF,$FF,$C2,$F0,$0A,$3F,$80,$44,$00,$42,$86,$AA
        fcb     $FF,$FF,$EA,$FE,$AA,$C1,$03,$FC,$44,$00,$43,$86
        fcb     $FF,$FF,$FE,$FF,$AA,$AA,$C1,$3F,$C0,$43,$00,$44
        fcb     $86,$FF,$FE,$AF,$F5,$AA,$AF,$43,$00,$45,$C1,$F0
        fcb     $0F,$81,$FF,$C1,$03,$FC,$41,$C1,$C0,$15,$43,$00
        fcb     $45,$C1,$FC,$03,$82,$FF,$FF,$45,$00,$46,$82,$FF
        fcb     $FF,$45,$00,$46,$82,$FF,$FF,$C1,$3F,$C0,$44,$00
        fcb     $46,$C1,$C0,$3F,$81,$FF,$C1,$3F,$C0,$44,$00,$46
        fcb     $82,$AF,$FF,$C1,$03,$FC,$44,$00,$45,$C1,$F0,$0A
        fcb     $82,$AF,$FF,$C1,$03,$FC,$44,$00,$44,$C1,$F0,$0A
        fcb     $84,$AA,$AA,$FF,$FF,$44,$00,$44,$C1,$F0,$0A,$84
        fcb     $AA,$AA,$FF,$FF,$44,$00,$44,$85,$AA,$AA,$FF,$FF
        fcb     $AA,$C1,$3F,$C0,$43,$00,$44,$85,$AA,$AA,$AF,$FF
        fcb     $AA,$C1,$3F,$C0,$43,$00,$44,$85,$AA,$AA,$AF,$FF
        fcb     $AA,$C1,$0F,$F0,$43,$00,$44,$81,$AA,$C2,$3F,$80
        fcb     $0F,$F0,$41,$81,$FF,$C1,$03,$FC,$43,$00,$43,$C1
        fcb     $F0,$0A,$81,$AA,$C2,$3F,$80,$0F,$F0,$41,$C1,$C0
        fcb     $3F,$81,$FF,$C1,$3F,$C0,$42,$00,$43,$C1,$F0,$0A
        fcb     $81,$AA,$C1,$3F,$80,$82,$FF,$FF,$C1,$F0,$0F,$81
        fcb     $FF,$C1,$03,$FC,$42,$00,$43,$C3,$F0,$0A,$03,$A8
        fcb     $FC,$03,$85,$FF,$EF,$FF,$FF,$FF,$C1,$3F,$C0,$41
        fcb     $00,$43,$C3,$F0,$0A,$03,$A8,$FC,$03,$86,$F7,$FF
        fcb     $FF,$EF,$FF,$FF,$C1,$3F,$C0,$00,$44,$C2,$03,$A8
        fcb     $F0,$0F,$82,$FF,$FF,$C1,$0F,$F0,$41,$C1,$C0,$3E
        fcb     $81,$AF,$C1,$3F,$C0,$00,$43,$C3,$F0,$0F,$0F,$F0
        fcb     $F0,$0F,$84,$FF,$FF,$FF,$FE,$C3,$3F,$80,$C0,$3F
        fcb     $3F,$C0,$00,$43,$C3,$C0,$3F,$0F,$F0,$F0,$0F,$83
        fcb     $FF,$FF,$FF,$C1,$3F,$C0,$41,$C1,$C0,$3F,$41,$00
        fcb     $42,$C1,$FC,$03,$81,$FF,$C1,$03,$FC,$42,$81,$FF
        fcb     $C1,$0F,$F0,$42,$C1,$C3,$3C,$41,$00,$42,$C1,$C0
        fcb     $3F,$81,$FF,$C1,$03,$FC,$48,$00
