* chtab4viz_029_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 31 rows x 6 bytes, 327 segment bytes
*
chtab4viz_029_p0:
        fcb     31,6  ; height, width in bytes
        fcb     $C1,$F0,$03,$81,$FF,$C1,$0F,$C0,$43,$00,$83,$FF
        fcb     $FC,$7F,$43,$00,$83,$FF,$FF,$7F,$C1,$3F,$00,$42
        fcb     $00,$C1,$F0,$03,$82,$FF,$FF,$C1,$0F,$C0,$42,$00
        fcb     $41,$C1,$C0,$0F,$81,$FF,$C1,$0F,$C0,$42,$00,$C1
        fcb     $F0,$01,$82,$7F,$FF,$C1,$3F,$00,$42,$00,$C1,$C0
        fcb     $0F,$81,$7F,$C1,$0F,$C0,$43,$00,$C1,$C0,$0F,$81
        fcb     $FF,$C1,$0F,$C0,$43,$00,$83,$7F,$FC,$7F,$43,$00
        fcb     $C1,$FC,$00,$82,$FF,$FF,$C1,$3F,$00,$42,$00,$C1
        fcb     $F0,$03,$82,$FF,$FF,$C1,$0F,$C0,$42,$00,$C1,$FC
        fcb     $00,$82,$AA,$FF,$C1,$0F,$F0,$42,$00,$C1,$FC,$00
        fcb     $82,$AA,$FF,$C1,$0F,$F0,$42,$00,$C1,$FC,$00,$82
        fcb     $AA,$FF,$C1,$0F,$F0,$42,$00,$C1,$FC,$00,$82,$AA
        fcb     $FF,$C1,$0F,$F0,$42,$00,$C2,$FC,$00,$03,$A8,$81
        fcb     $3F,$C1,$0F,$F0,$42,$00,$C1,$F0,$03,$82,$EA,$AF
        fcb     $C1,$0F,$F0,$42,$00,$84,$17,$EA,$AF,$FC,$42,$00
        fcb     $C2,$03,$10,$C0,$0A,$82,$AF,$FF,$C1,$0F,$C0,$41
        fcb     $00,$41,$C1,$C0,$0A,$82,$AF,$FF,$C1,$0F,$C0,$41
        fcb     $00,$41,$C1,$C0,$0A,$83,$FF,$FC,$AF,$41,$00,$41
        fcb     $C1,$C0,$0A,$83,$FF,$FF,$AF,$C1,$03,$F0,$00,$41
        fcb     $C1,$FC,$01,$83,$FF,$FF,$7F,$C1,$3F,$C0,$00,$41
        fcb     $C1,$FC,$01,$83,$FF,$FF,$7E,$C1,$3F,$00,$00,$C2
        fcb     $FC,$00,$0C,$81,$82,$7E,$FF,$C1,$03,$F0,$41,$00
        fcb     $C2,$FC,$00,$0C,$81,$82,$7E,$FF,$C1,$0F,$C0,$41
        fcb     $00,$C1,$FC,$00,$83,$AA,$A8,$AA,$42,$00,$C1,$FC
        fcb     $00,$82,$AA,$AA,$C1,$0F,$80,$42,$00,$C1,$FC,$00
        fcb     $82,$AA,$AA,$C1,$0F,$80,$42,$00,$C1,$FC,$00,$82
        fcb     $AA,$AA,$C1,$0F,$F0,$42,$00,$41,$C2,$C0,$0A,$0F
        fcb     $80,$43,$00
