* chtab4viz_003_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 36 rows x 11 bytes, 442 segment bytes
*
chtab4viz_003_p0:
        fcb     36,11  ; height, width in bytes
        fcb     $43,$C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$45,$00,$43
        fcb     $C1,$C0,$3F,$81,$FF,$C1,$03,$FC,$45,$00,$43,$C1
        fcb     $C0,$3F,$82,$FF,$FF,$45,$00,$43,$C1,$FC,$03,$82
        fcb     $FF,$FF,$C1,$3F,$C0,$44,$00,$44,$C1,$F0,$0F,$81
        fcb     $FF,$C1,$3F,$C0,$44,$00,$43,$C1,$FC,$01,$82,$7F
        fcb     $FF,$45,$00,$43,$C1,$F0,$0F,$81,$7F,$C1,$3F,$C0
        fcb     $45,$00,$43,$C1,$F0,$0F,$82,$FF,$FF,$45,$00,$43
        fcb     $C1,$C0,$3F,$82,$FF,$FF,$C1,$3F,$C0,$44,$00,$42
        fcb     $84,$AA,$AA,$FF,$FF,$C1,$0F,$F0,$44,$00,$C1,$FC
        fcb     $01,$85,$EA,$AA,$FF,$FF,$7F,$C1,$03,$FC,$44,$00
        fcb     $C1,$FC,$01,$86,$AA,$AF,$FF,$FF,$7F,$EA,$44,$00
        fcb     $44,$C1,$F0,$0F,$81,$FF,$C1,$03,$FC,$44,$00,$44
        fcb     $C1,$FC,$03,$82,$FF,$FE,$C1,$3F,$80,$43,$00,$44
        fcb     $C1,$FC,$03,$81,$FF,$C2,$0F,$F0,$3F,$80,$43,$00
        fcb     $45,$82,$FF,$FF,$44,$00,$45,$82,$FF,$FF,$44,$00
        fcb     $45,$82,$FF,$FF,$C1,$3F,$C0,$43,$00,$45,$82,$AF
        fcb     $FF,$C1,$3F,$C0,$43,$00,$45,$82,$AF,$FF,$C1,$3F
        fcb     $C0,$43,$00,$44,$C1,$F0,$0A,$82,$AA,$FF,$C1,$0F
        fcb     $F0,$43,$00,$44,$83,$AA,$FF,$AA,$C1,$0F,$F0,$43
        fcb     $00,$43,$C1,$F0,$0A,$83,$AA,$FF,$AA,$C1,$03,$FC
        fcb     $43,$00,$43,$85,$AA,$AA,$FF,$FF,$AA,$43,$00,$43
        fcb     $85,$AA,$AA,$AF,$FF,$AA,$43,$00,$43,$81,$AA,$C2
        fcb     $03,$A8,$F0,$0A,$82,$AF,$FF,$C1,$3F,$C0,$42,$00
        fcb     $42,$C1,$F0,$0A,$81,$AA,$C2,$3F,$80,$F0,$0F,$82
        fcb     $EA,$FF,$C1,$0F,$F0,$42,$00,$42,$C1,$F0,$0A,$81
        fcb     $AA,$C2,$3F,$80,$FC,$03,$82,$FE,$FF,$C1,$03,$FC
        fcb     $42,$00,$42,$C2,$F0,$0A,$03,$A8,$41,$C1,$FC,$03
        fcb     $83,$AF,$FF,$FE,$C1,$3F,$C0,$41,$00,$42,$C2,$F0
        fcb     $0A,$03,$A8,$42,$81,$FF,$C1,$F0,$0A,$81,$FF,$C1
        fcb     $0F,$F0,$41,$00,$42,$C2,$F0,$0A,$03,$A8,$42,$83
        fcb     $FF,$7F,$FF,$C1,$0F,$F0,$41,$00,$42,$C2,$F0,$0A
        fcb     $3F,$80,$42,$84,$FF,$FF,$FF,$7F,$C1,$3F,$C0,$00
        fcb     $42,$C2,$F0,$0F,$3F,$C0,$42,$82,$FF,$FF,$41,$C2
        fcb     $C0,$3F,$0F,$F0,$00,$42,$81,$FF,$C1,$3F,$C0,$42
        fcb     $81,$FF,$42,$C2,$F0,$0F,$0F,$F0,$00,$41,$82,$FF
        fcb     $FF,$C1,$3F,$C0,$45,$C2,$F0,$0F,$3F,$C0,$00,$41
        fcb     $C1,$C0,$3F,$81,$FF,$C1,$3F,$C0,$47,$00
