* chtab4viz_031_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 19 rows x 9 bytes, 234 segment bytes
*
chtab4viz_031_p0:
        fcb     19,9  ; height, width in bytes
        fcb     $43,$C1,$C0,$15,$45,$00,$43,$C1,$C0,$15,$45,$00
        fcb     $43,$C2,$C0,$17,$03,$E8,$44,$00,$43,$C2,$FC,$03
        fcb     $03,$E8,$44,$00,$44,$81,$AA,$C1,$3F,$80,$43,$00
        fcb     $44,$81,$AA,$C1,$03,$A8,$43,$00,$44,$C4,$F0,$0A
        fcb     $03,$A8,$C0,$3F,$3F,$C0,$41,$00,$45,$82,$F7,$FF
        fcb     $C1,$03,$FC,$41,$00,$C2,$F0,$0F,$3F,$C0,$42,$C1
        fcb     $F0,$0F,$83,$7F,$FF,$FF,$41,$00,$C1,$F0,$0F,$81
        fcb     $FF,$C1,$03,$FC,$41,$C1,$FC,$03,$83,$7F,$FF,$F5
        fcb     $C1,$3F,$C0,$00,$C1,$F0,$0F,$82,$FF,$FF,$C2,$03
        fcb     $FC,$C0,$3F,$83,$7F,$FF,$F5,$C1,$3F,$C0,$00,$C1
        fcb     $F0,$0A,$87,$FF,$F5,$7F,$FF,$FF,$FF,$FF,$C1,$3F
        fcb     $C0,$00,$C1,$F0,$0A,$87,$AF,$F5,$7F,$FF,$FE,$AA
        fcb     $FF,$41,$00,$88,$AF,$FF,$7F,$FF,$AA,$AA,$AA,$AA
        fcb     $41,$00,$87,$AA,$AA,$FF,$FF,$AA,$AA,$AA,$C1,$03
        fcb     $FC,$41,$00,$87,$AA,$AA,$FF,$FF,$AA,$AA,$AA,$C1
        fcb     $0F,$F0,$41,$00,$81,$AA,$C1,$0F,$F0,$85,$AA,$AA
        fcb     $FF,$FF,$AA,$C1,$03,$FC,$41,$00,$82,$AA,$F5,$C1
        fcb     $F0,$0A,$84,$AA,$AA,$AF,$FF,$C1,$0F,$F0,$41,$00
        fcb     $C1,$F0,$0A,$81,$F5,$C1,$F0,$0A,$82,$AA,$AA,$C1
        fcb     $3C,$83,$81,$FF,$42,$00
