* chtab4viz_027_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 38 rows x 4 bytes, 317 segment bytes
*
chtab4viz_027_p0:
        fcb     38,4  ; height, width in bytes
        fcb     $C1,$F0,$0F,$81,$FF,$42,$00,$82,$FF,$FF,$C1,$0F
        fcb     $F0,$41,$00,$82,$FF,$FF,$C1,$03,$FC,$41,$00,$C1
        fcb     $F0,$0F,$82,$FF,$FF,$41,$00,$41,$C1,$C0,$3F,$81
        fcb     $FF,$41,$00,$C1,$FC,$01,$81,$7F,$C1,$03,$FC,$41
        fcb     $00,$C1,$F0,$0F,$81,$7F,$42,$00,$C1,$F0,$0F,$81
        fcb     $FF,$C1,$3F,$C0,$41,$00,$82,$FF,$FF,$C1,$0F,$F0
        fcb     $41,$00,$82,$7F,$FF,$C1,$0F,$F0,$41,$00,$82,$7F
        fcb     $FF,$C1,$0F,$F0,$41,$00,$82,$7F,$FF,$C1,$03,$FC
        fcb     $41,$00,$82,$7F,$FF,$C1,$03,$FC,$41,$00,$C1,$F0
        fcb     $0A,$81,$AF,$C1,$03,$FC,$41,$00,$C2,$F0,$0A,$3C
        fcb     $83,$81,$FF,$41,$00,$C2,$F0,$0A,$3C,$83,$81,$FF
        fcb     $41,$00,$C2,$F0,$0A,$3C,$83,$81,$FF,$41,$00,$C1
        fcb     $F0,$0A,$82,$AF,$FF,$41,$00,$C1,$F0,$0A,$82,$AA
        fcb     $FF,$41,$00,$C1,$F0,$0A,$82,$AA,$FF,$41,$00,$C1
        fcb     $FC,$01,$82,$7E,$FF,$C1,$3F,$C0,$00,$C1,$FC,$01
        fcb     $82,$7E,$FF,$C1,$3F,$C0,$00,$C1,$FC,$01,$82,$7E
        fcb     $FF,$C1,$3F,$C0,$00,$41,$82,$AA,$FF,$C1,$3F,$C0
        fcb     $00,$41,$82,$AA,$FF,$C1,$3F,$C0,$00,$41,$82,$AA
        fcb     $FF,$C1,$3F,$C0,$00,$41,$82,$AA,$FF,$C1,$3F,$C0
        fcb     $00,$41,$82,$AA,$FF,$41,$00,$C1,$F0,$0A,$82,$AA
        fcb     $FF,$41,$00,$C1,$F0,$0A,$82,$AA,$FF,$41,$00,$C1
        fcb     $F0,$0A,$82,$AA,$FF,$41,$00,$C1,$F0,$0A,$82,$AA
        fcb     $AF,$C1,$3F,$C0,$00,$41,$82,$AA,$AF,$C1,$3F,$C0
        fcb     $00,$41,$82,$AA,$AF,$C1,$3F,$C0,$00,$41,$C2,$F0
        fcb     $0A,$03,$A8,$41,$00,$41,$C2,$FC,$03,$03,$FC,$41
        fcb     $00,$41,$C1,$C0,$3F,$81,$FF,$41,$00,$41,$C1,$F0
        fcb     $0F,$81,$FF,$41,$00
