* chtab4viz_004_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 33 rows x 13 bytes, 485 segment bytes
*
chtab4viz_004_p0:
        fcb     33,13  ; height, width in bytes
        fcb     $44,$82,$3F,$FC,$47,$00,$43,$C1,$F0,$03,$82,$FF
        fcb     $FF,$C1,$0F,$C0,$46,$00,$43,$C1,$F0,$03,$82,$FF
        fcb     $FF,$C1,$03,$F0,$46,$00,$44,$83,$FF,$FC,$3F,$46
        fcb     $00,$44,$C1,$FC,$00,$82,$FF,$FC,$46,$00,$44,$82
        fcb     $17,$FF,$C1,$03,$F0,$46,$00,$C1,$F0,$01,$81,$7F
        fcb     $C2,$3F,$00,$FC,$00,$82,$F7,$FF,$C1,$3F,$00,$46
        fcb     $00,$C1,$F0,$01,$82,$7F,$FE,$C1,$0C,$80,$83,$FF
        fcb     $FF,$FF,$C2,$C0,$0A,$0F,$80,$44,$00,$41,$C1,$FC
        fcb     $00,$86,$AA,$FF,$FF,$EA,$FE,$AA,$C1,$03,$FC,$44
        fcb     $00,$42,$C1,$FC,$00,$86,$FF,$FF,$FE,$FF,$AA,$AA
        fcb     $C1,$0F,$C0,$43,$00,$43,$C1,$FC,$00,$86,$FF,$FE
        fcb     $AF,$F5,$AA,$AF,$C1,$3F,$00,$42,$00,$45,$C1,$C0
        fcb     $0F,$82,$FF,$FC,$41,$81,$15,$C1,$3F,$00,$42,$00
        fcb     $45,$C1,$F0,$03,$82,$FF,$FF,$C1,$3F,$00,$44,$00
        fcb     $45,$C1,$FC,$00,$82,$FF,$FF,$C1,$3F,$00,$44,$00
        fcb     $45,$C1,$FC,$00,$82,$FF,$FF,$C1,$0F,$C0,$44,$00
        fcb     $46,$82,$3F,$FF,$C1,$0F,$C0,$44,$00,$45,$C1,$FC
        fcb     $00,$82,$AF,$FF,$C1,$03,$FC,$44,$00,$45,$C1,$C0
        fcb     $0A,$82,$AF,$FF,$C1,$03,$FC,$44,$00,$44,$C1,$C0
        fcb     $0A,$84,$AA,$AA,$FF,$FF,$C1,$3F,$00,$43,$00,$44
        fcb     $C1,$C0,$0A,$84,$AA,$AA,$FF,$FF,$C1,$3F,$00,$43
        fcb     $00,$43,$C1,$FC,$00,$85,$AA,$AA,$FF,$FF,$AA,$C1
        fcb     $0F,$C0,$43,$00,$43,$C1,$FC,$00,$85,$AA,$AA,$AF
        fcb     $FF,$AA,$C1,$0F,$C0,$43,$00,$43,$C1,$FC,$00,$85
        fcb     $AA,$AA,$AF,$FF,$AA,$C1,$03,$F0,$43,$00,$43,$C1
        fcb     $FC,$00,$81,$AA,$C3,$3C,$80,$03,$F0,$FC,$00,$82
        fcb     $FF,$FC,$43,$00,$43,$C1,$F0,$0A,$81,$AA,$C2,$3C
        fcb     $80,$03,$F0,$41,$82,$3F,$FF,$C1,$0F,$C0,$42,$00
        fcb     $43,$C1,$F0,$0A,$81,$AA,$C1,$3C,$80,$85,$FF,$0F
        fcb     $FF,$FC,$FF,$42,$00,$43,$C1,$F0,$0A,$81,$A8,$C1
        fcb     $F0,$03,$85,$FF,$EF,$FF,$FF,$FF,$C1,$0F,$C0,$41
        fcb     $00,$43,$C1,$F0,$0A,$81,$A8,$C1,$F0,$03,$86,$F7
        fcb     $FF,$FF,$EF,$FF,$FF,$C1,$3F,$C0,$00,$43,$C1,$FC
        fcb     $00,$81,$A8,$C1,$C0,$0F,$82,$FF,$FF,$C1,$03,$F0
        fcb     $41,$82,$3E,$AF,$C1,$3F,$C0,$00,$43,$C3,$F0,$0F
        fcb     $03,$F0,$C0,$0F,$84,$FF,$FF,$FF,$FE,$C1,$0F,$80
        fcb     $81,$3F,$C1,$3F,$C0,$00,$43,$81,$3F,$C2,$03,$F0
        fcb     $C0,$0F,$83,$FF,$FF,$FF,$C1,$0F,$C0,$41,$81,$3F
        fcb     $C1,$3F,$00,$00,$42,$C1,$F0,$03,$82,$FF,$FC,$42
        fcb     $81,$FF,$C1,$03,$F0,$42,$81,$3C,$41,$00,$42,$83
        fcb     $FF,$FC,$3F,$48,$00
