* chtab4viz_028_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 34 rows x 5 bytes, 316 segment bytes
*
chtab4viz_028_p0:
        fcb     34,5  ; height, width in bytes
        fcb     $C1,$C0,$0F,$81,$FF,$C1,$3F,$00,$42,$00,$82,$FF
        fcb     $FF,$C1,$03,$F0,$42,$00,$83,$FF,$FC,$FF,$42,$00
        fcb     $C1,$C0,$0F,$82,$FF,$FF,$C1,$3F,$00,$41,$00,$41
        fcb     $82,$3F,$FF,$C1,$3F,$00,$41,$00,$C1,$F0,$01,$82
        fcb     $7F,$FC,$42,$00,$C1,$C0,$0F,$81,$7F,$C1,$3F,$00
        fcb     $42,$00,$C2,$C0,$0F,$03,$FC,$43,$00,$82,$FF,$FF
        fcb     $C1,$0F,$C0,$42,$00,$C1,$C0,$0F,$81,$FF,$C1,$03
        fcb     $F0,$42,$00,$83,$FF,$FC,$7F,$42,$00,$83,$FF,$FC
        fcb     $7F,$42,$00,$C1,$C0,$0A,$82,$AF,$FC,$42,$00,$C1
        fcb     $C0,$0A,$82,$AF,$FF,$C1,$3F,$00,$41,$00,$C1,$C0
        fcb     $0A,$82,$AF,$FF,$C1,$3F,$00,$41,$00,$C1,$C0,$0A
        fcb     $82,$AF,$FF,$C1,$3F,$00,$41,$00,$C1,$C0,$0A,$82
        fcb     $AA,$FF,$C1,$0F,$C0,$41,$00,$C1,$FC,$00,$82,$AA
        fcb     $FF,$C1,$0F,$C0,$41,$00,$C1,$FC,$00,$82,$AA,$FF
        fcb     $C1,$0F,$F0,$41,$00,$C1,$F0,$03,$82,$EA,$FF,$C1
        fcb     $0F,$F0,$41,$00,$C1,$F0,$01,$82,$7E,$AF,$C1,$0F
        fcb     $F0,$41,$00,$C1,$F0,$01,$82,$7E,$AA,$C1,$0F,$F0
        fcb     $41,$00,$C1,$F0,$01,$82,$7E,$AA,$C1,$0F,$F0,$41
        fcb     $00,$C1,$C0,$0A,$82,$AA,$A8,$C1,$0F,$10,$41,$00
        fcb     $84,$AA,$AA,$AA,$FC,$41,$00,$84,$AA,$AA,$83,$FC
        fcb     $41,$00,$84,$AA,$AA,$AF,$FF,$C1,$03,$F0,$00,$84
        fcb     $AA,$AA,$83,$FF,$C1,$0F,$C0,$00,$82,$AA,$AA,$C1
        fcb     $0F,$80,$81,$3F,$C1,$3F,$00,$00,$C1,$C0,$0A,$82
        fcb     $AA,$A8,$42,$00,$C1,$C0,$0A,$82,$AA,$A8,$42,$00
        fcb     $41,$C1,$C0,$0A,$81,$FC,$42,$00,$41,$82,$3F,$FF
        fcb     $C1,$3F,$00,$41,$00,$C1,$FC,$00,$82,$FF,$FF,$C1
        fcb     $3F,$00,$41,$00
