* chtab4viz_028_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 34 rows x 5 bytes, 308 segment bytes
*
chtab4viz_028_p0:
        fcb     34,5  ; height, width in bytes
        fcb     $C1,$F0,$0F,$81,$FF,$43,$00,$82,$FF,$FF,$C1,$0F
        fcb     $F0,$42,$00,$82,$FF,$FF,$C1,$03,$FC,$42,$00,$C1
        fcb     $F0,$0F,$82,$FF,$FF,$42,$00,$41,$C1,$C0,$3F,$81
        fcb     $FF,$42,$00,$C1,$FC,$01,$81,$7F,$C1,$03,$FC,$42
        fcb     $00,$C1,$F0,$0F,$81,$7F,$43,$00,$C2,$F0,$0F,$03
        fcb     $FC,$43,$00,$82,$FF,$FF,$C1,$3F,$C0,$42,$00,$C1
        fcb     $F0,$0F,$81,$FF,$C1,$0F,$F0,$42,$00,$82,$7F,$FF
        fcb     $C1,$03,$FC,$42,$00,$82,$7F,$FF,$C1,$03,$FC,$42
        fcb     $00,$C1,$F0,$0A,$81,$AF,$C1,$03,$FC,$42,$00,$C1
        fcb     $F0,$0A,$82,$AF,$FF,$42,$00,$C1,$F0,$0A,$82,$AF
        fcb     $FF,$42,$00,$C1,$F0,$0A,$82,$AF,$FF,$42,$00,$C1
        fcb     $F0,$0A,$82,$AA,$FF,$C1,$3F,$C0,$41,$00,$41,$82
        fcb     $AA,$FF,$C1,$3F,$C0,$41,$00,$41,$82,$AA,$FF,$C1
        fcb     $0F,$F0,$41,$00,$C1,$FC,$03,$82,$EA,$FF,$C1,$0F
        fcb     $F0,$41,$00,$C1,$FC,$01,$82,$7E,$AF,$C1,$0F,$F0
        fcb     $41,$00,$C1,$FC,$01,$82,$7E,$AA,$C1,$0F,$F0,$41
        fcb     $00,$C1,$FC,$01,$82,$7E,$AA,$C1,$0F,$F0,$41,$00
        fcb     $C1,$F0,$0A,$81,$AA,$C2,$03,$A8,$CF,$10,$41,$00
        fcb     $83,$AA,$AA,$AA,$C1,$03,$FC,$41,$00,$82,$AA,$AA
        fcb     $C2,$3C,$83,$03,$FC,$41,$00,$84,$AA,$AA,$AF,$FF
        fcb     $C1,$0F,$F0,$00,$82,$AA,$AA,$C1,$3C,$83,$81,$FF
        fcb     $C1,$3F,$C0,$00,$82,$AA,$AA,$C2,$3F,$80,$C0,$3F
        fcb     $41,$00,$C1,$F0,$0A,$81,$AA,$C1,$03,$A8,$42,$00
        fcb     $C1,$F0,$0A,$81,$AA,$C1,$03,$A8,$42,$00,$41,$C2
        fcb     $F0,$0A,$03,$FC,$42,$00,$41,$C1,$C0,$3F,$81,$FF
        fcb     $42,$00,$41,$82,$FF,$FF,$42,$00
