* chtab4viz_030_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 22 rows x 6 bytes, 236 segment bytes
*
chtab4viz_030_p0:
        fcb     22,6  ; height, width in bytes
        fcb     $81,$15,$C1,$3F,$00,$44,$00,$83,$0F,$FF,$15,$C1
        fcb     $3F,$00,$42,$00,$C1,$F0,$03,$82,$FF,$FF,$C1,$0F
        fcb     $F0,$42,$00,$C1,$F0,$03,$83,$FF,$FC,$FF,$42,$00
        fcb     $41,$83,$FF,$FC,$3F,$42,$00,$41,$C1,$FC,$00,$81
        fcb     $FF,$C1,$0F,$F0,$42,$00,$41,$82,$17,$FF,$C1,$3F
        fcb     $00,$42,$00,$C1,$FC,$00,$83,$FF,$FC,$F7,$42,$00
        fcb     $C1,$FC,$00,$83,$FF,$FF,$FF,$C1,$3F,$00,$41,$00
        fcb     $C2,$F0,$03,$0F,$C0,$82,$3F,$FF,$C1,$0F,$C0,$41
        fcb     $00,$41,$C1,$FC,$00,$82,$FF,$FF,$C1,$03,$F0,$41
        fcb     $00,$41,$C1,$FC,$03,$82,$FF,$FF,$C1,$03,$F0,$41
        fcb     $00,$41,$C1,$FC,$03,$83,$FF,$FC,$FF,$41,$00,$41
        fcb     $C1,$FC,$03,$83,$FF,$FF,$FF,$C1,$3F,$00,$00,$41
        fcb     $C1,$FC,$03,$83,$FF,$FF,$EA,$C1,$3F,$00,$00,$42
        fcb     $C1,$C0,$0A,$82,$AF,$FF,$C1,$3F,$C0,$00,$41,$C1
        fcb     $FC,$00,$83,$AF,$FF,$AA,$C1,$3F,$C0,$00,$C1,$FC
        fcb     $00,$84,$AA,$FE,$AA,$FF,$C1,$3F,$C0,$00,$C1,$C0
        fcb     $0A,$84,$AA,$FE,$AA,$FF,$C1,$3F,$00,$00,$C1,$C0
        fcb     $0A,$84,$AA,$AA,$AA,$FF,$C1,$3F,$00,$00,$C1,$C0
        fcb     $0A,$84,$F5,$0A,$AF,$FC,$41,$00,$C1,$C0,$0A,$83
        fcb     $7E,$AF,$F5,$C1,$3F,$00,$41,$00
