* chtab4viz_032_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 11 rows x 11 bytes, 186 segment bytes
*
chtab4viz_032_p0:
        fcb     11,11  ; height, width in bytes
        fcb     $46,$C2,$C0,$3F,$03,$FC,$43,$00,$45,$C1,$C0,$3F
        fcb     $82,$FF,$FF,$C1,$3F,$C0,$42,$00,$43,$C1,$F0,$0F
        fcb     $84,$FF,$F5,$57,$FF,$C1,$0F,$F0,$81,$FF,$41,$00
        fcb     $43,$C1,$C0,$3F,$86,$57,$FF,$F7,$FF,$FF,$55,$C1
        fcb     $0F,$F0,$00,$43,$87,$57,$FF,$EF,$FF,$FF,$55,$FF
        fcb     $C1,$0F,$F0,$00,$42,$C1,$FC,$03,$87,$55,$57,$FF
        fcb     $FF,$F5,$55,$FF,$C1,$03,$FC,$00,$41,$C1,$C0,$3F
        fcb     $85,$FF,$F5,$55,$55,$FF,$C1,$0F,$50,$82,$AF,$FF
        fcb     $C1,$03,$FC,$00,$C1,$FC,$03,$83,$FF,$FF,$FF,$C2
        fcb     $3C,$C1,$FC,$01,$81,$55,$C1,$0F,$50,$82,$AA,$FF
        fcb     $C1,$03,$FC,$00,$C1,$FC,$03,$83,$FF,$F5,$FF,$C2
        fcb     $F0,$0A,$3C,$81,$84,$55,$57,$EA,$FF,$C1,$03,$FC
        fcb     $00,$C1,$FC,$03,$83,$FF,$55,$FF,$C2,$F0,$0A,$3C
        fcb     $81,$84,$55,$7F,$EA,$FF,$C1,$0F,$F0,$00,$C1,$FC
        fcb     $01,$41,$C1,$C0,$15,$85,$55,$55,$55,$55,$55,$41
        fcb     $81,$FF,$C1,$3F,$C0,$00
