* chtab4viz_031_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 19 rows x 9 bytes, 228 segment bytes
*
chtab4viz_031_p0:
        fcb     19,9  ; height, width in bytes
        fcb     $43,$81,$15,$C1,$3F,$00,$44,$00,$43,$81,$15,$C1
        fcb     $3F,$00,$44,$00,$43,$82,$17,$E8,$44,$00,$43,$C1
        fcb     $F0,$03,$81,$E8,$44,$00,$43,$C1,$FC,$00,$81,$AA
        fcb     $C1,$3F,$80,$43,$00,$43,$C1,$FC,$00,$82,$AA,$A8
        fcb     $43,$00,$44,$C1,$C0,$0A,$82,$A8,$3F,$C1,$0F,$C0
        fcb     $41,$00,$44,$C1,$FC,$00,$83,$FF,$FC,$F7,$41,$00
        fcb     $C2,$C0,$0F,$0F,$C0,$42,$C1,$C0,$0F,$83,$7F,$FF
        fcb     $FF,$C1,$3F,$00,$00,$C1,$C0,$0F,$82,$FF,$FC,$41
        fcb     $C1,$F0,$03,$83,$7F,$FF,$F5,$C1,$0F,$C0,$00,$C1
        fcb     $C0,$0F,$87,$3F,$F5,$7F,$FF,$FF,$FC,$FF,$C1,$0F
        fcb     $C0,$00,$C1,$C0,$0A,$87,$FF,$F5,$7F,$FF,$FF,$FF
        fcb     $FF,$C1,$0F,$C0,$00,$C1,$C0,$0A,$87,$AF,$F5,$7F
        fcb     $FF,$FE,$AA,$FF,$C1,$3F,$00,$00,$88,$AF,$FF,$7F
        fcb     $FF,$AA,$AA,$AA,$AA,$C1,$3F,$00,$00,$88,$AA,$FF
        fcb     $FF,$FC,$AA,$AA,$AA,$AA,$41,$00,$87,$AA,$AA,$FF
        fcb     $FF,$AA,$AA,$AA,$C1,$03,$F0,$41,$00,$88,$AA,$FF
        fcb     $FF,$FC,$AA,$F0,$AA,$AA,$41,$00,$87,$AA,$AA,$AF
        fcb     $FF,$F5,$0A,$AA,$C1,$03,$F0,$41,$00,$C1,$C0,$0A
        fcb     $84,$F5,$0A,$AA,$AA,$C1,$30,$83,$81,$FF,$42,$00
