* chtab4viz_029_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 31 rows x 6 bytes, 306 segment bytes
*
chtab4viz_029_p0:
        fcb     31,6  ; height, width in bytes
        fcb     $C1,$FC,$03,$81,$FF,$C1,$3F,$C0,$43,$00,$82,$7F
        fcb     $FF,$C1,$03,$FC,$43,$00,$83,$FF,$FF,$7F,$43,$00
        fcb     $C1,$FC,$03,$82,$FF,$FF,$C1,$3F,$C0,$42,$00,$41
        fcb     $C1,$F0,$0F,$81,$FF,$C1,$3F,$C0,$42,$00,$C1,$FC
        fcb     $01,$82,$7F,$FF,$43,$00,$C1,$F0,$0F,$81,$7F,$C1
        fcb     $3F,$C0,$43,$00,$C1,$F0,$0F,$81,$FF,$C1,$3F,$C0
        fcb     $43,$00,$82,$7F,$7F,$C1,$03,$FC,$43,$00,$41,$82
        fcb     $FF,$FF,$43,$00,$C1,$FC,$03,$82,$FF,$FF,$C1,$3F
        fcb     $C0,$42,$00,$41,$82,$AA,$FF,$C1,$0F,$F0,$42,$00
        fcb     $41,$82,$AA,$FF,$C1,$0F,$F0,$42,$00,$41,$82,$AA
        fcb     $FF,$C1,$0F,$F0,$42,$00,$41,$82,$AA,$FF,$C1,$0F
        fcb     $F0,$42,$00,$41,$C3,$03,$A8,$C0,$3F,$0F,$F0,$42
        fcb     $00,$C1,$FC,$03,$82,$EA,$AF,$C1,$0F,$F0,$42,$00
        fcb     $C1,$C0,$17,$82,$EA,$AF,$C1,$03,$FC,$42,$00,$C2
        fcb     $CF,$10,$F0,$0A,$82,$AF,$FF,$C1,$3F,$C0,$41,$00
        fcb     $41,$C1,$F0,$0A,$82,$AF,$FF,$C1,$3F,$C0,$41,$00
        fcb     $41,$C1,$F0,$0A,$82,$AF,$FF,$C1,$03,$FC,$41,$00
        fcb     $41,$C1,$F0,$0A,$83,$FF,$FF,$AF,$C1,$0F,$F0,$00
        fcb     $41,$C1,$FC,$01,$83,$FF,$FF,$7F,$C1,$3F,$C0,$00
        fcb     $41,$C1,$FC,$01,$83,$FF,$FF,$7E,$41,$00,$41,$C1
        fcb     $3C,$81,$82,$7E,$FF,$C1,$0F,$F0,$41,$00,$41,$C1
        fcb     $3C,$81,$82,$7E,$FF,$C1,$3F,$C0,$41,$00,$41,$82
        fcb     $AA,$AA,$C1,$03,$A8,$42,$00,$41,$82,$AA,$AA,$C1
        fcb     $3F,$80,$42,$00,$41,$82,$AA,$AA,$C1,$3F,$80,$42
        fcb     $00,$41,$82,$AA,$AA,$C1,$0F,$F0,$42,$00,$41,$C2
        fcb     $F0,$0A,$3F,$80,$43,$00
