* chtab4viz_030_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 22 rows x 6 bytes, 220 segment bytes
*
chtab4viz_030_p0:
        fcb     22,6  ; height, width in bytes
        fcb     $C1,$C0,$15,$45,$00,$C2,$C0,$15,$F0,$0F,$81,$FF
        fcb     $43,$00,$C1,$FC,$03,$82,$FF,$FF,$C1,$0F,$F0,$42
        fcb     $00,$C1,$FC,$03,$82,$FF,$FF,$C1,$03,$FC,$42,$00
        fcb     $41,$C1,$C0,$3F,$81,$FF,$C1,$03,$FC,$42,$00,$42
        fcb     $81,$FF,$C1,$0F,$F0,$42,$00,$41,$C1,$C0,$17,$81
        fcb     $FF,$43,$00,$41,$82,$F7,$FF,$C1,$03,$FC,$42,$00
        fcb     $41,$83,$FF,$FF,$FF,$42,$00,$C3,$FC,$03,$3F,$C0
        fcb     $C0,$3F,$81,$FF,$C1,$3F,$C0,$41,$00,$42,$82,$FF
        fcb     $FF,$C1,$0F,$F0,$41,$00,$41,$C1,$FC,$03,$82,$FF
        fcb     $FF,$C1,$0F,$F0,$41,$00,$41,$C1,$FC,$03,$82,$FF
        fcb     $FF,$C1,$03,$FC,$41,$00,$41,$C1,$FC,$03,$83,$FF
        fcb     $FF,$FF,$41,$00,$41,$C1,$FC,$03,$83,$FF,$FF,$EA
        fcb     $41,$00,$42,$C1,$F0,$0A,$82,$AF,$FF,$C1,$3F,$C0
        fcb     $00,$42,$83,$AF,$FF,$AA,$C1,$3F,$C0,$00,$41,$84
        fcb     $AA,$FE,$AA,$FF,$C1,$3F,$C0,$00,$C1,$F0,$0A,$84
        fcb     $AA,$FE,$AA,$FF,$41,$00,$C1,$F0,$0A,$84,$AA,$AA
        fcb     $AA,$FF,$41,$00,$C1,$F0,$0A,$81,$F5,$C1,$F0,$0A
        fcb     $81,$AF,$C1,$03,$FC,$41,$00,$C1,$F0,$0A,$83,$7E
        fcb     $AF,$F5,$42,$00
