* chtab4viz_032_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 11 rows x 11 bytes, 166 segment bytes
*
chtab4viz_032_p0:
        fcb     11,11  ; height, width in bytes
        fcb     $46,$82,$3F,$FC,$43,$00,$45,$C1,$C0,$3F,$82,$FF
        fcb     $FF,$C1,$0F,$C0,$42,$00,$43,$C1,$F0,$0F,$86,$57
        fcb     $FF,$F0,$FF,$FF,$F5,$C1,$3F,$00,$00,$43,$87,$57
        fcb     $FF,$F7,$FF,$FF,$55,$3F,$C1,$0F,$F0,$00,$42,$C1
        fcb     $FC,$00,$87,$57,$FF,$EF,$FF,$FF,$55,$FF,$C1,$0F
        fcb     $F0,$00,$42,$C1,$F0,$03,$88,$57,$FF,$FF,$FC,$FF
        fcb     $F5,$55,$55,$00,$41,$8A,$50,$AF,$FF,$FC,$FF,$F5
        fcb     $55,$55,$3F,$FF,$00,$C1,$F0,$03,$84,$FF,$FF,$FF
        fcb     $C1,$C1,$30,$01,$85,$50,$AA,$FF,$FC,$55,$00,$C1
        fcb     $F0,$03,$84,$FF,$FF,$F5,$0A,$C1,$30,$81,$85,$57
        fcb     $EA,$FF,$FC,$55,$00,$C1,$F0,$03,$84,$FF,$FF,$55
        fcb     $0A,$C1,$30,$81,$84,$55,$7F,$EA,$FF,$C1,$0F,$F0
        fcb     $00,$C2,$F0,$01,$3F,$00,$86,$55,$55,$55,$55,$15
        fcb     $55,$C1,$3C,$00,$81,$FF,$C1,$0F,$C0,$00
