* chtab4viz_011_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 36 rows x 9 bytes, 437 segment bytes
*
chtab4viz_011_p0:
        fcb     36,9  ; height, width in bytes
        fcb     $44,$C2,$C0,$3F,$03,$FC,$43,$00,$43,$C1,$FC,$03
        fcb     $82,$FF,$FF,$C1,$3F,$C0,$42,$00,$43,$C1,$FC,$03
        fcb     $82,$FF,$FF,$C1,$0F,$F0,$42,$00,$44,$C1,$C0,$3F
        fcb     $81,$FF,$C1,$03,$FC,$42,$00,$45,$81,$FF,$C1,$03
        fcb     $FC,$42,$00,$44,$C1,$C0,$17,$81,$FF,$C1,$0F,$F0
        fcb     $42,$00,$43,$82,$AA,$FF,$C1,$03,$FC,$43,$00,$42
        fcb     $C1,$F0,$0A,$82,$AA,$FF,$C1,$03,$FC,$43,$00,$42
        fcb     $84,$AA,$AA,$AF,$FF,$C1,$3F,$C0,$42,$00,$41,$C1
        fcb     $FC,$03,$84,$EA,$AA,$AA,$FF,$C1,$0F,$F0,$42,$00
        fcb     $41,$C3,$FC,$03,$03,$FC,$F0,$0A,$82,$AA,$FF,$C1
        fcb     $0F,$F0,$42,$00,$41,$C2,$C0,$17,$3F,$C0,$41,$82
        fcb     $AA,$FF,$C1,$0F,$F0,$42,$00,$41,$C1,$C0,$15,$42
        fcb     $82,$AA,$FF,$C1,$03,$FC,$42,$00,$41,$C1,$CF,$10
        fcb     $42,$82,$AA,$FF,$C1,$03,$FC,$42,$00,$44,$82,$AA
        fcb     $FF,$C1,$03,$FC,$42,$00,$44,$82,$AA,$FF,$C1,$0F
        fcb     $F0,$42,$00,$44,$82,$AA,$FF,$C1,$0F,$F0,$42,$00
        fcb     $44,$82,$AA,$FF,$C1,$0F,$F0,$42,$00,$44,$82,$AA
        fcb     $FF,$C1,$0F,$F0,$42,$00,$43,$C1,$F0,$0A,$82,$AF
        fcb     $FF,$C1,$0F,$F0,$42,$00,$43,$83,$AF,$FF,$AA,$C1
        fcb     $0F,$F0,$42,$00,$42,$C1,$FC,$03,$83,$AF,$FF,$EA
        fcb     $C1,$0F,$F0,$42,$00,$42,$C1,$C0,$3E,$83,$FF,$FF
        fcb     $AA,$C1,$0F,$F0,$42,$00,$41,$C1,$F0,$0F,$84,$FE
        fcb     $AA,$FF,$FF,$C1,$0F,$F0,$42,$00,$41,$85,$AA,$AA
        fcb     $FF,$FF,$FE,$C1,$0F,$F0,$42,$00,$C1,$F0,$0F,$85
        fcb     $AA,$AF,$FF,$FF,$FE,$C1,$03,$E8,$42,$00,$C1,$FC
        fcb     $03,$85,$AA,$AF,$FF,$FE,$FE,$C1,$03,$A8,$42,$00
        fcb     $41,$C1,$C0,$3E,$83,$FF,$FF,$AA,$C1,$F0,$0A,$81
        fcb     $AA,$C1,$3F,$80,$41,$00,$41,$C1,$F0,$0A,$82,$AA
        fcb     $FF,$42,$81,$AA,$C1,$3F,$80,$41,$00,$41,$C1,$F0
        fcb     $0A,$81,$AA,$C1,$3F,$80,$42,$81,$AA,$C1,$03,$A8
        fcb     $41,$00,$41,$C2,$F0,$0A,$03,$A8,$43,$81,$AA,$C1
        fcb     $03,$A8,$41,$00,$41,$C2,$F0,$0A,$03,$A8,$43,$C2
        fcb     $F0,$0A,$03,$A8,$41,$00,$42,$C1,$3F,$80,$44,$C2
        fcb     $FC,$03,$3F,$C0,$00,$41,$C2,$C0,$3F,$3F,$C0,$44
        fcb     $C2,$FC,$03,$0F,$F0,$00,$C1,$FC,$03,$81,$FF,$C1
        fcb     $3F,$C0,$44,$C2,$C0,$3F,$03,$FC,$00,$82,$7F,$FF
        fcb     $C1,$3F,$C0,$46,$00
