* chtab4viz_026_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 14 rows x 14 bytes, 253 segment bytes
*
chtab4viz_026_p0:
        fcb     14,14  ; height, width in bytes
        fcb     $43,$C1,$FC,$03,$81,$FF,$C1,$0F,$F0,$48,$00,$43
        fcb     $C1,$C0,$3F,$82,$FF,$FF,$48,$00,$43,$C1,$FC,$03
        fcb     $82,$EA,$FF,$48,$00,$42,$C1,$FC,$03,$82,$FF,$EA
        fcb     $C1,$03,$FC,$41,$C2,$C0,$3F,$03,$FC,$45,$00,$42
        fcb     $C1,$F0,$0F,$82,$FF,$FE,$C1,$03,$A8,$41,$82,$FF
        fcb     $55,$45,$00,$42,$C1,$C0,$3F,$82,$FF,$FE,$C2,$03
        fcb     $A8,$F0,$0F,$82,$F5,$55,$C1,$0F,$50,$44,$00,$41
        fcb     $C1,$FC,$01,$83,$FF,$FE,$7F,$C2,$03,$A8,$F0,$0F
        fcb     $83,$55,$55,$55,$44,$00,$41,$C1,$FC,$01,$84,$7F
        fcb     $FF,$EF,$EF,$C1,$F0,$0F,$84,$55,$55,$55,$55,$43
        fcb     $00,$41,$C2,$C0,$15,$F0,$0F,$83,$EF,$FF,$FF,$C1
        fcb     $FC,$01,$84,$55,$55,$55,$55,$C1,$0F,$50,$42,$00
        fcb     $41,$C1,$C0,$15,$83,$FF,$EF,$57,$C2,$03,$FC,$FC
        fcb     $01,$86,$55,$55,$55,$7F,$55,$55,$41,$00,$41,$C1
        fcb     $C0,$15,$84,$55,$55,$7F,$FE,$C2,$03,$A8,$C0,$15
        fcb     $85,$55,$55,$57,$FF,$55,$C1,$3F,$C0,$00,$41,$C1
        fcb     $C0,$15,$85,$55,$57,$FE,$AA,$55,$C2,$03,$A8,$C0
        fcb     $15,$84,$55,$55,$57,$FF,$C1,$3F,$C0,$00,$41,$C1
        fcb     $FC,$01,$82,$55,$55,$C1,$FC,$03,$83,$AA,$AA,$EA
        fcb     $C2,$03,$A8,$FC,$01,$81,$55,$C3,$0F,$50,$FC,$03
        fcb     $3F,$C0,$00,$44,$83,$AA,$AA,$AA,$C1,$03,$A8,$46
        fcb     $00
