* chtab4skel_031_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 1 rows x 1 bytes, 2 segment bytes
*
chtab4skel_031_p0:
        fcb     1,1  ; height, width in bytes
        fcb     $41,$00
