* chtab4skel_025_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 24 rows x 8 bytes, 265 segment bytes
*
chtab4skel_025_p0:
        fcb     24,8  ; height, width in bytes
        fcb     $44,$C2,$F0,$0F,$03,$FC,$42,$00,$44,$82,$FF,$FF
        fcb     $42,$00,$44,$C2,$F3,$08,$C0,$3F,$42,$00,$44,$C2
        fcb     $C3,$3C,$C0,$3F,$42,$00,$44,$C2,$3C,$83,$0F,$F0
        fcb     $42,$00,$44,$81,$FF,$C1,$3F,$C0,$42,$00,$44,$C2
        fcb     $FC,$03,$3F,$C0,$42,$00,$45,$C1,$3F,$80,$42,$00
        fcb     $44,$C2,$F0,$0F,$3F,$C0,$42,$00,$43,$C2,$FC,$03
        fcb     $0F,$F0,$81,$FE,$C1,$0F,$F0,$41,$00,$43,$C1,$FC
        fcb     $03,$81,$FF,$C2,$0F,$F0,$0F,$F0,$41,$00,$44,$C3
        fcb     $3F,$80,$F0,$0F,$0F,$F0,$41,$00,$42,$C1,$0F,$F0
        fcb     $41,$81,$FF,$C2,$0F,$F0,$C3,$3C,$41,$00,$41,$C3
        fcb     $FC,$03,$0F,$F0,$FC,$01,$41,$C2,$CF,$10,$C3,$3C
        fcb     $41,$00,$41,$C3,$FC,$03,$03,$FC,$FC,$03,$81,$FF
        fcb     $C2,$0F,$F0,$C0,$3F,$41,$00,$41,$C2,$F0,$0F,$3F
        fcb     $C0,$41,$C4,$03,$FC,$C0,$3F,$FC,$03,$3F,$C0,$00
        fcb     $41,$C1,$C0,$3F,$81,$7F,$C5,$03,$FC,$F0,$0F,$0F
        fcb     $50,$FC,$03,$3F,$C0,$00,$41,$C3,$C0,$3E,$03,$FC
        fcb     $F0,$0F,$81,$EF,$C3,$0F,$F0,$FC,$03,$3F,$C0,$00
        fcb     $41,$C2,$03,$FC,$F0,$0F,$82,$FF,$7F,$41,$C1,$FC
        fcb     $01,$41,$00,$C3,$F0,$0F,$3F,$C0,$F0,$0F,$81,$FF
        fcb     $C2,$F0,$0F,$3F,$C0,$42,$00,$C1,$F0,$0F,$43,$C1
        fcb     $FC,$03,$81,$F5,$42,$00,$C1,$03,$7C,$44,$81,$FF
        fcb     $42,$00,$45,$C1,$C0,$3F,$42,$00,$C1,$CF,$10,$47
        fcb     $00
