* chtab4skel_032_p0 — runtime-blit segment data, phase 0
* GENERATED by harness/tools/cel_blit_prep.py — do not hand-edit.
* 10 rows x 11 bytes, 171 segment bytes
*
chtab4skel_032_p0:
        fcb     10,11  ; height, width in bytes
        fcb     $45,$C1,$FC,$01,$81,$7F,$C1,$03,$FC,$43,$00,$44
        fcb     $C1,$FC,$01,$83,$7F,$FF,$55,$43,$00,$44,$C1,$FC
        fcb     $01,$83,$7F,$FF,$55,$C2,$F0,$0F,$03,$FC,$41,$00
        fcb     $43,$C1,$FC,$01,$86,$FF,$FE,$FF,$FF,$55,$57,$41
        fcb     $00,$42,$C1,$C0,$15,$87,$F5,$7F,$FF,$FF,$55,$7F
        fcb     $55,$C1,$3F,$C0,$00,$41,$C1,$C0,$3F,$88,$F5,$7E
        fcb     $FF,$FF,$55,$55,$55,$7F,$C1,$3F,$C0,$00,$41,$C2
        fcb     $C0,$3F,$3F,$C0,$41,$C2,$CF,$10,$C0,$3F,$84,$FF
        fcb     $FE,$AF,$FF,$C1,$3F,$C0,$00,$C1,$FC,$03,$82,$FF
        fcb     $55,$C3,$0F,$50,$03,$A8,$C0,$3F,$81,$FF,$C1,$0F
        fcb     $F0,$82,$AF,$FF,$C1,$3F,$C0,$00,$C1,$FC,$03,$82
        fcb     $FF,$55,$C3,$0F,$50,$03,$A8,$CF,$10,$81,$FF,$C1
        fcb     $0F,$F0,$82,$AF,$FF,$41,$00,$C2,$FC,$01,$FC,$01
        fcb     $85,$55,$55,$57,$FF,$55,$C3,$03,$FC,$F0,$0F,$03
        fcb     $FC,$41,$00
